crates/dbsp/src/algebra/zset/zset_macro.rs, crates/dbsp/src/circuit/circuit_builder.rs, crates/dbsp/src/operator/aggregate/mod.rs
I hadn't run `cargo test --doc` before submitting the PR that added a lot of docs, so this PR fixes those errors, plus a few minor doc typos.
=> Minor docs improvements

crates/dataflow-jit/src/ir/nodes/sum.rs, crates/dataflow-jit/src/ir/optimize/mod.rs, crates/dataflow-jit/src/ir/optimize/passthrough_sums.rs, crates/dataflow-jit/src/ir/optimize/shake.rs
Fixes #144, I'm not really sure where the submodule thing comes from
=> [JIT] Fixed dead node shaking irt Sum nodes, added opt for single-input sums

sql-to-dbsp-compiler/README.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/CompilerMain.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/optimize/NoIntegralVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/visitors/PassesVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java, sql-to-dbsp-compiler/lib/genlib/src/lib.rs, sql-to-dbsp-compiler/lib/hashing/src/lib.rs, sql-to-dbsp-compiler/lib/readers/src/lib.rs, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs, sql-to-dbsp-compiler/lib/sqllib/src/geopoint.rs, sql-to-dbsp-compiler/lib/sqllib/src/interval.rs, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs, sql-to-dbsp-compiler/lib/sqlvalue/src/lib.rs
These two commits fix some things that I noticed. The first commit fixes Clippy warnings that `tools/pre-push` found. The second commit fixes a problem I noticed when testing the SQL compiler to make sure that Clippy fixes hadn't broken it.
=> SQL related fixes

.github/workflows/ci.yml, .github/workflows/containers.yml, Cargo.lock, Earthfile, crates/pipeline_manager/Cargo.toml, deploy/docker-compose-dev.yml, deploy/docker-compose.yml, web-ui/src/pages/_app.tsx, web-ui/src/types/manager/core/OpenAPI.ts, web-ui/src/types/manager/core/request.ts, web-ui/src/types/manager/services/PipelineService.ts
* Makes use of `window.location.origin` instead of hard coded URL bases.
* Uses Github secrets to inject the MUIX license into the build.
* Uses the ghcr.io/feldera namespace in the created container names.
* I couldn't yet fix the ghcr push issue properly. I'll look into that separately after this PR merged.
=> UI fixes towards dev-form factor

crates/dataflow-jit/src/codegen/call.rs, crates/dataflow-jit/src/codegen/math.rs, crates/dataflow-jit/src/codegen/mod.rs, crates/dataflow-jit/src/tests/issue_141.rs, crates/dataflow-jit/src/tests/issue_181.rs, crates/dataflow-jit/src/tests/mod.rs
=> Bugfix for #181

sql-to-dbsp-compiler/README.md, sql-to-dbsp-compiler/SQL-compiler/pom.xml, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/optimize/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPDecimalLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDecimal.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/JitTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/NaiveIncrementalTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresNumericTests.java, sql-to-dbsp-compiler/doc/sql/decimal.rst, sql-to-dbsp-compiler/doc/sql/float.rst, sql-to-dbsp-compiler/lib/sqllib/Cargo.toml, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
inc, sign, cell, floor
Fixes some of the Postgres tests to run on both numeric and FP values.
=>  Implement more numeric functions

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/optimize/PropagateEmptySources.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/optimizer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/InnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPIndexedZSetLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPZSetLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DbspJdbcExecutor.java
=> Optimize away operators with constant empty inputs

crates/dbsp/src/operator/input.rs
Before this commit, an `append` of `N` values across `k` workers added `N/k` values to the first `k - 1` workers and the rest (as many as `N/k + k - 1` values) to the final worker.  This commit makes it so that all of the workers get either `N/k` or `N/k + 1` values.
Before this commit, all the values were first copied into a buffer inside the `CollectionHandle`, and then copied into the worker.  This commit removes the buffers from the `CollectionHandle` and skips the copy.
Before this commit, the `next_worker` pointer inside the `CollectionHandle` was always advanced by the number of workers.  This has no useful effect because only its value modulo the number of workers is useful.  It also meant that, if `append` was the only way that data was added to the collection, that the last …
=> dbsp: Avoid double-copy and unfairness in `CollectionHandle::append()`.

.vscode/settings.json, Cargo.lock, crates/nexmark/Cargo.toml, crates/pipeline_manager/Cargo.toml, crates/pipeline_manager/src/db/mod.rs, crates/pipeline_manager/src/runner.rs, demo/__init__.py, demo/project_demo04-SecOps/run.py, web-ui/src/pages/_app.tsx, web-ui/src/pages/streaming/introspection/[config]/[view].tsx, web-ui/src/streaming/PipelineTable.tsx, web-ui/src/types/defaultQueryFn.ts, web-ui/src/types/manager/models/FileInputConfig.ts, web-ui/src/types/manager/models/NewPipelineRequest.ts, web-ui/src/types/manager/models/PipelineConfig.ts, web-ui/src/types/manager/models/PipelineDescr.ts, web-ui/src/types/manager/models/PipelineStatus.ts, web-ui/src/types/manager/models/ProgramDescr.ts, web-ui/src/types/manager/models/UpdateConnectorRequest.ts, web-ui/src/types/manager/models/UpdatePipelineRequest.ts, web-ui/src/types/manager/models/UpdateProgramRequest.ts, web-ui/src/types/manager/services/ConnectorService.ts, web-ui/src/types/manager/services/PipelineService.ts, web-ui/src/types/manager/services/ProgramService.ts
=> Secops demo fixup

crates/dbsp/examples/tutorial/tutorial9.rs, crates/dbsp/src/operator/aggregate/mod.rs, crates/dbsp/src/operator/group/mod.rs, crates/dbsp/src/trace/layers/column_layer/builders.rs, crates/dbsp/src/tutorial.rs
=> Records with 0 weights passed to `Builder`.

Cargo.lock, Earthfile, crates/dbsp/Cargo.toml, crates/dbsp/examples/tutorial/tutorial2.rs, crates/dbsp/examples/tutorial/tutorial3.rs, crates/dbsp/examples/tutorial/tutorial4.rs, crates/dbsp/examples/tutorial/tutorial5.rs, crates/dbsp/examples/tutorial/tutorial6.rs, crates/dbsp/examples/tutorial/tutorial7.rs, crates/dbsp/examples/tutorial/tutorial8.rs, crates/dbsp/examples/tutorial/tutorial9.rs, crates/dbsp/src/operator/communication/exchange.rs, crates/dbsp/src/trace/persistent/mod.rs, crates/dbsp/src/trace/persistent/trace.rs
=> Get persistence feature compiling again

sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ArrayTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/BaseSQLTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/CastTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/JitTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/MultiViewTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/TimeTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresBoolTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresDateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresNumericTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresTimestampTests.java
@Kixiron this should help narrow down the failing JIT tests
=> Emit information in the Rust code about the SQL unit test that is being run

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Utilities.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/BaseSQLTests.java, sql-to-dbsp-compiler/lib/sqllib/Cargo.toml, sql-to-dbsp-compiler/lib/sqlvalue/src/lib.rs, sql-to-dbsp-compiler/lib/tuple/Cargo.toml, sql-to-dbsp-compiler/lib/tuple/src/lib.rs, sql-to-dbsp-compiler/temp/Cargo.toml
Fixes #247 
Although, frankly, I suspect this won't really make much of a difference.
Don't really know how to test this properly; the sql compiler tests pass, but this needs to be exercised from the outside.
=> [sql] Conditionally compile some Rust packages

sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/config.fmpp, sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/CalciteCompilerTests.java
=> Support for DROP keyword in CalciteCompiler

CONTRIBUTING.md, demo/project_demo04-SecOps/simulator/src/main.rs
Also reduce verbosity of a demo test
=> Update contribution guide

Cargo.lock, docs/docusaurus.config.js, web-ui/package.json, web-ui/yarn.lock
part of https://github.com/feldera/dbsp/issues/86
=> Adds search functionality to docs using algolia.

.github/workflows/containers.yml, Earthfile, deploy/README.md, deploy/docker-compose.yml
=> Docker user experience fixes

crates/adapters/src/controller/error.rs, crates/adapters/src/controller/mod.rs, crates/adapters/src/server/mod.rs, crates/adapters/src/transport/http/input.rs, crates/pipeline_manager/src/main.rs
See individual commits for details.
=> Improved error handling in `crates/adapters`.

docs/docs/sql/string.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/cfg/JITBlockParameter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/instructions/JITFunctionCall.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/instructions/JITMuxInstruction.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/operators/JITSubtractOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/types/JITKVType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/types/JITRowType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/types/JITScalarType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/types/JITType.java
This should fix the build after the JIT schema changes in #219 
Also, added more documentation for "LIKE" SQL keyword.
Once the tests pass I will merge this into main.
=> Change JIT code generation to fix build

Earthfile, crates/pipeline_manager/src/db/test.rs
- Update rust version to 1.70
- Add `--locked` to cargo install to prevent future failures
- Fix a manager test failure (unrelated)
=> Fix CI build.

crates/pipeline_manager/src/integration_test.rs
Add a test that led to https://github.com/feldera/dbsp/issues/343
=> integration-test: test pipeline creation and actions endpoint

crates/dataflow-jit/src/codegen/call.rs, crates/dataflow-jit/src/codegen/intrinsics.rs, crates/dataflow-jit/src/codegen/math.rs, crates/dataflow-jit/src/codegen/mod.rs, crates/dataflow-jit/src/ir/exprs/constant.rs, crates/dataflow-jit/src/ir/validate.rs
=> Allow parsing decimals from strings

crates/dataflow-jit/src/ir/validate.rs, docs/docs/sql/float.md, docs/docs/sql/types.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/instructions/JITLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/instructions/JITTupleLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/instructions/JITZSetLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/operators/JITConstantOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitCastTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitPostgresDateTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitPostgresNumericTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresBaseTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresBoolTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresCollateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresDateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresFloat4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresNumericTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresStringTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresTimestampTests.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs
Found one more bug in Calcite: https://issues.apache.org/jira/browse/CALCITE-5843!
=> Floating-point and more jit tests

crates/dataflow-jit/src/codegen/math.rs, crates/dataflow-jit/src/dataflow/mod.rs, crates/dataflow-jit/src/dataflow/nodes.rs, crates/dataflow-jit/src/ir/nodes/aggregate.rs, crates/dataflow-jit/src/ir/nodes/constant.rs, crates/dataflow-jit/src/ir/nodes/differentiate.rs, crates/dataflow-jit/src/ir/nodes/filter_map.rs, crates/dataflow-jit/src/ir/nodes/flat_map.rs, crates/dataflow-jit/src/ir/nodes/index.rs, crates/dataflow-jit/src/ir/nodes/io.rs, crates/dataflow-jit/src/ir/nodes/join.rs, crates/dataflow-jit/src/ir/nodes/mod.rs, crates/dataflow-jit/src/ir/nodes/subgraph.rs, crates/dataflow-jit/src/ir/nodes/sum.rs, crates/dataflow-jit/src/ir/nodes/topk.rs, crates/dataflow-jit/src/ir/validate.rs, crates/dataflow-jit/src/ir/visit.rs, crates/dbsp/src/operator/group/topk.rs
Adds the TopK operator to the jit
=> [JIT] TopK Operator

crates/pipeline_manager/src/db/mod.rs, crates/pipeline_manager/src/db/test.rs
Otherwise the query would not detect that a new revision is needed if e.g., only the SQL changes and there are no inputs/output connectors configured.
=> Use left outer joins for config revision checks.

docs/docs/sql/datetime.md, docs/docs/sql/decimal.md, docs/docs/sql/types.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilationError.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/SourceFileContents.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateTableStatement.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/DropTableStatement.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDecimal.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/CalciteCompilerTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresArrayTests.java, sql-to-dbsp-compiler/lib/sqllib/src/string.rs
=> Improve error reporting for illegal types; change array_to_string definition

sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
Missing a % for the after-second part.
=> Fix TIME format parsing.

.github/workflows/ci.yml, Earthfile, python/dbsp/connection.py, python/dbsp/pipeline.py
Fixes logic that check if an entity already exists for program and pipeline.
=> Make sure we can run the same python script n-times.

Cargo.lock, crates/adapters/Cargo.toml, crates/adapters/src/lib.rs, crates/adapters/src/test/mock_input_consumer.rs, crates/adapters/src/transport/mod.rs, crates/adapters/src/transport/url.rs
I'm having a fight with the CI on this. So far (crossing fingers for latest rebase) I don't think that the failures are related to my changes.
=> dbsp_adapters: Add input adapter for URLs.

web-ui/src/connectors/dialogs/GenericEditorConnector.tsx, web-ui/src/connectors/dialogs/KafkaInputConnector.tsx, web-ui/src/connectors/dialogs/KafkaOutputConnector.tsx, web-ui/src/connectors/dialogs/UrlConnector.tsx, web-ui/src/connectors/dialogs/index.ts, web-ui/src/connectors/drawer/AddSourceDrawer.tsx, web-ui/src/pages/connectors/create.tsx, web-ui/src/types/connectors.tsx, web-ui/src/types/manager/models/TransportConfig.ts
=> Changes UI File connector to be the URL connector instead.

crates/pipeline_manager/src/integration_test.rs
We removed the daemonization feature in https://github.com/feldera/dbsp/pull/447. As part of that change, we
reworked a few instances where we'd explicitly create an async runtime after
daemonization could happen. We missed to do so in
`initialize_local_dbsp_instance()`, which broke that function. It was used by
the integration tests to bring up a local pipeline manager for convenience; it
panicked with the "cannot start a runtime from within a runtime" error.
Fixing this was not as simple as just removing the extra runtime being created.
This is because we cannot simply reuse the tokio runtime instance created by
the test (e.g., the one implicitly created via [actix_web::test]) to create the
compiler, local runner and api futures.  The reason is that when the first
test completes, these …
=> integration-test: fix local pipeline manager initialization regression 

.gitignore, Cargo.toml, crates/adapters/Cargo.toml, crates/dataflow-jit/Cargo.toml, crates/dbsp/Cargo.toml, crates/dbsp/src/algebra/present.rs, crates/dbsp/src/lib.rs, crates/nexmark/Cargo.toml, crates/pipeline_manager/Cargo.toml, crates/webui-tester/Cargo.toml, demo/project_demo00-SecOps/simulator/Cargo.toml, sql-to-dbsp-compiler/lib/hashing/Cargo.toml, sql-to-dbsp-compiler/lib/readers/Cargo.toml, sql-to-dbsp-compiler/lib/sqllib/Cargo.toml, sql-to-dbsp-compiler/lib/sqlvalue/Cargo.toml, sql-to-dbsp-compiler/lib/tuple/Cargo.toml, sql-to-dbsp-compiler/temp/Cargo.toml
This series of commits makes some progress toward making dbsp crates (especially `dbsp` itself) publishable on crates. See issue #14 for a tracking issue for progress.
=> Packaging for crates.io

web-console/src/lib/components/streaming/management/PipelineTable.tsx
Before we were using deprecated form of router.
=> Attempt at fixing button clicks in Chrome based browser by using new hook from nextjs.

Cargo.lock, crates/adapters/src/catalog.rs, crates/adapters/src/format/json/input.rs, crates/adapters/src/format/json/mod.rs, crates/adapters/src/format/json/output.rs, crates/adapters/src/server/mod.rs, crates/adapters/src/test/data.rs, crates/adapters/src/transport/kafka/test.rs, crates/dbsp/src/operator/distinct.rs, crates/dbsp/src/operator/filter_map.rs, crates/dbsp/src/operator/time_series/rolling_aggregate.rs, crates/dbsp/src/operator/upsert.rs, crates/pipeline_manager/src/db/test.rs, crates/pipeline_manager/src/integration_test.rs
=> Make output streams distinct.

web-console/src/lib/components/connectors/dialogs/KafkaInputConnector.tsx, web-console/src/lib/components/connectors/dialogs/tabs/TabKafkaInputDetails.tsx, web-console/src/lib/components/home/WelcomeCard.tsx, web-console/src/lib/functions/connectors.ts
=> Add group id for kafka

web-console/package.json, web-console/yarn.lock
=> Downgrade iconfiy icons.

Earthfile, README.md, deploy/README.md, deploy/docker-compose.yml, docs/intro.md, scripts/bump-versions.sh
Also adapts the release script to update the container image version in docker-compose.yml, and uses cargo metadata to find the current pipeline-manager package version.
=> docker: make the feldera version configurable

docs/contributors/dev-flow.md, web-console/src/lib/components/home/pipelines/PipelineThumb.tsx
Fix a link in docs
Fix formatting of tput in Home page
=> Minor fixes

docs/demo/demo.md, docs/tour/tour.md
localhost:8085 -> localhost:8080
=> Fix port number in docs.

crates/pipeline_manager/src/api.rs, deploy/Dockerfile
=> pipeline-manager: banner URL and documentation link fixes

web-console/src/lib/components/connectors/dialogs/KafkaInputConnector.tsx, web-console/src/lib/components/connectors/dialogs/tabs/TabKafkaInputDetails.tsx
=> Make sure having no topics is invalid for kafka input.

web-console/src/lib/components/connectors/dialogs/tabs/TabKafkaInputDetails.tsx
=> Don't require user to press enter when adding one topic at the time.

web-console/src/lib/components/connectors/dialogs/KafkaOutputConnector.tsx, web-console/src/lib/components/connectors/dialogs/tabs/TabKafkaOutputDetails.tsx, web-console/src/lib/functions/connectors.ts
=> Remove auto.offset.reset for kafka output.

crates/dbsp/src/algebra/lattice.rs, crates/dbsp/src/algebra/order.rs, crates/dbsp/src/circuit/circuit_builder.rs, crates/dbsp/src/circuit/operator_traits.rs, crates/dbsp/src/time/antichain.rs, crates/dbsp/src/time/mod.rs, crates/dbsp/src/time/nested_ts32.rs, crates/dbsp/src/trace/cursor/mod.rs, crates/dbsp/src/trace/mod.rs, crates/dbsp/src/trace/spine_fueled.rs
I was really confused and I spent some time reading code.  I hope that this documentation helps reduce confusion for others.
=> dbsp: Add documentation for traces and times.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitCastTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitPostgresDateTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitTimeTests.java
This is a follow up from the recent fixes to the JIT.
=> JIT support for more date/time functions

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/CalciteCompilerTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitTimeTests.java
=> Nicer error reporting for duplicate column names

Earthfile, crates/adapters/src/controller/mod.rs, crates/adapters/src/format/csv.rs, crates/adapters/src/format/json/input.rs, crates/adapters/src/format/json/output.rs, crates/adapters/src/format/mod.rs, crates/adapters/src/server/mod.rs, crates/adapters/src/test/http.rs, crates/adapters/src/test/kafka.rs, crates/adapters/src/test/mock_output_consumer.rs, crates/adapters/src/transport/file.rs, crates/adapters/src/transport/http/output.rs, crates/adapters/src/transport/kafka/output.rs, crates/adapters/src/transport/kafka/test.rs, crates/adapters/src/transport/mod.rs, crates/adapters/src/util.rs
=> Enforce max Kafka message size

crates/dbsp/src/trace/persistent/tests/proptests.rs, crates/dbsp/src/trace/persistent/trace.rs
This doesn't change behavior, it just makes the code easier to read (for me).
=> Rocksdb concat merge

crates/adapters/src/test/kafka.rs
Just because `create_topics` succeeded doesn't guarantee the new topics are avilable (see https://github.com/confluentinc/confluent-kafka-python/issues/524).
This caused failures in Kafka tests when running on CI machines with slow disks.  The test harness deletes an existing instance of the topic before creating a new one, which seems to cause the delay because the previous instance is still being deleted when the
`create_topics` command arrives.
I added a probing loop that checks whether the topic is available to consume from for up to 20seconds to the test harness.
Question is, do we want to do something like this in the Kafka adapter. I don't want to do this by default, so that the adapters fails quickly if the topic truly doesn't exist (common case).  But this could be a config …
=> Kafka tests: wait for new topics to be available.

crates/adapters/src/transport/kafka/input.rs, demo/project_demo00-SecOps/run.py, demo/project_demo00-SecOps/simulator/src/main.rs, deploy/docker-compose.yml
=> Regression in secops demo

crates/dbsp/README.md
=> fix broken links to docs.rs

crates/adapters/src/test/kafka.rs
I found that even the previous check wasn't enough.  This fixes the problem for me.
This solves a problem for upcoming code that does more with topics and partitions immediately after Kafka comes up.  I have not seen this problem with the existing code.
I changed the backoff from 1 second to 100 ms plus doubling after each failure.  This is because I consistently see at least one backoff in my testing and 100 ms was consistently enough, so this avoids slowing the tests more than necessary.
=> dbsp_adapters: Check even more carefully that Kafka topics are created.

deploy/Dockerfile
e.g., passes
docker build -f deploy/Dockerfile --target release .
=> Make sure dockerfile is correct

crates/dataflow-jit/src/codegen/intrinsics/deserialize.rs, crates/dataflow-jit/src/codegen/intrinsics/mod.rs, crates/dataflow-jit/src/codegen/json/serialize.rs, crates/dataflow-jit/src/facade/demands.rs, crates/dataflow-jit/src/facade/handle.rs, crates/dataflow-jit/src/facade/mod.rs, crates/dataflow-jit/src/main.rs
=> [JIT] Implemented JIT output demands

crates/dataflow-jit/src/codegen/json/deserialize.rs, crates/dataflow-jit/src/facade/handle.rs, crates/dataflow-jit/src/facade/mod.rs
=> Small refactoring of the JIT facade to align it with adapters.

Cargo.lock, crates/dataflow-jit/src/codegen/intrinsics/mod.rs, crates/dataflow-jit/src/codegen/intrinsics/serialize.rs, crates/dataflow-jit/src/codegen/json/serialize.rs, crates/dataflow-jit/src/codegen/json/tests.rs, crates/dataflow-jit/src/codegen/mod.rs, crates/dataflow-jit/src/facade/demands.rs, crates/dataflow-jit/src/facade/mod.rs, crates/dataflow-jit/src/facade/tests.rs, crates/dataflow-jit/src/ir/ids.rs, crates/dataflow-jit/src/ir/mod.rs, crates/dataflow-jit/src/main.rs
* Switched to using demand ids (fixes #739)
* Fixed compilation failure when creating a default decimal type
* Switched serialization to fill a `Vec<u8>` instead of a `String` (fixes #736)
=> [JIT] Various Improvements

web-console/src/app/(root)/(app)/streaming/builder/page.tsx, web-console/src/app/(root)/(app)/streaming/inspection/page.tsx, web-console/src/app/(root)/layout.tsx, web-console/src/lib/components/connectors/DataSourceTable.tsx, web-console/src/lib/components/connectors/dialogs/AnyConnector.tsx, web-console/src/lib/components/connectors/dialogs/UnknownConnector.tsx, web-console/src/lib/components/connectors/dialogs/kafka/TabKafkaInputDetails.tsx, web-console/src/lib/components/connectors/drawer/AddSourceDrawer.tsx, web-console/src/lib/components/streaming/builder/NodeTypes/InputNode.tsx, web-console/src/lib/components/streaming/builder/NodeTypes/OutputNode.tsx, web-console/src/lib/components/streaming/inspection/InspectionTable.tsx, web-console/src/lib/components/streaming/inspection/InspectionToolbar.tsx, web-console/src/lib/components/streaming/inspection/RowDeleteButton.tsx, web-console/src/lib/components/streaming/management/PipelineTable.tsx, web-console/src/lib/functions/connectors.ts, web-console/src/lib/types/connectors.ts
Implement https://github.com/feldera/feldera/issues/664
Fix https://github.com/feldera/feldera/issues/671
Fix https://github.com/feldera/feldera/issues/672
Fix https://github.com/feldera/feldera/issues/713
Fix https://github.com/feldera/feldera/issues/687
=> Enable editing connectors in Pipeline Builder, UI fixes

Cargo.lock, crates/pipeline_manager/Cargo.toml, python/feldera-api-client/pyproject.toml
=> release: bump project version to 0.1.5

deploy/docker-compose.yml
=> Post release v0.1.5

CHANGELOG.md
=> Start v0.1.4 changelog

CHANGELOG.md
=> docs: add changelog for 0.1.5 release

crates/adapters/src/controller/mod.rs, crates/adapters/src/test/mod.rs, crates/adapters/src/transport/file.rs, crates/adapters/src/transport/kafka/input.rs, crates/adapters/src/transport/kafka/output.rs, crates/adapters/src/transport/mod.rs, crates/adapters/src/transport/url.rs
These are things I spotted while reading code. They do not affect functionality, so if whoever reads them doesn't like them, I'll drop it.
=> Minor code cleanups for `dbsp_adapters`

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/README.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/ZSet.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/package-info.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/types/IntegerSqlType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/types/IntegerWeight.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/types/SqlType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/types/SqlTypeBase.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/types/SqlTypeName.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/types/StringSqlType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/types/UnlimitedWeight.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/types/WeightType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/types/package-info.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/values/BaseSqlValue.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/values/DynamicSqlValue.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/values/IntegerSqlValue.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/values/SqlTuple.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/values/StringSqlValue.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/values/package-info.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/simulator/SimulatorTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/simulator/package-info.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresTimeTests.java
=> Code supporting the blog post for Java Z-sets implementation

crates/dataflow-jit/src/codegen/intrinsics/mod.rs, crates/dataflow-jit/src/codegen/layout.rs, crates/dataflow-jit/src/codegen/vtable/cmp.rs, crates/dataflow-jit/src/row.rs
=> [JIT] Fixed issue with nullish and padding values producing wrong eq results

CONTRIBUTING.md, crates/dataflow-jit/src/codegen/layout.rs, crates/dataflow-jit/src/codegen/mod.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/DBSPAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JitDbspExecutor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/TestCase.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs, sql-to-dbsp-compiler/lib/sqllib/src/operators.rs, sql-to-dbsp-compiler/lib/sqllib/src/string.rs
=> [JIT] Fix bug in aggregate code generation

crates/pipeline_manager/src/integration_test.rs
=> integration-test: allow configurable shutdown and failed timeouts

Cargo.lock, Earthfile, crates/adapters/Cargo.toml, deploy/Dockerfile
=> build: statically compile in SSL for rdkafka

Earthfile, crates/adapters/src/catalog.rs, crates/adapters/src/format/csv.rs, crates/adapters/src/format/json/mod.rs, crates/adapters/src/format/mod.rs, crates/adapters/src/jit/pipeline.rs, crates/adapters/src/server/mod.rs, crates/adapters/src/static_compile/deserialize_with_context.rs, crates/adapters/src/transport/kafka/input.rs, crates/adapters/tests/jit_integration_test.rs, crates/dataflow-jit/src/facade/mod.rs, crates/dbsp/src/algebra/arcstr.rs, crates/dbsp/src/time/antichain.rs, crates/dbsp/src/time/nested_ts32.rs, crates/dbsp/src/trace/mod.rs, crates/dbsp/src/trace/spine_fueled.rs, crates/dbsp/src/tutorial.rs
=> Add format-check to Earthfile.

CHANGELOG.md, crates/adapters/src/transport/kafka/output.rs
Fixes https://github.com/feldera/feldera/issues/842
=> Fix busy-wait loop in Kafka producer.

crates/pipeline_manager/src/db/test.rs, crates/pipeline_manager/src/integration_test.rs
=> integration-test: run migrations in itest (#856 postfix)

CHANGELOG.md, web-console/src/lib/components/home/Health.tsx
Fix https://github.com/feldera/feldera/issues/784
=> Prefer last lines of output when reporting an error

Cargo.lock, crates/pipeline_manager/Cargo.toml, python/feldera-api-client/pyproject.toml
=> release: bump project version to 0.1.7

CHANGELOG.md, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml, scripts/bump-versions.sh
=> Post release v0.1.7

crates/dataflow-jit/src/codegen/mod.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/OutputViewDescription.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/operators/JITOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TypeCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPIfExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPUnaryExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPI32Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JitDbspExecutor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JitTestBatch.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/TestBatch.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Utilities.java
This PR looks bigger than it is: most of the code that changed has been moved from the JitDbspExecutor to the JitTestBatch class.
The PR includes two bug fixes in the JIT code generator.
With this change we can run 10K JIT tests in one execution.
=> Batch execution of JIT SLT tests

CHANGELOG.md, docs/contributors/compiler.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateRelationStatement.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java
=> Emit primary key information as metadata from compiler

docs/connectors/sources/debezium-mysql.md
Draft for the Debezium-MySQL source connector.
=> doc: Debezium-MySQL source connector

CHANGELOG.md, Earthfile, deploy/docker-compose.yml
=> docker: fix regression caused by backward-incompatible argument use

scripts/pre-push, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/instructions/JITUnaryInstruction.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/EliminateFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Utilities.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitFpTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitPostgresNumericTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresNumericTests.java
=> [SQL] Implement JIT numeric operations 

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/ZSet.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/simulator/SimulatorTests.java
Forgot to add these when I added the code for the blog post.
=> Missing simulator code for blog post

crates/dataflow-jit/src/codegen/call.rs, crates/dataflow-jit/src/codegen/intrinsics/deserialize.rs, crates/dataflow-jit/src/codegen/intrinsics/mod.rs, crates/dataflow-jit/src/codegen/intrinsics/serialize.rs, crates/dataflow-jit/src/codegen/json/deserialize.rs, crates/dataflow-jit/src/codegen/json/serialize.rs, crates/dataflow-jit/src/codegen/json/tests.rs, crates/dataflow-jit/src/codegen/mod.rs, crates/dataflow-jit/src/codegen/utils.rs, crates/dataflow-jit/src/codegen/vtable/clone.rs, crates/dataflow-jit/src/codegen/vtable/cmp.rs, crates/dataflow-jit/src/codegen/vtable/csv.rs, crates/dataflow-jit/src/codegen/vtable/debug.rs, crates/dataflow-jit/src/codegen/vtable/hash.rs, crates/dataflow-jit/src/codegen/vtable/tests.rs, crates/dataflow-jit/src/facade/mod.rs, crates/dataflow-jit/src/ir/exprs/constant.rs, crates/dataflow-jit/src/ir/exprs/mod.rs, crates/dataflow-jit/src/ir/types.rs, crates/dataflow-jit/src/main.rs, crates/dataflow-jit/src/row.rs, crates/dataflow-jit/src/utils.rs
Implements support for the time type within the jit
=> Implement time type in jit

crates/adapters/Cargo.toml, crates/dbsp/Cargo.toml, crates/pipeline_manager/Cargo.toml, sql-to-dbsp-compiler/lib/sqllib/Cargo.toml, sql-to-dbsp-compiler/temp/Cargo.toml
=> Update Rust chrono library versions

crates/dataflow-jit/src/tests/issue_902.json, crates/dataflow-jit/src/tests/issue_902.rs, crates/dataflow-jit/src/tests/mod.rs
#902 seems to be fixed on main, so I just added a regression test for it
cc @mihaibudiu, I couldn't reproduce so could you confirm?
=> Added regression test for #902

crates/dataflow-jit/proptest-regressions/codegen/tests.txt, crates/dataflow-jit/src/codegen/call.rs, crates/dataflow-jit/src/codegen/intrinsics/mod.rs, crates/dataflow-jit/src/codegen/intrinsics/time.rs, crates/dataflow-jit/src/codegen/math.rs, crates/dataflow-jit/src/codegen/mod.rs, crates/dataflow-jit/src/codegen/tests.rs, crates/dataflow-jit/src/codegen/vtable/cmp.rs, crates/dataflow-jit/src/codegen/vtable/mod.rs, crates/dataflow-jit/src/facade/mod.rs, crates/dataflow-jit/src/ir/function/builder.rs, crates/dataflow-jit/src/ir/row_layout.rs, crates/dataflow-jit/src/ir/types.rs, crates/dataflow-jit/src/main.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/JitCsvInputDescription.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitPostgresNumericTests.java
- Implements sqrt for decimal types
- Fixes decimal equality bug (native repr of decimals can't be compared bitwise)
- Implemented time functions
- `@dbsp.time.hour(time) -> u32`
- `@dbsp.time.minute(time) -> u32`
- `@dbsp.time.second(time) -> u32`
- `@dbsp.time.millisecond(time) -> u32`
- `@dbsp.time.microsecond(time) -> u32`
=> Utility Functions

crates/dataflow-jit/src/ir/exprs/constant.rs, crates/dataflow-jit/src/ir/validate.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToRustJitLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/instructions/JITLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/types/JITU32Type.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPStringLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPVecLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeCode.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Utilities.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitPostgresTimeTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresTimeTests.java
Note that this also fixes a bug in time parsing in the dataflow-jit crate.
=> [SQL] JIT code generation for Time datatype

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, deploy/docker-compose.yml, python/feldera-api-client/pyproject.toml
=> release: bump project version to 0.2.0

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitFpTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitPostgresNumericTests.java
=> Enable JIT tests that pass

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> Post release v0.2.0

CHANGELOG.md, deploy/docker-compose.yml
=> Reduce docker logging noise

crates/adapters/src/jit/deinput.rs, crates/adapters/src/jit/json.rs, crates/adapters/src/jit/mod.rs, crates/adapters/src/jit/schema.rs, crates/adapters/tests/jit_integration_test.rs, crates/dataflow-jit/src/facade/mod.rs, crates/dataflow-jit/src/ir/graph/mod.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/CompilerMain.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPMapOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMapOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/InputTableDescription.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/JitCsvInputDescription.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/operators/JITSourceMapOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/operators/JITSourceOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/operators/JITSourceSetOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustHandleVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/IncrementalizeVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeIncrementalVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeProjectionVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/RemoveDeindexOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Utilities.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java
The corresponding new test is disabled waiting for #890
=> [SQL] support for tables with primary keys in JIT

crates/pipeline_manager/src/bin/migrations.rs
=> pipeline-manager: make sure migrations script returns non-zero error code on failure

CHANGELOG.md, docs/cloud/assets.md, docs/cloud/deployment.md, docs/cloud/index.md, docs/sidebars.js
Restructure the cloud documentation into its own directory with separate files and add extra explanation/wording.
=> doc: cloud restructure

crates/pipeline_manager/src/api.rs, crates/pipeline_manager/src/local_runner.rs, python/feldera-api-client/feldera_api_client/models/update_program_request.py
Is this a user-visible change (yes/no): no (the breaking change won't make it to a published release)
=> Jit mode postfix

crates/pipeline_manager/src/integration_test.rs, crates/pipeline_manager/src/pipeline_automata.rs
It's not a good user experience to have pipelines be marked as failed when there are intermittent failures, especially when they only exist between the runner and the pipeline itself.
This patch makes the pipeline automata also probe pipelines when in a failed state to catch intermittent issues. It also increases initialization timeouts which can be a concern in a cluster manager setting (due to connectivity issues not being a function of the pipeline itself, but of the networking control plane being slow).
=> pipeline-manager: probe pipelines even after failure

crates/pipeline_manager/src/pipeline_automata.rs
Updating the pipeline status causes a DB update, which in turn awakens the pipeline automata loop via a notification. We therefore avoid spurious updates when the actual pipeline status doesn't change.
=> pipeline-manager: avoid spurious status updates on failure

docs/cloud/secret-management.md, docs/connectors/sources/debezium-mysql.md, docs/sidebars.js
=> Documentation: secret management

crates/pipeline_manager/src/integration_test.rs
=> itest: shutdown pipeline at test end

docs/sql/aggregates.md, docs/sql/grammar.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIndexedTopKOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDate.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/TopKTests.java
=> Support for DENSE_RANK and ROW_NUMBER in TopK

CHANGELOG.md, web-console/src/lib/components/home/Pipelines.tsx, web-console/src/lib/components/streaming/inspection/InspectionTable.tsx, web-console/src/lib/components/streaming/inspection/InspectionToolbar.tsx, web-console/src/lib/components/streaming/management/PipelineTable.tsx, web-console/src/lib/compositions/streaming/inspection/useTableUpdater.ts
Increase refetch interval for Pipeline Metrics
Fix https://github.com/feldera/feldera/issues/603
Fix https://github.com/feldera/feldera/issues/893
=> Implement pause/resume for displaying rows in Data Inspection table

crates/pipeline_manager/src/pipeline_automata.rs
=> pipeline-manager: avoid another point of spurious failure updates (#972 postfix)

crates/pipeline_manager/src/pipeline_automata.rs
=> Improve debug messages for state transitions

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, python/feldera-api-client/pyproject.toml
=> release: bump project version to 0.3.0

CHANGELOG.md, crates/pipeline_manager/src/api.rs
=> pipeline-manager: display version below Feldera banner

crates/adapters/src/controller/mod.rs, crates/adapters/src/controller/stats.rs, crates/adapters/src/format/json/input.rs, crates/adapters/src/format/mod.rs, crates/adapters/src/lib.rs, crates/adapters/src/test/kafka.rs, crates/adapters/src/test/mock_input_consumer.rs, crates/adapters/src/test/mock_output_consumer.rs, crates/adapters/src/test/mod.rs, crates/adapters/src/transport/durable_kafka/input.rs, crates/adapters/src/transport/durable_kafka/mod.rs, crates/adapters/src/transport/durable_kafka/output.rs, crates/adapters/src/transport/durable_kafka/test.rs, crates/adapters/src/transport/file.rs, crates/adapters/src/transport/http/input.rs, crates/adapters/src/transport/http/output.rs, crates/adapters/src/transport/kafka/input.rs, crates/adapters/src/transport/kafka/mod.rs, crates/adapters/src/transport/kafka/output.rs, crates/adapters/src/transport/kafka/test.rs, crates/adapters/src/transport/mod.rs, crates/adapters/src/transport/url.rs, crates/pipeline-types/src/transport/durable_kafka.rs, crates/pipeline-types/src/transport/mod.rs
This is a resubmission of PR #960, which had failures in CI after merge. This version ran and passed CI 5 times in a row, as well as on my own machine, so I think it's ready.
=> (Resubmit) Add basic fault tolerance that requires replay from start.

web-console/src/lib/compositions/streaming/inspection/useTableUpdater.ts
Fix https://github.com/feldera/feldera/issues/993
=> Fix Data browser shows the same data in all views

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, python/feldera-api-client/pyproject.toml
=> Release v0.3.1

crates/adapters/src/controller/mod.rs
=> adapters: reduce log noise

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, python/feldera-api-client/pyproject.toml
=> Release v0.3.2

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> docker: point compose file to Feldera version 0.3.2

docs/sql/string.md, sql-to-dbsp-compiler/SQL-compiler/pom.xml, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPVecLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBaseType.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/TimestampdiffTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresArrayTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresBaseTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresFloat4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresNumericTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresStringTests.java, sql-to-dbsp-compiler/lib/sqllib/src/string.rs, sql-to-dbsp-compiler/slt/pom.xml
This allows us to re-enable some of the tests which failed due to Calcite bugs.
=> Upgrade to Calcite 1.36

crates/adapters/src/transport/kafka/ft/input.rs, crates/adapters/src/transport/kafka/ft/mod.rs, crates/adapters/src/transport/kafka/ft/test.rs
Fix a bug found while working on test_empty_input, and then re-enable test_empty_input, in the fault-tolerant Kafka implementation.
=> Fault tolerance fixes

docs/tour/tour.md
=> docs: Fix capitalization error in docs.

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, python/feldera-api-client/pyproject.toml, scripts/bump-versions.sh
=> release: bump project version to 0.4.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> docker: point compose file to Feldera version 0.4.0

docs/sql/aggregates.md
=> Capitalization error upset yarn.

docs/sql/aggregates.md, docs/sql/grammar.md
=> Document BIT* aggregate functions

CONTRIBUTING.md
Fixes https://github.com/feldera/feldera/issues/689
=> docs: document release process

CHANGELOG.md, web-console/src/lib/components/streaming/management/PipelineTable.tsx
Fix https://github.com/feldera/feldera/issues/1032
=> Add "Queued" status for pipelines whose programs are enqueued to be compiled

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ComplexQueriesTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/foodmart/FoodmartBaseTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpchTest.java
=> [SQL] Fix bug when generating code with --ignoreOrder

docs/tutorials/basics/part1.md
=> docs: Add missing punctuation mark.

crates/pipeline_manager/src/config.rs, crates/pipeline_manager/src/probe.rs, docs/contributors/dev-flow.md
=> Authentication documentation

crates/pipeline_manager/src/pipeline_automata.rs
=> pipeline-manager: correctly cleanup automaton after pipeline deletions

sql-to-dbsp-compiler/SQL-compiler/pom.xml, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/AggregateDescription.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/collections/BaseCollection.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/collections/IndexedZSet.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/collections/ZSet.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/collections/package-info.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/operators/BaseOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/operators/FilterOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/operators/IndexOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/operators/JoinOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/operators/SelectOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/operators/UnaryOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/operators/package-info.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/InputTableDescription.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/TriFunction.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/simulator/SimulatorTests.java
=> [blog] Support code for Z-set blog post

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, python/feldera-api-client/pyproject.toml
=> release: bump project version to 0.5.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
- docker: point compose file to Feldera version 0.5.0
=> post release v0.5.0

crates/pipeline_manager/src/api.rs, python/feldera-api-client/feldera_api_client/api/manager/get_authentication_config.py
Partially addresses the issue in https://github.com/feldera/feldera/issues/1084
=> pipeline-manager: remove relative path from config/authentication API doc

CONTRIBUTING.md, README.md
=> docs: refer to Feldera instead of DBSP in README and CONTRIBUTING

sql-to-dbsp-compiler/lib/readers/src/lib.rs
=> sql-lib: add missing test dependencies

CHANGELOG.md, docs/sql/float.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TrigonometryTests.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
* Add trigonometric functions: tan, cot, asin, acos, atan, atan2, degrees, radians
* Add the cube root function cbrt
* Handle edge cases for casting floating point numbers to string
Fixes: #1124
=> [SQL] Add trigonometric functions

docs/demo/demo.md
The schema and relationships aren't shown above.  (They are shown below, but I don't think it's necessary to say that.)
=> Minor documentation fix.

crates/pipeline_manager/src/api/mod.rs
=> pipeline-manager: reduce actix log clutter due to /healthz probes

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, python/feldera-api-client/pyproject.toml
=> release: bump project version to 0.6.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> docker: point compose file to Feldera version 0.6.0

web-console/src/app/(root)/(authenticated)/(app)/analytics/editor/page.tsx, web-console/src/app/(root)/(authenticated)/(app)/streaming/builder/page.tsx, web-console/src/lib/components/analytics/TableSqlPrograms.tsx, web-console/src/lib/components/connectors/drawer/AddSourceDrawer.tsx, web-console/src/lib/components/home/Health.tsx, web-console/src/lib/components/home/pipelines/PipelineThumb.tsx, web-console/src/lib/components/layouts/analytics/editor.tsx, web-console/src/lib/components/streaming/builder/NoSchemaDialog.tsx, web-console/src/lib/components/streaming/management/PipelineTable.tsx, web-console/src/lib/components/streaming/management/RevisionStatus.tsx, web-console/src/lib/services/manager/models/AttachedConnector.ts, web-console/src/lib/services/manager/models/NewPipelineRequest.ts, web-console/src/lib/services/manager/models/PipelineDescr.ts, web-console/src/lib/services/manager/models/UpdatePipelineRequest.ts, web-console/src/lib/services/pipelineManagerQuery.ts
Change UI to reference programs and connectors by name when managing pipelines
=> Use new API to reference programs and connectors

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPApplyOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPControlledFilterOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/TranslateVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneRef.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneValue.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/RefProjection.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/ScalarProjection.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/TupleProjection.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/ValueProjection.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/MonotoneOperators.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/CastTests.java, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
=> [SQL] Adapt lateness dataflow analysis to work with dereferences

docs/sql/casts.md, docs/sql/datetime.md, docs/sql/integer.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/CompilerMain.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/DBSPPartialCircuit.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/IErrorReporter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/StderrErrorReporter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TypeCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/Catalog.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/FindDeadCode.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Repeat.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/DBSPNode.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/BaseSQLTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TestCase.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/CastTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs
Fixes #1180
Also, made the documentation on casts more explicit for abnormal behaviors.
=> [SQL] Fix incorrect simplification of constant casts to integers

sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs
=> [SQL] Run time error if casting string to integer fails

sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt2Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt8Tests.java
=> [SQL] Add tests for casting between Integer types

Earthfile
This adds a stage to the Earthfile to test whether DB migrations work from the last stable release to the tested commit.
For now, this stage only tests whether the API server and DB are functioning at all after the migration. Going forward, we'll need some suite of tests we run instead (e.g., trying to run pipelines that were created before the migration and assert that they continue to work).
=> docker: test migrations from the last stable release

sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/SqlIoTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java
=> [SQL] Add SQLIoTest::qf for failing rust test case

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPControlledFilterOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainKeysOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPJoinOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/MonotoneOperators.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPBlockExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ComplexQueriesTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresAggregatesTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresArrayTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresBoolTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresCaseTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresCollateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresDateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresIntervalTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresLimitTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresStringTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresTimeTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresTimestampTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/PivotTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TopKTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/NexmarkTest.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs
=> [SQL] Bounded join storage using lateness

docs/sql/integer.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/SqlIoTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt2Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt8Tests.java, sql-to-dbsp-compiler/lib/sqllib/src/operators.rs
Should be merged after #1179 
Fixes: #1195
=> [SQL] Handle modulo operations with negative values

sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TinyintTests.java
Fixes: #1145
The tests are hand written taking inspiration from Postgres Integer tests.
=> [SQL] Add tests for TINYINT

crates/dbsp/src/circuit/dbsp_handle.rs, crates/dbsp/src/circuit/runtime.rs
Record information about panics that occur in worker threads in the DBSP runtime and return this information to DBSP API callers via `Error::WorkerPanic` (which previously only contained failing worker id and no detailed error info).
This works by installing a custom Rust panic handler.
This commit also makes the handling of panics more robust by using the crossbeam `Select` object to listen for replies from all worker threads in parallel so that if one of them crashes and the others get stuck waiting for it, the API returns an error instead of going in a deadlock state.  In addition, upon detecting a panic the DBSP API will return an error immediately without waiting for all worker threads to terminate.
Addresses #1208 
=> Return detailed worker panic info from DBSP API methods.

CHANGELOG.md, docs/contributors/dev-flow.md, web-console/package.json, web-console/src/@core/layouts/components/shared-components/UserDropdown.tsx, web-console/src/app/(root)/(blank)/auth/aws/page.tsx, web-console/src/app/(root)/(blank)/login/page.tsx, web-console/src/lib/compositions/auth/useAuth.ts, web-console/yarn.lock
=> Display authorized user name

docs/sidebars.js, docs/sql/udf.md
Signed-off-by: Lalith Suresh <suresh.lalith@gmail.com>
=> docs: fix docusaurus build failure and leave a disclaimer for UDF feature

.earthlyignore, .gitignore, Earthfile, crates/pipeline_manager/src/bin/pipeline-manager.rs, openapi.json
We check in the OpenAPI spec so that we confirm on every
CI build whether it needs to be updated. Given that the spec
is also consumed by other repositories (like to generate our
website), it frees downstream consumers from having to build
the pipeline manager first (to retrieve the spec).
=> build: check in openapi.json

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json, python/feldera-api-client/pyproject.toml
=> release: bump project version to 0.7.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> docker: point compose file to Feldera version 0.7.0

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/collections/IndexedZSet.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/simulator/SimulatorTests.java
=> [blog] Code samples in the new blog post

Cargo.lock, openapi.json, python/feldera-api-client/feldera_api_client/models/new_pipeline_request.py, python/feldera-api-client/feldera_api_client/models/update_pipeline_request.py
=> Bump Rust dependencies flagged by dependabot.

sql-to-dbsp-compiler/README.md
This links to my personal OneDrive, but this is best, because I make frequent updates to this document,
=> [SQL] [doc] Link to always-fresh OneDrive documentation about SQL compiler

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPTupleExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPZSetLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
Fixes #1252 
From now on we run tests using 2 worker threads.
=> [SQL] Generate constants in a single thread

CHANGELOG.md, docs/sidebars.js, docs/videos.md
=> Adding a markdown page for videos

crates/dbsp/src/operator/distinct.rs, crates/dbsp/src/operator/time_series/radix_tree/partitioned_tree_aggregate.rs, crates/dbsp/src/operator/trace.rs, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TestCase.java
=> Issue 1260

web-console/src/app/(root)/(authenticated)/(app)/streaming/builder/page.tsx, web-console/src/lib/components/layouts/analytics/editor.tsx, web-console/src/lib/compositions/analytics/useUpdateProgram.ts, web-console/src/lib/compositions/streaming/builder/useUpdatePipeline.ts, web-console/src/lib/services/pipelineManagerQuery.ts
I did not update CHANGELOG.md because these are the regressions that were introduced within this sprint
Fix https://github.com/feldera/feldera/issues/1273 : Pipeline start/pause buttons no longer show the spinning wheel
Fix https://github.com/feldera/feldera/issues/1274 : Odd "Saved" button behavior with empty pipeline name
Fix https://github.com/feldera/feldera/issues/1275 : Web Console allows saving empty program name
Fix https://github.com/feldera/feldera/issues/1276 : Pipeline editort overlaps with "Add a new output"
=> Fix recent Program and Pipeline regressions

Cargo.lock, crates/feldera-storage/Cargo.toml
I missed this during cleanup before merging my previous pull request.
=> feldera-storage: Remove unnecessary dependency.

deploy/Dockerfile
=> docker: copy feldera-storage crate for compiler service

crates/dbsp/src/operator/trace.rs
Possibly obvious to others but not to me.
=> dbsp: Add circuit diagram to trace operator.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpcDsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/resources/tpcds.sql
The sources currently do not compile due to two bugs:
(1) a bug in the Calcite optimizer which crashes when optimizing some classes of joins
(2) #1281
=> [SQL] Add TPC-DS sources (currently test is disabled)

Earthfile, crates/dbsp/src/tutorial.rs, crates/nexmark/src/queries/q13.rs, docs/contributors/compiler.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/SanitizeStructNames.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeStruct.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/BaseSQLTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/SqlIoTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TestCase.java, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DbspJdbcExecutor.java
=> Document Rust code produced by the compiler

crates/pipeline_manager/src/config.rs
=> pipeline-manager: set up the minimal CORS configuration for docs API calls

Earthfile
The Earthly build currently spends time building clippy and test code for
crates when trying to selectively build some test stages (e.g., UI tests).
While fine in the CI (where the cache is always warm), it is quite painful for
local builds where we run some later stages to debug build failures occasionally.
It can take north of 30 minutes sometimes just to build through the whole
sequence once.
With the rust UDC we now use, we can lean on the cache to simplify and speedup
the build to avoid this case.
* Run clippy for the entire project in a separate stage, instead of once per stage.
* Run only `cargo build` during `+build-*` stages.
* Run only `cargo test` during `+test-*` stages.
This should make Earthly builds faster, especially for local builds.
Signed-off-by: Lalith Suresh …
=> build: only run cargo build during build-phase

docs/contributors/compiler.md
=> docs: fix a broken link

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json, python/feldera-api-client/pyproject.toml
=> release: bump project version to 0.8.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> docker: point compose file to Feldera version 0.8.0

Cargo.toml, crates/dbsp/src/utils/tuple/gen.rs, crates/dbsp/src/utils/tuple/mod.rs, docs/sql/string.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresStringTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpchTest.java, sql-to-dbsp-compiler/lib/hashing/src/lib.rs, sql-to-dbsp-compiler/lib/readers/Cargo.toml, sql-to-dbsp-compiler/lib/readers/src/lib.rs, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs, sql-to-dbsp-compiler/lib/sqllib/src/string.rs, sql-to-dbsp-compiler/lib/sqlvalue/src/lib.rs, sql-to-dbsp-compiler/run-tests.sh, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/Main.java, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/InputFunctionGenerator.java
=> [SQL] Handle correctly NULL arguments to several string functions

crates/feldera-storage/src/backend/mod.rs, crates/feldera-storage/src/bin/bench.rs, crates/feldera-storage/src/buffer_cache/mod.rs, crates/feldera-storage/src/file/mod.rs, crates/feldera-storage/src/lib.rs
=> feldera-storage: Fix errors from `cargo doc`.

Cargo.lock, crates/feldera-storage/Cargo.toml, crates/feldera-storage/proptest-regressions/backend/monoio_impl/tests.txt, crates/feldera-storage/proptest-regressions/buffer_cache/tests.txt, crates/feldera-storage/src/backend/monoio_impl/mod.rs, crates/feldera-storage/src/bin/bench.rs, crates/feldera-storage/src/buffer_cache/fbuf.rs, crates/feldera-storage/src/file/writer.rs, crates/feldera-storage/src/lib.rs
- Fix bug in bench binary when reporting read/write.
- Open files with Direct IO on monoio since we do our own caching.
- Minor improvements.
=> Fix storage benchmark.

CHANGELOG.md, docs/sql/decimal.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TinyintTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt2Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt8Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresNumericTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/CastTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
Alternative approach to: #1226
=> [SQL] Check decimal precision while casting

Cargo.lock, crates/feldera-storage/Cargo.toml, crates/feldera-storage/src/backend/glommio_impl/mod.rs, crates/feldera-storage/src/backend/glommio_impl/tests.rs, crates/feldera-storage/src/backend/monoio_impl/mod.rs, crates/feldera-storage/src/backend/monoio_impl/tests.rs, crates/feldera-storage/src/buffer_cache/cache.rs, crates/feldera-storage/src/buffer_cache/tests.rs, crates/feldera-storage/src/file/mod.rs, crates/feldera-storage/src/lib.rs, crates/feldera-storage/src/test.rs
Please see individual commits for proper explanations.
=> Locked memory limit and initialization order

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/EliminateFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
Fixes #1352 
I have moved some code from EliminateFunctions to ExpressionCompiler.
=> [SQL] Improve code generation for SQRT function

.github/workflows/benchmark-command.yml
=> Also upgrade benchmark-command CI.

crates/pipeline_manager/src/compiler.rs
The compiler server returns from its inner loop any time it encounters
an error when talking to the database. This is heavy-handed, given that
there are transient/benign errors it should simply recover from by
continuing its loop. One such instance of this is when the program is
outdated due to concurrent edits.
This patch allows the compiler to handle benign errors and resume normal
operation. It's more of a bandaid fix than I'd like; we'd ideally
refactor the compiler's inner loop instead and make the state machine
transitions testable.
Is this a user-visible change (yes/no): no (because it is a postfix for #1325)
=> pipeline-manager: the compiler should handle benign errors

.github/workflows/ci.yml
=> Print ulimit output in ci.yml

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ComplexQueriesTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/foodmart/FoodmartPivotTests.java
=> [SQL] Use a lossless encoding in Rust for floating point literals

CHANGELOG.md, Cargo.lock, Earthfile, crates/pipeline_manager/Cargo.toml, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml, openapi.json
=> release: bump project version to 0.9.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> Update container images.

crates/dbsp/src/operator/aggregate/mod.rs, crates/dbsp/src/operator/distinct.rs, crates/dbsp/src/operator/filter_map.rs, crates/dbsp/src/operator/input_upsert.rs, crates/dbsp/src/operator/join.rs, crates/dbsp/src/operator/trace.rs, crates/dbsp/src/operator/upsert.rs, crates/dbsp/src/trace/layers/file/column_layer/builders.rs, crates/dbsp/src/trace/ord/file/indexed_zset_batch.rs, crates/dbsp/src/trace/ord/file/mod.rs, crates/dbsp/src/trace/ord/file/val_batch.rs, crates/dbsp/src/trace/ord/file/zset_batch.rs, crates/dbsp/src/trace/ord/vec/mod.rs, crates/feldera-storage/src/file/mod.rs, crates/feldera-storage/src/file/reader.rs, crates/feldera-storage/src/file/writer.rs
The individual commits here are meaningful. I think that all of them except for the final commit are ones that make sense to merge even if we are not ready for storage to be enabled for everything.
@ryzhyk I realize you might not have time to review this now.
=> Keep traces that are likely to become large on storage

CHANGELOG.md, docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/SqlIoTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/DateFormatsTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresDateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresTimestampTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/NexmarkTest.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
Fixes #1397 
This contains both a new contribution and a fix because the bug was discovered while testing the new contribution. This needs a few more tests. It has uncovered 2 more bugs in Calcite.
=> [SQL] Support for format_date function; fix semantics of incorrect dates

CHANGELOG.md, docs/sql/aggregates.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/BaseSQLTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ComplexQueriesTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/NexmarkTest.java, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
=> Tumbling window support

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CustomFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
=> [SQL] Case-insensitive function name lookup

CHANGELOG.md, web-console/src/lib/components/settings/Authentication.tsx, web-console/src/lib/components/settings/CreateApiKeyDialog.tsx
Fix https://github.com/feldera/feldera/issues/1148
=> Show the entire generated API key

demo/demos/productitems-continuous/README.md, demo/demos/productitems-continuous/demo.json, demo/demos/productitems-continuous/demo.template.json, demo/demos/productitems-continuous/generate_continuous_data.py, demo/demos/productitems-continuous/generate_demo_json.py, demo/demos/productitems-continuous/program.sql
Continuous version of the ProductItems demo that uses Kafka input connectors.
=> demo: productitems-continuous

demo/demos/productitems-continuous/README.md
=> demo: productitems-continuous: fix url in readme

sql-to-dbsp-compiler/README.md
=> sql-to-dbsp-compiler: Update required Java version.

sql-to-dbsp-compiler/SQL-compiler/pom.xml, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/AvroSchemaWrapper.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CalciteTableDescription.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateRelationStatement.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/adapters/AvroSchemaTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/adapters/package-info.java
This is a first step in supporting the Kafka Schema Registry. This PR adds support for converting Avro schemas into Schemas that are understood by Calcite.
=> [SQL] Support for Avro schemas

demo/demos/product-availability/README.md, demo/demos/product-availability/demo.json, demo/demos/product-availability/demo.template.json, demo/demos/product-availability/generate_continuous_data.py, demo/demos/product-availability/generate_demo_json.py, demo/demos/product-availability/program.sql
=> demo: product-availability

Earthfile, deploy/docker-compose-debezium.yml
Additionally, pull correct debezium mysql version in Earthfile.
=> demo: debezium-mysql: change demo sleep and healthcheck timeout

docs/tutorials/basics/part2.md
Two separate `curl` commands update tables, so there are two separate output updates instead of one.
=> docs: Fix output in basics tutorial part 2.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java
=> [SQL] Change type inference for arithmetic operations

crates/adapters/src/controller/mod.rs
=> Synchronization bug deleting an output endpoint

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.10.0

CHANGELOG.md, Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> Post release v0.10.0

crates/dbsp/src/circuit/dbsp_handle.rs
Until now, this test left 3 threads blocking in `sleep` in the kernel. This avoids the resource leak.
=> dbsp: Avoid leaking threads in `test_panic_no_deadlock`.

sql-to-dbsp-compiler/lib/readers/src/lib.rs
=> Fix cargo test for sqllib

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.11.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> docker: point compose file to Feldera version 0.11.0

Earthfile, rustfmt.toml, scripts/pre-push
See individual commits for more info.
=> Enable backtraces in tests and avoid rustfmt unstable features.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateViewStatement.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggScottTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/PostBaseTests.java
=> [SQL] Handle correctly queries that need columns that are never in the final result

docs/faq.md
Please suggest more questions and answers, or changes.
This version names no other names, but we can change that in the future.
=> What is Feldera? FAQ

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBaseType.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggScottTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/PostBaseTests.java, sql-to-dbsp-compiler/lib/sqllib/src/aggregates.rs
The grouping function is already documented, but the implementation was missing.
=> [SQL] Implement grouping function

scripts/bench-publish.bash, scripts/bench.bash
Avoids running persistence and ldbc benchmarks after dyn merge.
=> Fix benchmark scripts.

Earthfile
=> Bench fixes part2

web-console/src/lib/components/connectors/dialogs/GenericEditorConnector.tsx, web-console/src/lib/components/connectors/dialogs/UrlConnector.tsx, web-console/src/lib/functions/connectors.ts
Fix 1538: generic connector editor doesn't work
=> Fix connector editor doesn't work

deploy/Dockerfile
=> docker: storage crate is removed, so don't try to copy it in the Dockerfile

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.12.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> Post release v0.12.0

web-console/src/lib/components/connectors/drawer/AddSourceDrawer.tsx
=> Ability to select generic connector in pipeline config.

CHANGELOG.md, docs/sql/integer.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CustomFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/lib/sqllib/src/array.rs
Fixes: https://github.com/feldera/feldera/issues/1552
Also fixes edge conditions with NULL values for RLIKE.
=> [SQL] support for sequence() function

crates/dbsp/src/algebra/zset/mod.rs, crates/dbsp/src/circuit/mod.rs, crates/dbsp/src/dynamic/comparable.rs, crates/dbsp/src/dynamic/mod.rs, crates/dbsp/src/operator/mod.rs, crates/dbsp/src/storage/mod.rs, crates/dbsp/src/utils/tuple/gen.rs, crates/dbsp/src/utils/tuple/mod.rs
Nothing big here, just little things I noticed.
=> dbsp: Add and improve some rustdocs.

README.md
Is this a user-visible change (yes/no): _no__
=> Removing trailing slash from feldera.com hyperlinks

web-console/src/@core/theme/palette/index.ts, web-console/src/lib/components/streaming/management/AnalyticsPipelineTput.tsx, web-console/src/lib/components/streaming/management/PipelineMemoryGraph.tsx
Fix https://github.com/feldera/feldera/issues/1511 : some colors need adjustment for dark mode
=> Adjust some colors in dark mode

crates/dbsp/src/algebra/mod.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeDistinctVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/IHasZero.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/IsNumericType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMillisInterval.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMonthsInterval.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/AggregateTests.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs, sql-to-dbsp-compiler/lib/sqllib/src/operators.rs
Fixes #1578 
Fixes #1579 
Fixes #1580 
Fixes #1581
=> [SQL] Fix aggregate-related bugs 

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.13.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> Post-release adjustment.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeNull.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayFunctionsTests.java
=> [SQL] Fix bug in ARRAY_COMPACT function

docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TimeTests.java
=> [SQL] Fix documentation for interval literals

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TypeCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/IDiff.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/BaseSQLTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/StructTests.java
=> [SQL] Tests and fixes with nested structs and vectors

README.md
=> Update batches in README.md

CHANGELOG.md, docs/sql/aggregates.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Passes.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/DBSPAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPClosureExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresWindowTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggScottTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/AggregateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java, sql-to-dbsp-compiler/lib/sqllib/src/aggregates.rs
=> [SQL] Support for ARG_MIN, ARG_MAX aggregation functions

Cargo.lock, Cargo.toml, crates/dbsp/Cargo.toml, sql-to-dbsp-compiler/lib/json/Cargo.toml, sql-to-dbsp-compiler/lib/json/src/lib.rs
=> JSON: Initial implementation of JSON functions in rust

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java
More code will need to be reviewed.
=> In Calcite AND can have N operands

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/LowerCircuitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Projection.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeProjectionVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPBaseTupleExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPCloneExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPDerefExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPFlatmap.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPRawTupleExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPTupleExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPUnwrapExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBaseType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/ExplicitShuffle.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/IdShuffle.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Shuffle.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TestCase.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
=> [SQL] Fix the detection of projections

deploy/Dockerfile, web-console/src/lib/functions/kafka/authParamsSchema.ts
=> Two fixes for release

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.14.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> 0.14.0 post-release adjustments.

Cargo.lock, crates/dbsp/Cargo.toml, crates/dbsp/src/storage/backend/mod.rs, crates/dbsp/src/storage/backend/monoio_impl/mod.rs, crates/dbsp/src/storage/backend/posixio_impl.rs, crates/nexmark/Cargo.toml, crates/nexmark/benches/nexmark/main.rs, crates/nexmark/src/config.rs
Please see individual commit messages for details.
=> Add option for enabling storage to nexmark benchmark

docs/sql/integer.md
=> Fix typo in docs that causes build to crash.

Cargo.lock, docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TimeArithmeticTests.java, sql-to-dbsp-compiler/lib/json/Cargo.toml, sql-to-dbsp-compiler/lib/json/src/lib.rs, sql-to-dbsp-compiler/lib/sqllib/src/interval.rs, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
=> [SQL] Implement addition for TIME and INTERVAL types

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
=> [SQL] Use view column names for output structs if known

docs/tutorials/rest_api/index.md
=> Clarify API key docs.

crates/dbsp/src/circuit/dbsp_handle.rs, crates/dbsp/src/operator/dynamic/time_series/window.rs, crates/dbsp/src/storage/backend/mod.rs
=> Implement checkpoint/restore for window operator.

docs/sql/datetime.md
Fixes #1674 
None of these is critical to support, since they can be done in other ways. If someone asks for them, we'll consider implementing them. These were taken from the Postgres documentation.
=> [SQL] Remove from documentation unsupported functions

crates/adapters/src/format/parquet/test.rs, crates/adapters/src/integrated/delta_table/output.rs, crates/adapters/src/test/kafka.rs, crates/adapters/src/test/mod.rs, crates/adapters/src/transport/file.rs, crates/adapters/src/transport/kafka/ft/test.rs, crates/adapters/src/transport/kafka/nonft/test.rs, crates/adapters/src/transport/s3/mod.rs, crates/adapters/src/transport/url.rs, crates/pipeline_manager/src/integration_test.rs
=> Minor test improvements

demo/project_demo00-SecOps/run.py
=> demo: use the correct URL for the Avro schema registry

CHANGELOG.md, crates/pipeline_manager/src/compiler.rs
=> Fix manager logic where profile isn't chosen consistently.

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.15.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> docker: point compose file to feldera version 0.15.0

CHANGELOG.md, crates/adapters/src/controller/mod.rs, crates/pipeline-types/src/config.rs, crates/pipeline_manager/src/api/mod.rs, crates/pipeline_manager/src/db/pipeline.rs, crates/pipeline_manager/src/db/test.rs, crates/pipeline_manager/src/local_runner.rs, crates/pipeline_manager/src/pipeline_automata.rs, openapi.json, web-console/src/lib/components/analytics/TableSqlPrograms.tsx, web-console/src/lib/components/streaming/management/PipelineTable.tsx, web-console/src/lib/services/manager/core/OpenAPI.ts, web-console/src/lib/services/manager/index.ts, web-console/src/lib/services/manager/models/ColumnType.ts, web-console/src/lib/services/manager/models/ConnectorConfig.ts, web-console/src/lib/services/manager/models/DeltaTableWriterConfig.ts, web-console/src/lib/services/manager/models/PipelineConfig.ts, web-console/src/lib/services/manager/models/RuntimeConfig.ts, web-console/src/lib/services/manager/models/TransportConfig.ts
=> Configurable storage

docs/sql/string.md
=> Docusaurus is very strict about html

crates/dbsp/src/algebra/mod.rs, crates/dbsp/src/algebra/present.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeRawTuple.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeTuple.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat8Tests.java, sql-to-dbsp-compiler/lib/sqllib/src/interval.rs, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
=> Small fixes cherry-picked from the dynamic typing branch

sql-to-dbsp-compiler/SQL-compiler/pom.xml, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPVecLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/SqlIoTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TableParser.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/DateFormatsTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/TimestampdiffTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/VarbinaryTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat8Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt8Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresNumericTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresTimeTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayFunctionsTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/CastTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
=> [SQL] Migrate to Calcite 1.37

benchmark/README.md, benchmark/feldera-sql/README.md, benchmark/feldera-sql/run.py, benchmark/run-nexmark.sh, benchmark/suite.mk, crates/adapters/src/transport/kafka/nonft/input.rs, crates/nexmark/examples/generate.rs, web-console/src/lib/functions/kafka/librdkafkaOptions.ts
This is a first stab at an end-to-end benchmark test.
=> End-to-end Nexmark benchmark

web-console/src/lib/components/streaming/import/ImportToolbar.tsx
=> Fix UI build error

crates/adapters/src/transport/kafka/nonft/input.rs
Commit 127cdd74aa79 ("Allow 'enable.partition.eof' Kafka option for non-ft kafka input connector.") added the ability to read a Kafka topic until its current end.  However, it only worked properly when the topic had only one partition, because each partition receives a separate EOF error indication.  This commit fixes the problem by keeping track of the partitions that have received an EOF.
=> dbsp_adapters: Make 'enable.partition.eof' work with multiple partitions

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.16.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> docker: point compose file to Feldera version 0.16.0

docs/concepts.md, docs/contributors/compiler.md, docs/demo/demo.md, docs/intro.md, docs/sql/intro.mdx, docs/tour/tour.md, docs/tutorials/basics/index.mdx, docs/tutorials/rest_api/index.md, docs/tutorials/writing-sql.md, docs/what-is-feldera.md
Also apply Lalith's suggested changes to concepts.md, and refill paragraphs there.
Suggested by Lalith.
=> docs: Drop "Platform" from product name.

python/feldera/_sql_table.py, python/feldera/output_handler.py, python/feldera/rest/attached_connector.py, python/feldera/rest/config.py, python/feldera/rest/connector.py, python/feldera/rest/pipeline.py, python/feldera/rest/program.py, python/feldera/sql_context.py, python/feldera/sql_schema.py, python/tests/test_wireframes.py
=> py: use per-instance variables instead of static

docs/papers.md
Signed-off-by: Lalith Suresh <suresh.lalith@gmail.com>
=> docs: improvements to the publication page

python/feldera/sql_context.py
=> py: do not pause before shutting down the pipeline

crates/dbsp/src/operator/dynamic/join.rs
Improve the readability of circuit graphs by grouping `join` and `antijoin` circuits into regions.
=> Add regions to join and antijoin circuits.

docs/sidebars.js
=> fix routing to python docs from website sidebar

python/feldera/rest/client.py
=> py: apply backpressure by default for http egress

CHANGELOG.md
=> Update Changelog to include python SDK

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.17.0

python/feldera/_callback_runner.py, python/feldera/_helpers.py, python/feldera/output_handler.py, python/feldera/rest/client.py, python/feldera/sql_context.py, python/tests/test_wireframes.py
=> py: implement foreach_chunk method for streaming HTTP output

Cargo.lock, crates/adapters/Cargo.toml, crates/adapters/src/controller/mod.rs, crates/adapters/src/controller/stats.rs, crates/pipeline-types/src/config.rs, openapi.json, web-console/src/lib/services/manager/models/PipelineConfig.ts, web-console/src/lib/services/manager/models/RuntimeConfig.ts
This addresses https://github.com/feldera/feldera/issues/1769.
=> dbsp: Report metrics as part of "/stats".

crates/adapters/src/integrated/delta_table/input.rs, demo/project_demo10-FraudDetectionDeltaLake/run.py
This script demonstrates the use of Feldera for real-time feature engineering on top of Delta Lake.
It is based on this blog post: https://www.feldera.com/blog/feature-engineering-part2/.
The script first creates a Feldera pipeline that reads a snapshot of labeled historical data from a
Delta Lake and derives feature vectors from it. It retrieves the computed feature vectors into
a Pandas dataframe and uses them to train an ML model to detect fraudulent credit card transactions.
Next, we create the second pipeline that simulates real-time feature computation by scanning the
transaction log of another Delta table. We read computed features via HTTP and feed them to the
trained ML model for inference.
By default, this script connects to a Feldera instance at http://localhost:8080.  See …
=> Demo script based on the ML blog.

Cargo.lock, crates/nexmark/Cargo.toml, crates/nexmark/benches/nexmark/main.rs
These metrics only appear when storage is enabled.
=> dbsp_nexmark: Add some basic storage metrics to output.

python/.gitignore, python/pyproject.toml
=> py: add typing-extensions to pyproject.toml

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMapOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeStruct.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
Fixes #1755 
This PR only makes sure that the Rust generated is legal, but there are no tests feeding data that is a nested struct.
=> [SQL] Correctly handle tables with nested structs and primary keys

benchmark/feldera-sql/run.py, crates/adapters/src/controller/mod.rs, crates/dbsp/src/trace/ord/fallback/utils.rs, crates/pipeline-types/src/config.rs, crates/pipeline_manager/src/db/test.rs, openapi.json, web-console/src/lib/services/manager/models/PipelineConfig.ts, web-console/src/lib/services/manager/models/RuntimeConfig.ts
This fixes both issue #1811 and a bug in merger code found while fixing it. They are in separate commits.
=> Issue 1811

crates/adapters/src/controller/error.rs, crates/adapters/src/controller/mod.rs, crates/pipeline-types/src/config.rs, crates/pipeline-types/src/transport/delta_table.rs, docs/connectors/index.mdx, docs/connectors/sinks/delta.md, docs/connectors/sources/delta.md, docs/sidebars.js, openapi.json
=> Delta Lake connector documentation.

docs/cloud/index.md, docs/contributors/dev-flow.md, docs/demo/demo.md, docs/faq.md, docs/tour/tour.md, docs/tutorials/basics/part1.md
=> docs: Fixup broken links to docker.md

CHANGELOG.md, python/.gitignore, python/docs/examples.rst, python/feldera/_helpers.py, python/feldera/formats.py, python/feldera/sql_context.py, python/tests/test_wireframes.py
=> py: HTTP GET input connector

python/feldera/_helpers.py, python/feldera/sql_context.py, python/tests/test_wireframes.py
=> py: raise error if dataframe has no column names

CHANGELOG.md, python/.gitignore, python/docs/examples.rst, python/docs/introduction.rst, python/feldera/__init__.py, python/feldera/_helpers.py, python/feldera/formats.py, python/feldera/rest/__init__.py, python/feldera/rest/config.py, python/feldera/rest/feldera_client.py, python/feldera/rest/pipeline.py, python/feldera/sql_context.py, python/tests/__init__.py, python/tests/test_wireframes.py
* also rename `Client` to `FelderaClient`
In a follow up PR, add builders for Connectors.
=> py: kafka connector

CHANGELOG.md, crates/pipeline-types/src/config.rs, crates/pipeline_manager/src/db/test.rs, crates/pipeline_manager/src/integration_test.rs, openapi.json
Allows the user to specify a storage class in the pipeline resources.
=> pipeline-types: storage_class field in ResourceConfig

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TimeTests.java, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
=> [SQL] Fixes for #1843 and #1844

crates/adapters/Cargo.toml, crates/adapters/src/server/mod.rs
use it on non-linux platforms.
=> jemalloc-pprof only works on linux so we make sure we don't

CHANGELOG.md, docs/sql/grammar.md, sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/config.fmpp, sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/SqlCreateLocalView.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/SqlLateness.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/SqlRemove.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/package-info.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateViewStatement.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/TableModifyStatement.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ParserTests.java
=> [SQL] Support LOCAL views, which do not produce circuit outputs

crates/nexmark/benches/nexmark/main.rs
Wasn't sure why some configuration don't end up reading anything.
=> Print cache hit and miss metrics.

docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/DateArithmeticTests.java, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
=> Support for date and interval arithmetic

crates/dbsp/src/storage/backend/metrics.rs, crates/dbsp/src/trace/mod.rs, crates/dbsp/src/trace/spine_fueled.rs, crates/nexmark/benches/nexmark/main.rs
=> Compaction metrics.

web-console/yarn.lock
=> Update yarn lockfile with the new dependencies

web-console/public/icons/vendors/databricks-delta-lake-icon.svg
=> Improve the display of DeltaLake icon in Pipeline view

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.18.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> Post v0.18 commit.

CHANGELOG.md, docs/sql/aggregates.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayFunctionsTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TinyintTests.java, sql-to-dbsp-compiler/lib/sqllib/src/array.rs, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
=> [SQL] Support for SQL ARRAY_AGG aggregate function

Earthfile, scripts/bench-publish.bash, scripts/bench.bash
Is this a user-visible change (yes/no): No
This PR adds the running of Nexmark tests with SQL to the CI. There is another PR for the benchmarks repo that uses compiles test results into graphs shown on https://benchmarks.feldera.io/.
=> SQL benchmarks graph

CHANGELOG.md, crates/adapters/src/format/avro/output.rs, crates/pipeline-types/src/format/avro.rs, python/feldera/formats.py
=> avro: make serializing schema ID configurable

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/FindDeadCode.java
The previous PR has broken the compiler, this is fixing it.
=> [SQL] Fix bug in dead code elimination

Cargo.lock, crates/adapters/Cargo.toml, crates/adapters/src/catalog.rs, crates/adapters/src/format/parquet/mod.rs, crates/adapters/src/integrated/delta_table/output.rs, crates/adapters/src/integrated/delta_table/test.rs, crates/adapters/src/static_compile/deinput.rs, crates/adapters/src/static_compile/seroutput.rs
=>  Upgrade delta-rs to 0.18. 

crates/dbsp/src/operator/dynamic/join.rs, crates/dbsp/src/operator/join.rs
A generalization of the `join` operator equivalent to `stream.join(..).flat_map()`.
=> join_flatmap

crates/pipeline_manager/src/integration_test.rs
=> pipeline-manager: reduce logging in integration tests

docs/sql/table.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/SqlIoTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
=> [SQL] Support hopping windows for nullable timestamp columns

docs/sql/table.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPHopOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/UnsupportedException.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ExpandHop.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeIncrementalVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPIntervalMillisLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPIntervalMonthsLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/IsIntervalLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/StreamTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/lib/sqllib/src/lib.rs, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
This PR is already rebased on #1887, since it touches the same parts of the code, but that one has been already submitted for review.
=> [SQL] Monotonicity analysis for hopping windows

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/GlobalTypes.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
=> [SQL] Do not assume that user-defined types are structs

python/feldera/sql_context.py
API to create user-defined SQL types from Python.
=> py: SQLContext.register_type

CHANGELOG.md, demo/project_demo10-FraudDetectionDeltaLake/notebook.ipynb, demo/project_demo10-FraudDetectionDeltaLake/run.py, docs/use_cases/fraud_detection/fraud_detection.md, python/docs/examples.rst, python/docs/introduction.rst, python/feldera/sql_context.py, python/tests/test_wireframes.py
=> py: add register_local_view

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CSE.java
=> [SQL] Fix bug in CSE pass

python/feldera/_sql_view.py, python/feldera/sql_context.py
`LATENESS` is yet anothet type of SQL statement we support: https://www.feldera.com/docs/sql/streaming#lateness-expressions
=> py: add_lateness.

benchmark/feldera-sql/run.py
Every metric provided by the api will now be logged.
=> Log more SQL metrics

benchmark/feldera-sql/run.py, crates/adapters/src/controller/stats.rs
=> Sampled histograms

crates/adapters/src/controller/stats.rs
=> dbsp_adapters: Fix typo in comment.

Earthfile, crates/dbsp/src/circuit/runtime.rs, crates/pipeline_manager/src/integration_test.rs
Fixes [#1638](https://github.com/feldera/feldera/issues/1638)
=> Enable storage in testing

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/LowerCircuitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPVecLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayTests.java, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
=> [SQL] proper unnest check for null arguments

docs/use_cases/fraud_detection/fraud_detection.md
=> docs: simplify the fraud detection preamble

Cargo.lock, crates/adapters/Cargo.toml, crates/adapters/src/integrated/delta_table/test.rs
=> Bump delta

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> Release v0.19.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> Post release v0.19.0

python/.gitignore, python/docs/feldera.rst, python/docs/index.rst, python/feldera/sql_context.py
This PR changes the structure of the python docs. 
We change the structure of `feldera.rst` file and include it in version control so that the important parts show up first. 
Note that this means, if a new module / file is added, it must be manually inserted in `feldera.rst`. 
Unsure if this requires a changelog entry.
=> Improve py docs

crates/dbsp/Cargo.toml, crates/dbsp/Makefile.toml, crates/dbsp/benches/galen.rs, crates/dbsp/src/algebra/floats.rs, crates/dbsp/src/operator/csv.rs, crates/dbsp/src/operator/mod.rs, scripts/bench.bash, sql-to-dbsp-compiler/lib/readers/Cargo.toml, sql-to-dbsp-compiler/temp/Cargo.toml
Fixes commit a90980262c0 ("dbsp: Get rid of "spill" and "unspill".")
=> dbsp: Fix build of `galen` benchmark.

demo/project_demo10-FraudDetectionDeltaLake/notebook.ipynb, python/feldera/sql_context.py
=> py: max_queue_records param to connect_source_kafka

crates/pipeline_manager/src/compiler.rs, crates/pipeline_manager/src/config.rs, crates/pipeline_manager/src/integration_test.rs
9090 is the default port of prometheus.
=> Switch binary download port from 9090 to 8085.

demo/demo_notebooks/requirements.txt
https://stackoverflow.com/questions/78650222/valueerror-numpy-dtype-size-changed-may-indicate-binary-incompatibility-expec
=> Fix for numpy regression.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/CompilerMain.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/NonMonotoneType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/ScalarMonotoneType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/MonotoneAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Passes.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPApplyExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPApplyMethodExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPIntervalMillisLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/BaseSQLTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ComplexQueriesTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/StreamingTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/lib/sqllib/src/interval.rs
=> [SQL] Improve monotonicity analysis

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPUpsertFeedbackOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/StreamingTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpcDsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpchTest.java
=> [SQL] Improve monotonicity for aggregations

benchmark/feldera-sql/run.py, crates/dbsp/src/operator/dynamic/distinct.rs, crates/dbsp/src/operator/dynamic/time_series/waterline.rs
=> Minor profiling-related improvements

benchmark/feldera-sql/run.py
=> Post-fix for unsuccessful rebase in PR1971.

benchmark/flink/README.md
renew-anon-volume is not a valid option, but renew-anon-volumes is
=> Fix docker command

benchmark/run-nexmark.sh, crates/adapters/src/transport/kafka/nonft/input.rs, crates/adapters/src/transport/kafka/nonft/test.rs, crates/nexmark/examples/generate.rs, crates/pipeline-types/src/transport/kafka.rs, openapi.json
Please see individual commits for details.
See https://github.com/feldera/feldera/issues/964 for background.
=> Improve Kafka input performance for small messages

benchmark/feldera-sql/run.py, benchmark/run-nexmark.sh, scripts/bench.bash
Also, set the default to 10 for the benchmark runners, because that produces the best results.
=> benchmark: Make poller threads configurable for SQL benchmarks.

web-console/src/app/(spa)/(root)/(authenticated)/(app)/streaming/inspection/page.tsx
Fix https://github.com/feldera/feldera/issues/1995 : Issue switching from BROWSE tab of materialized view to a non-materialized view
=> Disable navigation from materialized to non-materialized view

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.20.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> v0.20.0 post-release.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
=> [SQL] Improved monotonicity analysis for filter operators

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPAggregateOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPDelayOutputOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPHopOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPJoinFilterMap.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPStreamAggregateOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPSortExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Fix bugs in implementations of LIMIT

CONTRIBUTING.md, docs/contributors/dev-flow.md, web-console-sveltekit/README.md, web-console/README.md
=> Add docs for the new WebConsole project

crates/pipeline_manager/build.rs, crates/pipeline_manager/src/api/mod.rs
=> Disable sveltekit build

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMapOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
=> [SQL] Fix bug for primary key fields that need cloning

deploy/grafana_dashboard.json
=> Update grafana_dashboard.json with some storage metrics

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeAny.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeFunction.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeRef.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeStruct.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeTupleBase.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBaseType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBinary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBool.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDecimal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeFP.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeGeoPoint.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeISize.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeInteger.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeKeyword.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMillisInterval.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMonthsInterval.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeNull.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeStr.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeString.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeTime.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeTimestamp.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeUSize.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeVoid.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeStream.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeUser.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/AggregateTests.java
=> [SQL] Correctly handle nullable types in ARG_MAX

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPWaterlineOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPBaseTupleExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
=> [SQL] Use waterline and not waterline_monotonic

deploy/Dockerfile
For some reason after installation `bun` executable cannot be resolved. So as a workaround it is linked as /usr/lib/bun executable
=> Fix bun build in deploy/Dockerfile

scripts/bench.bash
=> Reset min-storage-bytes to default

Earthfile
Updates the Flink benchmark to run all the queries, not just q0.
=> Make Flink run all queries

demo/project_demo12-HopsworksTikTokRecSys/1_pipeline.py, demo/project_demo12-HopsworksTikTokRecSys/features/interactions.py, demo/project_demo12-HopsworksTikTokRecSys/requirements.txt, demo/project_demo12-HopsworksTikTokRecSys/sql_program.py, demo/project_demo12-HopsworksTikTokRecSys/test.py
- Make sure data is generated in timestamp order, so the LATENESS annotation is actually correct.
- Add a simple test script.
=> TikTok demo: Fixes and refactoring.

docs/tutorials/monitoring/index.md
=> Fix port in documentation.

benchmark/feldera-sql/run.py
This PR adds automatically choosing input records for the SQL benchmarks based on SQL tables.
=> Read input connector names from SQL

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.21.0

Earthfile, deploy/docker-compose-debezium.yml, deploy/docker-compose.yml
=> docker: point compose file to Feldera version 0.21.0

docs/contributors/dev-flow.md, web-console-sveltekit/src/lib/functions/common/array.ts, web-console/src/lib/functions/common/array.ts, web-console/src/lib/functions/pipelineMetrics.ts
Fix https://github.com/feldera/feldera/issues/2058 : Web console graphs and statistics disappeared
This reapplies change in PR https://github.com/feldera/feldera/pull/2036 and also fixes a bug in groupBy function that broke this feature
=> Fix aggregating metrics when multiple connectors per relation

CHANGELOG.md, python/feldera/output_handler.py, python/feldera/sql_context.py, python/tests/test_wireframes.py
=> py: add SQLContext.input_json() to send json data

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] validate table properties syntax

docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/SourceFileContents.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/ExternalFunction.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlCreateFunctionDeclaration.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ComplexQueriesTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ParserTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Fix bugs related to SQL UDFs

README.md
=> docs: fix getting started link in README

crates/adapters/src/controller/error.rs, crates/adapters/src/controller/mod.rs, crates/adapters/src/controller/stats.rs, crates/adapters/src/server/error.rs, crates/adapters/src/server/mod.rs, crates/pipeline-types/src/config.rs, crates/pipeline_manager/src/api/mod.rs, crates/pipeline_manager/src/api/pipeline.rs, demo/project_demo06-SupplyChainTutorial/run.py, openapi.json
Implements RFC #2096.
See individual commits for details.
TODOs:
* Rework pipeline manager API as part of ongoing API refactoring
* Documentation (post-refactoring)
=> Connector orchestration

Earthfile, crates/pipeline-types/src/format/json.rs, crates/pipeline-types/src/serde_with_context/serde_config.rs, demo/project_demo13-DebeziumPostgres/project.sql, demo/project_demo13-DebeziumPostgres/run.py, deploy/docker-compose-debezium-mysql.yml, deploy/docker-compose-debezium-postgres.yml, docs/connectors/sources/debezium-mysql.md, docs/connectors/sources/debezium-postgres.md, docs/sidebars.js, openapi.json, scripts/bump-versions.sh
Added a demo reading from a Debezium Postgres source connector.  It is almost identical to the Debezium MySQL demo.
=> Debezium Postgres demo.

docs/contributors/compiler.md, docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/TimestampdiffTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/NaiveIncrementalTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/SqlIoTest.java, sql-to-dbsp-compiler/lib/sqllib/src/casts.rs, sql-to-dbsp-compiler/lib/sqllib/src/geopoint.rs, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
=> [SQL] Document and test TIMESTAMPADD function; improve Calcite optimizer structure

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.22.0

crates/adapters/src/controller/mod.rs, crates/adapters/src/test/mod.rs, crates/adapters/src/transport/datagen.rs, crates/pipeline-types/src/format/json.rs, crates/pipeline-types/src/serde_with_context/serde_config.rs, crates/pipeline-types/src/transport/datagen.rs, openapi.json, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
This produces around 550k records/sec per thread (for TestStruct2) on my x86 cpu, before it was around 250k records/thread
=> Fast(er) datagen

python/feldera/sql_context.py, python/tests/test_wireframes.py
=> py: allow specifying update format in SQLContext.input_json

docs/tutorials/rest_api/index.md
=> Rework REST API tutorial to use the new API

scripts/bench-publish.bash
=> Fix CI error with bench-publish

docs/tutorials/basics/part1.md, docs/tutorials/basics/part2.md, docs/tutorials/basics/part3.md, docs/tutorials/basics/part4.md
=> Updated the interactive tutorial.

CODE_OF_CONDUCT.md, LICENSE, bruno_api_preset/bruno.json, codecov.yml, import-sorter.json
=> repo: cleanup top-level folder

Earthfile, demo/project_demo13-DebeziumPostgres/project.sql, demo/project_demo13-DebeziumPostgres/run.py, deploy/docker-compose-debezium-postgres.yml
=> Reworked debezium postgres demo

demo/project_demo13-DebeziumPostgres/run.py
Add a comment to the Postgres Debezium demo script explaining how to start the auxiliary services it needs.
=> Add instructions to the Postgres Debezium demo.

docs/tutorials/basics/part3.md, docs/tutorials/basics/part4.md
Refer to the `Change Stream` tab in the tutorial.
=> docs: Update tutorial text for WebConsole changes.

web-console/src/lib/components/pipelines/editor/ChangeStream.svelte, web-console/src/lib/compositions/setupHttpClient.ts, web-console/src/lib/services/pipelineManager.ts
=> WebConsole: fix eggress query doesn't work with auth disabled

deploy/Dockerfile
=> docker: fix mold download link

web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte, web-console/src/lib/components/pipelines/editor/ChangeStream.svelte, web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte, web-console/src/lib/components/pipelines/list/Actions.svelte, web-console/src/lib/compositions/pipelines/usePipelineActionCallbacks.svelte.ts, web-console/src/lib/functions/pipelines/changeStream.ts, web-console/src/lib/services/pipelineManager.ts, web-console/src/lib/types/common/function.ts, web-console/src/lib/types/pipelineManager.ts
start paused to follow the stream from the beginning
Enable following multiple streams
=> Improve change stream UI

web-console/src/lib/components/pipelines/list/Status.svelte, web-console/src/lib/services/manager/schemas.gen.ts, web-console/src/lib/services/manager/types.gen.ts, web-console/src/lib/services/pipelineManager.ts, web-console/src/routes/(authenticated)/+page.svelte, web-console/src/routes/(authenticated)/+page.ts, web-console/src/routes/(authenticated)/demos/+page.svelte
=> Pull demos from API on home page reload

crates/pipeline_manager/src/api/config_api.rs, crates/pipeline_manager/src/api/mod.rs, crates/pipeline_manager/src/demo.rs, openapi.json, web-console/src/lib/components/layout/pipelines/PipelineEditorStatusBar.svelte, web-console/src/lib/components/pipelines/List.svelte, web-console/src/lib/components/pipelines/editor/ChangeStream.svelte, web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte, web-console/src/lib/functions/pipelines/changeStream.ts, web-console/src/lib/services/manager/schemas.gen.ts, web-console/src/lib/services/manager/types.gen.ts, web-console/src/routes/(authenticated)/+layout.svelte, web-console/src/routes/(authenticated)/+page.svelte, web-console/src/routes/(authenticated)/+page.ts
=> pipeline-manager: demo title and list sorted by file path

Earthfile, benchmark/flink/get-memory.bash, benchmark/flink/run-flink-ci.sh
This pull request monitors and logs peak memory utilization for Flink benchmarks.
=> Added memory tracking for Flink

crates/nexmark/benches/nexmark/main.rs
The `step_done_tx` channel's tx side was cloned and passed to two threads. If one thread panicked, then the channel stayed open because the other thread might still send to it.
This commit breaks the channel into two channels, each of which has its tx side sent to a different thread.  If one thread panics, then its rx side returns an error because nothing can send to it anymore.  This fixes the hang.
=> dbsp_nexmark: Exit without hanging if a DBSP thread panics.

web-console/src/lib/components/pipelines/editor/ChangeStream.svelte, web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte, web-console/src/lib/compositions/auth.ts, web-console/src/routes/(authenticated)/+layout.ts, web-console/src/routes/+layout.ts
Fixes issue:
Using AWS Cognito as authentication,
1) Logout from web-console
2) Try to login with Google
3) Get redirected to an empty page
=> Fix login with Google after logout

web-console/src/lib/components/auth/AuthButton.svelte, web-console/src/lib/components/auth/AuthPopupMenu.svelte, web-console/src/lib/compositions/@axa-fr/auth.ts, web-console/src/lib/compositions/auth.ts, web-console/src/lib/types/auth.ts, web-console/src/routes/+layout.ts
=> Fix profile picture not displayed

web-console/src/lib/compositions/pipelines/usePipelineActionCallbacks.svelte.ts
Is this a user-visible change (yes/no):yes
=> Add null check

benchmark/feldera-sql/benchmarks/nexmark/table.sql, benchmark/feldera-sql/benchmarks/tiktok/table.sql, benchmark/feldera-sql/run.py
This removes the `--merge` option because it was already broken and we hadn't noticed (so it couldn't be too important) and the `--output` option because it was a bit of work to keep it and we didn't use it.
=> benchmark: Convert SQL benchmarks for Nexmark and Tiktok to new API.

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.23.0

docs/tutorials/basics/index.mdx, docs/tutorials/basics/part1.md
=> Update stale text in the tutorial.

demo/project_demo11-Hopsworks/1_feature_pipeline.ipynb
=> Update the Hopsworks demo for the new API.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java
=> [SQL] waterlines need a delay

crates/adapters/src/transport/s3/mod.rs
=> Increase timeouts in S3 tests

benchmark/feldera-sql/benchmarks/nexmark/queries/q12.sql, docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeIncrementalVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/annotation/AlwaysMonotone.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/annotation/Annotation.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/annotation/NoInc.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
This is motivated by #2229 
It does not solve #2229, because there is no key to join on in that issue.
Fixing that case will require some help from DBSP, e.g., a broadcast join.
=> [SQL] Improve key analysis for equijoins

web-console/src/lib/components/pipelines/editor/ChangeStream.svelte
=> Fix default change stream behavior not following list end

web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte, web-console/src/lib/components/pipelines/List.svelte, web-console/src/lib/components/pipelines/editor/ChangeStream.svelte, web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte, web-console/src/lib/components/pipelines/list/Actions.svelte, web-console/src/lib/components/pipelines/list/PipelineStatus.svelte, web-console/src/routes/(authenticated)/+layout.svelte
Fix https://github.com/feldera/feldera/issues/2208: Table from different pipelines get mixed up
=> Multiple WebConsole fixes

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
=> [SQL] Infer monotonicity from comparisons of the shape `col + constant >= expression`

Cargo.lock, deploy/Dockerfile
=> dockerfile: copy nexmark crate for compiler

benchmark/feldera-sql/run.py
Running run.py with --circuit-profile will now save circuit profiles for all the queries run.
=> Add option to collect circuit profile in benchmark

docs/tutorials/monitoring/index.md
=> Fix monitoring command.

deploy/Dockerfile
=> docker: install git so sql-compiler's build.sh runs

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.24.0

Earthfile, deploy/docker-compose-debezium-mysql.yml, deploy/docker-compose-debezium-postgres.yml, deploy/docker-compose.yml
=> Post release v0.24.0

docs/sql/decimal.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDecimal.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresNumericTests.java
Is this a user-visible change (yes/no): maybe?
Fixes #2012
=> [SQL] Correct supported range of decimal values

crates/adapters/src/transport/mod.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/lib/sqllib/src/array.rs
=> [SQL] stddev result may always be null

benchmark/feldera-sql/benchmarks/tiktok/README.md, demo/project_demo12-HopsworksTikTokRecSys/1_pipeline.py, demo/project_demo12-HopsworksTikTokRecSys/README.md, demo/project_demo12-HopsworksTikTokRecSys/config.py, demo/project_demo12-HopsworksTikTokRecSys/requirements.txt, demo/project_demo12-HopsworksTikTokRecSys/tiktok-gen/src/main.rs
=> update README for tiktok demo / benchmarks

benchmark/feldera-sql/benchmarks/tiktok/README.md, benchmark/feldera-sql/benchmarks/tiktok/generate.bash
Allow specifying custom Kafka broker address in the tiktok benchmark.
=> [tiktok] Make Kafka endpoint configurable.

docs/connectors/sources/datagen.md
Fixes https://github.com/feldera/feldera/issues/2300
Also add some examples.
=> Fix doc link.

docs/contributors/compiler.md, docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNowOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/IncrementalizeVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/InternalNowTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
=> [SQL] Implement the NOW table as a generator

docs/contributors/compiler.md
=> Fix broken link.

Cargo.lock, crates/adapters/Cargo.toml, crates/dbsp/Cargo.toml, crates/pipeline-types/Cargo.toml, crates/pipeline_manager/Cargo.toml, sql-to-dbsp-compiler/lib/json/Cargo.toml, sql-to-dbsp-compiler/temp/Cargo.toml
=> Update serde-json dependency.

crates/dbsp/src/operator/aggregate.rs, crates/dbsp/src/operator/dynamic/aggregate/mod.rs
The new operator implements linear aggregation with a postprocessing step. It is equivalent to
`self.aggregate_linear(f).map_index(|(k, v)|(k, postprocess(v)))`, but is more efficient, because it computes `postprocess(v)` on the fly without first storing `v` in a trace.
This is useful in particular in implementing SQL-style linear aggregates for nullable values (which are not actually exactly linear).  In SQL, if all elements in a group are NULL, their aggregate is NULL; otherwise aggregate is computed over non-NULL values in the group.
A test in this commit illustrates how the new operator allows implementing this.
I also remove the unused `aggregate_linear_generic` operator.
=> dbsp: aggregate_linear_postprocess operator.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPDecimalLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPDoubleLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPFPLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPI128Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPI16Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPI32Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPI64Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPI8Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPISizeLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPIntLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPIntervalMillisLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPIntervalMonthsLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPRealLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPU128Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPU16Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPU32Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPU64Literal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPUSizeLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/IsIntervalLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/IsNumericLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/StreamTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
=> [SQL] Do not perform % on negative numbers

docs/sql/binary.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/SourceFileContents.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CustomFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/VarbinaryTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/lib/sqllib/src/binary.rs
=> [SQL] Add TO_INT function to convert a byte array to an integer

crates/pipeline_manager/src/db/test.rs
=> pipeline-manager: manual database tests

crates/adapters/src/test/data.rs, crates/adapters/src/transport/datagen.rs, crates/pipeline-types/src/program_schema.rs, crates/pipeline-types/src/transport/datagen.rs, docs/connectors/sources/datagen.md, sql-to-dbsp-compiler/lib/sqllib/src/binary.rs
=> Support BINARY, VARBINARY in datagen.

benchmark/feldera-sql/benchmarks/tpc-h/generate.bash, crates/adapters/src/transport/datagen.rs, crates/pipeline-types/src/transport/datagen.rs, docs/connectors/sources/datagen.md, openapi.json
=> [Datagen] time, date, timestamp range support with strings.

CHANGELOG.md, Cargo.lock, crates/pipeline_manager/Cargo.toml, openapi.json
=> release: bump project version to 0.25.0

Earthfile, deploy/docker-compose-debezium-mysql.yml, deploy/docker-compose-debezium-postgres.yml, deploy/docker-compose.yml
=> Post release v0.25.0

python/.gitignore, python/tests/sql_aggregates/test_array_agg.py, python/tests/sql_aggregates/test_average.py, python/tests/sql_aggregates/test_bit_and.py, python/tests/sql_aggregates/test_bit_or.py, python/tests/sql_aggregates/test_bit_xor.py, python/tests/sql_aggregates/test_count.py, python/tests/sql_aggregates/test_count_col.py, python/tests/sql_aggregates/test_every.py, python/tests/sql_aggregates/test_max.py, python/tests/sql_aggregates/test_min.py, python/tests/sql_aggregates/test_some.py, python/tests/sql_aggregates/test_stddev_pop.py, python/tests/sql_aggregates/test_stddev_samp.py, python/tests/sql_aggregates/test_sum.py, python/tests/test_average.py, python/tests/test_sum.py
=> Aggregation tests in python

benchmark/feldera-sql/benchmarks/nexmark/disabled-queries/q16.sql, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CSE.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
This also rewrites Nexmark's q16 to be slightly more efficient
=> [SQL] Do not CSE operators that are followed by GC operators

benchmark/run-nexmark.sh, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
The previous graphviz output didn't show all functions for waterline operators.
=> [SQL] Improved debugging graphs 

docs/sql/aggregates.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPStringLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeString.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggScottTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/lib/sqllib/src/aggregates.rs, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DbspJdbcExecutor.java
=> [SQL] Fix arg_min aggregate

Cargo.lock, crates/fda/Cargo.toml, crates/fda/src/cli.rs, crates/fda/src/main.rs, crates/fda/src/shell.rs
=> A CLI shell for adhoc queries.

deploy/docker-compose-debezium-postgres.yml
Fix CI job broken by
https://github.com/feldera/feldera/pull/2391
=> [demo] Fix Debezium Postgres CI job.

Cargo.lock, crates/adapters/Cargo.toml, crates/adapters/src/format/parquet/mod.rs, crates/adapters/src/test/data.rs
This avoids compiling two different datafusion versions.
=> Update delta-rs crate.

crates/adapters/src/adhoc/table.rs
I was confused on what schema datafusion wants where.
=> Distinguish between table and projected schemas.

crates/adapters/src/format/avro/test.rs, crates/adapters/src/format/json/output.rs, crates/adapters/src/format/parquet/test.rs, crates/adapters/src/test/mock_output_consumer.rs
Add a unit test for the recently added Confluent JDBC connector feature.
=> [avro] Confluent JDBC avro output format unit test.

Earthfile, crates/adapters/README.md, crates/adapters/src/server/mod.rs, demo/docs-demo/README.md, demo/project_demo12-HopsworksTikTokRecSys/README.md, deploy/docker-compose.yml
Let's see if this fixes the issue with the CI not being able to pull the container.
=> Upgrade redpanda container

python/tests/dtype_based_tests/test_avg.py, python/tests/dtype_based_tests/test_base_class.py, python/tests/dtype_based_tests/test_sum.py
=> Add tests for average and sum aggregate for decimal type

README.md
With the merge queue, the badge status needs to be read in another form.
=> Update README.md batches

crates/dbsp/src/dynamic/lean_vec.rs, crates/dbsp/src/profile/mod.rs
And warning fix for the build.
=> Percentage calculation fix for profiles

crates/adapters/src/adhoc/table.rs, crates/adapters/src/controller/mod.rs
Ad-hoc insertion didn't work because the code was manually flushing records to the circuit and telling the controller that it was available to be flushed, but the controller couldn't flush it itself (because it didn't have any access to the buffer and it was already flushed anyhow). Therefore, even though the data was in the circuit, the controller didn't know that and never dropped the buffered record count or increased the processed record count.  I'm not sure why this ever worked.
This commit fixes the problem by adding a way to hand input buffers to the controller outside the context of a connector.  The controller can then deal with accounting for them properly.
This also adds an explicit notification for when the input buffers have been processed.  I don't think the old way was …
=> dbsp_adapters: Fix adhoc insertion.

crates/fda/src/cli.rs, crates/fda/src/main.rs, crates/fda/src/shell.rs, crates/fda/test.bash
Fixes #2472
Fixes #2474
> I get a cryptic error ("Unable to parse the error returned from the server (EOF while parsing a value at line 1 column 0)")
Note that this error is fixed once try.feldera is updated to the latest version. But now this only happens if you delete a pipeline after already in a shell since we check if the name is valid upfront.
=> Fda improvements

crates/adapters/src/adhoc/table.rs, crates/adapters/src/controller/mod.rs, crates/adapters/src/server/error.rs, crates/pipeline-manager/src/integration_test.rs
=> Allow inserts for non-materialized tables.

crates/fda/src/cli.rs, crates/fda/src/main.rs
Execute a SQL query in adhoc mode and prints result on stdout.
Makes it easy to pipe it into a file and then diff two results.
=> Add exec command to fda.

web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte, web-console/src/lib/components/pipelines/editor/TabPipelineErrors.svelte, web-console/src/lib/compositions/health/systemErrors.ts, web-console/src/lib/compositions/useWritablePipeline.svelte.ts, web-console/src/lib/services/pipelineManager.ts, web-console/src/routes/(authenticated)/(pipelines)/create/+page.ts, web-console/src/routes/(authenticated)/(pipelines)/pipelines/[pipelineName]/+page.svelte, web-console/src/routes/(authenticated)/(pipelines)/pipelines/[pipelineName]/+page.ts
Fix https://github.com/feldera/feldera/issues/2459 : [UI] SQL textarea is editable while pipeline is running
Fix https://github.com/feldera/feldera/issues/2478 : WebConsole keeps polling deleted pipeline
Fix https://github.com/feldera/feldera/issues/2367 : [WEBUI] UI does not differentiate between warnings and errors
=> Fix code editor not becoming readonly when starting pipeline

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/DateArithmeticTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
=> [SQL] Constant string expressions should not be considered monotone

crates/adapters/src/static_compile/catalog.rs
The ad hoc query engine operates on the integrals of materialized tables and views maintained by the circuit.  It takes a snapshot of the integral from each worker and uses it as a separate datafusion table partition.  This enables datafusion to parallelize the execution of the query.  However, since datafusion does not understand negative weights, we have to make sure that they don't appear in any of the partitions. In DBSP it's possible that the same record can appear with weights +1 ans -1 in two different partitions.  In particular, the left join operator can produce such records (but there might be others), causing the ad hoc engine to return incorrect results
The solution is to consolidate such records in the same worker, so that negative weights cancel out, by sharding the output …
=> [adhoc] Eliminate negative weights in outputs.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/LowerCircuitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeProjectionVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPFlatmap.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
=> [SQL] Propagate monotonicity information through flatmap operators

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPControlledFilterOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java, sql-to-dbsp-compiler/lib/sqllib/src/aggregates.rs
=> [SQL] NULL values for columns with LATENESS are never considered late

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/lib/sqllib/src/array.rs
=> [SQL] Do not ignore FILTER for ARRAY_AGG

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Projection.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/CustomOrdMonotoneType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/NonMonotoneType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPCustomOrdField.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
Fixes #2530 
I hope this is right. This was harder than I expected.
Maybe this can be improved, but hopefully it's good enough for a while.
=> [SQL] Propagate monotonicity information through ASOF joins

crates/pipeline-manager/src/integration_test.rs
It might take time for the logs to become available or upon shutdown they become no longer available, as such the test now passes with any of three possible endings.
=> pipeline-manager: fix logs ending test

web-console/src/assets/icons/feldera-material-icons/close_circle_outline.svg, web-console/src/lib/components/pipelines/List.svelte, web-console/src/lib/components/pipelines/editor/ProgramStatus.svelte, web-console/src/lib/components/pipelines/editor/TabPipelineErrors.svelte, web-console/src/lib/components/pipelines/editor/TabSQLErrors.svelte, web-console/src/routes/(authenticated)/+layout.svelte
Fix error icon in Pipeline Errors tab
Fix https://github.com/feldera/feldera/issues/2567: Reduce whitespace around the logo and the New Pipeline button.
=> Move top left Feldera logo to top left

crates/sqllib/src/casts.rs, crates/sqllib/src/variant.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/ExternalFunction.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteObject/CalciteObject.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteObject/CalciteRelNode.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteObject/CalciteRexNode.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPCastExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPMapLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeCode.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/VariantTests.java
=> [SQL] Support casts between VARIANT and ARRAY and MAP

crates/adapters/src/transport/datagen.rs, crates/feldera-types/src/transport/datagen.rs, docs/connectors/sources/datagen.md, openapi.json, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
Fixes 
- https://github.com/feldera/feldera/issues/2528
- https://github.com/feldera/feldera/issues/2545
- https://github.com/feldera/feldera/issues/2585
- https://github.com/feldera/feldera/issues/2594
=> Datagen fixes

crates/fda/src/cli.rs, crates/fda/src/main.rs, crates/fda/test.bash, crates/pipeline-manager/src/api/pipeline.rs, docs/reference/cli.md, openapi.json
To retrieve the logs of a pipeline.
=> Implement `fda log` command.

README.md
Thanks to [cube2222](https://news.ycombinator.com/user?id=cube2222) for reporting
=> docs: update paper link in README.md

crates/sqllib/src/lib.rs, docs/sql/decimal.md, docs/sql/float.md, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat8Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresNumericTests.java
This should also fix the build of the main branch.
Fixes #1347
Enables a few more disabled tests
=> [SQL] Adapt to latest Calcite fixes in FP arithmetic

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Implement FILTER for ARG_MIN/MAX

Earthfile
The aggregate tests are run in every CI invocation as they are one single program.
However, the python tests are multiple different programs and take longer, therefore are only run in the nightly CI.
Fixes: #2399
=> [ci] py-tests: run aggregate tests in CI & python tests in nightly

crates/dbsp/src/algebra/floats.rs, crates/sqllib/README.md, crates/sqllib/src/aggregates.rs, crates/sqllib/src/array.rs, crates/sqllib/src/binary.rs, crates/sqllib/src/casts.rs, crates/sqllib/src/geopoint.rs, crates/sqllib/src/interval.rs, crates/sqllib/src/lib.rs, crates/sqllib/src/operators.rs, crates/sqllib/src/source.rs, crates/sqllib/src/timestamp.rs, crates/sqllib/src/variant.rs, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggScottTests.java
=> [sqllib] Document (and hide private functions) the sqllib crate

python/tests/aggregate_tests/aggtst_base.py, python/tests/aggregate_tests/main.py, python/tests/aggregate_tests/test_varchar_arr_agg.py, python/tests/aggregate_tests/test_varchar_table.py
In addition to the tests, the error handling has been modified to enable a custom error message that specifies which view has failed during an assertion error.
=> py: varchar type tests for ARRAY_AGG

crates/pipeline-manager/src/db/types/program.rs, python/tests/test_pipeline.py, scripts/start_manager.sh, sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/PropertyList.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/SqlCreateTable.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/SqlCreateView.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/SqlFragment.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/SqlFragmentCharacterString.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/SqlFragmentIdentifier.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/NegativeParserTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ParserTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
=> [SQL] Validate the top-level table and view properties in the compiler

CONTRIBUTING.md, README.md
=> [docs] Improve dependencies documentation

crates/adapters/src/transport/datagen.rs
=> Fix range calculation in uniform timestamp generation.

crates/adapters/src/transport/s3/mod.rs, python/tests/aggregate_tests/test_varchar_max.py
The S3 adapter was not sending `eoi()` notification to the controller after reading all objects.
=> [adapters] S3 adapter sends EOI.

crates/dbsp/src/operator/dynamic/time_series/rolling_aggregate.rs
This fixes a bug in the rolling aggregate implementation that happened under the following circumstances:
* A partition goes from non-empty to empty.
* The merger removes this partition from the radix tree.
* But not yet from the trace of the collection.
=> [dbsp] Fix a corner case in rolling_aggregate.

crates/sqllib/src/array.rs, crates/sqllib/src/lib.rs, crates/sqllib/src/map.rs, docs/sql/aggregates.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/AggregateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/MapTests.java
=> [SQL] Support for ARRAY and MAP constructors applied to subqueries

web-console/src/lib/components/other/CreateApiKeyForm.svelte, web-console/src/lib/components/pipelines/editor/TabAdHocQuery.svelte, web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte, web-console/src/lib/components/pipelines/editor/TabLogs.svelte, web-console/src/lib/compositions/actions/clickedClass.ts, web-console/src/lib/compositions/localStore.svelte.js, web-console/src/lib/compositions/pipelines/useTryPipeline.ts, web-console/src/lib/compositions/useWritablePipeline.svelte.ts, web-console/src/lib/functions/pipelines/changeStream.ts, web-console/src/lib/services/pipelineManager.ts, web-console/src/routes/(authenticated)/(pipelines)/create/+page.ts, web-console/src/routes/(authenticated)/(pipelines)/pipelines/[pipelineName]/+page.svelte
Increase change stream parser's buffer size to 8 MiB per relation
Fix https://github.com/feldera/feldera/issues/2757: change stream is not reporting all changes
Fix https://github.com/feldera/feldera/issues/2760: Deleting pipeline and switching to another keeps returning to main page
Fix https://github.com/feldera/feldera/issues/2756: Have a way to provide udf-rs and udf-toml strings when creating a sandbox with a link
Fix https://github.com/feldera/feldera/issues/2753: Add visual feedback for copy-to-buffer icon
Fix hardcoded adhoc query endpoint origin
=> [WebConsole] Fix change stream not displaying some changes

docs/sidebars.js
The markdown file got removed from docs.
=> Remove missing markdown file in docs from sidebar.js.

docs/sql/aggregates.md
By converting it to a markdown table.
=> Fix table that breaks docusaurus build in docs.

web-console/src/lib/components/layout/pipelines/PipelineMemoryGraph.svelte, web-console/src/lib/components/layout/pipelines/PipelineThroughputGraph.svelte, web-console/src/lib/components/pipelines/editor/TabPerformance.svelte, web-console/src/lib/functions/pipelineMetrics.ts, web-console/src/lib/functions/pipelines/changeStream.ts
Fix unsubscribe from logs stream when leaving page
Fix https://github.com/feldera/feldera/issues/2745 : anomalous behavior of throughput graph
=> [WebConsole] Fix weird graph behavior when switching pipelines

docs/enterprise/index.md
=> docs: fix spurious character at the end of sandbox link

docs/get-started.mdx
=> docs: keep get started section consistent with subsections

crates/adapters/src/transport/mod.rs, docs/sql/streaming.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainKeysOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainValuesOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/ViewMetadata.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/PropertyList.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateViewStatement.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/IHasSchema.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/AppendOnly.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InstrumentDump.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/CheckRetain.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/KeyPropagation.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/MonotoneAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/package-info.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPType.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
Fixes #2775
@ryzhyk please take a look at the documentation and new tests especially
=> [SQL] Support for `emit_final` view annotation

crates/dbsp/src/storage/dirlock/mod.rs
The type and therefore the size of `libc::F_UNLCK` is different in different platforms (eg: linux and macos / bsd).
As a workaround, we cast to `c_int` before we use it to pattern match.
=> [dbsp] workaround: `libc::F_UNLCK` type inconsistency between platforms

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
=> [SQL] window computed for emit_final should be half-open on top

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
=> [SQL] GC output of ChainAggregate

docs/sql/intro.mdx, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
=> [SQL] Emit a warning if a program contains an ORDER BY clause which is ignored

docs/connectors/sources/datagen.md
Fixes: https://github.com/feldera/feldera/issues/2849
=> docs: datagen connector example with values inline in columnar format

.github/workflows/check-failures.yml, .github/workflows/ci-integration.yml, .github/workflows/ci-nightly.yml, Earthfile
=> [SQL] Separate SQL and SLT tests

docs/tutorials/time-series.md
Two small clarifications to the time series analysis guide.
=> [docs] Time-series guide clarifications.

web-console/src/lib/components/layout/pipelines/PipelineMemoryGraph.svelte, web-console/src/lib/components/layout/pipelines/PipelineThroughputGraph.svelte, web-console/src/lib/components/pipelines/editor/ReverseScrollList.svelte, web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte, web-console/src/lib/compositions/health/systemErrors.ts
Fix horizontal scroll stops stick-scroll-to-bottom in Change Stream
Fix regression - Rust stderr not parsed into individual errors
[WebConsole] Fix misplaced throughput graph tooltip
=> [WebConsole] Multiple minor fixes

demo/packaged/sql/03-feature-engineering.sql
Fix a silly mistake in the newly added demo.
=> [demo] Typo in the feature eng demo.

Earthfile, crates/sqllib/src/aggregates.rs, crates/sqllib/src/lib.rs, crates/sqllib/src/operators.rs, docs/sql/aggregates.md, docs/sql/casts.md, docs/sql/comparisons.md, docs/sql/types.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/ExpandCasts.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Projection.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/NegativeParserTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresArrayTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/MiscTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/OperatorTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/StructTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/StructTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TopKTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TableParser.java
=> [SQL] Support for ROW type

crates/dbsp/src/trace/spine_async/mod.rs
This prevents memory size from ballooning in case the merger is the bottleneck (which it usually is with storage).
This is a super simple strategy that I found effective for limiting the memory in a range of workloads and benchmarks that we have. I have code for supposedly better strategies too that look at bytes per-level etc. but for now maybe we can learn something with getting this very simple policy in for now.
=> Re-introduce backpressure into Async merger.

docs/connectors/sinks/confluent-jdbc.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
Also fixes a typo in the documentation.
Fixes #2939 
Fixes #2940
=> [SQL] Proper validation of duplicate view column names

sql-to-dbsp-compiler/build.sh, web-console/src/lib/components/pipelines/List.svelte, web-console/src/lib/components/pipelines/editor/TabAdHocQuery.svelte, web-console/src/lib/functions/pipelineMetrics.ts, web-console/src/lib/functions/pipelines/changeStream.ts
Reduce Calcite download size during SQL compiler build
Fix pipeline throughput graph beginning is jerky
Fix https://github.com/feldera/feldera/issues/2938: Cannot cancel a long-running ad hoc query
=> [WebConsole] Improve error handling when parsing streams

crates/sqllib/src/lib.rs, crates/sqllib/src/timestamp.rs, docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/TimestampdiffTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
Fixes #2943 
Fixes #2946 
Fixes #2949
=> Three commits fixing 3 different reported bugs

docs/sql/types.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Allow users to define new type names for existing types

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] CalciteException does not signal an internal compiler error

sql-to-dbsp-compiler/build.sh
This a temporary workaround to fix the build in main until we merge #2967
=> Use a Calcite branch that has the expected commit

crates/adapters/src/adhoc/mod.rs
For now we ran adhoc queries in the actix runtime. However, the actix-rt is fully partitioned and single-threaded meaning tasks spawned inside of a http handler will always run on the same thread (and core) of the single-threaded runtime.
This doesn't help for adhoc queries that can leverage parallelism in the query plan. By spawning the dataframe execution in the dbsp tokio runtime we make sure the engine can use all available CPU resources to execute a query.
Before this change:
```
❯ time fda query storage 'select count(*) from t;' 
+-----------+
| count(*)  |
+-----------+
| 100000000 |
+-----------+
fda query storage 'select count(*) from t;'  0.05s user 0.04s system 0% cpu 28.396 total
```
With this change:
```
❯ time fda query storage 'select count(*) from t;' 
+-----------+
| …
```
=> Make sure we run adhoc queries in the dbsp tokio rt.

crates/sqllib/src/string.rs, docs/sql/string.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresStringTests.java
Fix issue:
https://github.com/feldera/feldera/issues/2721
We want to add support for split_part for postgres string.
=> [SQL] support split_part for postgres string

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/CircuitToString.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNestedOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeIncrementalVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/RecursiveComponents.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/RemoveViewOperators.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPStringLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/recursive/RecursiveTests.java
Fixes #2978 
Fixes #2979 
Fixes #2980 
There is a separate Java test for each of these cases.
=> [SQL] Fix 3 bugs related to recursive programs

python/feldera/pipeline.py, python/feldera/rest/feldera_client.py, python/tests/test_pipeline_builder.py, python/uv.lock
=> [python] detailed error message on start / pause

crates/adapterlib/src/transport.rs, crates/adapters/src/controller/mod.rs, crates/adapters/src/controller/stats.rs, crates/adapters/src/integrated/delta_table/input.rs, crates/adapters/src/transport/adhoc.rs, crates/adapters/src/transport/file.rs, crates/adapters/src/transport/http/input.rs, crates/adapters/src/transport/kafka/ft/input.rs, crates/adapters/src/transport/kafka/nonft/input.rs, crates/adapters/src/transport/nexmark.rs, crates/adapters/src/transport/pubsub/input.rs, crates/adapters/src/transport/s3/mod.rs, crates/adapters/src/transport/url.rs, crates/datagen/src/lib.rs
This fixes a hang in the controller when an input adapter fails, reported by Ashwin Kirpalani in the community Slack.
=> Error handling bug fixes in input adapters

crates/sqllib/src/interval.rs, crates/sqllib/src/lib.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/IsDateType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/IsIntervalType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/IsTimeRelatedType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMillisInterval.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMonthsInterval.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeTime.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeTimestamp.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/TimestampdiffTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/MiscTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TableParser.java
This adds more tests and implements a few functions which were documented but not properly supported.
Fixes #3021
=> [SQL] Reorganize date computations

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
The compiler maintains information about each operator and tries to infer whether its output is distinct.
With this PR this information is passed to the DBSP layer as well using `.mark_distinct()` on streams.
=> [SQL] Pass distinctness information to DBSP layer

crates/sqllib/src/interval.rs, docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresCaseTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresDateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresIntervalTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresWindowTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/RedshiftTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/AggregateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayFunctionsTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/SqlIoTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TableParser.java
=> [SQL] Implement more arithmetic operations on intervals

web-console/src/lib/components/dialogs/GlobalModal.svelte, web-console/src/lib/components/layout/ModalDrawer.svelte, web-console/src/lib/components/layout/PipelineBreadcrumbs.svelte, web-console/src/lib/components/pipelines/Table.svelte, web-console/src/lib/components/pipelines/list/Actions.svelte, web-console/src/routes/(authenticated)/+layout.svelte, web-console/src/routes/(authenticated)/+page.svelte
Fix https://github.com/feldera/feldera/issues/3022: new UI: cannot scroll pipeline list dropdown in a pipeline page
Fix https://github.com/feldera/feldera/issues/3020: new UI: Slack links should be invitation links
Fix https://github.com/feldera/feldera/issues/3019: new UI: Documentation link doesn't do anything
Fix https://github.com/feldera/feldera/issues/3017: New UI: use a single configuration button
Fix https://github.com/feldera/feldera/issues/3007: New UI: Warning bars interfere with dropdowns
=> [WebConsole] Multiple UI fixes

crates/dbsp/src/trace/ord/file/val_batch.rs
Until now, the implementation of the builder for FileValBatch only compared the key from one tuple to the next, which meant that it could write multiple records for a single value, which violates invariants.
=> dbsp: Fix tuple builder for FileValBatch.

crates/sqllib/src/casts.rs, crates/sqllib/src/decimal.rs, crates/sqllib/src/lib.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/MinMaxOptimize.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/Monotonicity.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPBinaryExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt2Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresTimestampTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
There is one commit for each bug.
Fixes #3035, #3038, #3039, #3040, #3041, #3042, #3043
=> [SQL] Fixes several bugs found using SqlLancer.

crates/dbsp/src/storage/file/writer.rs, crates/dbsp/src/trace/test/mod.rs, crates/dbsp/src/trace/test/test_batch.rs
Please see individual commit messages.
=> Add tests for FileValBatch.

python/tests/aggregate_tests/main.py, python/tests/aggregate_tests/test_array_arr_agg.py, python/tests/aggregate_tests/test_array_count.py, python/tests/aggregate_tests/test_array_count_col.py, python/tests/aggregate_tests/test_array_every.py, python/tests/aggregate_tests/test_array_some.py, python/tests/aggregate_tests/test_array_tbl.py
Also added a column with **MAP<VARCHAR, INT> ARRAY** type and adjusted ARRAY_AGG tests accordingly.
=> py: ARRAY type tests for COUNT, EVERY and SOME aggregates

Cargo.lock, crates/dbsp/Cargo.toml, crates/fda/Cargo.toml, crates/feldera-types/Cargo.toml, crates/pipeline-manager/Cargo.toml, crates/sqllib/Cargo.toml, openapi.json, python/pyproject.toml
=> release: bump project version to 0.31.1

Earthfile, deploy/docker-compose-extra.yml, deploy/docker-compose.yml, docs/docker.md
- **release: bump project version to 0.31.1**
- **docker: point compose file to Feldera version 0.31.31**
=> post release v0.31.1

crates/sqllib/src/casts.rs, crates/sqllib/src/timestamp.rs, docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/BaseCompilerException.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/CastTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/OptimizedVariantTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/VariantTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java, sql-to-dbsp-compiler/build.sh
Fixes #3070 
Fixes #3071 
Fixes #3072 
Fixes #3073 
Fixes #3074 
Fixes #3076
=> [SQL] Fixes bugs found by SQLancer

crates/adapters/src/controller/mod.rs, crates/adapters/src/format/json/input.rs, crates/adapters/src/test/mod.rs, crates/feldera-types/src/format/json.rs, crates/pipeline-manager/src/api/mod.rs, docs/formats/json.md, openapi.json, web-console/src/lib/services/manager/schemas.gen.ts, web-console/src/lib/services/manager/types.gen.ts
Fixes: https://github.com/feldera/feldera/issues/3029
=> dbsp_adapters: Add support for multiline JSON.

README.md, crates/sqllib/src/timestamp.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeMap.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeVec.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TimeTests.java
Fixes #3086 
Fixes #3083 
Fixes #3074
=> [SQL] Three commmits fixing bugs in the SQL compiler runtime

docs/sql/array.md, docs/sql/map.md, python/tests/aggregate_tests/main.py, python/tests/aggregate_tests/test_array_arg_max.py, python/tests/aggregate_tests/test_array_arg_min.py
Also added documentation for comparison operations on Array types.
=> py: ARRAY type tests for ARG_MIN and ARG_MAX aggregates

crates/fda/Cargo.toml, crates/fda/src/cli.rs, crates/fda/src/main.rs, crates/pipeline-manager/src/api/examples.rs, crates/pipeline-manager/src/api/pipeline.rs, openapi.json
Fixes https://github.com/feldera/feldera/issues/2784
Fixes https://github.com/feldera/feldera/issues/3010
=> [fda] fix --recompile and add --version

sql-to-dbsp-compiler/build.sh
I want to do some work in the variant branch of Calcite to get that merged into main.
So I saved the commit that works in the `stable-variant` branch.
=> [SQL] Build compiler based on a branch which does not change accidentally

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Projection.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/LowerCircuitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt2Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt4Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt8Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java, sql-to-dbsp-compiler/temp/Cargo.toml
=> [SQL] a function that clones a complex value (e.g. an ARRAY) is still a projection

Earthfile, README.md, deploy/docker-compose-extra.yml, deploy/docker-compose.yml, docs/docker.md
- **release: bump project version to 0.31.2**
- **docker: point compose file to Feldera version 0.31.2**
=> post release v0.31.2

docs/sql/datetime.md, docs/sql/udf.md
The table in datetime.md does not render correctly now.
=> [DOC] Small SQL documentation fixes

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/ExpandCasts.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
=> [SQL] Workaround Calcite's inconsistent typing of ROW fields (#3119)

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
=> [SQL] Correctly optimize initializer functions in ChainAggregate operators (#3145)

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Insert explicit casts for several function arguments

crates/sqllib/src/casts.rs, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Do not panic when parsing a null string into a nullable integer

python/docs/examples.rst, python/feldera/enums.py, python/feldera/pipeline.py, python/feldera/pipeline_builder.py, python/feldera/rest/feldera_client.py, python/feldera/rest/pipeline.py, python/tests/test_pipeline.py, python/tests/test_pipeline_builder.py, python/uv.lock
* add setting timeout while waiting for compilation and state transitions
Fixes: #3101
Fixes: #1832
Fixes: #3118
=> [py] expose inner pipeline metadata

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] For cross-joins outer joins are the same as inner joins

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Two commits fixing two bugs

docs/connectors/index.mdx, python/docs/examples.rst, python/feldera/pipeline.py, python/feldera/rest/feldera_client.py, python/tests/test_pipeline_builder.py, python/uv.lock
* add example of adhoc query to the python docs
* add checkpoint api to `Pipeline` class
Fixes: #3127 
Fixes: #2821 
Fixes: #2910
=> [py] add support for connector orchestation

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
=> [SQL] Point to the right column name on foreign key validation failure

python/tests/arithmetic_tests/test_date.py, python/tests/arithmetic_tests/test_time.py, python/tests/arithmetic_tests/test_timestamp.py
Changes:
1. Add TIME/DATE/TIMESTAMP -/+ LONG and SHORT interval 
2. Negate Intervals created by subtracting TIME, DATE and TIMESTAMP values
Prior to these changes, there were only tests for DATE/TIMESTAMP -/+ Interval SECOND and TIME -/+ INTERVAL HOUR/MINUTE.
=> py: update arithmetic tests

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/recursive/RecursiveTests.java
=> [SQL] Improve error message for recursive view type mismatch (#2977)

python/tests/aggregate_tests/main.py, python/tests/aggregate_tests/test_empty_set.py, python/tests/aggregate_tests/test_row_count_col.py
Contains:
1. ROW type tests for COUNT aggregate
2. Tests that return Empty for various aggregates
=> py: add ROW type tests for COUNT aggregate and tests returning empty

crates/adapters/src/catalog.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/ViewMetadata.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
This adds an undocumented compiler flag and an undocumented view property.
We may document them later if we decide to expose them.
=> [SQL] Experimental support for mixing SQL and Rust views

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNestedOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Do not crash when comparing different recursive components

python/feldera/pipeline.py, python/feldera/rest/feldera_client.py
Documents the edge case encountered by: #3230
=> py: docs: all FP nums are deserialized as Decimal

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] CalciteException during parsing is not an ICE

Cargo.lock, crates/adapters/src/adhoc/table.rs, crates/adapters/src/format/avro/input.rs, crates/adapters/src/format/parquet/mod.rs, crates/adapters/src/format/parquet/test.rs, crates/adapters/src/integrated/delta_table/test.rs, crates/adapters/src/test/data.rs, crates/adapters/src/test/datagen.rs, crates/adapters/src/test/mod.rs, crates/feldera-types/src/program_schema.rs, crates/feldera-types/src/serde_with_context/serde_config.rs, crates/sqllib/Cargo.toml, crates/sqllib/src/binary.rs, docs/connectors/sinks/delta.md, docs/connectors/sources/delta.md
See individual commits for details.
=> [adapters] Delta Lake tests + doc improvements.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CustomFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayFunctionsTests.java
=> [SQL] More lenient type checking for ARRAYS_OVERLAP (#3272)

crates/feldera-types/src/program_schema.rs
We have a manually written parser for type `Field`.  The parser ignored `key` and `value` fields used in `MAP` fields.  This affected maps nested inside struct's, row's and other containers.
=> [adapters] Fix program schema parser.

crates/sqllib/src/lib.rs, crates/sqllib/src/operators.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] IS DISTINCT FROM can have nullable arguments (#3278)

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNestedOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CSE.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/RecursiveComponents.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/recursive/RecursiveTests.java
=> [SQL] Remove spurious warning; CSE for delta operators

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDecimal.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeString.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/build.sh
Will mark this as draft until some Calcite PRs are merged enabling us to solve the issues completely.
https://issues.apache.org/jira/browse/CALCITE-6413
https://issues.apache.org/jira/browse/CALCITE-6770
=> [SQL] Better error messages involving string and decimal types (#3247)

crates/dbsp/src/operator/dynamic/input_upsert.rs, crates/dbsp/src/operator/dynamic/trace.rs, crates/dbsp/src/operator/dynamic/upsert.rs, crates/dbsp/src/operator/trace.rs, crates/dbsp/src/trace/mod.rs, crates/dbsp/src/trace/ord/file/val_batch.rs, crates/dbsp/src/trace/ord/mod.rs, crates/dbsp/src/trace/ord/vec/indexed_wset_batch.rs, crates/dbsp/src/trace/ord/vec/key_batch.rs, crates/dbsp/src/trace/ord/vec/val_batch.rs, crates/dbsp/src/trace/ord/vec/wset_batch.rs, crates/dbsp/src/trace/test/mod.rs, crates/dbsp/src/trace/test/test_batch.rs
Fixes #3303.
See commit messages for details
=> Correctly GC output of `chain_aggregate`.

docs/enterprise/helm-guide.md, docs/enterprise/quickstart.md
=> release: bump enterprise version docs to reference 0.15.1

docs/sidebars.js, docs/tutorials/index.md
Added a top-level page for the Guides section, so we can reference it, e.g., from README.
=> [docs] Index page for the Guides section.

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/containers.yml, .github/workflows/kafka-connect-image.yml, deploy/Dockerfile, deploy/Dockerfile.demo
Ensure devcontainer works on arm64
Fix https://github.com/feldera/feldera/issues/2365: build arm images
=> [CI] Add arm64 release image build to containers.yml

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/CircuitToString.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/DBSPCircuit.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNestedOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/dot/ToDot.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/dot/ToDotNodesVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitGraph.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitGraphs.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Graph.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeIncrementalVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/RecursiveComponents.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeCode.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/graph/Port.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/recursive/IncrementalRecursiveTests.java
=> [SQL] Local views in recursive components can be used by non-recursive code

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Correctly handle named field accesses in nested structures (#3326)

crates/dbsp/src/dynamic/rkyv.rs, crates/dbsp/src/operator/group/custom_ord.rs, crates/dbsp/src/storage/file/mod.rs, crates/dbsp/src/trace/mod.rs, crates/dbsp/src/trace/spine_async/mod.rs, crates/sqllib/src/variant.rs
This means we need to use `SharedDeserializeMap` instead of `Infallible` in Deserialize.
=> Make sure we accept Arc<Variant> in circuits.

docs/connectors/sources/s3.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/IConstructor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/ExpandCasts.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPBaseTupleExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPCastExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPIndexedZSetExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPMapExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPVecExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPZSetExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPLiteral.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBaseType.java
I should implement some way of checking this in the compiler. I will think about it.
=> [SQL] Add a few missing clone() calls in the generated Rust code

docs/enterprise/helm-guide.md, docs/enterprise/quickstart.md
=> helm: update Enterprise version to v0.16.1

crates/adapters/src/format/avro/deserializer.rs, crates/adapters/src/static_compile/deinput.rs
We use four different deserializers in the adapters crate: JSON, CSV, Avro, and Arrow. As a result, every `Deserialize` implementation for every input tablecrecord type was instantiated four times, once for each `Deserializer` type.  To fix this, we use the `erased-serde` crate, which provides a dynamically typedc`Deserializer` API. By wrapping all deserializers in `erased_serde::Deserializer` we ensure that the `impl Deserialize` is instantiated exactly once for each type.  On a program with 30 or so large input table and no views, this optimization reduces generated LLVM code from 6.5M to 4.5M lines.
=> [adapters] Reduce serde code.

crates/dbsp/src/storage/backend/mod.rs
Feldera's most common deployment environment (EKS) disables io_uring in the default seccomp profile (and it's hard to set a profile that specifically allows io_uring), so it's better to use the POSIX storage backend by default so that most Feldera testing runs the same code as most deployments.
=> [dbsp] Disable io_uring storage by default.

crates/dbsp/src/operator/sum.rs
Label the output of the `Sum` operator as sharded if all inputs are sharded.
=> [dbsp] The sum of sharded streams is sharded.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresWindowTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
Fixes https://github.com/feldera/internal_planning/issues/126
=> [SQL] Improved error message for unsupported WINDOW aggregates

crates/feldera-types/src/serde_with_context/deserialize.rs, crates/feldera-types/src/serde_with_context/serialize.rs, crates/sqllib/src/casts.rs, crates/sqllib/src/lib.rs, crates/sqllib/src/map.rs, crates/sqllib/src/variant.rs, docs/sql/udf.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/NonLinearAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPMapExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPType.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeCode.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeBTreeMap.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeOption.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeResult.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeTypedBox.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeUser.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeVec.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeWithCustomOrd.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/IsolatedTest.java
This is a step towards reducing the cost of cloning big structures.
For now this is only applied to Map values, since there are relatively few functions.
After this is merged, the next step is to apply this to Variant and Vec values as well.
=> [SQL] Use Arc for Map implementations

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/UnimplementedException.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteObject/CalciteRexNode.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Give a good error message for joins on struct types

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
Fixes https://github.com/feldera/internal_planning/issues/177
=> [SQL] Correctly handle temporal filters that return nullable values

crates/sqllib/src/array.rs, crates/sqllib/src/map.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNestedOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/EliminateDump.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/ExpandWriteLog.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/NonLinearAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPAssignmentExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPBlockExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeVoid.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TestCase.java, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
=> [SQL] Eliminate unnecessary clones from array_agg and map_agg

docs/enterprise/helm-guide.md, docs/enterprise/quickstart.md
=> release: bump Enterprise version to v0.18.0

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitGraph.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/UnusedFields.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
=> [SQL] Trimming input fields has to preserve the map operator after the input (#3427)

Earthfile
CI Logs are very large and browsing them is difficult.
This should reduce spew.
=> [CI] Quiet cargo execution

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/FieldUseMap.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/ReplaceCommonProjections.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/derived/DBSPTypeTupleBase.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/OuterTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/OuterJoinTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
=> [SQL] Produce narrower antijoins when implementing outer joins

crates/sqllib/src/lib.rs, scripts/start_manager.sh
Two small post-fixes for the `Array` PR.
=> Array postfixes.

crates/dbsp/src/circuit/runtime.rs, crates/dbsp/src/profile/mod.rs, crates/dbsp/src/storage/buffer_cache/cache.rs, crates/dbsp/src/storage/file/cache.rs, crates/dbsp/src/storage/file/mod.rs, crates/dbsp/src/storage/file/reader.rs, crates/dbsp/src/storage/file/writer.rs, crates/dbsp/src/trace/ord/file/indexed_wset_batch.rs, crates/dbsp/src/trace/ord/file/key_batch.rs, crates/dbsp/src/trace/ord/file/val_batch.rs, crates/dbsp/src/trace/ord/file/wset_batch.rs, crates/feldera-types/src/config.rs, openapi.json, web-console/src/lib/services/manager/schemas.gen.ts, web-console/src/lib/services/manager/types.gen.ts
Also adds some profile statistics for the size and occupancy of the cache.
=> [dbsp] Add user configuration for the storage cache size.

crates/sqllib/src/casts.rs, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/CastTests.java
=> [SQL] Accept intervals with a + sign in leading position

crates/pipeline-manager/src/api/endpoints/metrics.rs, crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs, crates/pipeline-manager/src/api/error.rs, crates/pipeline-manager/src/api/examples.rs, crates/pipeline-manager/src/compiler/error.rs, crates/pipeline-manager/src/integration_test.rs, crates/pipeline-manager/src/metrics.rs, crates/pipeline-manager/src/runner/error.rs, crates/pipeline-manager/src/runner/interaction.rs, crates/pipeline-manager/src/runner/local_runner.rs, crates/pipeline-manager/src/runner/main.rs, crates/pipeline-manager/src/runner/pipeline_automata.rs, crates/pipeline-manager/src/runner/pipeline_executor.rs, openapi.json, web-console/src/lib/services/pipelineManager.ts
The errors during pipeline interaction, runner interaction and runner deployment are improved to be more meaningful (e.g., provide contextual hints and suggestions) as well actionable (e.g., suggest a way to resolve the error if possible).
The HTTP client used to interact with the pipeline and the runner is now reused by both the API server and the runner, which should reduce CPU utilization and shorten response times.
=> pipeline-manager: improved pipeline and runner error reporting

crates/pipeline-manager/src/api/endpoints/config.rs, crates/pipeline-manager/src/api/main.rs
Fixes: https://github.com/feldera/feldera/issues/3453
=> pipeline-manager: revision in welcome message and GET `/config`

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/LowerCircuitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPFieldExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/build.sh
=> [SQL] Fields access in a nullable struct is a nullable result

crates/dbsp/src/circuit/metadata.rs, crates/dbsp/src/circuit/runtime.rs, crates/dbsp/src/profile/mod.rs, crates/dbsp/src/storage/buffer_cache/cache.rs, crates/dbsp/src/storage/file/cache.rs, crates/dbsp/src/storage/file/mod.rs, crates/dbsp/src/storage/file/reader.rs, crates/dbsp/src/storage/file/writer.rs, crates/dbsp/src/trace/ord/file/indexed_wset_batch.rs, crates/dbsp/src/trace/ord/file/key_batch.rs, crates/dbsp/src/trace/ord/file/val_batch.rs, crates/dbsp/src/trace/ord/file/wset_batch.rs, crates/dbsp/src/trace/spine_async/mod.rs
This improves performance in multiple ways. Please see the individual commits for details.
=> Performance improvements

crates/pipeline-manager/src/runner/interaction.rs
After the API server has issued a request to a pipeline but has not yet received a response, the connection might be broken. The reason for this disconnect is likely due to a failure at the pipeline itself (e.g., a fatal error or panic), causing it to be unable to return a response. The error message until this commit for this scenario is not very illuminating and slightly confusing due to the usage of the word "connector": "Failed to connect to host: Internal error: connector has been disconnected". The error message is improved by explaining further and hinting towards likely causes.
=> pipeline-manager: custom error message for disconnect during request

crates/dbsp/src/circuit/circuit_builder.rs, crates/dbsp/src/circuit/runtime.rs, crates/dbsp/src/operator/communication/exchange.rs, crates/dbsp/src/operator/dynamic/communication/gather.rs, crates/dbsp/src/operator/input.rs, crates/dbsp/src/operator/output.rs, crates/dbsp/src/profile/mod.rs, crates/dbsp/src/storage/buffer_cache/cache.rs, crates/dbsp/src/trace/spine_async/mod.rs
Please see individual commits for more details.
=> Report cache statistics separately for foreground and background workers

crates/sqllib/src/casts.rs, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Handle correctly + sign for intervals DAY TO SECOND

crates/dbsp/src/operator/dynamic/time_series/window.rs, crates/dbsp/src/storage/buffer_cache/fbuf.rs, crates/dbsp/src/storage/buffer_cache/mod.rs, crates/dbsp/src/storage/file/mod.rs, crates/dbsp/src/storage/file/writer.rs
Thanks to @lalithsuresh for reporting many of these.
=> Multiple optimizations for writing to storage

crates/dbsp/src/dynamic/data.rs, crates/dbsp/src/dynamic/declare_trait_object.rs
This may help with some perf work.
=> [dbsp] Implement Hash for dyn DataTrait.

crates/adapters/src/transport/url.rs
- Log the HTTP status code at info level
- Stricter handling of `Content-Range` header, returning an error if it is present for a response which is not 206 Partial Content
- Request timeout changed from default (5s) to dedicated constant (10s)
=> adapters: improve URL connector error reporting

crates/dbsp/src/operator/dynamic/controlled_filter.rs
Fixes https://github.com/feldera/feldera/issues/3513.
=> [dbsp] Properly sort error stream for controlled filters.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNestedOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/FieldUseMap.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/FindCommonProjections.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/ReplaceCommonProjections.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ir/UnusedFieldsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Correctly handle nullable tuples in unused field elimination

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggScottTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
This makes the validator accept queries of the from 
`SELECT x FROM t GROUP BY 1;`
=> [SQL] Enable GROUP BY column index

crates/dbsp/src/operator/dynamic/aggregate/mod.rs, crates/dbsp/src/trace/ord/file/indexed_wset_batch.rs, crates/dbsp/src/trace/ord/file/key_batch.rs, crates/dbsp/src/trace/ord/file/val_batch.rs, crates/dbsp/src/trace/ord/file/wset_batch.rs, crates/dbsp/src/trace/ord/vec/indexed_wset_batch.rs, crates/dbsp/src/trace/ord/vec/key_batch.rs, crates/dbsp/src/trace/ord/vec/val_batch.rs, crates/dbsp/src/trace/ord/vec/wset_batch.rs
Thanks to Leonid Ryzhyk for the suggestions (from https://github.com/feldera/feldera/pull/3528).
=> [dbsp] Polish new builder API implementation.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
Fixes https://github.com/feldera/internal_planning/issues/179
=> [SQL] Do not trust the nullability of some Calcite expressions

crates/dbsp/src/trace/ord/file/wset_batch.rs
`step_val` invalidated both the key and value, which is wrong.  `step_val` should only invalidate the value.
=> [dbsp] trace: Fix implementation of FileWSetCursor::step_val.

crates/feldera-types/src/error.rs, crates/pipeline-manager/src/api/main.rs, crates/pipeline-manager/src/integration_test.rs, crates/pipeline-manager/src/runner/error.rs, crates/pipeline-manager/src/runner/local_runner.rs, crates/pipeline-manager/src/runner/pipeline_automata.rs, crates/pipeline-manager/src/runner/pipeline_executor.rs
The runner writes deployment check outcomes to the runner log and the pipeline log. The check informs about the resources provisioned for the deployment. This information is useful for debugging.
=> pipeline-manager: deployment check

crates/dbsp/src/circuit/runtime.rs
=> [dbsp] Log message improvements.

crates/dbsp/src/trace/ord/fallback/utils.rs
Commit 722f9b053e87 ("[dbsp] trace: Change `Builder` to reduce copying and comparing.") updated the GenericMerger to handle the new `Builder` interface, but it inadvertently dropped support for untimed batches in merging diffs.  This fixes the problem (which manifested as a pipeline panic).
=> [dbsp] Fix GenericMerger for untimed batches.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/LazyStatics.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/FieldUseMap.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/FindUnusedFields.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBool.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/OuterJoinTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
=> [SQL] Pull one-sided predicates before joins

sql-to-dbsp-compiler/slt/skip.txt, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/Main.java, sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
=> [SLT] Disable known broken tests

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Fix detection of cross-joins #3589

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Proper error message for unhandled UNNEST

docs/connectors/sinks/redis.md, docs/sidebars.js
* Added Redis docs to the sidebars.js.
* Improved the wording in the intro section.
=> [docs] Add Redis docs to ToC.

web-console/src/lib/functions/common/promise.ts
Fix https://github.com/feldera/feldera/issues/3602: Polling of /stats continues on main screen occasionally
=> [WebConsole] Fix polling loop not cancelling when a request is in progress

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/build.sh
=> [SQL] ARRAY_JOIN is an alias for ARRAY_TO_STRING 

docs/connectors/orchestration.md, docs/sql/ad-hoc.md
Fix two links broken by recent API documentation work.
=> [docs] Fixup REST API links.

docs/sql/recursion.mdx, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteObject/CalciteRelDataType.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
=> [SQL] More lenient validation for recursive view declarations

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
=> [SQL] Additional validation for default values

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CustomFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
=> [SQL] For views with declarations use the declared type rather than the inferred type

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/TrimFilters.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
=> [SQL] Do not remove unused fields from nested structures

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPViewDeclarationOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateViewStatement.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
=> [SQL] Use declared view type in metadata as well

crates/adapters/src/controller/stats.rs
Resolve a deadlock where the same thread took a read lock and then attempted to take a write lock on ControllerStatus::inputs.
- The main controller thread takes the read lock and calls `InputReader::queue` on each input connector.
- A connector pushes some records to the circuit and calls `ControllerStats::completed`, which determines that the connector is finished and calls `start_dependencies` to unpause any connectors waiting for this one to finish.
- `start_dependencies` invokes `start_input_endpoint`, which tries to take a write lock in order to set ep.paused to true.
To solve this, I changed the type of the `paused` flag to `AtomicBool`, so it only requires a read lock.
=> [adapters] Deadlock with connector orchestration.

web-console/src/lib/components/pipelines/editor/TabLogs.svelte
Fix shutdown warning disappears over logs when compiling
=> [WebConsole] Fix pipeline log not fetched in Unavailable state

crates/pipeline-manager/src/runner/pipeline_automata.rs
=> pipeline: increase initialization timeout

docs/sql/types.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] User-defined types cannot be recursive

crates/pipeline-manager/src/compiler/rust_compiler.rs
Makes use of the `Drop` trait to terminate the Rust compilation process group both upon normal cancellation (i.e., outdated or no longer exists) or when the manager process is terminated itself (e.g., using Ctrl-C in the terminal). Note that the process group is only terminated if the `Drop` trait is actually called. The triggering of destructors happens usually, but is not guaranteed.
In my local testing:
- Ctrl-C in terminal: triggered
- Manually `kill -s SIGINT <pid of pipeline-manager>`: triggered
- Manually `kill -s SIGKILL <pid of pipeline-manager>`: not triggered
This sufficiently covers our use case.
Useful command to see the current processes:
```
ps o user,group,gid,pid,ppid,pgrp,%cpu,%mem,start,time,comm
```
=> pipeline-manager: terminate Rust compilation process group upon cleanup

web-console/src/lib/compositions/health/systemErrors.ts, web-console/src/lib/functions/pipelines/monaco.ts
Fix https://github.com/feldera/feldera/issues/3660: Rust warnings in dbsp make all SQL code an error
=> Fix Rust warnings highlighted as errors in code editor

crates/pipeline-manager/src/api/endpoints/config.rs, crates/pipeline-manager/src/api/main.rs, openapi.json, web-console/src/lib/services/manager/services.gen.ts, web-console/src/lib/services/manager/types.gen.ts, web-console/src/lib/services/pipelineManager.ts, web-console/src/routes/+layout.ts
This turns it into an authenticated endpoint.
=> pipeline-manager: move `/config` endpoint to `/v0/config`

crates/adapters/src/util.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/StructTests.java
=> [SQL] Correctly handle Option<Tup<Option<Array<>>>> array field access

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TopKTests.java
=> [SQL] Accept more TopK patterns

crates/feldera-types/src/query_params.rs, openapi.json
=> api: make API docs URL MDX parseable

docs/connectors/orchestration.md
=> docs: fix broken API documentation link

crates/adapters/src/controller/mod.rs
Regression fix: The metrics recorder must be initialized before the circuit or else the DBSP metrics will not be recorded.
=> [adapters] initialize metrics recorder before circuit

crates/adapters/src/adhoc/mod.rs, crates/adapters/src/controller/mod.rs
This should make sure that queries don't just use an unlimited amount of memory and eventually also spill to disk. At least for now it seems that spill to disk for sorting isn't quite working yet, see
https://github.com/apache/datafusion/issues/15028
https://github.com/apache/datafusion/issues/15271
So the behaviour with this patch is that the query just aborts if you have a resource limit set in the pipeline config.
=> Add resource limits to datafusion config.

crates/dbsp/src/trace/spine_async/list_merger.rs
ListMerger::work uses the MergeCursor::has_mut() method to determine whether the cursor is able to yield elements by value. It only called this method on the first cursor, making an assumption that it returns the same value on all cursors in the list. This is not the case, since the list can contain a mix of in-memory and file-based cursors, which caused a panic.
The fix is to maintain an array of flags, one per cursor.
=> [dbsp] Panic in ListMerger.

python/tests/arithmetic_tests/main.py, python/tests/arithmetic_tests/test_interval.py, python/tests/arithmetic_tests/test_timestamp.py
=> py: update interval arithmetic tests

crates/adapters/src/format/parquet/mod.rs, docs/sql/types.md
=> Fix for issue 3701

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/UnimplementedException.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
=> [SQL] Improve error message for unimplemented functions

docs/tutorials/time-series.md, python/feldera/pipeline.py
=> docs: fix some broken URLs to the documentation

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/RelColumnMetadata.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/IHasSchema.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/UnusedFields.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/adapters/AvroSchemaTest.java
=> [SQL] Add information in schema.json about unused columns

docs/sql/udf.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/BaseRustCodeGenerator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ICodeGenerator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustWriter.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/MultiCrates.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/ExternalFunction.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MultiCrateTests.java
=> [SQL] Represent ROW and UDT as Tuples and not structs

crates/adapters/src/transport/kafka/ft/input.rs, crates/adapters/src/transport/kafka/mod.rs, crates/adapters/src/transport/kafka/nonft/input.rs
This should work around https://github.com/feldera/feldera/issues/3794. I have not investigated the underlying cause of the problem.
=> [adapters] Serialize Kafka adapter initialization.

crates/pipeline-manager/src/compiler/rust_compiler.rs
Environment variable `RUSTFLAGS` is now inherited by the Rust compilation if it is defined.
Reduce logging verbosity of Rust compilation cleanup.
=> pipeline-manager: Rust compilation inherits `RUSTFLAGS`

crates/pipeline-manager/src/compiler/sql_compiler.rs, demo/packaged/sql/07-time-series-tutorial.sql, docs/sql/identifiers.md, docs/sql/json.md, docs/sql/table.md, docs/tutorials/time-series.md, sql-to-dbsp-compiler/SQL-compiler/pom.xml, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CustomFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ToJsonVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/FoodmartPivotTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/OperatorTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/StreamTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/AggregateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayFunctionsTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/PivotTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/SerdeTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TrigonometryTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/VariantTests.java, sql-to-dbsp-compiler/build.sh, sql-to-dbsp-compiler/using.md
=> [SQL] Upgrade Calcite

crates/adapters/src/controller/mod.rs
This should avoid occasional failures in some of our higher-level tests.
=> [adapters] Avoid race for running ad hoc query after input processed.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/CompilerMain.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpchTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/resources/metadataTests-generateDFRecursive.json
=> [SQL] another round of predicate pushdown in Calcite

docs/sql/string.md, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
Translating more hand-written Rust tests for Nexmark correctness to SQL tests
Part of #164 
More work needs to be done, so the issue cannot be closed yet
=> [SQL] More Nexmark tests

crates/adapterlib/src/transport.rs
=> [adapters] Add transition diagram for `InputReaderCommand`.

crates/adapterlib/src/transport.rs, crates/dbsp/src/typed_batch.rs
=> [dbsp] Implement rkyv traits for TypedBox.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
=> [SQL] Derive required traits for compiler-generated structures

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPOperatorWithError.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/dot/ToDotNodesVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/BaseCompilerException.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilationError.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteObject/CalciteObject.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteObject/CalciteSqlParserPos.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ToJsonVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
=> [SQL] Improved error reporting; fix missing JSON for nodes with 2 outputs

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/resources/metadataTests-generateDF.json, sql-to-dbsp-compiler/SQL-compiler/src/test/resources/metadataTests-generateDFRecursive.json
Fixes #3902 
I have written a Python test to check that this is fixed, but I didn't check it in; it is based on the issue filed.
=> [SQL] Struct name hash should depend on field names

sql-to-dbsp-compiler/build.sh
Pick up a newer version of Calcite, with a fix for #3926
=> [SQL] Upgrade Calcite version

crates/sqllib/src/interval.rs, docs/sidebars.js, docs/sql/array.md, docs/sql/casts.md, docs/sql/datetime.md, docs/sql/decimal.md, docs/sql/json.md, docs/sql/map.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
=> abs for INTERVAL

crates/dbsp/src/storage/file/writer.rs
The code that writes to layer files has to guess a good size for the blocks it writes.  There's a fixed minimum block size, but there's no fixed maximum size; there can't be, because a block must be big enough to fit some number of data items, and data items don't have a fixed maximum size. It's better to guess an accurate block size in advance to avoid data copying.  The code here was meant to guess that the next block would be the same size as the previous one, but it had a bug: it instead guessed that it would be the same size as the previous buffer capacity, which might be (much) larger than the block.  This meant that each buffer was always at least as large as the previous one, so that buffers could grow but not shrink.  If a large block came along (because of large data items) but …
=> [dbsp] Better size storage buffers for writing.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
This should improve slightly the incremental compilation
=> [SQL] Strip all table/view properties from the JSON passed to the circuit 'register' APIs

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
Fixes https://github.com/feldera/cloud/issues/818
=> [SQL] Add hash to input stream before registering them

crates/pipeline-manager/src/compiler/rust_compiler.rs, crates/pipeline-manager/src/compiler/sql_compiler.rs, crates/pipeline-manager/src/compiler/util.rs
The compilation process is now put into a process group, such that it's possible to terminate it with all of its spawned subprocesses. This is done using the `ProcessGroupTerminator` which terminates the process group when going out of scope. This is the same approach as used for the Rust compiler.
- Fixes: https://github.com/feldera/feldera/issues/3985
=> pipeline-manager: fix SQL compiler terminating upon cancel

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/visitors/outer/TemporalFilterTests.java
The first bug is that the code would generate inefficient implementations using joins in many cases where this was not necessary.
The second bug is that the code would use unwrap() unsafely in the evaluation of some synthesized filters. The correct way is not to unwrap, but to interpret NULL as FALSE.
=> [SQL] Fix two bugs in the generation of temporal filters

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/WinAggPostTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
=> [SQL] Window aggregates can have constant arguments

.github/workflows/test-integration.yml, web-console/src/lib/components/pipelines/editor/TabPerformance.svelte, web-console/src/lib/compositions/layout/useIsMobile.svelte.ts, web-console/src/lib/types/pipelineManager.ts
=> [WebConsole] Display when pipeline has started

.github/workflows/build-docker-dev.yml, deploy/build.Dockerfile
Plus some adjustments to the dev container build.
=> generate dev-container on aarch64

crates/adapters/src/server/mod.rs, crates/fda/src/main.rs, crates/feldera-types/src/checkpoint.rs, crates/feldera-types/src/config.rs, crates/feldera-types/src/lib.rs, crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs, crates/pipeline-manager/src/api/main.rs, crates/pipeline-manager/src/db/types/utils.rs, crates/pipeline-manager/tests/integration_test.rs, docs/pipelines/fault-tolerance.md, openapi.json
Fixes some checkpoint-related issues:
* https://github.com/feldera/feldera/issues/3992
* https://github.com/feldera/feldera/issues/4022
* https://github.com/feldera/feldera/issues/3200
=> Checkpoints

crates/adapters/src/format/avro/schema.rs, crates/adapters/src/format/avro/serializer.rs, crates/adapters/src/format/avro/test.rs, crates/adapters/src/test/data.rs, crates/adapters/src/test/datagen.rs, crates/adapters/src/transport/kafka/ft/input.rs
Partially fixes #4019
* Fix Avro parser for case-sensitive columns
* Fix parse error reporting in Kafka input connector
=> [adapters] Avro parser fixes.

crates/adapters/Cargo.toml, crates/adapters/src/transport/kafka/ft/input.rs, crates/adapters/src/transport/kafka/ft/mod.rs, crates/adapters/src/transport/kafka/ft/output.rs, crates/adapters/src/transport/kafka/mod.rs, crates/adapters/src/transport/kafka/nonft/output.rs, crates/dbsp/src/storage/backend/posixio_impl.rs, crates/feldera-types/src/transport/kafka.rs
Commits to help with https://github.com/feldera/feldera/issues/4038
=> Memory usage

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/BaseRustCodeGenerator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/CrateGenerator.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MultiCrateTests.java
Fixes #4049 
It's nice that the bug is fixed by essentially only deleting code.
=> [SQL] Comparisons need to use the sqllib Compare function

web-console/src/lib/components/layout/userPopup/DarkModeSwitch.svelte, web-console/src/lib/components/other/ClipboardCopyButton.svelte, web-console/src/lib/components/pipelines/editor/TabPerformance.svelte, web-console/src/lib/components/pipelines/list/Actions.svelte
=> [WebConsole] Improve Performance tab design and UX

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/IAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/LinearAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/MinMaxAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/NonLinearAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
Fixes #4053.
This fix was suggested by Mihai for the behavior described in #4053.
=> [sql] Emit optimized implementation of MAX.

docs/literature/blog.md, docs/literature/papers.md, docs/literature/videos.mdx, docs/sidebars.js
Fixes #4052 
Blog articles are impossible to discover.
This table of contents is in the feldera sidebar; it does not include the "incremental updates".
=> [DOCS] Create blog TOC; update videos and papers

crates/adapters/src/transport/s3/mod.rs, crates/adapters/src/util.rs, crates/dbsp/src/circuit/operator_traits.rs, crates/feldera-types/src/transport/s3.rs, docs/connectors/sources/s3.md, openapi.json
A series of fixes to the S3 connector. See commit messages for details.
=> [adapters] S3 connector fixes

docs/operations/guide.md
=> docs: call out StorageFull errors in the troubleshooting page

crates/adapters/src/integrated/postgres/output.rs
=> adapters: postgres: properly quote table and field names

crates/adapters/src/static_compile/deinput.rs, crates/adapters/src/transport/s3/mod.rs
See commit messages for details
=> [adapters] S3 connector improvements

deploy/build.Dockerfile
Also make sure CARGO_HOME is set correctly for CI.
=> Add npm to build toolchain.

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
=> [SQL] FP aggregations are never linear

python/feldera/pipeline.py
This small PR throws an exception on invalid `update_format`.
=> Throw exception on invalid update_format

crates/sqllib/src/dec.rs
By default, libdecnumber chooses between standard and scientific notation automatically. serde_arrow only supports the former when serializing decimals to arrow, causing errors in ad hoc queries when the table contains values that end up printed using scientific notation. We use the `to_standard_notation_string` function instead of `to_string` to enforce standard notation.
=> [adapters] Fix dec serialization.

crates/dbsp/src/storage/file/reader/fetch_indexed_zset.rs, crates/dbsp/src/storage/file/reader/fetch_zset.rs, crates/dbsp/src/storage/file/reader/mod.rs
The optimized "distinct" and "join" operators in commit 09322ca5d93a ("[dbsp] Implement overlapping I/O for merge, join, and distinct.") forgot to use the Bloom filters as an additional optimization.  This commit adds that back in.  It achieves an extra ~10% end-to-end performance improvement for my test case.
=> [dbsp] Use Bloom filter in "distinct" and "join" operator optimizations.

.github/workflows/build-java.yml, .github/workflows/build-rust.yml, .github/workflows/test-java.yml, Cargo.lock, Cargo.toml, crates/adapterlib/Cargo.toml, crates/adapterlib/src/utils/datafusion.rs, crates/adapters/Cargo.toml, crates/adapters/src/adhoc/table.rs, crates/adapters/src/integrated/delta_table/output.rs, crates/pipeline-manager/src/compiler/rust_compiler.rs, deploy/build.Dockerfile, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/MultiCratesWriter.java, sql-to-dbsp-compiler/temp/Cargo.toml
Our patches are released we don't have to rely on our fork anymore.
=> [deps] Upgrade datafusion/arrow/serde_arrow/iceberg/delta-rs.

.cargo/config.toml, .github/workflows/test-integration.yml, crates/adapters/src/integrated/delta_table/test.rs, crates/pipeline-manager/src/db/pg_setup.rs
Tests if we can start our docker image in environments without network access.
=> Add integration tests that runs without network.

docs.feldera.com/docs/sql/array.md, docs.feldera.com/docs/sql/function-index.md, docs.feldera.com/docs/sql/map.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/LowerCircuitVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPFlatmap.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeMap.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MultiCrateTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/MapTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpcDsTest.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
=> [SQL] Implement UNNEST for MAP values

crates/adapters/src/integrated/delta_table/test.rs, crates/dbsp/src/circuit/circuit_builder.rs, crates/dbsp/src/storage/file/writer.rs
Fixed three bit-rotten doc tests.
=> [dbsp] Doc test regressions.

docs.feldera.com/docs/changelog.mdx, docs.feldera.com/docs/sidebars.js, docs.feldera.com/package.json, docs.feldera.com/src/css/custom.css
Used to inform uses about changes to enterprise edition.
=> Add changelog to docs.

crates/adapters/src/server/mod.rs
The HTTP server locked the controller (albeit for a short period) on every API call. This is completely unnecessary, since all controller operations require a read-only controller reference. The only reason a lock is needed is for operations that destroy the controller, so they can write None to `state.controller`. For this, a RwLock is sufficient. In the new implementation, only operations that destroy the controller (suspend, shutdown, and fatal error) will take the write lock. All other API calls take the read lock and should be able to run in parallel.
=> [adapters] Convert controller lock to RwLock.

crates/adapters/src/controller/mod.rs
* fixes a bug where calling `sync_checkpoint` would block until the sync succeeded
=> s3_sync: don't block when syncing to s3

crates/sqllib/src/aggregates.rs, crates/sqllib/src/casts.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java
=> [SQL] Use wider accumulators for WINDOW aggregates

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java
This bug was discovered while testing the code for interning.
I am very disappointed that it could have lived in the compiler for so long.
Tests should have caught it sooner.
=> [SQL] Fix right join implementation bug

python/feldera/enums.py, python/feldera/pipeline.py, python/feldera/pipeline_builder.py, python/feldera/rest/feldera_client.py, python/tests/aggregate_tests/aggtst_base.py, python/tests/test_pipeline_builder.py, web-console/src/lib/components/MonacoEditorRunes.svelte, web-console/src/lib/components/dialogs/DangerDialog.svelte, web-console/src/lib/components/other/ApiKeyMenu.svelte, web-console/src/lib/components/pipelines/Table.svelte, web-console/src/lib/components/pipelines/editor/CodeEditor.svelte, web-console/src/lib/components/pipelines/list/Actions.svelte
=> Improve stop options dropdown

crates/sqllib/src/casts.rs, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresTimestampTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/CastTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TableParser.java
Fixes #4255
These have been picked out of #4245, which is growing too much anyway
=> [SQLLIB] Add two missing casts in SQLLIB

crates/sqllib/src/string.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
Fixes #4263 
Fixes #4264 
Fixes #4265
=> [SQL] Fix 3 bugs in string functions

web-console/src/lib/components/pipelines/Table.svelte, web-console/src/lib/components/pipelines/table/AvailableActions.svelte, web-console/src/lib/services/pipelineManager.ts
Fix batch clearing pipelines' storage triggers a different action
Fix excessive polling of pipeline status after multiple start/stop actions
=> [WebConsole] Stop UI postfixes

deploy/build.Dockerfile, docs.feldera.com/docs/pipelines/checkpoint-sync.md, python/feldera/__init__.py, python/feldera/enums.py, python/feldera/pipeline.py, python/feldera/pipeline_builder.py, python/feldera/rest/_helpers.py, python/feldera/rest/feldera_client.py, python/pyproject.toml, python/uv.lock
Fixes: #4282 
All the commits solve different issues and are self contained. Please review commit by commit, instead of everything at once.
=> revert required python version to 3.10 and related fixes

Cargo.toml, crates/fxp/Cargo.toml, crates/fxp/src/lib.rs
This adds some of the functionality requested by @mihaibudiu.
=> Fixed point

crates/adapters/src/controller/mod.rs, crates/adapters/src/controller/test.rs, crates/adapters/src/transport/url.rs, crates/dbsp/src/operator/dynamic/input.rs
Three unrelated fixes that together make the script in #4285 work.
=> Several bootstrapping-related fixes.

crates/adapters/src/integrated/delta_table/input.rs, crates/adapters/src/integrated/delta_table/test.rs
Make sure that the delta connector doesn't get stuck in the barrier state indefinitely even if the transaction log of the table is empty.
=> [adapters] Fix delta connector stuck in the barrier state.

web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte, web-console/src/lib/components/pipelines/CreatePipelineButton.svelte, web-console/src/lib/components/pipelines/Table.svelte, web-console/src/lib/components/pipelines/editor/ProgramStatus.svelte, web-console/src/lib/components/pipelines/list/Actions.svelte, web-console/src/routes/(system)/(authenticated)/(pipelines)/create/+page.ts, web-console/src/routes/(system)/(authenticated)/+page.svelte, web-console/src/routes/(system)/(authenticated)/demos/+page.svelte
Fix https://github.com/feldera/feldera/issues/4317: run in sandbox button doesnt work anymore
Fix https://github.com/feldera/feldera/issues/4315: In pipeline screen when pipeline is in suspending there is no ability to force-stop it
Fix https://github.com/feldera/feldera/issues/4273: Incorrect icon shown for SQL incase of compilation failure due to system error
=> Multiple UI fixes

docs.feldera.com/docs/get-started/enterprise/authentication.md, docs.feldera.com/docs/get-started/enterprise/index.md, docs.feldera.com/docs/sidebars.js
This took me way too long to figure out (and I had a reference to compare with).
They key is to pick Single-page application (SPA), otherwise the settings may look almost identical but nothing works.
=> Add AWS Cognito configuration docs.

scripts/start_manager.sh, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/FieldUseMap.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/FindUnusedFields.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/RemoveUnusedFields.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/RewriteFields.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/TrimFilters.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/DBSPAggregateList.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/IAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/LinearAggregate.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java, sql-to-dbsp-compiler/temp/Cargo.lock, sql-to-dbsp-compiler/temp/src/udf.rs
=> [SQL] Unused field removal for aggregates

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSimpleOperator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/intern/InternInner.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/intern/RewriteInternedFields.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPVariantExpression.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Linq.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
Fixed #4345 
In the end this bug was caused by an incorrect assertion.
But debugging it uncovered a few other inefficiencies which were fixed.
=> [SQL] VARIANT fields can have NULL values

web-console/CLAUDE.md, web-console/src/lib/components/dialogs/JSONDialog.svelte, web-console/src/lib/components/dialogs/JSONForm.svelte, web-console/src/lib/components/dialogs/MultiJSONDialog.svelte, web-console/src/lib/components/layout/pipelines/PipelineConfigurationsPopup.svelte, web-console/src/lib/components/layout/pipelines/PipelineToolbarMenuPopup.svelte, web-console/src/lib/components/pipelines/list/Actions.svelte
Fix https://github.com/feldera/feldera/issues/4385: Web console incorrectly caches failed changes to pipeline runtime configuration
Experimental: add Claude Code reference file for /web-console
=> [WebConsole] Fix pipeline config not reset when closing dialog with invalid data

crates/fxp/src/fixed.rs, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
=> [SQLLIB] Fix bug in MOD DECIMAL computation

sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
This bug was introduced by the error position PR and caused SLT tests to fail compiling.
=> [SLT] Add missing casts in output values

python/feldera/pipeline.py
=> [python] Improve docstring for `set_runtime_config`.

Cargo.lock, Cargo.toml, crates/pipeline-manager/src/runner/pipeline_logs.rs
Forked to solve actix issue https://github.com/actix/actix-web/issues/1313
=> pipeline-manager: use forked actix and improve cleanup

crates/dbsp/src/trace/mod.rs
The implementation used offset 0 as separator, but offset 0 is also generated when serializing an empty tuple. The fix is to use offset -1 instead as a separator.
=> [dbsp] Fix deserialize_indexed_wset.

.github/workflows/build-docker-dev.yml, .github/workflows/build-docker.yml, .github/workflows/build-docs.yml, .github/workflows/check-failures.yml, .github/workflows/ci-release.yml, .github/workflows/ci.yml, .github/workflows/docs-linkcheck.yml, .github/workflows/publish-python.yml, .github/workflows/test-adapters.yml, .github/workflows/test-integration.yml
This gives them a fixed IP for network isolation.
=> [ci] Switch default runners to org runners.

web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte
This implements UI support for https://github.com/feldera/feldera/pull/4452
=> [WebConsole] Allow editing code if storage is used but dev_tweaks.backfill_avoidance = true

crates/sqllib/src/string.rs, docs.feldera.com/docs/sql/function-index.md, docs.feldera.com/docs/sql/string.md, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CustomFunctions.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java
=> [SQL] Support for INITCAP_SPACES function

python/feldera/pipeline.py, python/feldera/rest/feldera_client.py, python/tests/test_shared_pipeline_stress.py
=> py: add logs method and test for it

python/feldera/pipeline.py, python/feldera/rest/feldera_client.py
=> py: `*_nowait` functions for start, stop, pause, resume

crates/adapters/src/transport/kafka/ft/input.rs
These commits add a small amount of detail to the Kafka input connector logs.
=> Kafka logging refinements

crates/adapters/src/transport/file.rs, crates/feldera-types/src/transport/file.rs, openapi.json
Fixes https://github.com/feldera/feldera/issues/4291.
=> [adapters] Allow the file input connector to accept file URLs.

Cargo.lock, crates/adapters/Cargo.toml, crates/adapters/src/controller/mod.rs, crates/adapters/src/server/metrics.rs, crates/dbsp/src/circuit/circuit_builder.rs, crates/dbsp/src/circuit/dbsp_handle.rs, crates/dbsp/src/circuit/metrics.rs, crates/dbsp/src/storage/backend/posixio_impl.rs, crates/dbsp/src/trace/spine_async/mod.rs, crates/pipeline-manager/tests/integration_test.rs, crates/storage/src/histogram.rs, crates/storage/src/metrics.rs
Please take a look at individual commit messages.
=> Adopt Prometheus metric and label naming conventions, and add more metrics

crates/adapters/src/transport/file.rs, crates/dbsp/benches/galen.rs, crates/dbsp/benches/path.rs, crates/dbsp/src/circuit/dbsp_handle.rs, crates/dbsp/src/circuit/runtime.rs, crates/dbsp/src/operator/communication/exchange.rs, crates/dbsp/src/operator/dynamic/communication/shard.rs, crates/dbsp/src/operator/dynamic/distinct.rs, crates/dbsp/src/operator/dynamic/join.rs, crates/dbsp/src/trace/spine_async/thread.rs
=> Replace several occurrences of std::thread::park with crossbeam::Parker.

docs.feldera.com/docs/connectors/sinks/file.md, docs.feldera.com/docs/connectors/sources/file.md, docs.feldera.com/docs/pipelines/fault-tolerance.md, docs.feldera.com/docs/sidebars.js
Fixes: https://github.com/feldera/feldera/issues/3549.
=> Document file connectors.

crates/fda/src/cli.rs, crates/fda/src/main.rs, crates/fda/test.bash, crates/pipeline-manager/src/api/endpoints/pipeline_interaction/support_bundle.rs, openapi.json, python/feldera/pipeline.py, python/feldera/rest/feldera_client.py, python/tests/test_shared_pipeline.py
=> Bundle selector

python/tests/variant_tests/dtype_and_variant.py
=> py: add unsigned int variant tests

crates/adapterlib/src/transport.rs
Based on discussion at https://github.com/feldera/feldera/pull/4461. Thanks to Jørn Lode for the suggestion.
=> [adapters] Improve comment on Resume.

Cargo.lock, crates/pipeline-manager/Cargo.toml, crates/pipeline-manager/migrations/V26__support_data_collections.sql, crates/pipeline-manager/src/api/endpoints/config.rs, crates/pipeline-manager/src/api/endpoints/pipeline_interaction/support_bundle.rs, crates/pipeline-manager/src/api/main.rs, crates/pipeline-manager/src/api/mod.rs, crates/pipeline-manager/src/api/support_data_collector.rs, crates/pipeline-manager/src/auth.rs, crates/pipeline-manager/src/config.rs, crates/pipeline-manager/src/db/operations/pipeline.rs, crates/pipeline-manager/src/db/storage.rs, crates/pipeline-manager/src/db/storage_postgres.rs, crates/pipeline-manager/src/db/test.rs, crates/pipeline-manager/src/db/types/pipeline.rs, crates/pipeline-manager/src/db/types/program.rs, crates/pipeline-manager/src/license.rs, openapi.json
Adds continous support bundle data collection to manager.
No.
=> [manager] Add continous support data collection.

crates/pipeline-manager/src/api/support_data_collector.rs
=> Support bundle tuning

crates/pipeline-manager/src/compiler/rust_compiler.rs, crates/sqllib/src/string.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/BaseRustCodeGenerator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/CrateGenerator.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/MultiCratesWriter.java, sql-to-dbsp-compiler/temp/Cargo.toml
=> [SQL] Use `arcstr::literal!` to intialize static string literals

crates/sqllib/src/timestamp.rs, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
=> [SQLLIB] Add missing EXTRACT functions to library

docs.feldera.com/docs/sql/binary.md, docs.feldera.com/docs/sql/datetime.md
=> docs: change documentation for binary and date-time

Cargo.lock, crates/adapterlib/src/transport.rs, crates/adapters/Cargo.toml, crates/adapters/src/controller/mod.rs, crates/adapters/src/integrated/delta_table/input.rs, crates/adapters/src/test/mock_input_consumer.rs, crates/adapters/src/transport/adhoc.rs, crates/adapters/src/transport/clock.rs, crates/adapters/src/transport/file.rs, crates/adapters/src/transport/http/input.rs, crates/adapters/src/transport/kafka/ft/input.rs, crates/adapters/src/transport/kafka/ft/test.rs, crates/adapters/src/transport/nexmark.rs, crates/adapters/src/transport/pubsub/input.rs, crates/adapters/src/transport/s3/mod.rs, crates/adapters/src/transport/url.rs, crates/adapters/src/util.rs, crates/datagen/src/lib.rs, crates/iceberg/src/input.rs
Fixes #4105 
( it modifies signature of `pub` trait and also changes behavior of logs / errors, but not sure if we count it as breaking change, so leaving checklist blank for now )
Add a few sentences describing the incompatible changes if any.
=> adapters: rate limit errors in InputConsumer with help of tag

crates/feldera-types/src/format/json.rs, crates/feldera-types/src/serde_with_context/serde_config.rs, crates/sqllib/src/binary.rs, docs.feldera.com/docs/formats/json.md
=> Add support for json_flavor "c_hex", and document json flavors.

docs.feldera.com/docusaurus.config.ts, docs.feldera.com/package.json, docs.feldera.com/yarn.lock
Add a few sentences describing the incompatible changes if any.
=> Fix hubspot tracker integration

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
=> [SQL] Two small fixes

docs.feldera.com/docs/sql/datetime.md, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/DateFormatsTests.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/BigQueryTests.java
=> [SQL] Fix documentation for incorrect date/time parsing

crates/pipeline-manager/src/api/main.rs, web-console/svelte.config.js, web-console/vite.config.ts
Bundle only used components of monaco-editor
=> Add cache middleware for web-console files in pipeline-manager

Cargo.lock, Cargo.toml
reverts patch to use forked actix from #4435
=> deps: revert use of forked actix

docs.feldera.com/docs/changelog.md
I figured these out looking at commits and tags.
=> docs: Update changelog release versions.

python/feldera/_callback_runner.py, python/feldera/_helpers.py, python/feldera/rest/feldera_client.py, python/tests/platform/test_shared_pipeline.py
=> py: support listening to case sensitive views

crates/adapters/src/controller/mod.rs, crates/adapters/src/controller/stats.rs, docs.feldera.com/docs/changelog.md, docs.feldera.com/docs/pipelines/transactions.md, docs.feldera.com/docs/sidebars.js, python/feldera/enums.py, python/feldera/pipeline.py, python/feldera/rest/feldera_client.py, python/feldera/stats.py
* Cleanup transaction status reporting by exposing fewer different states to the user.
* Python API for transactions status monitoring.
* Document the transaction API
=> Transaction docs

sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/ImplementStatics.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MultiCrateTests.java
=> [SQL] Fix bug in hash computation for static expressions

Cargo.lock, crates/adapters/Cargo.toml, crates/adapters/src/integrated/delta_table/input.rs, crates/adapters/src/integrated/delta_table/mod.rs, crates/adapters/src/integrated/delta_table/test.rs, docs.feldera.com/docs/connectors/sources/delta.md
Fixes #4695 
( where to update em? )
No. 
Adding support for unity catalog should not break any _existing_ functionality
=> adapters: enable unity catalog feature for deltalake

crates/adapters/src/util.rs
just improving readability and hopefully making tests more robust
=> adapters: use better variable names for rate limiter

crates/adapters/src/test/kafka.rs, crates/adapters/src/transport/kafka/ft/input.rs, crates/adapters/src/transport/kafka/ft/test.rs, crates/feldera-types/src/transport/kafka.rs, docs.feldera.com/docs/connectors/sources/kafka.md, openapi.json
This feature is a customer request.
No breaking changes.
=> [adapters] Allow tolerating missing data in Kafka topics on resume.

crates/adapters/src/format/avro/input.rs
Until now, when an Avro parser is created, it deferred creating the underlying AvroStream that it needs to flush data to the circuit until it obtained a schema.  This was fine when an AvroParser only flushed data that it parsed itself, since it couldn't have any data to flush until it parsed some, and it couldn't parse any data until it had a schema.
However, commit f5e6a41cb0bc ("[adapters] Add data staging support and implement for file, kafka adapters.") causes some input adapters to use an arbitrary example of a parser to flush data obtained from any fork of the same parser.  With the Avro parser, this could cause panics from a missing `input_stream` if data was obtained from one parser and then staged via another fork that had not yet obtained a schema.
This commit should fix the …
=> [adapters] Fix missing `input_stream` in AvroParser::stage().

crates/adapters/src/util.rs
Fixes #4751 ( hopefully ) by using Barrier to sync the threads
not required
nope, just fixing tests
=> adapters: use Barrier in rate limiter test to synchronize check

crates/dbsp/README.md, crates/dbsp/examples/tutorial/tutorial2.rs, crates/dbsp/examples/tutorial/tutorial3.rs, crates/dbsp/examples/tutorial/tutorial4.rs, crates/dbsp/examples/tutorial/tutorial5.rs, crates/dbsp/examples/tutorial/tutorial6.rs, crates/dbsp/examples/tutorial/tutorial7.rs, crates/dbsp/examples/tutorial/tutorial8.rs, crates/dbsp/examples/tutorial/tutorial9.rs, crates/dbsp/src/algebra/zset.rs, crates/dbsp/src/tutorial.rs
Thanks to @swanandx for reporting these.
Issue: https://github.com/feldera/feldera/issues/4769
=> [dbsp] Fix some nitpicks in the DBSP tutorial.

docs.feldera.com/docs/tutorials/time-series.md
Clarified warning about garbage collection for materialized tables.
=> Update garbage collection notes in time-series tutorial

crates/adapters/src/controller.rs, crates/adapters/src/server.rs, crates/dbsp/src/circuit/circuit_builder.rs, crates/dbsp/src/circuit/metadata.rs, crates/dbsp/src/profile.rs, crates/dbsp/src/storage/buffer_cache/cache.rs, crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs, crates/pipeline-manager/src/api/main.rs, sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Utilities.java, sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/ProfilingTests.java
I haven't tested the path through the pipeline manager, but I have a Java tests which checks that the produced profile is a legal json zipped file.
=> [DBSP] Enable retrieving profile as a JSON document

python/README.md, python/tests/README.md
=> [docs] Update Python Test invovations

crates/adapters/src/controller.rs
Maybe this solves the same problem as https://github.com/feldera/feldera/pull/4849 but is simpler?
=> [adapters] Fix initialization race.
