- .earthlyignore
- Cargo.lock
- Earthfile
- crates/adapters/Cargo.toml
- crates/adapters/src/controller/config.rs
- crates/adapters/src/server/mod.rs
- crates/dbsp/benches/gdelt/personal_network.rs
- crates/dbsp/src/operator/group/lag.rs
- crates/dbsp/src/operator/group/topk.rs
- crates/dbsp/src/trace/cursor/cursor_empty.rs
- crates/dbsp/src/trace/layers/erased/vtable.rs
- crates/dbsp/src/trace/ord/merge_batcher/mod.rs
- crates/dbsp/src/trace/persistent/cursor.rs
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/Makefile.toml
- crates/pipeline_manager/build.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/test.rs
- python/.earthlyignore
- scripts/start_manager.sh
- web-ui/.earthlyignore
- web-ui/package.json
Small fixes + add the following tests to CI:
- Add support for nightly Rust tests
- cargo clippy
- cargo fmt
- Python tests
> Progress on Earthly CI

- .gitmodules
git@ URLs don't work in the CI environment.
> Change submodule URL from git@ to https://

- crates/adapters/src/lib.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/http/input.rs
- crates/adapters/src/transport/http/output.rs
- crates/adapters/src/transport/kafka/input.rs
- crates/adapters/src/transport/kafka/output.rs
- crates/adapters/src/transport/mod.rs
I fell into a rabbit hole thinking that I needed dbsp_adapters to parse csv (which definitely isn't true), so I spent a little time adding some more documentation.
The only non-comment changes here are that I made the members of the *Config structs `pub`, because otherwise the readers of the documentation can't tell what configuration settings are available.
> adapters: Add some developer documentation for transports.

- crates/dataflow-jit/src/codegen/call.rs
- crates/dataflow-jit/src/codegen/index_by_column.rs
- crates/dataflow-jit/src/codegen/layout.rs
- crates/dataflow-jit/src/codegen/layout_cache.rs
- crates/dataflow-jit/src/codegen/mod.rs
- crates/dataflow-jit/src/codegen/utils.rs
- crates/dataflow-jit/src/codegen/vtable/clone.rs
- crates/dataflow-jit/src/codegen/vtable/default.rs
- crates/dataflow-jit/src/ir/exprs/mod.rs
- crates/dataflow-jit/src/ir/exprs/visit.rs
- crates/dataflow-jit/src/ir/function/passes/mod.rs
- crates/dataflow-jit/src/ir/function/passes/unit_ops.rs
- crates/dataflow-jit/src/ir/validate.rs
- crates/dataflow-jit/src/lib.rs
- crates/dataflow-jit/src/thin_str/mod.rs
- crates/dbsp/src/operator/group/lag.rs
- crates/pipeline_manager/src/db/mod.rs
Allows creating uninitialized values with the `Uninit` expression, fixes #117
Creating an uninit row value (equivalent to `UninitRow`, should be used in place of it since `UninitRow` is now deprecated)
```json
{
"Uninit": {
"Row": 1,
}
}
```
Creating an uninit scalar value
```json
{
"Uninit": {
"Scalar": "I32",
}
}
```
> [JIT] Allow creating uninit values

- crates/dataflow-jit/src/codegen/call.rs
- crates/dataflow-jit/src/codegen/intrinsics.rs
- crates/dataflow-jit/src/codegen/mod.rs
- crates/dataflow-jit/src/dataflow/tests.rs
- crates/dataflow-jit/src/facade.rs
- crates/dataflow-jit/src/ir/graph.rs
- crates/dataflow-jit/src/ir/literal.rs
- crates/dataflow-jit/src/ir/nodes/constant.rs
- crates/dataflow-jit/src/ir/nodes/io.rs
- crates/dataflow-jit/src/ir/nodes/mod.rs
- crates/dataflow-jit/src/ir/optimize/dedup.rs
- crates/dataflow-jit/src/ir/optimize/distinct.rs
- crates/dataflow-jit/src/ir/optimize/shake.rs
- crates/dataflow-jit/src/sql_graph.rs
- Bedrock for string parsing
- Fixed dead sources/sinks panicking (fixes #128)
- Added `.consolidate()`/`.to_consolidated()` methods to `StreamCollection` (addresses #125, if comparing two possibly non-consolidated `StreamCollections` you can consolidate and compare them)
- Adds an `input_layout: StreamLayout` field to `Sink`s (cc @mihaibudiu for json changes), new json will look like this
```json
"Sink": {
"input": 1,
"input_layout": { "Set": 2 }
}
```
> [JIT] Misc improvements

- sql-to-dbsp-compiler/lib/genlib/rustfmt.toml
This crate is autogenerated and there's no point.
> genlib: Do not format with `cargo fmt`.

- crates/dbsp/src/operator/apply3.rs
- crates/dbsp/src/operator/group/lag.rs
- crates/dbsp/src/operator/mod.rs
- crates/dbsp/src/operator/neighborhood.rs
- crates/dbsp/src/trace/cursor/mod.rs
- crates/dbsp/src/trace/cursor/reverse.rs
- demo/project_demo04-SecOps/run.py
The neighborhood operator helps to visualize the contents of a table.
The UI client may not have enough throughput/memory to store the entire
table, and will instead limit the state it tracks to a small range of rows
that fit on the screen.  We specify such a range, or _neighborhood_, in terms
of its center (or "anchor"), and the number of rows preceding and following
the anchor.  The user may be interested in a static snapshot of the
neighborhood or in a changing view.  Both modes are supported by this
operator.
A complete snapshot of a neighborhood contains a contiguous set of indexes, as
in the following example:
```
│  #  │ key │ val │ w
├─────┼─────┼─────┼───
│ -3  │ "a" │ 100 │ 1
│ -2  │ "a" │ 101 │ 1
│ -1  │ "b" │   5 │ 5
anchor ───► │  0  │ "b" │   7 │ 1
│  1  │ "b" │  10 │ 1
│  2 …
```
> `neighborhood` operator

- crates/dbsp/src/operator/group/test.rs
- crates/dbsp/src/operator/mod.rs
- crates/dbsp/src/operator/neighborhood.rs
- crates/dbsp/src/operator/time_series/rolling_aggregate.rs
- crates/dbsp/src/operator/time_series/window.rs
- crates/dbsp/src/trace/test_batch.rs
- crates/pipeline_manager/src/auth.rs
- crates/pipeline_manager/src/db/test.rs
- crates/webui-tester/src/ui.rs
This fixes Clippy warnings and doc warnings from `tools/pre-push`. The doc fix was manual, the Clippy ones automatic via `clippy --fix`.
> Clippy and doc fixes

- .github/workflows/ci.yml
- Earthfile
- demo/__init__.py
- demo/project_demo04-SecOps/run.py
- deploy/Dockerfile
- deploy/docker-compose.yml
- sql-to-dbsp-compiler/SQL-compiler/pom.xml
* Reuse the dbsp-manager, SQL compiler and demo artifacts to create the images
used by the docker compose test. Doing so duplicates some stages in the
Dockerfile, but allows us to reuse work across the build to keep CI turnarounds
shorter.
* Use shorter SecOps demo runs in the CI.
* some tweaks to reduce Docker image sizes.
> CI speedups

- crates/dbsp/src/error.rs
This makes it possible to use `DBSPError` with `anyhow`, so that you can write things like
```
use anyhow::Result;
use dbsp::RootCircuit;
fn main() -> Result<()> {
let (_circuit, ()) = RootCircuit::build(|_| Ok(()))?;
Ok(())
}
```
using `?` and without having to use `unwrap()` or explicit error handling.
> Make `DBSPError` implement `std::error::Error`.

- Earthfile
- sql-to-dbsp-compiler/SQL-compiler/pom.xml
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/config.fmpp
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
We currently use calcite-server's DDL parser, but would like to extend this with functionality from calcite-babel.  The only way to compose parsers like this is to create a custom parser by using FMPP/FTL files to customize Calcite's parser template.
This patch adds a custom parser that replaces the currently used DdlParser, and sets it up for further babel extensions.
At build time, we extract Parser.jj from the calcite jar, combine it with our FMPP/FTL files, and run java-cc on the result to codegen our custom parser.
> sql: use a custom parser for the SQL compiler

- .github/workflows/containers.yml
- deploy/Dockerfile
- deploy/docker-compose.yml
- deploy/kind/dbsp-deploy.yml
- deploy/kind/setup.sh
* Use docker compose's generated names to avoid container name conflicts.
* Sync the Kubernetes specs to recent Docker container changes
* Publish containers on a nightly cadence. These containers will be untagged, and we will only keep the 5 most recent versions (we use a `delete-package-version` GH action for it). Anyone interested in using these containers can them via <container-name>:latest. 
* Release versions of the containers are published using Github releases. These containers will be tagged with the release version, and will not be reaped by the `delete-package-version` action.
> Docker compose and Kubernetes spec tweaks

- .dockerignore
- demo/project_demo04-SecOps/run.py
- deploy/Dockerfile
Avoids using cargo run to run the SecOps simualator. Instead, we use a multi-stage Docker build to build the simulator binary, and have the SecOps demo's run.py use that if it cannot find cargo.  Doing so allows us to remove the rust toolchain from the demo-container image. It also speeds up the docker-compose workflow where the demo container is used.
In addition, we use a single RUN command to reduce the number of Docker layers in the demo-container image, where we also remove build-related dependencies after they're used (unzip, pkg-config, python3-pip).
The effect of these changes is that the demo container drops in size from ~1.8 GB to ~277MB.
> docker: streamline demo-container image

- Cargo.lock
- crates/pipeline_manager/src/db/ddl.sql
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/storage.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/runner.rs
Even though attached_connector simply combines pipelines and connectors, and augments the result with additional config information, it's worth tagging it also with the tenant_id because some APIs do query attached_connector directly.
Not doing so requires us to take fragile precautions when invoking APIs like attached_connector_is_input(), where we have to be sure the caller has the right permissions via other calls.
> pipeline-manager: reintroduce tenant_id to attached_connector

- Cargo.lock
- Cargo.toml
- Earthfile
Because it breaks `cargo build` in the base dir for non-CI builds.
> Revert change that added `temp` to workspace.

- crates/dbsp/examples/tutorial/tutorial4.rs
- crates/dbsp/examples/tutorial/tutorial5.rs
- crates/dbsp/examples/tutorial/tutorial6.rs
- crates/dbsp/examples/tutorial/tutorial7.rs
- crates/dbsp/examples/tutorial/tutorial8.rs
- crates/dbsp/examples/tutorial/tutorial9.rs
- crates/dbsp/src/operator/aggregate/average.rs
- crates/dbsp/src/operator/aggregate/mod.rs
- crates/dbsp/src/operator/count.rs
- crates/dbsp/src/tutorial.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/DBSPAggregate.java
Aggregation functions almost never care about the key. So I added a aggregate_simple_linear method which takes a function that ignores the key and just calls aggregate_linear. 
In fact, I am wondering whether the aggregation function can ever depend on the key while still being linear.
> Introduce aggregate_simple_linear function

- deploy/kind/dbsp-deploy.yml
- deploy/kind/setup.sh
* Removes local registry, which we no longer need due to GHCR
* Add ingress.class annotation to DBSP Ingress object. Without this annotation, the AWS nginx controller will ignore the entry.
> kubernetes: update DBSP Kind deployment setup

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/controller/error.rs
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/lib.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/transport/http/input.rs
- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/circuit/runtime.rs
- crates/dbsp/src/circuit/schedule/mod.rs
- crates/dbsp/src/error.rs
- crates/dbsp/src/lib.rs
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/auth.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/storage.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/main.rs
- crates/pipeline_manager/src/runner.rs
- python/dbsp-api-client/dbsp_api_client/api/connector/delete_connector.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/http_input.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_action.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_delete.py
- python/dbsp-api-client/dbsp_api_client/api/program/delete_program.py
- python/dbsp-api-client/dbsp_api_client/models/__init__.py
- python/dbsp-api-client/dbsp_api_client/models/error_response.py
- python/dbsp-api-client/dbsp_api_client/models/error_response_details.py
- sql-to-dbsp-compiler/lib/sqllib/src/casts.rs
Motivation
==========
- Errors must be logged in a uniform way, wherever they originate: the manager, the runner, or DBSP.
- Errors must contain metadata beyond the human-readable error message, which can be used for automated error handling, localization, etc.
Design
======
We introduce `trait DetailedError` for all our errors.  The trait defines the `error_code()` method, which must return a unique string that identifies the error, e.g., "InvalidUuidParam".  In addition the trait requires error types to implement `serde::Serialize`, which is used to generate error metadata (see below).  While we still widely use `anyhow::Error` for error reporting, we make sure that underneath all our errors are of one of the following types, which implement `trait DetailedError`.
- `ControllerError`
- …
> Error handling revamp, part 1.

- Cargo.lock
- crates/dataflow-jit/Cargo.toml
- crates/dataflow-jit/src/codegen/intrinsics.rs
- crates/dataflow-jit/src/codegen/mod.rs
- crates/dataflow-jit/src/facade.rs
- crates/dataflow-jit/src/ir/exprs/constant.rs
- crates/dataflow-jit/src/row.rs
- crates/dataflow-jit/src/tests/issue_146.rs
- crates/dataflow-jit/src/tests/issue_288.rs
- crates/dataflow-jit/src/tests/mod.rs
Addresses #288, dates and timestamps can be used in json.
@mihaibudiu The json should look like this, you can also use `Date` and `Timestamp` values within `ConstantStream`, `RowLiteral`, etc.
```json
{
"Constant": {
"Date": "2001-07-08"
}
}
```
```json
{
"Constant": {
"Timestamp": "2001-07-08T00:34:59.026+09:30"
}
}
```
> [JIT] Date and Timestamp constants

- crates/pipeline_manager/src/auth.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/pg_setup.rs
- crates/pipeline_manager/src/db/storage.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/main.rs
- crates/pipeline_manager/src/runner.rs
Replace all uses of `anyhow::Error` in `pipeline_manager::db` with strongly typed errors.
> Refactor `db` module to use strongly typed errors.

- crates/dataflow-jit/src/ir/exprs/mem.rs
- crates/dataflow-jit/src/ir/row_or_scalar.rs
Fixes the following errors in `cargo doc`
```
Documenting dataflow-jit v0.1.0 (/workspaces/dbsp/crates/dataflow-jit)
warning: incompatible link kind for `Copy`
--> crates/dataflow-jit/src/ir/exprs/mem.rs:179:7
|
179 | /// [`struct@Copy`] on the loaded value and then [`Store`]-ing the copied value
|       ^^^^^^^^^^^ this link resolved to a trait, which is not a struct
|
= note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
help: to link to the trait, prefix with `trait@`
|
179 | /// [`trait@opy`] on the loaded value and then [`Store`]-ing the copied value
|       ~~~~~~
warning: unresolved link to `IsNull`
--> crates/dataflow-jit/src/ir/exprs/mem.rs:180:42
|
180 | /// to `dest` (along with any required [`IsNull`]/[`SetNull`] juggling that has
| …
```
> Fix doc for dataflow-jit

- crates/adapters/src/catalog.rs
- crates/adapters/src/server/mod.rs
- crates/dbsp/src/operator/neighborhood.rs
- crates/pipeline_manager/src/main.rs
- python/dbsp-api-client/dbsp_api_client/api/pipeline/http_output.py
- python/dbsp-api-client/dbsp_api_client/models/neighborhood_query.py
The `anchor` value of `None` behaves equivalent to specifying the smallest value of the corresponding type.
> Make `NeighborhoodDescr::anchor` field optional.

- .github/workflows/ci.yml
- .vscode/settings.json
- Cargo.lock
- Earthfile
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/auth.rs
- crates/pipeline_manager/src/config.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/integration_test.rs
- crates/pipeline_manager/src/main.rs
- deploy/Dockerfile
- deploy/docker-compose.yml
- deploy/kind/dbsp-deploy.yml
This PR makes it easier to use auth features from the Docker compose workflow. It also updates the integration tests to use them if configured (via environment variables). The Earthly +integration-tests phase now always uses auth with one user from an AWS cognito user pool (I'll later change this to create/remove users on the fly).
Lastly, it splits the actix `App` configuration into two parts, a root scope used for all static content, and an API scope "/v0". The auth middleware only applies to the API scope, which means the static content can be served without any authentication.
> Improve auth workflow

- Earthfile
- demo/__init__.py
- demo/demo_notebooks/fraud_detection.ipynb
- python/dbsp-api-client/dbsp_api_client/api/connector/connector_status.py
- python/dbsp-api-client/dbsp_api_client/api/connector/delete_connector.py
- python/dbsp-api-client/dbsp_api_client/api/connector/list_connectors.py
- python/dbsp-api-client/dbsp_api_client/api/connector/new_connector.py
- python/dbsp-api-client/dbsp_api_client/api/connector/update_connector.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/http_input.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/http_output.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/list_pipelines.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/new_pipeline.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_action.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_committed.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_delete.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_stats.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_status.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_validate.py
- python/dbsp-api-client/dbsp_api_client/api/pipeline/update_pipeline.py
- python/dbsp-api-client/dbsp_api_client/api/program/cancel_program.py
- python/dbsp-api-client/dbsp_api_client/api/program/compile_program.py
- python/dbsp-api-client/dbsp_api_client/api/program/delete_program.py
- python/dbsp-api-client/dbsp_api_client/api/program/list_programs.py
- python/dbsp-api-client/dbsp_api_client/api/program/new_program.py
- python/dbsp-api-client/dbsp_api_client/api/program/program_code.py
- python/dbsp-api-client/dbsp_api_client/api/program/program_status.py
- python/dbsp-api-client/dbsp_api_client/api/program/update_program.py
- python/dbsp-api-client/dbsp_api_client/types.py
- python/dbsp-api-client/pyproject.toml
- python/test.py
The web::scope() change affected the OpenAPI endpoint URLs. It affects the python bindings which are based off of the OpenAPI spec. The fix is to pass `<dbsp_hostname>:<port>/v0` as the URL to the python client when opening a connection.
> PR 328 postfix

- README.md
- demo/project_demo00-SecOps/project.sql
- docs/docs/papers.md
- docs/docs/sql/casts.md
- docs/docs/sql/float.md
- docs/docs/sql/grammar.md
- docs/docs/sql/identifiers.md
- docs/docs/sql/intro.mdx
- docs/docs/sql/string.md
- sql-to-dbsp-compiler/README.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/config.fmpp
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/CalciteCompilerTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/JitTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresStringTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/string.rs
This PR includes documentation about POSIX regular expressions, but currently there is no function implemented that supports them. I was about to implement regexp_replace, when I realized that the Postgres version of this function is completely different than the Calcite version (which implements the MYSQL version).
> Support REPLACE, PRIMARY KEY, FOREIGN KEY in SQL compiler

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Utilities.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/BaseSQLTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java
Fixes #353 
This also gets rid of the annoying surefire plugin warnings during tests:
`Corrupted channel by directly writing to native stream in forked JVM 1.`.
> Capture background process output in files instead of inheriting file descriptors

- crates/dbsp/src/operator/neighborhood.rs
Given a descriptor of the form `{anchor, before, after}`, the `neighborhood` operator used to return up to `before + after` rows, including `before` rows preceding the anchor, the anchor, and `after - 1` rows following the anchor.  If `before` and `after` were both set to `0`, the output neighborhood was empty. I am no longer sure why this seemed like a good idea, but users (@gz) found this confusing.
This commit changes the semantics of `neighborhood` to always return the `anchor` (unless the specified `anchor` exceeds the largest value in the collection), and up to `before` preceding and `after` succeeding rows, up to a total of `before + after + 1` rows.
> More intuitive semantics of `neighborhood`.

- Earthfile
Before https://github.com/feldera/dbsp/pull/358, we had dbsp_pipeline_manager as the package and binary name. So we ran integration tests by invoking a binary named dbsp_pipeline_manager. This behavior changed with https://github.com/feldera/dbsp/pull/358, where we have multiple binaries being generated, and the package itself is now a library. This patch fixes the Earthfile to accommodate this change.
> Pr358 postfix

- crates/pipeline_manager/src/pipeline_manager.rs
Using separate scopes for the APIs vs the static content broke the swagger UI. We fix this by adding a server variable to the openapi spec served by the Swagger UI.
Fixes #376
> pipeline-manager: add server modifier to OpenAPI doc

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/transport/http/output.rs
There is a bug in actix (https://github.com/actix/actix-web/issues/1313) that prevents it from dropping HTTP connections on client disconnect unless the endpoint periodically sends some data.  As a result, all API-based data transfers eventually start to fail in the UI.  As a workaround, we generate an empty output chunk if there is no real payload to send for more than 3 seconds.
> Workaround for actix-web bug.

- Cargo.lock
- Cargo.toml
- crates/dbsp/Cargo.toml
- crates/nexmark/Cargo.toml
- crates/nexmark/src/model.rs
- crates/nexmark/src/queries/q14.rs
- crates/nexmark/src/queries/q16.rs
- crates/nexmark/src/queries/q9.rs
DBSP relies on bincode version 2.0.0-rc3, which was released at the end of March 2023.  DBSP also uses arcstr and we want to serialize and deserialize `ArcStr`s with bincode.  Unfortunately, arcstr doesn't support bincode 2.0 yet and won't until bincode 2.0 finally gets released[1], which could be a long time, so we have a patch in Cargo.toml to support that.
We'd like to publish DBSP to crates.io[2], but we can't if it depends on patches, so it seems best to avoid them.  This commit drops the patch and switches to using #[bincode(with_serde)] to serialize ArcStr fields.
[1]: https://github.com/thomcc/arcstr/pull/45
[2]: https://github.com/feldera/dbsp/issues/14
Fixes: https://github.com/feldera/dbsp/issues/395
> Eliminate dependency on arcstr patch that isn't upstream yet.

- crates/adapters/src/server/mod.rs
- crates/adapters/src/test/http.rs
The HTTP connector can now send chunks without data.  Adjust the test to account for this.
> Fix regression in `adapterss::test_server`.

- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/storage.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/pipeline_manager.rs
The compiler service now attempts to reconcile its local state with the program objects available in the DB. If it sees any evidence of programs without local versioned binaries, but have started or completed compilation, the service re-queues the program for compilation.
The PR also adds some tests for the compiler service to check this behavior.
Addresses the compiler issue in https://github.com/feldera/dbsp/issues/235
> Handle compiler restarts with potential volume refreshes

- .devcontainer/Dockerfile
- .devcontainer/Dockerfile.script
- .devcontainer/setup.sh
Added installation of all dependencies to build and launch sql-compiler, pipeline_manager and web-console(web-ui) within devcontainer out-of-the-box. Container now exposes non-root user by default with the ability to sudo.
Preserved original Dockerfile to ease the transition.
> Add dependencies in devcontainer to build packages

- crates/dataflow-jit/src/dataflow/mod.rs
- crates/dataflow-jit/src/dataflow/nodes.rs
- crates/dataflow-jit/src/ir/graph.rs
- crates/dataflow-jit/src/ir/nodes/mod.rs
- crates/dataflow-jit/src/ir/optimize/dedup.rs
- crates/dataflow-jit/src/ir/validate.rs
- crates/dataflow-jit/src/ir/visit.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ToJitVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/operators/JITStreamDistinctOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/ProgramAndTester.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/BaseSQLTests.java
This PR makes some step towards running the SLT tests on top of the JIT infrastructure.
This compiles the SQL into JIT programs. Still missing is the code to actually compare outputs and feed inputs.
The JIT is missing some *non incremental* operators. We add the StreamDistinct operator.
We will also need non-incremental versions of the Aggregate and Join. (We could implement these by using some I and Ds, though).
> SLT JIT support

- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/test.rs
Failing execution.
```
Diff < left / right > :
<There is no change to commit for pipeline
>Unexpected Postgres error: 'db error: ERROR: duplicate key value violates unique constraint "program_history_pkey"
>DETAIL: Key (id, revision)=(03000000-0000-0000-0000-000000000000, 01000000-0000-0000-0000-000000000000) already exists.'
.
minimal failing input: [
NewProgram(
TenantId(
03000000-0000-0000-0000-000000000000,
),
03000000-0000-0000-0000-000000000000,
"",
"",
"",
),
SetProgramStatusGuarded(
TenantId(
03000000-0000-0000-0000-000000000000,
),
ProgramId(
03000000-0000-0000-0000-000000000000,
),
Version(
1,
),
CompilingSql,
),
NewPipeline(
TenantId(
03000000-0000-0000-0000-000000000000,
),
03000000-0000-0000-0000-000000000000,
Some(
ProgramId(
03000000-0000-0000-0000-000000000000,
),
),
"", …
```
> PR 407 regression

- docs/docs/sql/datetime.md
This seems to be a Calcite limitation.
See https://github.com/feldera/dbsp/issues/443.
> sql: Document that date and time literals don't allow trailing spaces.

- crates/dbsp/src/algebra/mod.rs
External crates must be able to implement `MulByRef` for `Option<T>`, but this wasn't possible because `Option` is part of `std`.  This fixes the problem by adding a generic implementation for `Option<T>` when there is already an implementation for `T`.
Thanks to Chase Wilson for the suggestion.
> dbsp: Add `MulByRef` implementation for generic `Option<T>`.

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/controller/stats.rs
Add `rss_bytes` field to pipeline stats, which reports the amount of RAM used by the pipeline process.
> Report pipeline memory usage via `/stats`.

- crates/dbsp/Cargo.toml
ordered-float v3.9.0 is broken:
https://github.com/reem/rust-ordered-float/issues/137
Until it's fixed or yanked, avoid upgrade.
> dbsp: Prevent ordered-float upgrade beyond v3.8.0.

- crates/dbsp/Cargo.toml
The extremely lovely maintainer already released a fixed version.
> dbsp: Upgrade ordered-float past the broken 3.9.0 release.

- Cargo.lock
- Earthfile
- scripts/bump-versions.sh
Adds a script to bump versions and create release commits. Usage looks like this.
```
./bump-versions.sh major|minor|patch
```
It currently:
* bumps versions for all rust packages in the project workspace
* lines up the SQL compiler's version (in pom.xml) to the updated rust package versions. 
* It then creates a release commit with the tag "v$version" 
* It then bumps the SQL compiler to a SNAPSHOT release for the following patch version, and creates a "start post-v$version release cycle" commit.
The `clap` library we use for the rust binaries CLI already intrinsically adds a "-V" argument to display the package versions for the binaries.
This fixes #529 except for separating release from main documentation. We'll need the docusaurus experts to help sort that out.
You can see example …
> Release management (fixes #529)

- Earthfile
- deploy/docker-compose.yml
This reverts the earlier fix for https://github.com/feldera/feldera/issues/496, and instead, uses the Redpanda sizing guidelines of setting at least 2GB per core via the --memory argument. It was previously at 1GB per core. I can confirm using `docker stats` that the redpanda container does not use more than 2GB during the SecOps demo.
> docker: set redpanda memory using --memory instead of docker limits

- Cargo.lock
- Cargo.toml
This avoids the following warning given by Rust 1.72:
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
> cargo: Set resolver version 2.

- crates/adapters/src/transport/kafka/input.rs
- demo/project_demo00-SecOps/run.py
- demo/project_demo00-SecOps/simulator/Cargo.toml
- demo/project_demo00-SecOps/simulator/src/main.rs
The SecOps generator used to run continuously whether the demo was running or not.  This created a small but non-trivial I/O and CPU load on the system.
The fix is to only run the generator when the pipeline is running and is close to exhausting all previously generated messages.  We achieve this but monitoring the consumer group offset.  When the offset is more than 1000 messages behind the producer, the generator stops.
This requires the producer to know consumer group id, so we use a fixed group id for one of the topics in the demo.
> Pause SecOps generator when demo is not running.

- crates/pipeline_manager/src/api.rs
- deploy/docker-compose.yml
This reduces the noise from actix-web's logs by default in the container deployment. To give users feedback, it adds info! logging for all API operations with side effects.
One gap though is that there is still no log feedback that a program is being compiled.
> pipeline-manager: log mutating operations and reduce actix-web log noise

- crates/pipeline_manager/src/compiler.rs
When the compiler restarts with a fresh filesystem state, it needs to invalidate existing binary references to its filesystem. Otherwise, what happens is that when the compiler resets the program status and triggers a recompile, it will fail to insert the new reference into the database.
This is relevant in the context of upgrading pipeline-manager container images.
> pipeline-manager: fix compiler reconciliation on filesystem reset

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/server/error.rs
- crates/dbsp/Cargo.toml
- crates/dbsp/src/algebra/present.rs
- crates/dbsp/src/error.rs
- crates/dbsp/src/tutorial.rs
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/db/error.rs
- crates/pipeline_manager/src/error.rs
Some of the things we report as HTTP errors are benign events that are part of the normal operation.  One example is retrieving a program by name to check if it exists.  Another one is probing pipeline status to determine whether it's finished initializing.
Logging such errors at the ERROR log level is confusing to the user. This commit makes error log level configurable by extending the `DetaileError` trait, which all our errors implment, with the `log_level()` method.  It return `Level::Error`, by default, but can be customized.  For now I reduced the log level of some obvious candidates to Info.  Going forward, we now have a way to fine tune this behavior.
> Reduce log level for some errors.

- Cargo.lock
- crates/adapters/src/server/mod.rs
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/bin/compiler-server.rs
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/config.rs
- crates/pipeline_manager/src/integration_test.rs
- crates/pipeline_manager/src/local_runner.rs
- crates/pipeline_manager/src/runner.rs
- deploy/Dockerfile
This PR allows the api-server, compiler-server and local-runner to run as separate processes without any local filesystem to coordinate over. It adds a web endpoint to the compiler service to serve binaries, which the local runners now make use of. This is done by using the binary-ref table, where location URLs can now also be http/https links pointing to the compiler service's endpoint.
I have not removed fileref support for backward compatibility (we can keep it around for a while).
> Remove localhost assumptions in the code

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/transport/kafka/input.rs
- crates/dataflow-jit/src/codegen/vtable/tests.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/test.rs
- Enable SSL and SASL authentication in `rdkafka`. Without these, config options related to authentication don't work.
- Workaround for `librdkafka` bug.  Let's see if this resolves failures in Kafka tests in CI.
> Redpanda stability

- crates/adapters/src/server/mod.rs
- crates/adapters/src/transport/http/input.rs
- crates/pipeline_manager/src/api.rs
- crates/pipeline_manager/src/local_runner.rs
- python/feldera-api-client/feldera_api_client/api/pipelines/http_input.py
Add `?force` flag to the `/ingress` endpoint, which forces the endpoint to push data to the pipeline even if it is in the paused state.  This is useful for debugging, including WebConsole-based debugging, where we want to pause the pipeline and play with some test inputs.
@Karakatiza666, this should address #612 , just make sure to pass `?flag=true` to all `/ingress` calls from the UI.
> Ingest data via HTTP in paused state.

- Cargo.lock
- crates/dbsp/Cargo.toml
This release mainly includes some additional documentation.  It is a major version bump because it removes `merging` from the public interface for `dbsp::trace::Spine`.
> dbsp: Release `dbsp` 0.2.0.

- .github/workflows/ci.yml
This will print some statistics for individual task build times so we can find & optimize the worst offenders.
> Enable verbose for earthly.

- crates/dataflow-jit/src/codegen/intrinsics.rs
- crates/dataflow-jit/src/codegen/json.rs
JSON doesn't have a way to express NaN or Inf floating point values, so we have to handle them specifically to convert them to and from strings
> JIT JSON (de)serialization now works for NaN/Inf values

- crates/pipeline_manager/src/config.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db_notifier.rs
- crates/pipeline_manager/src/integration_test.rs
- crates/pipeline_manager/src/lib.rs
- crates/pipeline_manager/src/local_runner.rs
- crates/pipeline_manager/src/pipeline_automata.rs
- deploy/Dockerfile
* Splits out the pipeline-automaton out of the local runner code so that it can be reused.
* Exposes some existing types and adds a new async-trait to write different runners.
* Makes the local runner no longer prepare and use metadata.json when bringing up pipelines, as it is unused on the pipeline side.
* Fixes some unrelated regressions.
> Add more public types to pipeline-manager to make it usable as a library

- crates/pipeline_manager/src/db/mod.rs
Otherwise, this leads to errors like this in the log:
```
2023-09-15 19:07:23 INFO [manager] 2023-09-15 12:07:23.668 PDT [1224747] ERROR:  prepared statement "s19" does not exist
```
> Use the same connection for query and prepare in Postgres.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/UnimplementedException.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteObject.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java
Still not perfect, but hopefully an improvement.
Previous error message:
```
error: Not yet implemented: OVER currently does not support sorting on nullable column  CalciteObject:rel#74:LogicalWindow.(input=LogicalProject#72,window#0=window(partition {0} order by [1] range between $3 PRECEDING and CURRENT ROW aggs [COUNT($2), $SUM0($2)]))
```
New error message:
```
error: Not yet implemented: OVER currently does not support sorting on nullable column 'FULFILLMENT_DATE': SELECT `PART_ORDER`.`CUSTOMER`, `FULFILLMENT`.`FULFILLMENT_DATE`, DATEDIFF(DAY, `PART_ORDER`.`TARGET_DATE`, `FULFILLMENT`.`FULFILLMENT_DATE`) AS `$2`, 90 * INTERVAL '1' DAY AS `$3`, COUNT(DATEDIFF(DAY, `PART_ORDER`.`TARGET_DATE`, `FULFILLMENT`.`FULFILLMENT_DATE`)) OVER (PARTITION BY `PART_ORDER`.`CUSTOMER` ORDER BY …
```
> SQL: print SQL in error messages, not internal compiler data structures

- crates/dataflow-jit/src/codegen/json/mod.rs
- crates/dataflow-jit/src/codegen/json/serialize.rs
- crates/dataflow-jit/src/codegen/json/tests.rs
- crates/dataflow-jit/src/facade/mod.rs
These changes help with the JIT integration with `adapters`:
- rename `SerializeJsonFn` -> `SerializeFn` - I expect all serialization functions to have the same signature
- `DbspCircuit::json_ser_function()` method to retrieve a pointer to JSON serialization function by layout id.
- Made the `DbspCircuit::outputs` field `pub`.
> Minor changes to `dataflow-jit`.

- crates/adapters/src/server/mod.rs
By default actix starts the number of threads equal to the number of cores, which is an overkill and can lead to file descriptor exhaustion when running multiple pipelines on systems with >100 cores.  We use a fixed number of threads instead.  Four should be more than enough, but we can make it configurable if needed.
> adapters: Fix the number of actix threads.

- Earthfile
- crates/adapters/src/format/json/input.rs
- crates/adapters/src/format/json/mod.rs
- demo/__init__.py
- demo/demo.sh
- demo/project_demo05-DebeziumMySQL/project.sql
- demo/project_demo05-DebeziumMySQL/run.py
- deploy/docker-compose-debezium.yml
- deploy/docker-compose.yml
This commit adds a new demo program that ingests data into Feldera
from a MySQL database using Debezium.
We configure the following services:
- Redpanda
- Kafka Connect with Debezium connector using the RedPanda service as
its internal state store.
- MySQL container with a simple database from the Debezium MySQL tutorial
and create a Debezium connector that streams updates to the database to
RedPanda topics (one topic per table).  All of this setup is done outside
of Feldera.  Inside Feldera, we create a SQL program that mirrors the MySQL
program and build a pipeline with one Kafka connector per topic.
Connectors are configured to parse the Debezium JSON format (I
implemented support for it earlier and only had to fix it up slightly).
With this setup we are able to ingest the contents of …
> Debezium MySQL demo

- crates/adapters/src/format/csv.rs
- crates/pipeline_manager/src/integration_test.rs
The CSV parser library is supposed to recognize `\r`, `\n`, and `\r\n` as line terminators, but it does it in a strange way with the `\r\n` being split in the middle.  This caused the parser to recognize the final `\n` in a block of CSV records as an invalid record.
> Regression in CSV parser

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/static_compile/deserialize_with_context.rs
- demo/project_demo05-DebeziumMySQL/run.py
- docs/api/json.md
Debezium uses a very unfortunate default representation of decimal numbers that only encodes the digits, leaving it up to the consumer to infer the position of the decimal dot.  This cannot be done in a robust and efficient way.  The most obvious approach is to infer the scale of the number from the SQL table definitions that we have, but these definitions are not guaranteed to precisely match the source DB, esp when it comes to decimal precision.  An alternative is to infer it from the table schema that Debezium attaches to each record by default.  But including the schema in each message is exceedingly expensive, so we should allow (and recommend) the users to disable it, so that's also not a good solution.
When the schema registry is available, a reference to the schema registry can be …
> Adjustments for Debezium decimal parsing.

- CHANGELOG.md
- crates/pipeline_manager/src/api.rs
- demo/demo-container.sh
- demo/project_demo00-SecOps/run.py
- demo/project_demo06-SupplyChainTutorial/project.sql
- demo/project_demo06-SupplyChainTutorial/run.py
- deploy/docker-compose.yml
- docs/tutorials/basics/part1.md
- docs/tutorials/basics/part3.md
- python/dbsp/__init__.py
- python/dbsp/connector.py
- python/dbsp/pipeline.py
- python/feldera-api-client/feldera_api_client/models/__init__.py
- python/feldera-api-client/feldera_api_client/models/url_input_config.py
I created a new demo based on the "Feldera: The Basics" tutorial.  The idea is that people who are too lazy to go through all the steps in the tutorial can just play with the resulting pipeline.
- Added missing Python API to create URL input connectors.
- Added `project_demo06-SupplyChainTutorial` demo, which creates and configures the pipeline described in the tutorial using API with one difference:  it doesn't set Kafka broker address in the connectors, so that the pipeline picks them up from the `REDPANDA_BROKERS` env variable. This way the demo works both in docker and locally.
- Modified `docker-compose.yml` to create the new demo, along with the SecOps demo in the demo profile.
- In the process, added a dependency on the redpanda container to the demo, so it doesn't start until …
> Add tutorial as the second demo.

- deploy/docker-compose-debezium.yml
Update version of the Debezium demo container to 0.1.6 (was 0.1.3 before).
> Debezium demo container version to 0.1.6

- crates/adapters/src/catalog.rs
- crates/adapters/src/jit/deinput.rs
- crates/adapters/src/jit/json.rs
- crates/adapters/src/jit/mod.rs
- crates/adapters/tests/jit_integration_test.rs
- crates/adapters/tests/sql_tests/.gitignore
- crates/adapters/tests/sql_tests/datetime/config.yaml
- crates/adapters/tests/sql_tests/datetime/project.sql
- crates/dataflow-jit/src/codegen/intrinsics/deserialize.rs
- crates/dataflow-jit/src/codegen/intrinsics/mod.rs
- crates/dataflow-jit/src/codegen/json/deserialize.rs
- crates/dataflow-jit/src/codegen/json/mod.rs
- crates/dataflow-jit/src/codegen/json/tests.rs
- crates/dataflow-jit/src/codegen/layout.rs
- crates/dataflow-jit/src/codegen/mod.rs
- crates/dataflow-jit/src/codegen/vtable/tests.rs
- python/feldera-api-client/feldera_api_client/models/json_flavor.py
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/JitJsonOutputDescription.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/jit/ir/types/JITScalarType.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java
Added the ability to parse dates/times from more formats, fixes #773
Changes config format, columns should look like this now:
```json
{
"key": "/bar",
"spec": null,
}
{
"key": "/bar",
"spec": {
"DateTimeFromStr": {
"format": "%F"
}
}
}
{
"key": "/bar",
"spec": "TimeFromMicros",
}
{
"key": "/bar",
"spec": "TimeFromMillis",
}
{
"key": "/bar",
"spec": "DateFromDays",
}
```
> Implemented alternative date/time parsing options for json

- crates/pipeline_manager/build.rs
- web-console/.gitignore
- web-console/next.config.js
fixes this stuff  (I think)
```
➜  kubernetes-runner git:(issue-31) ✗ cargo test -- --nocapture
Compiling pipeline-manager v0.1.6 (/Users/lalith/code/cloud/feldera/crates/pipeline_manager)
error: couldn't read /Users/lalith/code/cloud/feldera/web-console/out/_next/static/chunks/webpack-849dc3b25543c6b2.js: No such file or directory (os error 2)
--> /Users/lalith/code/cloud/kubernetes-runner/target/debug/build/pipeline-manager-2da2ebda90645148/out/generate_sets/set_1.rs:62:62
|
62 | ...bpack-849dc3b25543c6b2.js",n(i!("/Users/lalith/code/cloud/feldera/web-console/out/_next/static/chunks/webpack-849dc3b25543c6b2.js"),1695937463,"application/javas...
|                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
> Fix the web-console asset errors during rust build.

- CHANGELOG.md
- web-console/src/lib/components/connectors/dialogs/DebeziumInputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/KafkaInputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/kafka/TabKafkaAuth.tsx
Forbid empty group.id in Kafka form: Fix https://github.com/feldera/feldera/issues/840
Enable multiline input for .pem SSL certificates: Fix https://github.com/feldera/feldera/issues/841
> Forbid empty group.id in Kafka form

- .github/workflows/containers.yml
- Earthfile
- deploy/Dockerfile
- deploy/docker-compose-debezium.yml
In preparation for adding support for the Snowflake output connector, we replace the pre-built Kafka Connect image from Debezium with a custom one that adds Snowflake connector classes to the image.  There are a couple of Kafka Connect base images we could build upon, including one from Confluent, but that one seems to assume Apache Kafka and may not work well with Redpanda (first thing it did when I tried it is complain about not having Zookeeper around :) ).
In addition, we want the image to contain Debezium connectors, so building on the Debezium image from RedHat seemed like a good choice.
This commit:
1. Adds a Kafka Connect container build step to Earthfile
2. Adds identical instructions for building the connector to Dockerfile
3. Sets up github CI to build the container along with …
> Custom Kafka Connect docker image.

- CHANGELOG.md
- crates/pipeline_manager/src/api.rs
- crates/pipeline_manager/src/bin/api-server.rs
- crates/pipeline_manager/src/bin/compiler-server.rs
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/storage.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/lib.rs
- crates/pipeline_manager/src/probe.rs
- crates/pipeline_manager/src/retries.rs
- deploy/Dockerfile
- deploy/docker-compose.yml
* Adds endpoints that can be invoked by external tools for health checks. For the pipeline-manager services, this primarily means checking for DB connectivity. We can extend this over time with more detailed info.
* This patch also makes these services attempt connecting to the DB several times on startup instead of failing immediately and going into crash-restart loops.
> pipeline-manager: add health checks for DB connectivity

- CHANGELOG.md
- docs/cloud.md
- docs/sidebars.js
This is still WIP. I need to also add documentation on how to obtain the container images and Helm packages.
This is also missing info about setting up connectors which will follow soon.
> docs: add Feldera Cloud deployment documentation

- CHANGELOG.md
- crates/pipeline_manager/src/auth.rs
- crates/pipeline_manager/src/bin/api-server.rs
- crates/pipeline_manager/src/bin/compiler-server.rs
- crates/pipeline_manager/src/bin/migrations.rs
- crates/pipeline_manager/src/bin/pipeline-manager.rs
- crates/pipeline_manager/src/db/error.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/test.rs
- deploy/Dockerfile
We currently perform database migrations while initializing connections. This is fraught with risks in a production setting (e.g., makes rollbacks difficult).
This PR separates out running migrations from the connection initialization code. The pipeline-manager all-in-one binary should appear no different than before. The individual service binaries however no longer run migrations on their own. They are complemented with a new binary that does nothing but connect to the DB and runs the migration.
> Decouple DB migrations from connection setup

- CHANGELOG.md
- crates/pipeline_manager/src/bin/migrations.rs
- crates/pipeline_manager/src/pipeline_automata.rs
- crates/pipeline_manager/src/runner.rs
Several state transitions in the pipeline automata shutdown the pipeline the moment it encounters a failure. This behavior is undesirable in production settings where pipelines can fail for myriad reasons, and it's good to have them stick around to be diagnosed.
Pipelines can anyhow only be restarted via the /start action after an explicit shutdown by the user.
> Avoid force-shutdowns for pipelines that encounter errors during lifecycle state changes

- crates/pipeline_manager/build.rs
Typo in build.rs caused excessive pipeline manager re-compilation.
> Typo in build.rs

- CHANGELOG.md
- web-console/package.json
- web-console/src/lib/components/analytics/TableSqlPrograms.tsx
- web-console/src/lib/components/common/table/DataGridProDeclarative.tsx
- web-console/src/lib/components/common/table/EntityTable.tsx
- web-console/src/lib/components/common/table/ResetColumnViewButton.tsx
- web-console/src/lib/components/connectors/DataSourceTable.tsx
- web-console/src/lib/components/layouts/AuthProvider.tsx
- web-console/src/lib/components/streaming/import/ImportToolbar.tsx
- web-console/src/lib/components/streaming/import/InsertionTable.tsx
- web-console/src/lib/components/streaming/inspection/InspectionTable.tsx
- web-console/src/lib/components/streaming/inspection/InspectionToolbar.tsx
- web-console/src/lib/components/streaming/management/PipelineTable.tsx
- web-console/src/lib/compositions/persistence/dataGrid.ts
- web-console/src/lib/functions/common/array.ts
- web-console/src/lib/functions/common/object.ts
- web-console/yarn.lock
Also created a wrapper over MUI DataGridPro to enable more declarative API.
Fix https://github.com/feldera/feldera/issues/696
> Persist data grid column configuration on page refresh

- .gitignore
- CHANGELOG.md
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/integration_test.rs
Use the `--outputsAreSets` compiler flag to enforce that pipelines produce distinct outputs.  See https://github.com/feldera/feldera/issues/871 for a detailed discussion.
Also use the `--ignoreOrder` compiler flag to ignore the `order by` clause in SQL.
Added an integration test for the distinct output behavior.  And while I was at it, documented steps for running integration tests, which I always forget.
> Use `outputsAreSets` flag.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JitDbspExecutor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JitTestBatch.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/TestBatch.java
Some SLT tests create intermediate views. With this change we handle them correctly.
> Handle correctly intemediate views in SLT tests

- .gitignore
- crates/adapters/src/format/json/output.rs
- crates/adapters/tests/jit_integration_test.rs
We used to not place a newline in the end of a batch of ND-JSON records. The issue with this is that when multiple such batches are stored in a file, sent over HTTP or some other transport that doesn't have well-defined message boundaries, there is no newline between two batches, making it invalid ND-JSON.
> Add newline in the end of an NDJSON block.

- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/operator/trace.rs
- crates/dbsp/src/operator/upsert.rs
Strict operators (i.e., operators on the backedge of a feedback loop) have a feature that allows the parent circuit to consume the last output of the operator after its clock epoch ends.  This is useful to make the result of a fixed point computation availabel to the parent.  This behavior used to be mandatory for all strict operators.  For the `Z1Trace` operator, when configured to integrate inputs across multiple clock epochs this meant that it had to manufacture a bogus empty trace just to keep the API happy.  It turns out that empty traces are expensive when using RocksDB for persistence.
The fix is to make the export feature optional and not create an export stream for operators like `Z1Trace`, since these are not used anyway.
> Don't export the output of Z1Trace.

- crates/dbsp/src/operator/communication/gather.rs
- crates/dbsp/src/operator/communication/shard.rs
This fix makes sure we use spine_fueled::Spine in
the communication module where we dont need persistent traces. Otherwise we would find ourselves creating (and dropping) new rocksdb column families quite a bit during regular operation (which doesn't scale and is very slow)
See also:
https://github.com/facebook/rocksdb/blob/543191f2eacadf14e3aa6ff9a08f85a8ad82da95/include/rocksdb/db.h#L365
With this commit no new PersistentTraces are created after startup which leads to much better performance with multiple cores:
nexmark q16 with 1 / 8 cores before:
~17s / ~4635s
nexmark q16 with 1 / 8 cores now:
~13s / ~39s
> Avoid using persistent Spines for thread communication.

- crates/adapters/tests/jit_integration_test.rs
This `supply_chain_test` integration test assumed fixed order of output rows, which is not guaranteed with multiple worker threads.  This caused non-deterministic test failures in CI.
> Fix `supply_chain_test`.

- CHANGELOG.md
- docs/sidebars.js
- docs/sql/binary.md
- docs/sql/string.md
- docs/sql/types.md
- scripts/pre-push
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TypeCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPBinaryLiteral.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPZSetLiteral.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeCode.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBinary.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/NaiveIncrementalTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitPostgresStringTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/jit/JitTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresBaseTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresStringTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/binary.rs
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
> Preliminary support for BINARY SQL data type

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/test/kafka.rs
- crates/adapters/src/test/mod.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/kafka/test.rs
- crates/adapters/src/transport/url.rs
- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/operator/communication/exchange.rs
- crates/dbsp/src/operator/communication/shard.rs
- crates/dbsp/src/operator/input.rs
- crates/dbsp/src/operator/time_series/mod.rs
- crates/dbsp/src/operator/time_series/rolling_aggregate.rs
- crates/dbsp/src/operator/time_series/waterline.rs
- crates/dbsp/src/operator/time_series/watermark.rs
- crates/dbsp/src/operator/time_series/window.rs
- crates/dbsp/src/operator/trace.rs
- crates/dbsp/src/operator/upsert.rs
- crates/nexmark/src/queries/q5.rs
- crates/nexmark/src/queries/q7.rs
- crates/nexmark/src/queries/q8.rs
Part of work on #873.
This PR implements an API to specify data retainment policies for keys and/or values in a trace.
Background
==========
Relations that store time series data typically have the property that any new updates can only affect records with recent timestamps.  Depending on how the relation is used in queries this might mean that, while records with older timestamps still exist in the relation, they cannot affect any future incremental computation and therefore don't need to be stored.
Design
======
We support two mechanisms to specify and eventually discard such unused records.
The first (already existing) mechanism, exposed via the `Stream::integrate_trace_with_bound` method, is only applicable when keys and/or values in the collection are ordered by time.  It allows …
> Apply retainment policies to traces

- crates/dbsp/benches/ldbc-graphalytics/pagerank.rs
PR941 broke a benchmark, which doesn't run in CI.
> Postfix for PR941.

- Cargo.lock
- Earthfile
- crates/adapters/Cargo.toml
- crates/adapters/src/lib.rs
- crates/dbsp/Cargo.toml
Only pull in JIT dependencies when building the standalone executable.
This should reduce compilation times for statically compiled pipelines.
> Feature-gate JIT compiler.

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/test/kafka.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/url.rs
Add `.unwrap()`'s to `adapters` tests to make sure the tests fail on timeout.
> Fail on timeout in tests.

- crates/dbsp/src/operator/group/custom_ord.rs
- crates/dbsp/src/operator/group/mod.rs
- crates/dbsp/src/operator/group/test.rs
- crates/dbsp/src/operator/group/topk.rs
- crates/dbsp/src/operator/mod.rs
Existing implementations of top-k use natural ordering of values in a group, which may require rearranging the data so that the natural ordering matches the ORDER BY clause in the SQL query, and even that isn't sufficient when sorting by multiple columns, e.g., `ORDER BY COL1 ASCENDING, COL2 DESCENDING`.
We add a new top-K operator parameterized with a user-defined comparison function.  Internally, the operator wraps values in the input stream in a wrapper type that implements `trait Ord` by invoking the user-defined comparison function, invokes `topk_asc` on the resulting transformed batches and removes the wrapper from values in the resulting output batches.
> Top-K operator with custom comparison function.

- CHANGELOG.md
- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/transport/kafka/input.rs
- crates/adapters/src/transport/kafka/output.rs
- crates/adapters/src/transport/mod.rs
- crates/adapters/src/transport/secret_resolver.rs
- crates/pipeline-types/src/lib.rs
- crates/pipeline-types/src/secret_ref.rs
**Overview:**
* Secret reference: add enumeration type `SimpleStringOrSecretReference` with constructor that takes in a string. If the string follows the `${secret:example}` pattern, it returns a secret reference to `example`. Else, it returns a simple
string with the direct content. Its pattern is similar to that of [Kafka Connect / Debezium](https://debezium.io/blog/2019/12/13/externalized-secrets/).
* Secret resolver: converts a secret reference to the secret string it refers to.
- Resolution options: currently, only secret references named "^[a-z0-9]+(-[a-z0-9]+)*$" are allowed, and are resolved by checking if a file "/etc/secret-volume/.example" exists (e.g., for the secret named `example`). This file needs to be made available by mounting the secret volume in advance.
- Resolution …
> Connector secrets

- CHANGELOG.md
- web-console/src/lib/components/streaming/management/PipelineTable.tsx
Removes any rounding of the number of records, instead directly printing the number (see also [#926](https://github.com/feldera/feldera/issues/926)).
> web-console: number of records in pipeline table is no longer rounded

- crates/dbsp/src/operator/group/test.rs
- crates/dbsp/src/operator/group/topk.rs
- When computing the SQL `rank` function, a row with weight `N` occupies `N` slots in the ranking. The previous implementation counted it as a single slot.
- The SQL `row_number` function should map a row with weight `N` into `N` rows with consecutive numbers and weight 1 each.  The previous implementation output a single row with weight `N`.
> Account for weights in `rank` and `row_number`.

- crates/pipeline_manager/src/config.rs
- crates/pipeline_manager/src/integration_test.rs
- crates/pipeline_manager/src/local_runner.rs
- crates/pipeline_manager/src/runner.rs
Having to always build the JIT pipeline runner executable to run the pipeline manager interferes with dev workflow. This commit enables the manager to run with JIT support disabled.  Specifically, if the user does not specify the path to the JIT pipeline runner on the command line and it is not found at the default location, the manager starts successfully with a warning, but any  Aattempts to start a pipeline in JIT mode will return an error.
cc: @Karakatiza666
> Allow pipeline manager to run without JIT support.

- CHANGELOG.md
- crates/adapters/src/transport/kafka/input.rs
- crates/adapters/src/transport/kafka/output.rs
- crates/adapters/src/transport/secret_resolver.rs
Changes the default secrets directory from `/etc/secret-volume` to `/etc/secrets`.
In addition, changes some comment and variable terminology to be more in line with a directory in which there are secrets as files.
> Change default secrets directory and update related terminology

- Cargo.lock
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/pipeline_automata.rs
- crates/pipeline_manager/src/runner.rs
The pipeline automaton is written as one large method that blends several concerns. It is one big loop that waits on external triggers (or timeouts), advances the state machine, changes timeouts, and updates the pipeline state in the database in the state machine itself. This made it difficult to follow the automaton's behavior and to test targeted executions.
This commit breaks up the automaton to separate out triggers that tick the automaton, from the state machine and transitions, to actually reflecting state updates to the database. `PipelineHandle` API calls are still embedded within the logic to identify state transitions. In doing so, we also remove a few functions and indirections that are no longer needed.
With this commit we can now write tests where we construct an automaton …
> pipeline-manager: refactor automaton to be testable

- crates/pipeline_manager/src/pipeline_automata.rs
> pipeline-manager: do not print misleading error on shutdown -> shutdown transition

- crates/adapters/README.md
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/format/mod.rs
- crates/adapters/src/lib.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/test/kafka.rs
- crates/adapters/src/test/mock_input_consumer.rs
- crates/adapters/src/test/mock_output_consumer.rs
- crates/adapters/src/test/mod.rs
- crates/adapters/src/transport/durable_kafka/input.rs
- crates/adapters/src/transport/durable_kafka/mod.rs
- crates/adapters/src/transport/durable_kafka/output.rs
- crates/adapters/src/transport/durable_kafka/test.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/http/input.rs
- crates/adapters/src/transport/http/output.rs
- crates/adapters/src/transport/kafka/input.rs
- crates/adapters/src/transport/kafka/mod.rs
- crates/adapters/src/transport/kafka/output.rs
- crates/adapters/src/transport/kafka/test.rs
- crates/adapters/src/transport/mod.rs
- crates/adapters/src/transport/url.rs
- crates/adapters/tests/jit_integration_test.rs
- crates/pipeline-types/src/transport/durable_kafka.rs
- crates/pipeline-types/src/transport/mod.rs
- crates/pipeline_manager/src/compiler.rs
- sql-to-dbsp-compiler/README.md
This series adds durable input and output and uses them to build basic support for fault tolerance. This fault tolerance requires rerunning everything from the start of the input. Storage support, later, will allow restarting from a checkpoint.
I am really happy with how some commits in the middle of this series get rid of console spew running `cargo test -p dbsp_adapters`, properly capturing all the output.
This has inadequate testing, partly captured by issue #793.
> Add basic fault tolerance that requires replay from start.

- sql-to-dbsp-compiler/SQL-compiler/pom.xml
Fixes https://github.com/feldera/feldera/issues/942
The jar size goes down from 135M to 28M.
> sql-compiler: remove SLT from SQL-compiler dependencies

- crates/adapters/README.md
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/test/kafka.rs
- crates/adapters/src/transport/kafka/input.rs
- crates/adapters/src/transport/kafka/mod.rs
- crates/adapters/src/transport/kafka/output.rs
- crates/adapters/src/transport/kafka/test.rs
- crates/adapters/tests/jit_integration_test.rs
- crates/pipeline_manager/src/compiler.rs
- sql-to-dbsp-compiler/README.md
This is a resubmission of the small fixes and improvements that lead up to the fault tolerance code. These commits are a subset of those reverted yesterday with commit a23d48134877 ("dbsp_adapters: Temporarily roll back fault tolerance series."). Now, these commits have gone through and passed CI three times, so I do not think that these are a problem, and I will re-merge them.
> Fixes and minor improvements leading up to fault tolerance integration

- crates/adapters/Cargo.toml
This test kept failing for me, because `pipeline` wasn't being built, which in turn was because I wasn't passing in the right features.  This avoids the problem.
> dbsp_adapters: Fix dependencies for jit_integration_test.

- CHANGELOG.md
- web-console/src/lib/functions/common/tanstack.ts
- web-console/src/lib/services/pipelineManagerQuery.ts
The issue was that when checking if start/pause/shutdown request is redundant, a stale request cache was used to determine current pipeline status. Since the previous mutation the cache for `.pipelineStatus()` query was invalidated, but by default `getQueryData()` returns both valid and stale cache. By adding { stale: false } filter, we ensure that only valid status data is used for the check. Also we apply status consolidation via `consolidatePipelineStatus()` to `.pipelineStatus()` query, just like to `.pipelines()` query, to ensure identical behavior.
> Fix a bug in Pipeline Management table where sometimes pipeline action buttons do not send requests

- deploy/Dockerfile
- python/dbsp/pipeline.py
* Make sure we don't use generated attached connector names. This is needed to keep pipeline metrics endpoints human interpretable. 
* Avoid invoking snowsql during Docker build.
> Miscellaneous patches while working on metrics

- demo/demo_notebooks/fraud_detection.ipynb
- python/dbsp/pipeline.py
- python/test.py
Fixes https://github.com/feldera/feldera/issues/1024
> python: use explicit names for file-type attached-connectors

- crates/adapters/src/transport/kafka/ft/test.rs
I didn't spot this in testing the previous commit because it was ignored.
Fixes: e6391827d8cf ("dbsp_adapters: Unify `kafka` and `durable_kafka` transports.")
> dbsp_adapters: Fix config string in ignored test.

- Cargo.lock
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/bin/compiler-server.rs
- crates/pipeline_manager/src/bin/pipeline-manager.rs
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/lib.rs
- crates/pipeline_manager/src/metrics.rs
This commit starts adding metrics to the pipeline-manager components. We'll start with the compiler server for now. We'll expose histograms for compiler latencies as well as a counter for the number of invocations. These two metrics are faceted by two labels: the phase (SQL vs Rust) and the status (Success vs Error).
For now, we'll always host metrics via a scrape endpoint on a different port (0.0.0.0:9000/metrics) than the usual APIs (80/8080). This is to make sure that we can avoid exposing the scraping endpoint outside the docker ensemble or cluster in a real deployment.
> pipeline-manager: add metrics to compiler server

- CHANGELOG.md
- crates/pipeline-types/src/config.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/integration_test.rs
- python/feldera-api-client/feldera_api_client/models/new_pipeline_request.py
- python/feldera-api-client/feldera_api_client/models/pipeline_config.py
- python/feldera-api-client/feldera_api_client/models/pipeline_descr.py
- python/feldera-api-client/feldera_api_client/models/pipeline_revision.py
- python/feldera-api-client/feldera_api_client/models/runtime_config.py
- python/feldera-api-client/feldera_api_client/models/update_pipeline_request.py
`PipelineConfig` is an internal constructed type whereas `RuntimeConfig` can be publicly supplied by a REST client. `ResourceConfig` being in `PipelineConfig` meant that it could not be explicitly configured by clients. We therefore move `ResourceConfig` into `RuntimeConfig` to allow external configuration.
Fixes #1026 
> pipeline-manager: fold ResourceConfig into RuntimeConfig

- docs/sql/casts.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/DBSPNode.java
- sql-to-dbsp-compiler/lib/sqllib/Cargo.toml
- sql-to-dbsp-compiler/lib/sqllib/src/casts.rs
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
This implements the same semantics for casts as the Calcite simplification code.
Note that there are several open bugs against calcite's handling of casts, so this has to be continued.
Fixes #1048
> Fix casts in SQL

- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/jit/JitTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/NaiveIncrementalTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/OptimizedIncrementalTests.java
Exactly the same tests are being run as previously, but there is less bug-prone code duplication.
This essentially moves some code from NaiveIncrementalTests to EndToEndTests
> [SQL] Simplify the structure of the simple end to end tests

- CHANGELOG.md
- crates/adapters/src/static_compile/deserialize_with_context.rs
- docs/sql/grammar.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/InputColumnMetadata.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustHandleVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/RelColumnMetadata.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlExtendedColumnDeclaration.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/NegativeParserTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ParserTests.java
> [SQL] Add support for 'default' column values

- web-console/src/app/(root)/(blank)/auth/aws/page.tsx
- web-console/src/app/(root)/(blank)/login/page.tsx
Static Web Console app served by Pipeline Manager requires using trailing slashes in page URLs. This commit fixes missing trailing slash in redirect URL passed to Cognito
> Add trailing slash to Cognito redirect_uri

- crates/dbsp/src/trace/layers/mod.rs
The lifetime should only be bound on the cursor itself rather than the storage.
> Adjust lifetime bound.

- CHANGELOG.md
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/integration_test.rs
Pipeline validation was previously checking if the referenced program
was /being/ compiled instead of whether it was successfully compiled.
In particular, the validation would succeed when the program is in
the `CompilingRust` state.
The fix is in the validation code. The previous, indirect check was
probably an artifact from some older code. Instead we now keep it simple
and just check if the program is in the success state before we
continue. Checking whether the schema is also set should now be
redundant, but we keep it just in case the compilation pipeline changes
in the future.
We also add a simple integration test to catch this case.
Fixes #1057
> pipeline-manager: do not allow pipelines to be started mid-compilation

- crates/dbsp/Cargo.toml
- crates/dbsp/src/trace/layers/column_layer/builders.rs
- crates/dbsp/src/trace/layers/column_layer/cursor.rs
- crates/dbsp/src/trace/layers/column_layer/mod.rs
- crates/dbsp/src/trace/layers/column_layer/tests.rs
- crates/dbsp/src/trace/layers/erased/erased_key_leaf/builders.rs
- crates/dbsp/src/trace/layers/erased/erased_key_leaf/cursor.rs
- crates/dbsp/src/trace/layers/erased/erased_key_leaf/mod.rs
- crates/dbsp/src/trace/layers/erased/erased_leaf/builders.rs
- crates/dbsp/src/trace/layers/erased/erased_leaf/cursor.rs
- crates/dbsp/src/trace/layers/erased/erased_leaf/mod.rs
- crates/dbsp/src/trace/layers/mod.rs
- crates/dbsp/src/trace/layers/ordered/mod.rs
- crates/dbsp/src/trace/layers/ordered_leaf.rs
- crates/dbsp/src/trace/layers/unordered.rs
- crates/dbsp/src/trace/ord/indexed_zset_batch.rs
- crates/dbsp/src/trace/ord/key_batch.rs
- crates/dbsp/src/trace/ord/val_batch.rs
- crates/dbsp/src/trace/ord/zset_batch.rs
- crates/dbsp/src/utils/tests.rs
We add the DBWeight+DBData trait throughout the layer API, this prepares for storage because it ensures that the types in the layers are serializable.
It also makes trait changes in the future less painful (hopefully) as we only have to change the DBWeight and DBData traits.
> Simplify trait bounds in dbsp.

- web-console/src/app/(root)/(authenticated)/(app)/streaming/inspection/page.tsx
- web-console/src/lib/components/analytics/TableSqlPrograms.tsx
- web-console/src/lib/components/common/table/EntityTable.tsx
- web-console/src/lib/components/connectors/DataSourceTable.tsx
- web-console/src/lib/components/connectors/drawer/SelectSourceTable.tsx
- web-console/src/lib/components/streaming/management/PipelineTable.tsx
- web-console/src/lib/compositions/useHashPart.ts
Commit 1: Keeping predefined action buttons inside EntityTable component complicates adding anchors for UI testing and goes against dependency injection principle. Having similar "duplicates" of Edit and Delete buttons for each table simplifies the code and doesn't add much verbosity.
Commit 2: Fix unable to switch between INSERT and BROWSE tabs on Pipeline Data page (Fix https://github.com/feldera/feldera/issues/1044)
> Separate edit and delete row action buttons into respective parent components

- CONTRIBUTING.md
- sql-to-dbsp-compiler/SQL-compiler/pom.xml
- sql-to-dbsp-compiler/slt/pom.xml
Bump the source versions to 19, which should make a slew of quality-of-life features available to the compiler (records, local variable type inference, switch expressions etc).
Looked into using JDK 21. openjdk-21 is the latest JDK release (it's also LTS), but is not yet packaged for Ubuntu 22.04 which we use in our Docker builds. If we upgrade to Ubuntu 23.10 that should work too.
> sql-compiler: bump source version to JDK 19

- web-console/src/app/(root)/(authenticated)/layout.tsx
This change forces all and only required files of monaco-editor to statically bundle in the deployment
Fix https://github.com/feldera/feldera/issues/865: Ensure WebConsole dependencies do not load third party resources - when following Feldera Basics tutorial no external requests were performed.
> Remove runtime dependency of Monaco Editor

- CHANGELOG.md
- docs/sql/float.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TrigonometryTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
* Also updates the sin and cos tests to use PI instead of 3.14
Fixes: #1115
> [SQL] Add the mathematical constant PI

- CHANGELOG.md
- web-console/src/@core/layouts/components/shared-components/UserDropdown.tsx
- web-console/src/app/(root)/(authenticated)/(app)/connectors/create/page.tsx
- web-console/src/app/(root)/(authenticated)/(app)/streaming/builder/page.tsx
- web-console/src/lib/components/connectors/DataSourceTable.tsx
- web-console/src/lib/components/connectors/dialogs/AnyConnector.tsx
- web-console/src/lib/components/connectors/dialogs/DebeziumInputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/GenericEditorConnector.tsx
- web-console/src/lib/components/connectors/dialogs/KafkaInputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/KafkaOutputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/SnowflakeOutputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/UnknownConnector.tsx
- web-console/src/lib/components/connectors/dialogs/UrlConnector.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/TabFooter.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/TabGenericInputFormatDetails.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/TabOutputFormatDetails.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/debezium/DebeziumInputFormatDetails.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/kafka/TabKafkaAuth.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/kafka/TabKafkaInputDetails.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/kafka/TabKafkaNameAndDesc.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/kafka/TabKafkaOutputDetails.tsx
- web-console/src/lib/components/connectors/dialogs/tabs/snowflake/SnowflakeOutputFormatDetails.tsx
- web-console/src/lib/components/connectors/drawer/AddSourceDrawer.tsx
- web-console/src/lib/components/connectors/drawer/SelectSourceTable.tsx
- web-console/src/lib/components/layouts/vertical/AppBarContent.tsx
- web-console/src/lib/types/connectors/ConnectorDialogProps.ts
Open modal popup with non-editable config of the connector
Fix https://github.com/feldera/feldera/issues/1089
> Add 'Inspect connector' button to the connector list in Pipeline Builder

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/CompilerMain.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/BaseSQLTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ComplexQueriesTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/DBSPCompilerTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/HandlesTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/SqlIoTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TestCase.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpchTest.java
Fixes #1151 
We generate code in different ways for the pipeline and for testing locally. This centralizes this information into a new "internal" compiler flag, `emitHandles`. The flag is internal because it is not exposed as a compiler command-line option. It can be only modified programmatically.
I have moved several tests which need this flag into a common file, the testing infrastructure makes sure that you can only run together tests that have the same compiler flags.
> [SQL] Make 'emitHandles' an internal compiler options

- web-console/src/lib/components/streaming/inspection/InspectionTable.tsx
Introduced by recent change of OpenAPI base path
This is a temporary fix: manually add a v0 scope to a url
Will be replaced with usage of a safer generated code in the next commit
> Fix WebConsole calling incorrect endpoint for receiving egress data

- web-console/src/lib/compositions/streaming/inspection/useDeleteRows.ts
Regression is caused by refactoring where the same argument is passed in different conditions
> WebConsole: Fix regression of deleting rows 

- web-console/src/lib/components/streaming/inspection/InspectionTable.tsx
- web-console/src/lib/compositions/streaming/inspection/useQuantiles.ts
- web-console/src/lib/compositions/streaming/inspection/useTableUpdater.ts
- web-console/src/lib/functions/common/tanstack.ts
- web-console/src/lib/services/HttpInputOutputService.ts
- web-console/src/lib/types/common/function.ts
This should be robust enough until the proper fix that would directly use method generated from OpenAPI spec and build on top of it.
> WebConsole safe temp fix: enable auth for egress streaming http request

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TableContents.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/Catalog.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/FrontEndStatement.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/TestUtil.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/NegativeParserTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TopKTests.java
Fixes #1174 
In SQL one cannot naturally write a GROUP-BY TOPK query; one has to use a specific incantation using ROW_NUMBER and a WHERE. The compiler tries to recognize this pattern, but the recognition is brittle. By using the Calcite optimization to reorder filters and projections we make this slightly more robust.
There is also a fix to give good error messages when two tables with the same name are defined.
> [SQL] Reorder filter and project using Calcite

- crates/dbsp/src/operator/input.rs
- crates/dbsp/src/operator/trace.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPDelayOutputOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainKeysOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceBaseOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMapOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMultisetOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceTableOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/FindDeadCode.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TestCase.java
This implementation uses the DBSP `integrate_trace_retain_keys` operator to throw away group keys that will never be updated. It is used in conjunction with the lateness dataflow analysis to control the memory consumption of streams of monotone values. That operator has a very funky semantics, so the hope is that at some point we can do this in a simpler way.
This implementation is incomplete; it only handles (group-by)+aggregate operators and it is only limited to some simple graph topologies. 
We still have to handle:
- joins
- upserts as inserted after aggregates, inputs, and before outputs
- streams that have multiple consumers
> [SQL] Preliminary support for bounded memory computation on streams

- CHANGELOG.md
- docs/sql/decimal.md
- docs/sql/integer.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CustomFunctions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresNumericTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/TrigonometryTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
- sql-to-dbsp-compiler/lib/sqllib/src/operators.rs
Fixes #1200 
Initially I thought that division is a problematic operation in SQL because it throws on division by 0, so I redefined it to return NULL. Turns out that most SQL operations can throw, so there is no point in only changing the semantics of division. This PR reverts the typing and semantics of division to its standard SQL definition.
> [SQL] Use standard SQL semantics for division

- .github/workflows/ci.yml
- Earthfile
Removes the workarounds we'd used to cache our rust builds better in Earthly. We instead use Earthly's rust UDC: https://github.com/earthly/lib/tree/main/rust#set_cache_mounts_env
Also removes the rust toolchain/build arguments being scattered throughout the Earthfile that weren't being used. If a build or action wants to tune these, they can set the environment variables at the top.
I think we could simplify the file even further by only executing cargo build once (instead of per-package), but I didn't go there yet.
~~Replaces cargo machete with `cargo +nightly udeps`.~~
I removed the audit phase given we've been ignoring the results of`cargo audit`.
> Simplify Earthfile using rust UDC

- .github/workflows/benchmark-command.yml
- build: use earthly rust UDF to simplify Earthfile
- ci: use SET_CACHE_MOUNTS_ENV to correctly invoke cargo directly
- ci: remove RUST_TOOLCHAIN and RUST_BUILD_PROFILE args throughout the Earthfile
- ci: add stage to call cargo +udeps
- ci: use cargo machete anyway
- ci: remove stray --output
- ci: bump benchmark workflow to use Earthly 0.7.23 as well
> ci: bump benchmark workflow to use Earthly 0.7.23 as well

- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/service.rs
Split off the implementation of the service functions for the database (new, list, get_by_id, get_by_name, update, delete) into their own file. This helps with readability by reducing the number of lines in the mod file.
> pipeline-manager: db: split off service implementation into own file

- web-console/src/lib/components/connectors/drawer/AddSourceDrawer.tsx
> Fix connector logos not displayed in Add Source Drawer on Pipeline Builder page in Firefox

- crates/adapters/src/transport/kafka/ft/input.rs
- crates/adapters/src/transport/kafka/ft/mod.rs
- crates/dbsp/examples/orgchart.rs
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/circuit/metadata.rs
- crates/dbsp/src/operator/distinct.rs
- crates/dbsp/src/operator/join.rs
- crates/dbsp/src/operator/trace.rs
- crates/dbsp/src/operator/z1.rs
- crates/dbsp/src/profile/mod.rs
- crates/pipeline_manager/src/db/mod.rs
DBSP implements low-level profiling functionality that allows measuring the memory and CPU usage of individual operators.  Previously this functionality was only accessible through the `dump_profile()` API, which dumps per-worker-thread profile to dot files for manual inspection.
This commit adds a richer profiling API, which for example allows tracking the memory usage of a circuit programmatically.  This can be used for example to make sure that the circuit runs with bounded memory.
- Added the `retrive_profile()` method to the `DBSPHandle` API.  The method returns a `DbspProfile` object, which contains a vector of per-worker thread profiles, which can be inspected individually.
- In addition, `DbspProfile` provides methods to compute aggregated profiles of individual attributes, such …
> Improved profiling API.

- CHANGELOG.md
- crates/pipeline_manager/src/api/http_io.rs
- crates/pipeline_manager/src/api/mod.rs
- crates/pipeline_manager/src/runner.rs
We've been seeing a repeatable issue with our deployments where demos
generating high HTTP ingress/egress traffic load, eventually hit a 502
bad gateway error in the cloud form factor.
Repeating such a workload against a local instance of the pipeline
manager revealed the issue: we we were creating too many connections
from the pipeline-manager when forwarding HTTP streams, which in turn
led to resource exhaustion. This was because we were creating a new
awc::Client instance per stream to forward HTTP streams to the pipeline.
The awc::Client::new() documentation is clear that we should be
creating at most one instance of the client per thread (and we were
definitely not respecting that).
This PR fixes this issue by sharing one instance of an awc::Client
per actix server.
Signed-off-by: …
> pipeline-manager: share an awc::Client instance instead of creating one per ingress/egress stream

- crates/adapters/src/transport/url.rs
This defaulted to the number of CPU threads, which is way too many for a trivial test.
Thanks to Lalith Suresh for reporting the problem.
> dbsp_adapters: Reduce number of HTTP workers in `test_pause` test to 1.

- CHANGELOG.md
- docs/sql/integer.md
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/TinyintTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt2Tests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt4Tests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt8Tests.java
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
- sql-to-dbsp-compiler/lib/sqllib/src/operators.rs
Is this a user-visible change (yes/no): yes (updates the docs)
Partially Fixes: #1186 
Fixes: #1243 
This PR fixes the run time implementation by using the `checked` version of the arithmetic operation. However, the Calcite optimized code still overflows.
> [SQL] run time error for arithmetic overflow

- CHANGELOG.md
- crates/pipeline_manager/src/api/connector.rs
- crates/pipeline_manager/src/api/mod.rs
- crates/pipeline_manager/src/api/pipeline.rs
- crates/pipeline_manager/src/api/program.rs
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/db/connector.rs
- crates/pipeline_manager/src/db/mod.rs
- crates/pipeline_manager/src/db/pipeline.rs
- crates/pipeline_manager/src/db/program.rs
- crates/pipeline_manager/src/db/storage.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/db_notifier.rs
- crates/pipeline_manager/src/pipeline_automata.rs
- openapi.json
- python/feldera-api-client/feldera_api_client/api/connectors/create_or_replace_connector.py
- python/feldera-api-client/feldera_api_client/api/pipelines/create_or_replace_pipeline.py
- python/feldera-api-client/feldera_api_client/api/programs/create_or_replace_program.py
- python/feldera-api-client/feldera_api_client/models/__init__.py
- python/feldera-api-client/feldera_api_client/models/create_or_replace_connector_request.py
- python/feldera-api-client/feldera_api_client/models/create_or_replace_connector_response.py
- python/feldera-api-client/feldera_api_client/models/create_or_replace_pipeline_request.py
- python/feldera-api-client/feldera_api_client/models/create_or_replace_pipeline_response.py
- python/feldera-api-client/feldera_api_client/models/create_or_replace_program_request.py
- python/feldera-api-client/feldera_api_client/models/create_or_replace_program_response.py
- pipeline-manager: add PUT endpoints to create-or-replace programs, pipelines and connectors
- pipeline-manager: run create_or_replace_program() within a transaction
- pipeline-manager: run create_or_replace_connector() within a transaction
- pipeline-manager: run create_or_replace_pipeline() within a transaction
> pipeline-manager: add PUT endpoints for Programs, Pipelines, and Connectors

- crates/dbsp/src/operator/distinct.rs
- crates/dbsp/src/trace/ord/mod.rs
There were some type aliases for `Spine` based on various types, but most of them were entirely unused except for one that was used in a single place. This removes all of them to clarify their importance (none).
> Remove aliases for instances of the `Spine` type.

- crates/dbsp/src/trace/persistent/cursor.rs
Commit 680a3215a7e6 ("dbsp: Make batch cursors clonable.") added a `Clone` bound for cursors but didn't implement it for `PersistentTraceCursor`. This passed normal CI (because it doesn't enable persistence) but failed the benchmark runs.  This fixes the problem.
It's hard to actually clone these cursors because RocksDB doesn't provide a direct way to do it.
> dbsp: Add stub `Clone` implementation for `PersistentTraceCursor`.

- deploy/Dockerfile
- deploy/docker-compose.yml
Docker compose's virtual networking meddles with the CORS
configuration. This commit explicitly sets the allowed origins
to include http://localhost:8080 and the docs domain
to help our Docker Compose form factor.
> pipeline-manager: explicitly set allowed origins in Dockerfile

- crates/adapters/src/catalog.rs
- crates/adapters/src/lib.rs
- crates/adapters/src/static_compile/catalog.rs
- crates/dbsp/src/operator/input.rs
- crates/dbsp/src/operator/output.rs
- crates/dbsp/src/tutorial.rs
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
- Implemented `Debug` for `dyn SerBatch`, so we can easily debug-print
circuit outputs in the `adapters` crate.
- Added `Debug` trait bounds to `Input` and `Output` DBSP operator to
make sure we can always debug-print circuit inputs and outputs.
- Added a couple of missing exports to the `adapters` crate to allow
accessing the catalog API from outside.
> Minor improvements to simplify debugging

- CHANGELOG.md
- crates/adapters/src/catalog.rs
- crates/adapters/src/format/json/input.rs
- crates/adapters/src/format/json/mod.rs
- crates/adapters/src/format/json/output.rs
- crates/adapters/src/static_compile/catalog.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/static_compile/deserialize_with_context.rs
- crates/adapters/src/test/kafka.rs
- crates/adapters/src/test/mock_dezset.rs
- crates/adapters/src/test/mod.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/kafka/ft/test.rs
- crates/adapters/src/transport/kafka/nonft/test.rs
- crates/adapters/src/transport/url.rs
- crates/dbsp/src/operator/input.rs
- crates/dbsp/src/operator/input_upsert.rs
- crates/dbsp/src/operator/mod.rs
- crates/dbsp/src/operator/sample.rs
- crates/pipeline_manager/src/integration_test.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMapOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeStruct.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
This commit extends our support for UPSERT operations to allow partial modifications to existing records in the database.
The UPSERT operation is defined for tables with primary keys and allows overwriting an existing record associated with a key without explicitly deleting it first.  Previously, it required specifying the entire new value of the record.  Oftentimes the user needs to update only some of the fields of the record without explicitly listing all other fields (e.g., the value of a counter increased by 1, while its other properties haven't changed).  In fact, they may not even have access to the values of all other fields.
The new form of the UPSERT operator allows exactly that.  It is currently only supported for JSON inputs in the insert/delete format. We introduce the …
> Support patch semantics for upserts.

- crates/pipeline_manager/src/config.rs
Keep the default behavior when using cors to allow any origin.
> pipeline-manager: allow any origin by default

- Earthfile
It's easy to make mistakes in documentation and forget to check them with `cargo doc` before submitting.  This will find those problems.  With this commit, `cargo doc` problems will fail something like this:
```
+clippy *failed* | --> RUN set -e; cargo $args; cargo sweep -r -t $EARTHLY_SWEEP_DAYS; cargo sweep -r -i;
+clippy *failed* |     Checking pipeline_types v0.1.0 (/dbsp/crates/pipeline-types)
+clippy *failed* |     Checking feldera-storage v0.1.0 (/dbsp/crates/feldera-storage)
+clippy *failed* |  Documenting feldera-storage v0.1.0 (/dbsp/crates/feldera-storage)
+clippy *failed* |  Documenting pipeline_types v0.1.0 (/dbsp/crates/pipeline-types)
+clippy *failed* |    Compiling pipeline-manager v0.8.0 (/dbsp/crates/pipeline_manager)
+clippy *failed* |  Documenting pipeline-manager …
```
> Earthfile: Check that `cargo doc` succeeds during the CI build.

- CHANGELOG.md
- crates/pipeline_manager/migrations/V10__remove_program_status_none.sql
- crates/pipeline_manager/src/api/program.rs
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/db/program.rs
- crates/pipeline_manager/src/db/test.rs
- openapi.json
Both our UI and API workflows always issue a compilation request
after creating or modifying programs. There is no reason to have
progams that we don't intend on compiling.
This PR automatically sets all newly created or modified programs
to be in the "Pending" state, which automatically queues them for
compilation.
The previous /compile API is now a no-op (and shouldn't break any
existing workflows).
Feature requested by @Karakatiza666 
> pipeline-manager: automatically queue programs for compilation

- Earthfile
- crates/dbsp/src/operator/communication/exchange.rs
- crates/dbsp/src/trace/persistent/cursor.rs
- crates/dbsp/src/trace/persistent/trace.rs
- crates/feldera-storage/src/file/mod.rs
The problem was that the persistence code was using `rkyv::to_bytes`, which only works with one particular serializer that we're no longer using. This commit adds an equivalent for our serializer and switches the persistence code (and one other caller) to use it.
Thanks to @gz for reporting the problem.
Fixes: de643bf89bc1 ("Use storage backends in layer files and adapt dbsp to the changes.")
> dbsp: Fix build with `--features=persistence`.

- deploy/docker-compose-debezium.yml
In its initialization, MySQL first starts up a temporary server. This server is afterwards stopped and replaced at start-up with the actual server. It appears that even executing a query like `SELECT 1;` is not sufficient to check that the actual server is running and not the temporary one. Only near the very end of the temporary server, the entrypoint SQL is run (creating the databases therein). As such, `USE database;` is less likely to return success than `SELECT 1;` during the temporary server lifetime, and is thus a better health check (albeit, not perfect).
Latest CI run that likely failed because the MySQL was not yet started:
https://github.com/feldera/feldera/actions/runs/7705263364/job/20998907686?pr=1355
> docker: mysql healthcheck: USE database instead of SELECT 1

- CHANGELOG.md
- docs/sql/decimal.md
- docs/sql/float.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat8Part2Tests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat8Tests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresNumericTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
* [SQL] Add import float8 tests from Postgres
* bugfix: Implement ln for double
Fixes: #1328 
Fixes: #1326
Fixes: #1351 
Fixes: #1348 
Fixes: #1363
> [SQL] Add is_inf, is_nan, log for floats

- crates/dbsp/src/operator/sample.rs
- crates/dbsp/src/trace/ord/file/mod.rs
- crates/dbsp/src/trace/ord/file/val_batch.rs
- crates/dbsp/src/trace/ord/merge_batcher/tests.rs
- crates/dbsp/src/trace/ord/mod.rs
- crates/feldera-storage/src/file/reader.rs
This passes all `dbsp` tests if `FileValBatch` is used for `OrdValBatch`, but it doesn't do that substitution.
> dbsp: Add a file-backed ValBatch implementation.

- crates/feldera-storage/src/backend/monoio_impl/mod.rs
The CI OOM error always happens during runtime creation. We have a pretty high queue depth for the IO-uring which means more memory is needed for it. Maybe reducing this will help for now.
> Reducing the IO-uring queue depth.

- crates/dbsp/src/operator/communication/gather.rs
- crates/dbsp/src/operator/communication/shard.rs
- crates/dbsp/src/operator/output.rs
- crates/dbsp/src/trace/mod.rs
A few pieces of code used a `Spine` to merge a collection of batches.  This does more work than necessary, since `Spine` is all about merging batches with different times.  This commit replaces these users by a new function `merge_batches()`.
There is one remaining case that maybe should be replaced too, which is the use of `Spine` in `RecursiveStream`.  I'm not sure about that one because it adds batches one-by-one instead of all at once and therefore might benefit from how `Spine` could reduce intermediate data sizes by adding weights to zero.  That's data-dependent though.
> dbsp: Don't use `Spine` as an easy way to merge multiple batches.

- docs/sql/decimal.md
- docs/sql/float.md
- docs/sql/integer.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresFloat8Tests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresNumericTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/casts.rs
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
- sql-to-dbsp-compiler/lib/sqllib/src/operators.rs
* [SQL] modulo for fp and decimal
Modulo was already defined for fp and decimal in the docs but not implemented in Rust, this PR adds those implementations. 
This PR also adds tests for decimal type rounding and truncation. 
- Adds support for negative values while for rounding and truncation to be consistent with Postgres and MySQL. 
Fixes: #1327
> [SQL] decimal rounding and truncation tests

- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/operator/apply.rs
Commit 7adb42449bb2 ("dbsp: Don't use `Spine` as an easy way to merge multiple batches.") broke the `galen` benchmark, e.g. see https://github.com/feldera/feldera/actions/runs/7788912540/job/21239358442:
```
Finished bench [optimized + debuginfo] target(s) in 1m 00s
Running benches/galen.rs (target/release/deps/galen-0d27487e860f1e75)
Running galen benchmark with 10 workers
thread 'dbsp-worker-0' panicked at /dbsp/crates/dbsp/src/operator/apply.rs:183:9:
not implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This change triggered the problem:
```rust
.apply_owned_named("merge shards", |batches| {
merge_batches(batches)
});
```
It's because `apply_owned_named` doesn't consider its closure to arrive at a fixed point, see `apply.rs`:
```rust
fn …
```
> dbsp: Fix `galen` benchmark.

- CHANGELOG.md
- Cargo.lock
- crates/pipeline_manager/src/api/config_api.rs
- crates/pipeline_manager/src/api/mod.rs
- crates/pipeline_manager/src/auth.rs
- crates/pipeline_manager/src/config.rs
- crates/pipeline_manager/src/integration_test.rs
- openapi.json
> pipeline-manager: add a config API endpoint to get a list of canned demo URLs

- web-console/src/app/(root)/(authenticated)/(app)/streaming/builder/page.tsx
- web-console/src/app/(root)/(authenticated)/(app)/streaming/inspection/page.tsx
- web-console/src/lib/components/streaming/builder/NodeTypes/InputNode.tsx
- web-console/src/lib/components/streaming/builder/NodeTypes/SqlNode.tsx
- web-console/src/lib/components/streaming/import/ImportToolbar.tsx
- web-console/src/lib/components/streaming/import/InsertionTable.tsx
- web-console/src/lib/components/streaming/import/RngSettingsDialog.tsx
- web-console/src/lib/components/streaming/import/randomData/index.tsx
- web-console/src/lib/components/streaming/inspection/InspectionTable.tsx
- web-console/src/lib/components/streaming/inspection/InspectionToolbar.tsx
- web-console/src/lib/components/streaming/inspection/SQLTypeHeader.tsx
- web-console/src/lib/components/streaming/management/PipelineTable.tsx
- web-console/src/lib/compositions/streaming/builder/useAddIoNode.ts
- web-console/src/lib/compositions/streaming/builder/useAttachedPipelineConnectors.ts
- web-console/src/lib/compositions/streaming/builder/useAutoLayout.ts
- web-console/src/lib/compositions/streaming/import/useInsertRows.ts
- web-console/src/lib/compositions/streaming/inspection/useDeleteRows.ts
- web-console/src/lib/functions/felderaRelation.ts
- web-console/src/lib/services/manager/models/Field.ts
- web-console/src/lib/services/manager/models/Relation.ts
- web-console/src/lib/services/pipelineManagerQuery.ts
- web-console/tests/e2e/demoAccrual.spec.ts
Now, whenever a relation or a column is specified in quotes in an SQL program, WebConsole will display it in quotes everywhere, and use quotes when sending the name through the API
I'll update UI test snapshots when PR is greenlit
The changelog should be rebased an updated in the base PR
> Add support for case (in)sensitive table names in WebConsole

- demo/demo_notebooks/fraud_detection.ipynb
Google drive is throttling automatic downloads mercilessly, affecting the fraud detection CI job.  These datasets are small enough to store them on github, so we move them there.  As a bonus, we will be able to version them if needed.
> Download CI datasets from github.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/DBSPCircuit.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/DBSPPartialCircuit.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPAggregateOperatorBase.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNoopOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSinkOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceBaseOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMapOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMultisetOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPUnaryOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/CollectIdentifiers.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/FindDeadCode.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/IncrementalizeVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/IndexedInputs.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPZSetLiteral.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ComplexQueriesTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/SqlIoTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/Main.java
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
Turns out that the generated Rust would not compile if table names contained spaces.
This PR removes most source of "code injection" in the Rust code.
> [SQL] Handle correctly table names with spaces

- deploy/docker-compose-debezium.yml
According to [this thread](https://github.com/docker-library/mysql/issues/930), using TCP instead of a local socket for health check should resolve the race.
> Improve mysql container health check

- CHANGELOG.md
- web-console/src/app/(root)/(blank)/login/page.tsx
Fix https://github.com/feldera/feldera/issues/1364 : Use a generic login button
This PR makes the UI to redirect to Cognito Hosted UI right away.
Currently there is no UX reason to have a dedicated login page when using AWS Cognito as an auth provider. Hosted UI will already have Feldera branding.
In the future if any additional information should be displayed prior to login it will probably make sense to not display it on a login page, but elsewhere.
> Automatically redirect to AWS Cognito Hosted UI from login page

- CHANGELOG.md
- web-console/src/app/(root)/(authenticated)/(app)/demos/page.tsx
- web-console/src/app/(root)/(authenticated)/layout.tsx
- web-console/src/app/(root)/(blank)/auth/aws/page.tsx
I used SessionStorage to temporarily store the page to redirect to.
Tested with my private Cognito user pool
Fix https://github.com/feldera/feldera/issues/1380: Allow an external URL to launch demos directly in the sandbox. ... It should work even through authentication-related redirects.
> Enable preserving the page to redirect to after authentication when redirecting

- web-console/src/lib/components/streaming/builder/NodeTypes/SqlNode.tsx
- web-console/src/lib/components/streaming/management/PipelineTable.tsx
- web-console/src/lib/compositions/streaming/builder/useAddIoNode.ts
- web-console/src/lib/compositions/streaming/builder/useAutoLayout.ts
- web-console/src/lib/functions/felderaRelation.ts
Without this PR the problem can be observed when setting up SecOps demo and navigating to Pipeline Builder view - connectors are not connected to tables and views.
The bug got exposed up after a PR that makes case insensitive relation names lowercase by default, but the demo wasn't updated to configure lowercase attached_connectors. This configuration was interpreted OK in Pipeline Manager, and WebConsole should match this behavior (match uppercase case-insensitive attached_connector-s to lowercase case-insensitive tables).
> Improve handling of case independent names in Pipeline Builder

- Earthfile
This produced artifacs for me with `earthly -i -P +ui-playwright-tests`, but the original script did not.  I think that the likely reason is that ui-playwright-tests starts with `FROM +ui-playwright-container` and the latter target changes the workdir.
> Earthfile: Properly save playwright artifacts.

- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/config.fmpp
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/SqlRemove.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/TableModifyStatement.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/BaseSQLTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ParserTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
Fixes #1456 
This introduces a REMOVE statement in SQL, which is the exact counterpart of the INSERT statement. It supports pretty much the same forms as INSERT. The result of executing INSERT is to obtain a positive Z-set, whereas executing a REMOVE generates a negative Z-set. 
Both INSERT and REMOVE are used for writing nicer tests. Here is a fragment of an example of a Java test built using the new syntax:
```java
@Test
public void blogTest() {
String statements = """
CREATE TABLE CUSTOMER(name VARCHAR NOT NULL, zipcode INT NOT NULL);                               
CREATE VIEW DENSITY AS
SELECT zipcode, COUNT(name)
FROM CUSTOMER
GROUP BY zipcode
""";
DBSPCompiler compiler = this.testCompiler();
compiler.compileStatements(statements); …
```
> [SQL] Added REMOVE statement to create negative Z-sets

- crates/adapters/src/transport/kafka/ft/input.rs
The consumer in the kafka FT adapter splits all of its consumers off into separate partition queues, but in testing occasionally some messages show up there anyway.  This commit changes those panics into log messages, in case that actually fixes the problem and so that perhaps we can find out more if not.
See https://github.com/feldera/feldera/issues/1331.
> dbsp_adapters: Change `unreachable` to `warn` for partition queues.

- crates/pipeline-types/src/transport/kafka.rs
- openapi.json
Some Kafka FT tests fail intermittently in CI with a timeout setting up the initial connection.  It's unclear whether this is because of a real problem or because the broker is running slowly.  Each time it's occurred, the broker has in fact been running slowly (because creating the topic has been retried in each case), but I don't know how to tell whether that's the entire problem.
This tries to solve the problem by increasing the timeout 6x, from 10 seconds to 60 seconds.
See https://github.com/feldera/feldera/issues/1469.
> Increase Kafka initialization timeout to 60 seconds.

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- Earthfile
- crates/adapters/Cargo.toml
- crates/adapters/src/transport/mod.rs
- crates/adapters/src/transport/s3/mod.rs
- crates/pipeline-types/src/transport/mod.rs
- crates/pipeline-types/src/transport/s3.rs
- crates/pipeline_manager/src/api/mod.rs
- demo/project_demo09-S3/program.sql
- demo/project_demo09-S3/run.py
- deploy/docker-compose.yml
- openapi.json
This adds an `S3InputTransport` that reads objects from AWS S3.
It currently supports two read strategies, one that reads all objects
that match a prefix, and another to read individual objects.
It currently reads in the entire object at once before writing it to the
`InputConsumer`, which is not ideal. An improvement here would be to
perform reads one chunk at a time using the S3 `GetObject` API's `range`
feature.
> adapters: add an input transport for S3

- CHANGELOG.md
- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/catalog.rs
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/format/json/output.rs
- crates/adapters/src/format/mod.rs
- crates/adapters/src/format/parquet/mod.rs
- crates/adapters/src/format/parquet/test.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/static_compile/serde_config.rs
- crates/adapters/src/static_compile/serialize_with_context.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/adapters/src/test/mock_dezset.rs
- crates/adapters/src/test/mock_output_consumer.rs
- crates/adapters/src/transport/file.rs
- crates/dbsp/src/operator/neighborhood.rs
- crates/pipeline-types/src/format/json.rs
- crates/pipeline-types/src/format/mod.rs
- crates/pipeline-types/src/format/parquet.rs
- crates/pipeline-types/src/transport/file.rs
- crates/pipeline_manager/src/db/pipeline.rs
- docs/api/parquet.md
- docs/sidebars.js
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java
- sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
Adds pretty basic parquet/arrow support.
- The input/deserialization (for now) is done just by converting to JSON (this is pretty inefficient but doesn't require us to change the API in adapters as we can provide an [u8] buffer)
- The output/serialization is done using serde-arrow and some modifications in the APIs to make it work
Long term think about a better API that works well for column oriented data where parsing/conversion happens in external libraries.
We'll probably need to extend this further to customize the serialization/deserialization.
@mihaibudiu review for the compiler changes, @ryzhyk for the rest
> Initial support for parquet input/output format.

- crates/adapters/src/server/mod.rs
- crates/dbsp/src/operator/dynamic/group/lag.rs
- crates/dbsp/src/operator/dynamic/group/mod.rs
- crates/dbsp/src/operator/dynamic/group/test.rs
- crates/dbsp/src/operator/group/lag.rs
- crates/pipeline_manager/src/integration_test.rs
Adds a version of the `lag` operator where the ordering of elements
within a group is defined by a user-provided function, similar to
`topk_customr_order` and related operators.
Also eliminates the `lead` operator and instead generalizes
`lag` to take a signed offset, with negative offsets corresponding to
`lead`.
> Lag custom order

- CHANGELOG.md
- Earthfile
- crates/adapters/src/catalog.rs
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/format/csv.rs
- crates/adapters/src/format/json/output.rs
- crates/adapters/src/format/mod.rs
- crates/adapters/src/format/parquet/mod.rs
- crates/adapters/src/format/parquet/test.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/server/prometheus.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/adapters/src/test/mock_output_consumer.rs
- crates/adapters/src/transport/kafka/nonft/test.rs
- crates/dbsp/src/circuit/runtime.rs
- crates/dbsp/src/lib.rs
- crates/dbsp/src/typed_batch.rs
- crates/pipeline-types/src/config.rs
- crates/pipeline_manager/src/db/pipeline.rs
- crates/pipeline_manager/src/db_notifier.rs
- crates/pipeline_manager/src/pipeline_automata.rs
- openapi.json
Introduces an output buffering mechanism to decouple the rate at which the pipeline
pushes changes to the output transport from the rate of input changes.
By default, output updates produced by the pipeline are pushed directly to
the output transport. Some destinations may prefer to receive updates in fewer
bigger batches. For instance, when writing Parquet files, producing
one bigger file every few minutes is usually better than creating
small files every few milliseconds.
To achieve such input/output decoupling, users can enable output buffering by setting
the `enable_buffer` flag in the output endpoint config to `true`.  When buffering is
enabled, output updates produced by the pipeline are consolidated in an internal buffer
and are pushed to the output transport when one of two …
> Output buffering mechanism

- Cargo.lock
- crates/dbsp/Cargo.toml
- crates/dbsp/examples/json.rs
#1478 
A very simple example of using JSON with DBSP. 
- This implementation uses `ijson::IValue` for JSON type. [ijson](https://github.com/Diggsey/ijson/) is a more memory efficient alternative for `serde_json::Value`. 
- it doesn't support `rkyv` by default, we will need to work on that. Currently, we just call `todo!` on the `rkyv` trait implementations. https://github.com/abhizer/ijson/pull/1
- Here, we implement `parse_json` and `json_field` from the RFC. The inner types are interned and cloning shouldn't be bad.
> [DBSP] Example of using JSON with DBSP

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
Fixes: https://github.com/feldera/feldera/issues/1565
Don't think we need to add floor and ceil functions in the documentation for integer types.
> [SQL] Add noop implementations of ceil and floor for integer types

- Earthfile
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/transport/kafka/nonft/test.rs
- crates/pipeline-types/src/config.rs
- crates/pipeline_manager/src/api/examples.rs
- crates/pipeline_manager/src/db/pipeline.rs
- crates/pipeline_manager/src/db/storage.rs
- crates/pipeline_manager/src/db/test.rs
- docs/api/json.md
- openapi.json
My earlier PR that introduced output buffering did not include a REST
API to configure it. This commit adds such an API.  It does so in a
somewhat roundabout way though.  The challenge is that output buffer
config is not strictly part of the connector cofig, rather it's
an attribute of the endpoint (i.e., "attached connector" in the pipeline
manager terminology).  In the UI, this corresponds to the dotted arrow
connecting the pipeline with the connector.  In reality, I expect that
users will want to configure output buffers as part of the connector
rather than deal with separate per-endpoint settings and even if we want
to add per-endpoint config in the future, the default buffering settings
should come from the connector config.
This commit introduces the `ConnectorConfigTemplate` type, …
> Expose output buffer config in the API

- crates/dbsp/src/circuit/runtime.rs
I've managed to write code with bugs such that the `runtime.borrow()` in the `panic_hook` triggered a nested panic because the runtime was already borrowed.  This avoids the problem.  This seems better than having my tests hard-abort without useful debug output.
> dbsp: Avoid panicking within a panic handler.

- crates/adapters/src/controller/mod.rs
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/circuit/runtime.rs
- crates/dbsp/src/trace/ord/fallback/indexed_wset.rs
- crates/dbsp/src/trace/ord/fallback/wset.rs
- crates/pipeline-types/src/config.rs
- crates/pipeline_manager/src/db/pipeline.rs
- openapi.json
- web-console/src/lib/services/manager/models/PipelineConfig.ts
With this, even empty batches get written to storage if `min_storage_rows` is 0.  This consistency is helpful for checkpointing because every batch that could be stored will be, even if it is empty.
Thanks to @gz for reporting this.
> dbsp: Change `max_memory_rows` to `min_storage_rows`.

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- Earthfile
- crates/adapters/Cargo.toml
- crates/adapters/README.md
- crates/adapters/src/format/parquet/mod.rs
- crates/adapters/src/format/parquet/test.rs
- crates/adapters/src/integrated/delta_table/output.rs
- crates/adapters/src/integrated/mod.rs
- crates/adapters/src/lib.rs
- crates/pipeline-types/src/transport/delta_table.rs
- sql-to-dbsp-compiler/temp/Cargo.toml
The adapter now uses the transaction log rather than just writing
Parquet files.  It was also tested with S3 and the output is compatible
with Spark (at least the Databricks flavor of it).
> More complete Delta Table output adapter

- crates/pipeline_manager/src/compiler.rs
- sql-to-dbsp-compiler/temp/Cargo.toml
Re-enable default features of the `adapters` crate when using it to build a Feldera pipeline.
> PR 1639 postfix.

- deploy/Dockerfile
This commit removes a few inefficiencies from the Dockerfile.
* Avoid `COPY . .`, which copies over a lot of junk during local builds, and only selectively copy the files we need.
* Builds the web-server and java components in parallel with the pipeline-manager.
* Avoids building the split-up pipeline-manager components since we build them separately in our internal workflows.
* Sets two environment variables during the CI build to force `openssl-sys` to pick up libssl-dev and statically link it in to the binary. The first compilation (either via precompilation or otherwise), drops from 75s to 51s for me with this change.
> docker: streamline Dockerfile

- crates/dbsp/src/lib.rs
- crates/dbsp/src/operator/dynamic/trace.rs
- crates/dbsp/src/time/mod.rs
- crates/dbsp/src/time/nested_ts32.rs
- crates/dbsp/src/time/product.rs
- crates/dbsp/src/trace/cursor/mod.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/ord/fallback/indexed_wset.rs
- crates/dbsp/src/trace/ord/fallback/key_batch.rs
- crates/dbsp/src/trace/ord/fallback/mod.rs
- crates/dbsp/src/trace/ord/fallback/utils.rs
- crates/dbsp/src/trace/ord/fallback/val_batch.rs
- crates/dbsp/src/trace/ord/fallback/wset.rs
- crates/dbsp/src/trace/ord/file/indexed_wset_batch.rs
- crates/dbsp/src/trace/ord/file/key_batch.rs
- crates/dbsp/src/trace/ord/file/val_batch.rs
- crates/dbsp/src/trace/ord/file/wset_batch.rs
- crates/dbsp/src/trace/ord/mod.rs
- crates/dbsp/src/trace/ord/vec/indexed_wset_batch.rs
- crates/dbsp/src/trace/ord/vec/key_batch.rs
- crates/dbsp/src/trace/ord/vec/val_batch.rs
- crates/dbsp/src/trace/ord/vec/wset_batch.rs
- crates/dbsp/src/typed_batch.rs
The individual commits in this series are meaningful and it's worth looking at
them individually.
These complete the set of batch types that choose between memory or
storage implementations at creation time.  These fix the runtime for
the `galen` benchmark, which regressed when storage was introduced because
it uses valbatches.
> dbsp: New FallbackKeyBatch and FallbackValBatch types.

- crates/pipeline_manager/src/integration_test.rs
> pipeline-manager: increase compilation timeout in integration test

- docs/sql/aggregates.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/RelColumnMetadata.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggScottTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggTests.java
This was documented, but I never noticed it's supposed to work.
Calcite seems to be the only SQL which supports this esoteric feature.
Fixes #1481
> [SQL] Support COUNT() with multiple arguments

- docs/sql/grammar.md
- docs/sql/streaming.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/config.fmpp
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPWindowOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/InputColumnMetadata.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/AvroSchemaWrapper.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/RelColumnMetadata.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlExtendedColumnDeclaration.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/HasSchema.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ParserTests.java
This PR introduces front-end support for WATERMARK annotations on table columns. 
Right now the compiler does not use this information at all, so I am claiming this is not a user-visible change yet.
The documentation is marked as such.
Fixes #1678 
Requires #1680
> [SQL] Preliminary support for WATERMARK annotations

- CHANGELOG.md
- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/catalog.rs
- crates/adapters/src/controller/error.rs
- crates/adapters/src/format/avro/mod.rs
- crates/adapters/src/format/avro/output.rs
- crates/adapters/src/format/avro/serializer.rs
- crates/adapters/src/format/json/output.rs
- crates/adapters/src/format/mod.rs
- crates/adapters/src/format/parquet/test.rs
- crates/adapters/src/integrated/delta_table/output.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/adapters/src/test/data.rs
- crates/adapters/src/test/mock_dezset.rs
- crates/adapters/src/test/mock_output_consumer.rs
- crates/adapters/src/test/mod.rs
- crates/pipeline-types/src/format/avro.rs
- crates/pipeline-types/src/format/mod.rs
- crates/pipeline-types/src/serde_with_context/serde_config.rs
- crates/pipeline-types/src/serde_with_context/serialize.rs
- demo/project_demo00-SecOps/run.py
Avro connector that encodes output updates according to a user-specified Avro schema.  Can optionally post the supplied schema to a schema registry, but does not yet support downloading schema from the registry.
The tricky part of this commit is getting serde to generate precisely the encoding required by the Avro schema, where the same SQL type can be represented in multiple ways. In particular, timestamps can be in microseconds or milliseconds, and decimals are represented as bigints with fixed scale given as part of type definition.  To support this, I implemented a special serializer that traverses the Avro schema in parallel with the serialized object and encodes each field according to its schema.
There are currently several limitations, documented in `avro/output.rs`, including:
- …
> Initial support for Avro output format.

- CHANGELOG.md
- Earthfile
- deploy/Dockerfile
- deploy/docker-compose-dev.yml
- deploy/docker-compose.yml
This commit makes the pipeline-manager container self-contained.
This allows users to bring it up wherever they want without using
a separate postgres container and without needing Docker compose at
all.
This allows users to just do the following to bring up the pipeline-manager:
```
docker run -p 8080:8080 --rm -it ghcr.io/feldera/pipeline-manager
```
> docker: use pg-embed to make the pipeline-manager container self-contained

- CONTRIBUTING.md
- README.md
- deploy/README.md
- docs/tutorials/basics/part3.md
- docs/tutorials/rest_api/index.md
This sets us up to release the docker-compose file as an asset every release. I've edited the previous release. it fixes a common issue we have in that we expect users to use stable container images with `docker-compose.yml` files from main. It's not very robust when introducing changes.
This way, we always have a stable docker-compose file we can reference in our documentation.
> docker: release docker-compose file using Github

- crates/dbsp/src/operator/dynamic/group/lag.rs
- crates/dbsp/src/operator/dynamic/group/mod.rs
- crates/dbsp/src/operator/dynamic/group/test.rs
- crates/dbsp/src/operator/group/lag.rs
`lag` originally behaved as if all copies of a record occupied the same index in the list of values.  Apparently, SQL requires different semantics, with each copy occupying a separate slot.  This patch implements the new semantics.  Along the way I dropped the optimization that made sure that the operator output sorted tuples, since it was getting too complicated to maintain.
Addresses #1545 (that test now passes).
> Implement correct semantics for `lag`.

- Earthfile
- deploy/Dockerfile
Without this, the crate versions used for (pre)compiling in the pipeline manager can be surprising, leading to unexpected build failures.  In particular, we've had some problems with the crates for deltalake in CI, but that's just a symptom of the larger problem.
> deploy: Copy `Cargo.lock` into the workspace for precompiling.

- crates/dbsp/src/operator/dynamic/trace.rs
This should make some kinds of debugging easier.
Reported by Gerd.
> dbsp: Add names to the operators used for spilling and unspilling.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
Fixes https://github.com/feldera/feldera/issues/1701
But also creates https://github.com/feldera/feldera/issues/1702
> [SQL] Re-enable (unsound) rule to push filters into joins

- Cargo.lock
- crates/adapters/src/transport/url.rs
- crates/dbsp/src/utils/tuple/gen.rs
- crates/dbsp/src/utils/tuple/mod.rs
- crates/nexmark/Cargo.toml
- crates/nexmark/benches/nexmark-gen/main.rs
- crates/nexmark/benches/nexmark/main.rs
- crates/nexmark/examples/generate.rs
- crates/nexmark/src/config.rs
- crates/nexmark/src/generator/auctions.rs
- crates/nexmark/src/generator/bids.rs
- crates/nexmark/src/generator/config.rs
- crates/nexmark/src/generator/mod.rs
- crates/nexmark/src/generator/people.rs
- crates/nexmark/src/lib.rs
- crates/nexmark/src/model.rs
This adds an example program to the `dbsp_nexmark` crate to generate Nexmark input data into Kafka.
> First step toward end-to-end test

- crates/nexmark/benches/nexmark/main.rs
- crates/nexmark/src/config.rs
Before this, running the benchmark without `--storage` ran it entirely in memory, and with `--storage` entirely on disk.  With this commit, `--storage` takes an optional parameter that specifies the minimum (estimated) number of rows before spilling to disk.
> dbsp_nexmark: Make storage threshold configurable in nexmark benchmark.

- crates/adapters/src/transport/http/input.rs
- crates/dbsp/src/dynamic/factory.rs
- crates/dbsp/src/lib.rs
- crates/dbsp/src/operator/dynamic/aggregate/aggregator.rs
- crates/dbsp/src/operator/dynamic/time_series/radix_tree/mod.rs
- crates/dbsp/src/operator/dynamic/time_series/radix_tree/partitioned_tree_aggregate.rs
- crates/dbsp/src/utils/consolidation/utils.rs
- crates/pipeline_manager/src/db/pipeline.rs
- crates/pipeline_manager/src/db/storage.rs
I guess it's better at finding code that isn't used.
> Fix warnings for upgrade to Rust 1.78.

- CHANGELOG.md
- crates/adapters/src/server/mod.rs
- crates/adapters/src/test/kafka.rs
- crates/adapters/src/transport/kafka/ft/output.rs
- crates/adapters/src/transport/kafka/ft/test.rs
- crates/adapters/src/transport/kafka/mod.rs
- crates/adapters/src/transport/kafka/nonft/output.rs
- crates/adapters/src/transport/kafka/nonft/test.rs
- crates/pipeline-types/src/serde_with_context/serialize.rs
- crates/pipeline-types/src/transport/kafka.rs
- crates/pipeline_manager/src/api/mod.rs
- crates/pipeline_manager/src/config.rs
- demo/project_demo00-SecOps/run.py
- openapi.json
Added `headers` field to Kafka output connector config to specify a list
of headers to be added to each message.
Kafka headers are a list of key-value pairs.  Keys are strings.  The
same key can occur multiple times, therefore the ordering is important.
The value component of the header is an optional byte array.  For
convenience, we allow specifying it as an actual array of bytes in JSON
(`[1,2,3,4,5]`) or as a UTF8-encoded string ("foobar").  Here is an
example Kafka connector config with headers that I added to the SecOps
demo:
```
"config": {
"format": {
"name": "avro",
"config": {
"schema": schema,
"registry_urls": [pipeline_to_schema_registry],
}
},
"transport": {
"name": "kafka_output",
"config": {
"bootstrap.servers": pipeline_to_redpanda_server,
"topic": …
```
> Support for Kafka message headers

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/integrated/delta_table/output.rs
- openapi.json
`deltalake` v0.17.3 broke the build, as it is not backward compatible with 0.17.1.  It also uses arrow 0.51, so I upgraded all our dependencies to use that, and also ran `cargo update` for good measure.
> Upgrade deltalake and arrow crate.

- crates/pipeline_manager/src/config.rs
> pipeline_manager: `--demos` takes an HTTPS URL.

- CHANGELOG.md
- docs/intro.md
- docs/sidebars.js
- docs/troubleshooting/index.mdx
Signed-off-by: Lalith Suresh <suresh.lalith@gmail.com>
I'm trying to reorganize the top-level structure. Unfortunately the current content 
makes it hard to change a few key things:
* Demo/tour is somewhat redundant with the tutorial. They needn't go into separate sections.
* The Demo/tour is locked to working only with the docker install, which means the docker
installation instructions should precede it in the "Get started" section.
* Ideally, the deployment form factors should show up one top-level section. The rest of the
documentation (demos, tutorials etc) should have a context button that switches instructions
depending on whether the user is running against the Docker or Kubernetes FFs.
* The Reference section could use some groupings (e.g., all formats in one) and a better title. …
> docs: improve high-level structure for the documentation

- web-console/src/app/(root)/(authenticated)/(app)/streaming/inspection/page.tsx
Fix https://github.com/feldera/feldera/issues/1646 : Adding rows without inserting leads to invariant failed
The fix involves keeping rows (that are to be imported) in memory for each table, not just the current one
> Fix crash when switching between tables in Data Insert page

- crates/adapters/src/integrated/delta_table/input.rs
- crates/pipeline-types/src/transport/delta_table.rs
- openapi.json
The issue is reported [here](https://github.com/feldera/feldera/pull/1764) and is caused by the interaction between two serde `flatten` attributes, one on a HashMap and one on a tagged enum.  As a workaround, I removed the latter embedding its fields directly in the connector config, which actually seems cleaner as well.
> Fix serde issue with Delta input config.

- crates/dbsp/src/storage/backend/mod.rs
- crates/dbsp/src/storage/file/writer.rs
I think that this will make troubleshooting easier sometimes.
I'd like to add information about the operator in use, too, but it's harder to get that information.
> dbsp: Add worker thread index to file names.

- crates/adapters/src/controller/mod.rs
Without this, feeding just a few records to, say, the SecOps demo produces several hundred files on disk.  With this, no files are written.
Addresses https://github.com/feldera/feldera/issues/1712.
> dbsp: Fix excessive storage files using nonzero storage size threshold.

- CHANGELOG.md
- crates/adapters/src/server/mod.rs
- crates/adapters/src/transport/http/output.rs
- crates/pipeline_manager/src/api/http_io.rs
- openapi.json
The HTTP connector was designed for use in the web console where we want to listen to the output of the pipeline without blocking or slowing it down.  It therefore drops outputs on the floor if the client (or the network) are unabel to keep up.  Use cases where we rely on HTTP to receive correct and complete output require a different mode of operation where the connector waits for the client to receive all outputs and applies backpressure on the pipeline if the client cannot keep up.
We introduce the `backpressure` flag that enables this mode. This flag is passed as a parameter to the `/egress` endpoint: `/egress?backpressure=true`.
@abhizer
> Add backpressure mode to HTTP output connector.

- crates/dbsp/src/monitor/circuit_graph.rs
- crates/pipeline_manager/src/integration_test.rs
This tiny change improves the readability of circuit graphs generated by DBSP (which we use to debug and profile circuits).  Previously, there was no edge between the two halves of the Exchange operator.  As a result, multithreaded circuits ended up being partitioned into multiple fragments.
> Make profiles more readable.

- docs/sidebars.js
Will have a follow up PR for the website that'll build the docs.
> py: add Python SDK docs to the website sidebar

- Earthfile
- crates/adapters/src/integrated/delta_table/output.rs
- crates/adapters/src/integrated/delta_table/test.rs
- crates/pipeline-types/src/transport/delta_table.rs
- crates/pipeline_manager/src/api/mod.rs
- openapi.json
The Delta output connector defaulted to appending new data to an existing table if one exists at the target location.  This commit adds two additional modes:
- error_if_exists - fail if there exists a table at the target location.
- truncate - truncate all existing contents of the table before adding new updates to it.
@Karakatiza666 , can we include this new option to the webconsole PR for delta connectors. It's a drop-down list with three options: `append`/`truncate`/`error_if_exists`. The default is `append`.
> Delta out: `truncate` and `error_if_exists` modes.

- web-console/src/lib/components/input/BigNumberInput.tsx
> Fix obscure crash when displaying a number

- python/feldera/rest/client.py
Use `iter_lines` to read HTTP response line-by-line.  This way we don't need to worry about incomplete chunks.  The previous implementation also ran out of memory on large outputs.  I did not figure out what was going on exactly, but it used up 20GB of RAM while parsing a few thousand records.  This implementation does not seem to have that problem.
> [Python SDK] use iter_lines to read HTTP response.

- CHANGELOG.md
- crates/pipeline_manager/migrations/V15__program_compilation_profile_nullable.sql
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/config.rs
- crates/pipeline_manager/src/db/program.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/db_notifier.rs
- crates/pipeline_manager/src/integration_test.rs
- crates/pipeline_manager/src/pipeline_automata.rs
- openapi.json
- web-console/README.md
- web-console/openapi-fixes.patch
- web-console/package.json
- web-console/src/lib/components/layouts/analytics/editor.tsx
- web-console/src/lib/services/manager/core/OpenAPI.ts
- web-console/src/lib/services/manager/index.ts
- web-console/src/lib/services/manager/models/CompilationProfile.ts
- web-console/src/lib/services/manager/models/DeltaTableIngestMode.ts
- web-console/src/lib/services/manager/models/DeltaTableReaderConfig.ts
- web-console/src/lib/services/manager/models/ProgramConfig.ts
- web-console/src/lib/services/manager/models/TransportConfig.ts
- web-console/src/lib/services/manager/services/PipelinesService.ts
The program compilation profile is used if specified, and if not, the compiler default compilation profile is used. This removes the previous hint mechanism.
You can check it works by editing in a demo (for example, `demo/steady/demo.py`):
```python
response = requests.put(f"{api_url}/v0/programs/{program_name}", headers=headers, json={
"description": "",
"code": program_sql,
"profile": "optimized"
})
```
(EDIT: removed the surrounding `"program": { ...}` as it is now flattened)
... and then running it:
```
python3 demo.py --api-url http://localhost:8080 --target-rate-per-second 1
```
... you'll then see in the pipeline-manager log:
```
INFO [manager] Compiling Rust for program 00000000-0000-0000-0000-000000000000 with profile optimized
```
> pipeline-manager: program compilation profile with default

- .gitignore
This allows a developer to add a local `.cargo/config.toml` without it showing up in `git status` as uncommitted.
> gitignore: Add `.cargo/config.toml`.

- crates/dbsp/benches/fraud.rs
- crates/dbsp/examples/tutorial/tutorial5.rs
- crates/dbsp/examples/tutorial/tutorial6.rs
- crates/dbsp/examples/tutorial/tutorial8.rs
- crates/dbsp/src/operator/dynamic/time_series/rolling_aggregate.rs
- crates/dbsp/src/operator/time_series/rolling_aggregate.rs
- crates/dbsp/src/tutorial.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPAggregateOperatorBase.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMapOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPWindowAggregateOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/LowerCircuitVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPType.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeCode.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeOption.java
All rolling aggregate functions now have a uniform API: they take a Z-set indexed by timestamp and a closure that extracts partition id from the value.
> Unified signatures of rolling aggregate functions.

- python/feldera/rest/client.py
Unoptimized builds were introduced for use with the sandbox, so we can speed up compilation for severely rate limited demo pipelines, where performance is not needed.  In most other cases, optimized builds are a better default, and now that we can override this setting per-program, we can make sure that pipelines created via the Python SDK are optimized.  For now I hardwired the optimized mode.  It's easy enough to add an option to choose a different build profile if we have a use case for that.
> py: Enforce optimized build.

- python/feldera/_callback_runner.py
- python/tests/test_wireframes.py
The CallbackRunner, which runs in a separate thread now runs as a daemon. This means that the spawned thread will stop executing when the main thread ends.
Fixes: #1831 
> py: run spwaned listeners as daemons

- web-console/src/lib/components/streaming/import/InsertionTable.tsx
The default MUI behavior for "convenient" cell editing was forcing a string value on a strongly-typed numeric column
Fix https://github.com/feldera/feldera/issues/1795 : WebConsole error when adding rows: "e.toFixed is not a function"
> Disable default MUI behavior for editing the cell

- CHANGELOG.md
- python/feldera/sql_context.py
- python/tests/test_wireframes.py
Adds the function `wait_for_idle()` to the `SQLContext` class.
The goal of the function is to allow the user to wait for the pipeline to become idle (no change in input/processed records and they are equal) for a certain amount of time, thus an indication that the pipeline is done (though, not a guarantee). It should be followed up with checking the input and output records themselves whether they meet expectations.
It might be useful to add a `total_output_records` metric as well here in the future, indicating that the output records have been output to all sinks.
> py: function to wait for pipeline to become idle

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
Fixes #1842 
Now the JSON object returned will also contain a source code snippet if applicable, under the field "snippet":
```
{
"startLineNumber" : 1,
"startColumn" : 32,
"endLineNumber" : 1,
"endColumn" : 32,
"warning" : false,
"errorType" : "Error in SQL statement",
"message" : "Object 'T' not found",
"snippet" : "    1|CREATE VIEW V AS SELECT * FROM T\n                                     ^\n"
}
```
> [SQL] Add source code snippet to json error description

- crates/pipeline-types/src/format/json.rs
- crates/pipeline-types/src/serde_with_context/serde_config.rs
- openapi.json
- python/README.md
- python/feldera/_helpers.py
- python/feldera/output_handler.py
- python/feldera/rest/_httprequests.py
- python/feldera/rest/feldera_client.py
- python/feldera/sql_context.py
- python/tests/test_pipeline.py
- python/tests/test_wireframes.py
Fixes: #1840
Also does the following things:
* chunk dataframes into smaller groups of 1000 rows per request while ingesting data
* avoids adding empty dataframes to output buffer
* ignores the index while concatenating output dataframes
> py: properly serialize DataFrames with Timestamp columns

- Cargo.lock
- crates/dbsp/Cargo.toml
- crates/dbsp/src/storage/buffer_cache/cache.rs
I  ran the persistence demo a few more times with the per-thread-cache approach and runtime seems to vary enough so that I can say it probably doesn't differ much from the concurrent cache (where it takes ~341 seconds).
```
Running the training pipeline. Point your browser to http://localhost:8080/streaming/management/ to monitor the status of the pipeline.
Training time = 409.233
✘ gz@gz-desktop-pro  ~/workspace/dbsp/demo/project_demo10-FraudDetectionDeltaLake   per-thread-cache ±  python3 run.py
Running the training pipeline. Point your browser to http://localhost:8080/streaming/management/ to monitor the status of the pipeline.
Training time = 361.326
✘ gz@gz-desktop-pro  ~/workspace/dbsp/demo/project_demo10-FraudDetectionDeltaLake   per-thread-cache ±  python3 run.py
Running …
```
> Per-thread Storage cache.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPJoinFlatmapOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/FilterJoin.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPTupleExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPLiteral.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
Join followed by a filter will be implemented using join_flatmap.
I expect this will help a lot Q9 from nexmark.
> [SQL] Use join_flatmap when possible

- Earthfile
- benchmark/feldera-sql/run.py
- scripts/bench-publish.bash
- scripts/bench.bash
This pull request goes with another one in the benchmarks repository: https://github.com/feldera/benchmarks/pull/4
Changes in this PR:
- add one more statistic to the results of the Nexmark SQL test: peak memory usage. 
- add logging per-run metrics of Nexmark SQL tests to sql_nexmark_metrics.csv. These metrics are: test name, elapsed_seconds, rss_bytes, buffered_input_records, total_input_records, total_processed_records. There are also several disk metrics, for runs using disk storage: total_files_created, total_bytes_written, total_writes_success, buffer_cache_hit, and write_latency_histogram.
- add csv-metrics and metrics-interval args to feldera-sql/run.py to allow controlling metrics csv file location and how often metrics are recorded in …
> Log SQL metrics

- scripts/bench.bash
Rust nexmark tests are now run in separate cargo invocations so that memory statistics for each test can be more accurately measured.
> Run rust tests separately

- CHANGELOG.md
- crates/adapters/src/format/avro/serializer.rs
When serializing Avro data, the Rust type must generally match the Avro schema precisely.  One situation where we can relax this requirement is when serializing a non-optional field into an Avro union type.  This is important in practice, as we don't control the nullability of columns in views.
This commit should enable this behavior.  It introduces some additional performance overhead due to having to check the schema when serializing every field.
> Avro: Serialize non-nullable fields as nullable.

- docs/sql/grammar.md
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegresssionTests.java
> [SQL] Remove unsupported SQL construct (FILTER and OVER) from documentation

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/operators.rs
> [SQL] Prevent SQRT(negative value) in STDDEV due to unstable FP computations

- CHANGELOG.md
- docs/sidebars.js
- docs/sql/intro.mdx
- docs/sql/map.md
- docs/sql/types.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustFileWriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TypeCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPMapLiteral.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPVecLiteral.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeCode.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeMap.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ParserTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/MapTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/array.rs
MAP types have been on the wishlist for a long time.
They are also an important stepping stone for properly supporting JSON.
JSON objects are really `MAP<VARCHAR, VARIANT>` values.
> [SQL] Preliminary support for MAP types

- crates/dbsp/src/operator/dynamic/input_upsert.rs
The vec-based batches set keys, values, and weights to their default values when their builders accept tuples via `Builder::push` or `Builder::push_vals`, which take mutable references.  The code for `input_upsert` accumulates updates to keys in a `key_updates` vector, and then adds them to a builder via `extend`, which internally uses `Builder::push` and thus clears all the updates that were added to have weight 0.
Before this commit, that code didn't later clear the `key_updates` vector, which meant that anything added later was appended to a bunch of zeroed tuples.  This was benign because, the next time `key_updates` was used, it was first consolidated, which meant that all the zero-weight tuples were dropped.
This failed with the file-based batches, which don't have any special …
> dbsp: Fix hidden dependency on vec-based batches in input_upsert.

- crates/dbsp/src/storage/backend/io_uring_impl/mod.rs
- crates/dbsp/src/storage/file/writer.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/spine_async/merger.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/dbsp/src/trace/test/mod.rs
- crates/nexmark/benches/nexmark/main.rs
This means we work on multiple merges simultaneously. We can re-use the fuel approach to do that. But we need to make sure we can call the work-closure multiple times to continue merging. This involved being able to share Batch::Merger across threads too (if there is a better way instead of having the Send+Sync bound there I'd be happy to avoid that).
> Avoid head-of-line blocking in async spine.

- crates/dbsp/src/trace/spine_async/merger.rs
`BatchMerger::run` assumed that when all fuel is used up by the work function, the remaining value is exactly 0.  This may not be the case for an imperfect merger that uses more fuel than available and returns a negative value.  This may cause partially merged batches to be removed from the queue without sending an acknowledgement message.
> Handle negative fuel in merger.rs.

- Earthfile
- crates/pipeline_manager/src/compiler.rs
We run the pipeline manager inside docker when running integration tests
in CI.  As a result, we do not get to see its logs, which makes it hard
to debug CI errors.  This commit adds a `docker logs` command to the CI
job to output pipeline manager logs on error.
> Integration test logging

- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/circuit/runtime.rs
- crates/dbsp/src/storage/backend/metrics.rs
- crates/dbsp/src/storage/backend/mod.rs
- crates/dbsp/src/trace/layers/layer.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/spine_async/merger.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/dbsp/src/trace/spine_fueled.rs
The [channel code in std is identical to crossbeam](https://github.com/rust-lang/rust/pull/93563) (taken from on crossbeam-channel) except that https://github.com/rust-lang/rust/issues/107466 is fixed in std but not in crossbeam-channel.
I originally reworked this because the bug in 80ff3ff made me desperate to suspect something is wrong with the channel. While it didn't turn out to be an issue with the channels it's easier to depend on std code instead of a library.
> Switch from crossbeam-channel to std::sync::mpsc::channel.

- web-console/src/app/(spa)/(root)/(authenticated)/(app)/services/list/page.tsx
- web-console/src/app/(spa)/(root)/(authenticated)/(app)/streaming/builder/page.tsx
- web-console/src/lib/components/analytics/TableSqlPrograms.tsx
- web-console/src/lib/components/connectors/dialogs/DebeziumInputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/DeltaLakeInputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/DeltaLakeOutputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/KafkaInputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/KafkaOutputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/SnowflakeOutputConnector.tsx
- web-console/src/lib/components/connectors/dialogs/UrlConnector.tsx
- web-console/src/lib/components/services/dialogs/KafkaService.tsx
- web-console/src/lib/components/streaming/builder/NoSchemaDialog.tsx
- web-console/src/lib/components/streaming/management/RevisionStatus.tsx
- web-console/src/lib/compositions/streaming/inspection/useQuantiles.ts
- web-console/src/lib/functions/connectors/outputBuffer.ts
- web-console/src/lib/services/manager/core/request.ts
- web-console/src/lib/services/pipelineManagerQuery.ts
Is this a user-visible change (yes/no): no (intra-sprint regressions and improvements)
Fix https://github.com/feldera/feldera/issues/1931 : Output buffer attributes required even when the output buffer is disabled
Fix https://github.com/feldera/feldera/issues/1932 : Output buffer size gets serialized as string instead of int
Fix https://github.com/feldera/feldera/issues/1933 : Kafka input connector creation dialog: CREATE button doesn't work
Fix https://github.com/feldera/feldera/issues/1936 : UI truncates fields even if there is room to display them entirely
Fix https://github.com/feldera/feldera/issues/1938 : "Application error" during pipeline creation
Add output buffer config validation to Snowflake Output
Add an error popup when validation error during connector creation cannot be …
> Fix UI regressions

- crates/adapters/src/format/avro/serializer.rs
- crates/adapters/src/format/json/schema.rs
- crates/adapters/src/format/parquet/mod.rs
- crates/adapters/src/test/data.rs
- crates/pipeline-types/src/program_schema.rs
- crates/pipeline-types/src/serde_with_context/deserialize.rs
- crates/pipeline-types/src/serde_with_context/serialize.rs
- crates/pipeline_manager/src/integration_test.rs
- openapi.json
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
**Outstanding tasks/questions:**
**Error in program:**
```
Compiling project01904ed3-b496-76d3-8b29-af9a246e9671 v0.1.0 (/home/<user>/.feldera/cargo_workspace/project01904ed3-b496-76d3-8b29-af9a246e9671)
error[E0277]: the trait bound `BTreeMap<i32, i32>: DeserializeWithContext<'_, SqlSerdeConfig>` is not satisfied
--> project01904ed3-b496-76d3-8b29-af9a246e9671/src/main.rs:116:9
|
116 | /         deserialize_table_record!(struct_0["t", 1] {
117 | |             (field0, "map", false, Option<BTreeMap<i32, i32>>, Some(None))
118 | |         });
| |__________^ the trait `DeserializeWithContext<'_, SqlSerdeConfig>` is not implemented for `BTreeMap<i32, i32>`, which is required by `DeserializationContext<'_, SqlSerdeConfig, std::option::Option<BTreeMap<i32, i32>>>: DeserializeSeed<'de>`
|
= …
```
> pipeline-manager: SQL MAP type

- benchmark/feldera-sql/README.md
- benchmark/feldera-sql/run.py
- benchmark/run-nexmark.sh
- scripts/bench.bash
Changes to the end-to-end SQL benchmark run script:
- Argument to supply additional Kafka options such as for SSL and SASL configuration
- Argument to supply API key which is included as an HTTP header with each request
- Specify optimized compilation profile
- Comments for configuring pipeline resources
> benchmark: API key and Kafka option arguments

- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/integration_test.rs
This commit reverts our earlier decision to force views to behave as sets.
DBSP outputs can have non-unit weights.  As a result, a consumer that tracks the output of a circuit must generally keep track of multiplicities of records.  For example, two inserts followed by a delete leave the record in the Z-set with weight 1.  It turns out that many of the destinations we write to either do not support this semantics (or make it expensive to implement) and expect inputs to be distinct collections.
To support such destinations without surprising users with unexpected behavior, we used to automatically apply the `distinct` operator to all non-local views (by passing a --outputsAreSets flag to the compiler).
This no longer looks like a good choice for several reasons:
- Memory(storage) and CPU …
> Do not automatically distinct ouputs.

- CHANGELOG.md
- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/server/prometheus.rs
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/circuit/metrics.rs
- crates/dbsp/src/circuit/mod.rs
- crates/dbsp/src/circuit/runtime.rs
- crates/dbsp/src/storage/backend/io_uring_impl/mod.rs
- crates/dbsp/src/storage/backend/memory_impl.rs
- crates/dbsp/src/storage/backend/mod.rs
- crates/dbsp/src/storage/backend/posixio_impl.rs
- crates/dbsp/src/storage/bin/bench.rs
- crates/dbsp/src/storage/buffer_cache/cache.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/dbsp/src/trace/spine_fueled.rs
- crates/nexmark/benches/nexmark/main.rs
- crates/pipeline-types/src/config.rs
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/bin/pipeline-manager.rs
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/db/test.rs
- crates/pipeline_manager/src/metrics.rs
- openapi.json
- Use metrics-prometheus-exporter t inject dbsp
metrics into the adapter metrics endpoint.
- Access metrics of all running pipelines from
pipeline-manager /metrics endpoint
- Move dbsp metrics description from storage to circuit
module since they are global anyways.
- Annotate all metrics from a pipeline with
the name of the pipeline.
- Remove support for the tcp-metrics-exporter since
I expect we just use prometheus/grafana from now on
- Add a dummy metrics to measure steps since most
dbsp metrics we have right now only kick in when we use
storage code which makes it so no metrics appear
for a long time
> Expose dbsp metrics in pipeline metrics endpoint.

- crates/adapters/src/integrated/delta_table/input.rs
- crates/adapters/src/integrated/delta_table/output.rs
- crates/adapters/src/transport/s3/mod.rs
- crates/dbsp/src/circuit/mod.rs
- crates/dbsp/src/circuit/tokio.rs
- crates/dbsp/src/operator/communication/exchange.rs
> Use a single tokio runtime instead of `n`.

- docs/enterprise/kubernetes-guides/eks/cluster.md
It occurred that the storage class was not set to default, as such the PVC of the compiler server and db could not be allocated. This PR adds a note in the EKS cluster instructions to check `gp2` EBS storage class is set to default and instructions to change it if not.
> docs: eks cluster storage class check

- crates/adapters/src/circuit_handle.rs
- crates/adapters/src/controller/error.rs
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/server/mod.rs
- crates/dbsp/Cargo.toml
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/monitor/visual_graph.rs
- crates/dbsp/src/profile/mod.rs
- crates/pipeline_manager/src/api/pipeline.rs
- openapi.json
- web-console/src/lib/services/manager/services/PipelinesService.ts
With this change, `/dump_profile` becomes a way to download a profile of a running circuit. Previously, it just wrote the profile to the file system and left the user to go find it.
> Make profiles downloadable via API

- Earthfile
- benchmark/flink/run-flink.sh
- benchmark/flink/setup-flink.sh
Adds the flink-benchmark Earthly task which runs flink benchmarks and saves the result as flink_results.csv.
The command works as follows:
- installs a newer version of docker compose since the default one doesn't work
- installs maven, which is necessary for flink
- runs flink in docker and pipes the results to run-nexmark.sh, which parses the results into csv format
> Add script to run flink on CI

- .github/workflows/benchmark-command.yml
- .github/workflows/flink-benchmark.yml
- Earthfile
- benchmark/flink/publish-flink.sh
- benchmark/flink/refresh-flink-benchmark.sh
- scripts/bench-publish.bash
- scripts/clone-gh-pages.bash
This PR automates Flink benchmarks to be run every 30 days. Flink results are now stored in the benchmarks repo.
A new GitHub actions script, "Refresh Flink Benchmark", was added, and executes in the middle of what used to be bench-publish, between what are now 2 phases - clone-gh-pages, which clones the benchmarks repo, and the rest of bench-publish. This new script checks the benchmarks repo in a new flink folder for last_flink_run, which stores the last time flink was run, and if the last run is over 30 days ago, runs flink benchmarks and stores their results in flink_results.csv in the same folder. These results are then uploaded to the benchmarks repo.
> Automate Flink testing in CI

- Earthfile
Hopefully this will shrink the CI logs produced by maven
> Disable coloring in maven builds

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/dbsp/Cargo.toml
If not only the adapters metrics show up in the metrics endpoint. The reason is that rust can include with multiple crate version at the same time and turns out metrics from one version are not read from another version if they don't match.
> Make sure dbsp and adapters metrics verison match.

- docs/sql/datetime.md
- docs/sql/grammar.md
- python/feldera/sql_context.py
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/DBSPPartialCircuit.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/ProgramMetadata.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TableContents.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
With this PR the user no longer has to declare the 'NOW' table, it is synthesized internally by the compiler if the now() function is ever invoked in the program. (In fact, the table is always inserted, but it's removed if the function is never used.)
Fixes #2037 #2011
> [SQL] Have the compiler synthesize the 'NOW' table

- crates/adapters/src/transport/url.rs
- crates/pipeline-types/src/transport/url.rs
- openapi.json
- web-console/src/lib/services/manager/models/UrlInputConfig.ts
Until now, the `url` adapter has disconnected from the server immediately if the input adapter was paused, and then reconnected later if it was restarted.  If the pause is due to a backlog filling up, this is likely only a short pause, and incurs the cost of churning the connection to the server, for no gain given that the connection will be resumed later.
This commit adds a delay before disconnecting, solving the problem.
> dbsp_adapters: Wait a bit before disconnecting on pause in `url` adapter.

- crates/dbsp/src/monitor/circuit_graph.rs
- crates/dbsp/src/operator/dynamic/trace.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/ord/fallback/indexed_wset.rs
- crates/dbsp/src/trace/ord/fallback/key_batch.rs
- crates/dbsp/src/trace/ord/fallback/val_batch.rs
- crates/dbsp/src/trace/ord/fallback/wset.rs
- crates/dbsp/src/trace/ord/file/indexed_wset_batch.rs
- crates/dbsp/src/trace/ord/file/key_batch.rs
- crates/dbsp/src/trace/ord/file/val_batch.rs
- crates/dbsp/src/trace/ord/file/wset_batch.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/dbsp/src/trace/spine_async/tests.rs
@gz, this modifies the async spine code, mostly to simplify it a bit, but also to add some more profiling output to make it easier to understand what's happening storage-wise.
@ryzhyk, I changed the profiling output a bit to shorten paths because that makes the boxes a lot smaller and therefore it's easier to read the profiles. Would like your OK on that.
> Improve profiling output to make storage performance easier to understand

- Cargo.lock
- crates/nexmark/Cargo.toml
> nexmark: Use same `metrics` version as the rest of the crates.

- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/circuit/operator_traits.rs
- crates/dbsp/src/operator/dynamic/time_series/window.rs
- crates/dbsp/src/operator/dynamic/trace.rs
- crates/dbsp/src/operator/z1.rs
- crates/dbsp/src/storage/backend/io_uring_impl/mod.rs
- crates/dbsp/src/storage/buffer_cache/cache.rs
- crates/dbsp/src/storage/file/reader.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/ord/fallback/indexed_wset.rs
- crates/dbsp/src/trace/ord/fallback/key_batch.rs
- crates/dbsp/src/trace/ord/fallback/utils.rs
- crates/dbsp/src/trace/ord/fallback/val_batch.rs
- crates/dbsp/src/trace/ord/fallback/wset.rs
- crates/dbsp/src/trace/ord/file/indexed_wset_batch.rs
- crates/dbsp/src/trace/ord/file/key_batch.rs
- crates/dbsp/src/trace/ord/file/val_batch.rs
- crates/dbsp/src/trace/ord/file/wset_batch.rs
- crates/dbsp/src/trace/ord/vec/indexed_wset_batch.rs
- crates/dbsp/src/trace/ord/vec/key_batch.rs
- crates/dbsp/src/trace/ord/vec/val_batch.rs
- crates/dbsp/src/trace/ord/vec/wset_batch.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/dbsp/src/trace/spine_fueled.rs
- crates/dbsp/src/trace/test/test_batch.rs
On my system, this series reduces the runtime of the HopWorks demo with 10M events, with storage enabled, from >600s to 35s. The final commit is the only one I'm unsure about, since it drops several metrics (to save 71% on runtime!), but the rest of the commits are ones that make sense to me in production.
> Storage optimizations

- CHANGELOG.md
- web-console/src/lib/functions/pipelineMetrics.ts
This reverts commit 8a38423d006e526a424ca97434518aed382ffb85.
> Revert "WebConsole: Fix pipeline relation metrics not accumulated when there are multiple connectors per relation"

- scripts/bench.bash
This PR changes the benchmark of SQL in CI to use 100M events, just like the Rust benchmark.
> Benchmark with 100M events

- README.md
Change documentation links in the project root README.
> [README] fix broken documentation links

- crates/dbsp/src/dynamic/vec.rs
- crates/dbsp/src/trace/layers/layer.rs
- crates/dbsp/src/trace/layers/leaf.rs
`LeanVec::reserve` allocates more capacity than requested.  The vector-based merger used this function to allocate the maximum capacity it could need, so it was always allocating 1.5x to 2x the maximum it needed. This fixes the problem by adding `LeanVec::reserve_exact` and using it for initial allocations.
> dbsp: Don't reserve excess capacity for vector merge results.

- crates/pipeline-types/src/config.rs
- openapi.json
The `cpu_profiler` flag was set to `false` by default.  The reasoning behind this was that enabling the profiler can introduce some overhead; however I don't think this overhead is significant (or measurable) in practice.  It is valuable to make the CPU profile available on all pipelines, so we change the default to `true`.  We may eliminate the flag altogether in the future.
> Enable CPU profiler by default.

- benchmark/feldera-sql/benchmarks/nexmark/queries/q12.sql
- benchmark/feldera-sql/benchmarks/nexmark/queries/q14.sql
- benchmark/feldera-sql/benchmarks/nexmark/queries/q22.sql
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/ExternalFunction.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresTimeTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
- sql-to-dbsp-compiler/lib/sqllib/src/array.rs
- sql-to-dbsp-compiler/lib/sqllib/src/casts.rs
Turns out you can write some of the UDFs required in SQL, so I implemented `count_char` and `split_index`.
The remaining UDF is about regular expressions, so it cannot be done efficiently in SQL, we need a real UDF.
I also hopefully implemented q6 correctly using ARG_MAX instead of TOPK.
> [SQL] Enable 3 more Nexmark queries using SQL user-defined functions

- Earthfile
Make Earthly's cache global again. I'm seeing some commits in their repo that might address the cache contamination problem.
> build: bring back Earthly caching

- deploy/Dockerfile
Testing the product-availability demo I see improvements in incremental compilations of 20-40%. This includes recompiling the full program with just whitespace edits (30s -> 23s) and recompilation of a program with a single table from 14s -> 8s.
> docker: use mold linker for compiler-server

- web-console/src/routes/(authenticated)/+page.svelte
This is an attempt to reduce visual clutter in the examples page from the repetitive buttons. We'll need a redesign of this page in any case, I'm not sure if cards in a grid are the best UI for this.
@Karakatiza666 @gz I don't know how to change the font color of the titles to match the theme, so if you could tweak that that'd be great.
Before:
After:
> web-console: simplify the examples page

- Earthfile
This reverts commit 86d4af66315e10eb274ceeef093940645d755ecf.
> Revert "build: bring back Earthly caching"

- crates/pipeline-types/src/program_schema.rs
- crates/pipeline_manager/src/db/types/program.rs
- openapi.json
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java
> pipeline-manager: provide position in ConnectorGenerationError

- benchmark/feldera-sql/benchmarks/nexmark/queries/q16.sql
- benchmark/feldera-sql/benchmarks/nexmark/queries/q5.sql
- docs/sql/table.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPSourceMultisetOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/LowerCircuitVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/AppendOnly.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/FilterJoinVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/KeyPropagation.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/MonotoneAnalyzer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeMaps.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/CommonJoinExpansion.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/JoinExpansion.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/JoinFilterMapExpansion.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/annotation/NoIntegrator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPUnsignedWrapExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPVecLiteral.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBaseType.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/NullableFunction.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/NullablePredicate.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpcDsTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/SqlIoTest.java
- sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
These optimizations are applicable only for append-only relations which have foreign key information available.
These optimizations do several things:
- they do not use integrators on some sides of a join
- they can push monotonicity information past some joins
To fully take advantage of the first optimization, DBSP will have to provide a join operator where we can indicate that some integrators are not necessary. The compiler assumes that the integrators won't be there, and thus won't GC these integrators.
> [SQL] Optimize programs based on foreign-key joins

- README.md
The demo is now outdated, so it's better to point the user to the up-to-date tutorial.
> Point to tutorial instead of demo

- crates/dbsp/src/dynamic/lean_vec.rs
- crates/dbsp/src/dynamic/vec.rs
- crates/dbsp/src/trace/layers/layer.rs
- crates/dbsp/src/trace/layers/leaf.rs
> dbsp: Reduce memory use for merges with output smaller than the inputs.

- benchmark/run-nexmark.sh
Running output through `tee` as this does makes it look to Python that its stdout is non-interactive, so by default it buffers up a few kilobytes of output before printing it, which makes it hard to see a run's progress in anything like real time.  This fixes the problem.
It would be better to do this in `benchmark/feldera-sql/run.py`, making it set its stdout to always line-buffered, like one could do with a call to `setvbuf` in C, but I can't figure out how to do that in Python.
> benchmark: Make output from Feldera SQL runs appear without buffering.

- crates/dbsp/src/operator/dynamic/time_series/radix_tree/mod.rs
- crates/dbsp/src/operator/dynamic/time_series/radix_tree/prefix.rs
- crates/dbsp/src/operator/dynamic/time_series/radix_tree/treenode.rs
This commit reduces the memory overhead of radix trees. Each radix tree node consists of RADIX entries, each storing a child pointer and the pre-computed value of the aggregate.  The tree is supposed to be self-adjusting, merging nodes with a single child into the parent node; however it can still waste a lot of memory when there are many nodes with >=2 children.  This is especially bad when using the tree to compute multiple rolling aggregates where each entry stores multiple aggregate values.  In one example I saw the tree using 10x the memory of the input collection.
The simplest solution implemented here is to reduce the arity of the tree to a smaller power of two (8, 4, or 2).  I tried 4 and 2.  In both cases I didn't see significant impact on performance (but haven't done systematic …
> [DBSP]: Change radix value for radix trees to 2.

- docs/sql/aggregates.md
- docs/sql/table.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
> [SQL] Restrict tumbling window to 'short' SQL intervals

- crates/dbsp/src/num_entries.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPApply2Operator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPApplyOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPControlledFilterOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPDelayOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainKeysOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainValuesOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/SimplifyWaterline.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeMaps.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/annotation/Waterline.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/IsBoundedType.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBool.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDate.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDecimal.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDouble.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeISize.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeInteger.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMillisInterval.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMonthsInterval.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeReal.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeTime.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeTimestamp.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeUSize.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeTypedBox.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
Fixes #2228 
The way this works is that the circuits that evaluate the waterline for the SQL operators have the following structure:
```rust
fn (input: &(boolean, T)) -> S {
if input.0 { // first step
(input.0, min_value)
} else {
(input.0, actual_waterline(input.1))
}
}
```
input.0 is "true" for the first step, and "false" subsequently (achieved using a delay operator).
Upon reflection, even this fix isn't 100% safe, because it is conceivable that the conservative analysis of the compiler could deduce some bounds for waterlines that are outside the legal range of a datatype. For example, consider the case of dates BC - given early enough dates and a large enough LATENESS the minimum bound may be BC, which we don't support - the …
> [SQL] For the first step use the minimum possible waterline everywhere

- Cargo.lock
- crates/adapters/src/server/mod.rs
- crates/pipeline-types/Cargo.toml
- crates/pipeline-types/src/error.rs
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/api/api_key.rs
- crates/pipeline_manager/src/api/config_api.rs
- crates/pipeline_manager/src/api/mod.rs
- crates/pipeline_manager/src/api/pipeline.rs
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/db/error.rs
- crates/pipeline_manager/src/error.rs
- crates/pipeline_manager/src/pipeline_automata.rs
- demo/simple-count/run.py
**Try it out**
```bash
cargo run --package=pipeline-manager --features pg-embed --bin pipeline-manager -- --dev-mode
RUST_BACKTRACE=1 RUST_LOG=info,tokio_postgres=info cargo run --package=pipeline-manager --features pg-embed --bin pipeline-manager -- --dev-mode
RUST_BACKTRACE=1 RUST_LOG=debug,tokio_postgres=debug cargo run --package=pipeline-manager --features pg-embed --bin pipeline-manager -- --dev-mode
```
**Logging policy notes and changes**
Endpoints:
- Creation, update and deletion of pipelines and API keys are logged at info level
- Pipeline actions are logged at info level
Actix middleware:
- Requests are logged at debug level
- Success (200-299) and Not Modified (304) responses are logged at debug level
- Client responses (400-499) are logged at info level
- Other responses are …
> pipeline-manager: less verbose logging at lower level

- CONTRIBUTING.md
- crates/adapters/src/server/mod.rs
- crates/pipeline_manager/src/api/mod.rs
- crates/pipeline_manager/src/compiler.rs
- crates/pipeline_manager/src/db/storage_postgres.rs
- crates/pipeline_manager/src/logging.rs
- By default, the Feldera crates have info log level, other crates have warn log level
- API request log level is reduced from debug to trace
- Migrations log level is reduced from info to debug if no migrations were applied
- Compiler reconciliation log level is reduced from info to debug
- Instructions on how to configure log levels is added to CONTRIBUTING
> pipeline-manager: info log level for feldera crates and warn for others

- Cargo.lock
- crates/adapters/src/transport/kafka/nonft/input.rs
I noticed that setting `max_queue_size` to a small values (10000 or less in my use case) significantly reduced Kafka throughput.  This was due to the pause/unpause operation being very expensive.  This was in turn due to two factors:
* The POLL_TIMEOUT constant being too high (100ms), bounded the pause/unpause latency.
* Pausing the Kafka connector involves pausing all its partitions, which is an expensive operation as it flushes rdkafka's internal buffers, potentially dropping thousands of messages. Not pausing it is not possible in the current design, as rdkafka requires the consumer to keep polling to make sure that control traffic gets processed, so we must poll but without receiving any messages.
We solve the second problem by waiting for three seconds befor pausing the connector. …
> [adapters] Speed up pausing/unpausing Kafka.

- benchmark/feldera-sql/run.py
This was inadvertently introduced in commit 268115b8d3a9 ("dbsp_adapters: Add `nexmark` connector and use in benchmarks.").  It broke running the tiktok benchmark.
> benchmark: Fix bug in feldera-sql runner for non-Nexmark benchmarks.

- CONTRIBUTING.md
- Earthfile
- README.md
- deploy/Dockerfile
- docs/contributors/dev-flow.md
- scripts/start_manager.sh
- sql-to-dbsp-compiler/README.md
- sql-to-dbsp-compiler/SQL-compiler/pom.xml
- sql-to-dbsp-compiler/build.sh
- sql-to-dbsp-compiler/run-tests.sh
I am not sure whether I got all the necessary changes.
Currently the script builds with the released version of Calcite by default.
If we want to merge the asof branch we probably need to switch the default to be the unreleased version..
> Script to build compiler with released/unreleased Calcite

- docs/sql/grammar.md
- docs/sql/streaming.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/config.fmpp
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/includes/ddl.ftl
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/ViewMetadata.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/parser/SqlCreateView.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CalciteTableDescription.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateTableStatement.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateViewStatement.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ParserTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpchTest.java
This also adds some Statistics for the Calcite optimizer, in the hope they would help with choosing good query plans. (So far they don't). Added one such statistic, which can be provided for a table using a property:
```
CREATE TABLE T( ... )
WITH (
'expected_size' = 1000000
);
```
> [SQL] Give warnings about the 'materialized' property for views

- benchmark/feldera-sql/benchmarks/tiktok/generate.bash
Otherwise, if `MAX_EVENTS` was not provided, it failed with a confusing error message.
Thanks to Matei Budiu for reporting this.
> benchmark: Make tiktok generation script use default `MAX_EVENTS`.

- scripts/bench.bash
This used to be implicit because the number of events came from the number of events in the Kafka topic, but now that the events are internally generated it needs to be passed in.
Thanks to Mihai for reporting the problem.
> scripts: Pass --events to Feldera SQL benchmark.

- benchmark/run-nexmark.sh
This PR relabels cpu_seconds in flink to cpu_msecs which is what it actually is.
> Change cpu_seconds to cpu_msecs

- benchmark/feldera-sql/benchmarks/nexmark/queries/q13.sql
- benchmark/feldera-sql/benchmarks/nexmark/table.sql
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
This PR cannot be merged until we make a few other changes:
- the nexmark connector needs to populate the newly introduced `side_input` table
- the Calcite PR https://github.com/apache/calcite/pull/3924 is merged
> Enable query q13 in nexmark

- crates/adapters/src/transport/mod.rs
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/operator/dynamic/time_series/rolling_aggregate.rs
- crates/dbsp/src/operator/dynamic/time_series/window.rs
- crates/dbsp/src/operator/time_series/window.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/typed_batch.rs
- crates/nexmark/src/queries/q5.rs
- crates/nexmark/src/queries/q7.rs
- crates/nexmark/src/queries/q8.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPWindowOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
This cannot be merged until the compiler has been adjusted to use the new API.
The `window` operator used to treat the key range as closed on the left,
open on the right: [start..end).
This commit generalizes the operator to support any combinations of
open/closed intervals.
> Generalize `window` to support open/closed ranges.

- Cargo.lock
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/bin/pipeline-manager.rs
- crates/pipeline_manager/src/lib.rs
The rustls dependency, which pipeline manager now inherits from the `metrics-exporter-prometheus` crate, requires setting a default crypto provider for the process. The pipeline manager panics on startup without this.
> Set default crypto provider.

- python/docs/examples.rst
- python/docs/index.rst
- python/docs/pandas.rst
- python/feldera/_callback_runner.py
- python/feldera/_helpers.py
- python/tests/test_pipeline_builder.py
When receiving data from feldera and creating a Pandas dataframe, this commit considers the SQL schema of the data, and then uses appropriate pandas types for the data columns.
Fixes: #2142
> py: convert SQL types to proper pandas type

- benchmark/feldera-sql/benchmarks/tpc-h/disabled-queries/q21.sql
- benchmark/feldera-sql/benchmarks/tpc-h/generate.bash
- benchmark/feldera-sql/benchmarks/tpc-h/generate.py
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q1.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q10.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q11.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q12.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q13.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q14.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q15.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q16.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q17.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q18.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q19.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q2.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q20.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q22.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q3.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q4.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q5.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q6.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q7.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q8.sql
- benchmark/feldera-sql/benchmarks/tpc-h/queries/q9.sql
- benchmark/feldera-sql/benchmarks/tpc-h/table.sql
This PR adds the TPC-H benchmark to the suite. Two datasets are included, medium and large, and large is tested by default. You can change the dataset used by editing generate.py.
> Added TPC-H benchmark suite

- CHANGELOG.md
- Cargo.lock
- crates/pipeline_manager/Cargo.toml
- crates/pipeline_manager/src/db/error.rs
- crates/pipeline_manager/src/db/types/common.rs
- crates/pipeline_manager/src/integration_test.rs
- demo/project_demo08-DebeziumJDBC/run.py
Name must now, besides being non-empty, also be at most 100 characters long and contain only characters which are lowercase (a-z), uppercase (A-Z), numbers (0-9), underscores (_) or hyphens (-).
This naming restriction applies to:
- Pipeline name
- API key name
- Connector name
> pipeline-manager: restrict maximum length and pattern of names

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/transport/kafka/ft/test.rs
- crates/dbsp/src/circuit/runtime.rs
- crates/pipeline-types/src/config.rs
- crates/pipeline_manager/src/api/examples.rs
- crates/pipeline_manager/src/db/test.rs
- docs/sql/datetime.md
- openapi.json
- python/feldera/runtime_config.py
- scripts/start_manager.sh
Adds a pipeline configuration parameter that forces the pipeline to
perform a step periodically even in the absence of an external input.
This allows the value of `NOW()` to change, triggering any queries that
depend on it to incrementally update their output.
The default value of the timeout is 100ms.  With this feature, the
following example works.  It populates the input table with 100K
records, starting with the current time (expressed in ms since epoch),
spaced at 100ms intervals.  The output view contains all input records
whose timestamp is in the future.  Initially the view contains all
input records.  You will then see 1 record removed from the view every
100ms as the clock moves forward
```sql
create table test (
id bigint,
ts timestamp
) WITH (
'connectors' = '[{
"transport":{ …
```
> Update real-time clock periodically

- web-console/src/app.css
- web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte
- web-console/src/lib/components/pipelines/editor/ChangeStream.svelte
- web-console/src/lib/components/pipelines/editor/InteractionsPanel.svelte
- web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte
- web-console/src/lib/components/pipelines/editor/TabPerformance.svelte
- web-console/src/lib/components/pipelines/editor/TabPipelineErrors.svelte
- web-console/src/lib/functions/pipelines/changeStream.ts
- web-console/src/lib/functions/pipelines/status.ts
Improve look and padding around split pane resizers
Set a limit of 10 MiB which fits a couple batches of JSON from pipeline with a high throughput. Easily configurable hardcoded value.
> Add option to configure circular buffer threshold when parsing Change Stream 

- Cargo.lock
- crates/adapters/src/catalog.rs
- crates/adapters/src/format/avro/input.rs
- crates/adapters/src/format/avro/mod.rs
- crates/adapters/src/format/avro/output.rs
- crates/adapters/src/format/avro/schema.rs
- crates/adapters/src/format/avro/serializer.rs
- crates/adapters/src/format/avro/test.rs
- crates/adapters/src/format/mod.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/adapters/src/test/data.rs
- crates/adapters/src/test/mock_dezset.rs
- crates/dbsp/src/operator/input.rs
- crates/feldera-types/src/format/avro.rs
- demo/project_demo13-DebeziumPostgres/project.sql
- demo/project_demo13-DebeziumPostgres/run.py
Add support for parsing Avro input streams.  We currently support two Avro-based message formats:
- Raw format that carries table records without any additional metadata. Can only be used to express inserts and upserts, but not deletes.
- Debezium Avro message format.
In both cases, message schema can be defined as part of connector config or downloaded from a schema registry if one is configured.
By default the connector supports Confluent Avro messages that carry schema id in the header.  There is a config option to ingest raw Avro messages without the header (this format is used for instance by Hopsworks).
Temporary limitations (to be addressed in an upcoming revision):
- The connector doesn't yet support decimal types
- Only supports timestamps are expressed in microseconds (Avro …
> [adapters] Avro input format support.

- crates/dbsp/src/profile/mod.rs
This is very unpleasant, because my editor automatically replaces tabs with spaces in rust programs, so it's easy to break this.
> The Makefile embedded in the profile rust program needs tabs

- web-console/src/lib/components/pipelines/editor/ChangeStream.svelte
- web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte
- web-console/src/lib/services/pipelineManager.ts
- web-console/src/routes/+layout.ts
You can click on any (single) row in Change Stream and copy the row in the ingress JSON insert_delete format. For now only one row at a time can be copied.
You can paste rows by Ctrl+V or otherwise after clicking anywhere within Change Stream tab. Pasted row
```
{"insert":{"num":42},"relationName":"numbers"}
```
or array of rows
```
[
{"delete":{"num":42},"relationName":"numbers"},
{"insert":{"num":27},"relationName":"numbers"}
]
```
will be sent via HTTP ingress with flag `force`, so the change can be seen immediately even if the pipeline is PAUSED (and you checked the checkbox to follow the corresponding table).
You can insert records for different tables in the same operation. In this scenario all changes for each table will be sent in a single batch, preserving ordering of changes …
> Enable ingesting insert_delete changes by copy-paste in Change Stream

- Cargo.lock
- crates/fda/Cargo.toml
- crates/fda/build.rs
- crates/fda/src/cli.rs
- crates/fda/src/main.rs
- crates/fda/src/shell.rs
- crates/pipeline-manager/src/api/pipeline.rs
- crates/pipeline-manager/src/metrics.rs
- crates/pipeline-manager/src/pipeline_automata.rs
- crates/pipeline-manager/src/runner.rs
Increase timeouts generally, but especially choose larger values for ad-hoc SQL and to get the circuit profile as they can be long running.
> Increase and make HTTP timeouts more specific.

- crates/adapters/src/transport/kafka/ft/test.rs
The fault-tolerant Kafka connector has some stability issues due to rdkafka bugs. We plan to re-work the connector. In the meantime, we disable FT Kafka tests to avoid CI failures.
> [adapters] Disable FT Kafka connector tests.

- web-console/src/app.css
- web-console/src/lib/components/MonacoEditor.svelte
- web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte
- web-console/src/lib/components/layout/pipelines/PipelineEditorStatusBar.svelte
- web-console/src/lib/components/layout/pipelines/PipelineThroughputGraph.svelte
- web-console/src/lib/components/pipelines/editor/CodeEditor.svelte
- web-console/src/lib/components/pipelines/editor/InteractionsPanel.svelte
- web-console/src/lib/components/pipelines/editor/ProgramStatus.svelte
- web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte
- web-console/src/lib/components/pipelines/editor/TabPerformance.svelte
- web-console/src/lib/components/pipelines/list/Actions.svelte
- web-console/src/lib/compositions/decoupledState.svelte.ts
- web-console/src/lib/services/pipelineManager.ts
- web-console/src/routes/(authenticated)/(pipelines)/+layout.svelte
- web-console/src/routes/(authenticated)/(pipelines)/pipelines/[pipelineName]/+page.ts
- web-console/src/routes/(authenticated)/+layout.svelte
The goal of the PR is to introduce the UX of file tabs to Pipeline Edit page. While viewing the pipeline user can switch between multiple code tabs that represent different fields of pipeline configuration.
With initial UDF implementation the file tabs will be: `program.sql`, `udf.rs` and `Cargo.toml`.
Also: Improved Performance Tab tables, moved draggable horizontal divider to the border of code editor box, and other minor improvements.
Fix https://github.com/feldera/feldera/issues/2397 : Long table and view names obstruct metrics in performance tab
> Prepare for UDF UI: add file tabs to Pipeline Edit view

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/format/avro/input.rs
- crates/adapters/src/format/avro/output.rs
- crates/adapters/src/format/avro/schema.rs
- crates/adapters/src/format/avro/serializer.rs
- crates/adapters/src/format/avro/test.rs
- crates/adapters/src/format/csv.rs
- crates/adapters/src/format/json/output.rs
- crates/adapters/src/format/mod.rs
- crates/adapters/src/format/parquet/mod.rs
- crates/adapters/src/integrated/delta_table/output.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/adapters/src/test/mock_output_consumer.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/http/output.rs
- crates/adapters/src/transport/kafka/ft/output.rs
- crates/adapters/src/transport/kafka/nonft/output.rs
- crates/adapters/src/transport/mod.rs
- crates/feldera-types/src/format/avro.rs
- crates/feldera-types/src/program_schema.rs
- demo/project_demo08-DebeziumJDBC/run.py
- deploy/Dockerfile
Add support for the Avro output format compatible with Confluent JDBC sink connector.
This format encodes primary key columns as Kafka message keys. Inserts and updates carry the complete value of the new record in the message payload.  Deletes are represented as tombstone messages with null values.
The connector supports all three standard subject name strategies: topic name, record name, and topic + record name.
The connector automatically generates value schema where all non-key columns are nullable.  This helps to make generated schemas predictable, as otherwise the user has little control over the nullability of SQL view columns.
Here is a minimal connector config example, which should to the right thing in most cases:
```
create view test_view
WITH (
'connectors' = '[{
"format": { …
```
> [avro] Confluent JDBC sink connector Avro format.

- crates/adapters/src/format/avro/deserializer.rs
- crates/adapters/src/format/avro/input.rs
- crates/adapters/src/format/avro/mod.rs
- crates/adapters/src/format/avro/output.rs
- crates/adapters/src/format/avro/schema.rs
- crates/adapters/src/format/avro/serializer.rs
- crates/adapters/src/format/avro/test.rs
- crates/adapters/src/format/json/input.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/test/data.rs
- crates/adapters/src/test/mock_dezset.rs
- crates/adapters/src/test/mod.rs
- crates/adapters/src/transport/s3/mod.rs
- crates/feldera-types/src/serde_with_context/deserialize.rs
The Avro parser currently insists on the Avro schema matching the SQL table definition precisely (with one exception: we can ignore fields that are in the schema, but not in the table). This requires aligning the SQL table declaration with the schema in every detail, which can be annoying. In addition, this prevents schema evolution. Specific scenarios we'd like to support:
* allow nullable table columns that don't appear in the Avro schema (this is helpful when parsing data encoded using an old version of the schema)
* allow parsing non-nullable values to nullable columns
* support millisecond-resolution timestamp and time values
Changes in this commit also enable us to feed nullable values to non-nullable column; however such schemas currently won't pass validation, since they can cause …
> [avro] Make Avro parser less strict.

- python/feldera/enums.py
- python/feldera/rest/feldera_client.py
- python/tests/requirements.txt
- python/tests/test_pipeline_builder.py
Wait for 15 seconds for a pipeline to shutdown. If the pipeline doesn't shutdown even after the timeout, resend the shutdown request, and wait a little longer.
Fixes: #2432
> py: wait for a failed pipeline to shutdown

- Cargo.lock
- crates/adapters/src/server/mod.rs
- crates/adapters/src/transport/kafka/ft/output.rs
- crates/adapters/src/transport/kafka/ft/test.rs
- crates/adapters/src/transport/kafka/mod.rs
- crates/adapters/src/transport/kafka/nonft/output.rs
- crates/adapters/src/transport/kafka/nonft/test.rs
- crates/feldera-types/src/transport/kafka.rs
- openapi.json
The Kafka output connector relied on the `max_inflight_messages` config option to implement flow control.  It tracked the number of buffered messages and waited for it to be belo `max_inflight_messages` before sending a new message.
This introduced an unnecessary control knob, since rdkafka has its own configurable mechanism to track in-flight messages (`queue.buffering.max.messages`).  Furthermore, it caused lost messages when `max_inflight_messages` was greater than `queue.buffering.max.messages`.
In this commit I removed this setting and instead changed the connector to re-send the message after a timeout when it gets rejected due to the queue being full.  This way we basically delegate flow control to rdkafka.
> [kafka] Improve flow control in Kafka output.

- Earthfile
- python/tests/test_pipeline_builder.py
Instead of importing from `feldera` package, the import was made from `build.lib.feldera`.
> py: fix build error introduced in `60390d3`

- .github/workflows/benchmark-command.yml
- .github/workflows/ci.yml
- Cargo.lock
- Earthfile
- crates/fda/Cargo.toml
- crates/fda/src/cli.rs
- crates/fda/src/main.rs
- crates/fda/src/shell.rs
- docs/api/cli.md
- scripts/bench.bash
Dynamically fetch pipeline names for autocompletion.
Also refactored command structure because of a clap bug we can't have pipeline names that are the same as the subcommand name that follows, e.g.,
`fda pipeline shell shell`
wasn't parsed properly.
https://github.com/clap-rs/clap/issues/5513
I factored the name from pipeline into the leaf commands and folded pipeline directly into the top-level commands, which means less typing anyways so it's probably a good idea anyways.
> Improve auto-complete in shell.

- crates/adapters/src/catalog.rs
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/static_compile/catalog.rs
- crates/adapters/src/static_compile/deinput.rs
The circuit thread locked the catalog for much longer than needed, grabbing unrelated locks while holding the catalog lock and causing a deadlock.  A simple fix would have been narrowing the critical section, but @gz pointed out that the catalog is only read after it is initially populated, so the mutex is not necessary.  This commit refactors the code to eliminate the mutex around the catalog and enables previously disabled tests.
> [adapters] Fix deadlock around catalog handle.

- crates/pipeline-manager/src/api/metrics.rs
- crates/pipeline-manager/src/api/mod.rs
- crates/pipeline-manager/src/integration_test.rs
- deploy/docker-compose.yml
- deploy/grafana/prometheus_docker.yaml
- deploy/prometheus/prometheus.yml
- docs/tutorials/monitoring/index.md
- openapi.json
Introduces a `/metrics` endpoint that returns pipeline metrics for all running pipelines owned by this tenant.
> pipeline-manager: implement `/metrics` endpoint

- crates/pipeline-manager/src/runner/error.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
Whe the pipeline crashes due to OOM or some other reason that we cannot catch, the manager reported TCP connection error, which is confusing to the user.
This is a purely cosmetic fix, which gives a better explanation of the error.
We can improve this by extracting additional info from the OOM killer in the local form factor or from k8s in the cloud form factor.
> [manager] Improve reporting when the pipeline is dead.

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/server/mod.rs
- crates/pipeline-manager/src/integration_test.rs
Addresses #2342.
After a fatal error like panic, we changed pipeline state to failed, but did not shutdown the controller, which kept trying to step every 100ms by default, logging an error message on each step.  The motivation for this was the possibility of a nested panic, which would crash the pipeline process, preventing it from reporting the original error. However, this can be easily prevented.
> [adapters] Shutdown pipeline on a fatal error.

- crates/adapters/src/adhoc/table.rs
- sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
We use `serde_arrow` to deserialize rows received as part of ad hoc
queries. It implements the `Deserializer` interface, through which it
allows deserializing time, date, and timestamp values as integers or
strings.  We use the latter (`deserialize_str`), which returns strings
encoded as `%FT%T%.f` (timestamp), `%T` (time), `%Y-%m-%d` (date),
but SqlSerdeConfig was not configured correctly, so `insert` queries
involving one of these types failed.  This commit switches to using
the correct configuration.
> Correctly deserialize timestamps from arrow.

- crates/dbsp/src/operator/dynamic/input.rs
Commit 6bf4e2dbbb6d ("dbsp_adapters: Allow the size of each step to be limited.") changed input adapters to take batches out of parsers in the form of `Box<dyn InputBuffer>` and then eventually flush those batches into the circuit's input handles.
This works fine when each of those buffers has many records, but there was an unexpected pitfall for the case where buffers have only one (or a few) records.  That is that each of the buffers, when it is taken from its parser, is cloned, and through a couple of layers of indirection this meant that the `CollectionHandle` that ultimately appends to the input handle was cloned too.  That `CollectionHandle` maintains an index into the workers, which points to the next worker to receive a record.  But when it was cloned every time, this meant that …
> dbsp: Fix performance with small input batches.

- python/feldera/rest/feldera_client.py
- python/tests/dtype_based_tests/test_avg.py
- python/tests/dtype_based_tests/test_sum.py
- python/tests/sql_aggregates/test_array_agg.py
- python/tests/sql_aggregates/test_average.py
- python/tests/sql_aggregates/test_bit_and.py
- python/tests/sql_aggregates/test_bit_or.py
- python/tests/sql_aggregates/test_bit_xor.py
- python/tests/sql_aggregates/test_count.py
- python/tests/sql_aggregates/test_count_col.py
- python/tests/sql_aggregates/test_every.py
- python/tests/sql_aggregates/test_max.py
- python/tests/sql_aggregates/test_min.py
- python/tests/sql_aggregates/test_some.py
- python/tests/sql_aggregates/test_stddev_pop.py
- python/tests/sql_aggregates/test_stddev_samp.py
- python/tests/sql_aggregates/test_sum.py
This fixes one real bug in the Python SDK and disables flaky tests until we have Python API for ad hoc queries.
See commit messages for details.   
Fixes #2494
> Avoid loss of precision in deserializing decimals from JSON in python

- crates/adapters/src/format/parquet/mod.rs
- crates/feldera-types/src/serde_with_context/serde_config.rs
- sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs
Addresses #2380.
When serializing time values as 64-bit numbers that represent nanoseconds since midnight, `serde_arrow` for some reason expects a signed integer, whereas we only supported unsigned values (what in the world is a negative time of day?).  I added another time serialization option for this purpose.  With this change, FDA is able to display time columns.  I also checked that it correctly displays timestamps and dates.
We will add more systematic tests for different combinations of types shortly.
> [adhoc] Fix serialization of time values.

- crates/adapters/src/adhoc/mod.rs
- crates/adapters/src/adhoc/table.rs
- crates/pipeline-manager/src/integration_test.rs
This can happen if dataframe didn't produce any record batches in the async execution. Which we didn't account for in the output logic.
Fixes #2506
> Fix a bug in the text output that sometimes doesn't send the result headers

- crates/dbsp/src/operator/dynamic/communication/gather.rs
- crates/dbsp/src/operator/dynamic/communication/shard.rs
- crates/dbsp/src/operator/dynamic/output.rs
- crates/dbsp/src/operator/dynamic/trace.rs
- crates/dbsp/src/trace/mod.rs
For Nexmark q9 with 16 workers and 100M events, this reduces the overall runtime on my system from 133 seconds to 114 seconds, by doing less data copying during merges.
> dbsp: Speed up sharding by implementing N-way merge.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPControlledFilterOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPJoinFilterMapOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToDotVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Projection.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/KeyPropagation.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/MonotoneAnalyzer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/NarrowJoins.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeMaps.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
Fixes #2532 
This should also reduce memory consumption because we carry fewer redundant fields in joins
> [SQL] Do not carry in joins fields that are already available in keys

- docs/sql/grammar.md
* Document the form of ASOF JOIN that we support today (<=, LEFT)
* `&lt;` and other HTML operators don't get rendered in markdown.
* Use >= instead ot <= in the example.
> Fixup ASOF JOIN docs.

- crates/dbsp/src/circuit/metadata.rs
- crates/dbsp/src/operator/dynamic/distinct.rs
- crates/dbsp/src/operator/dynamic/join.rs
- crates/dbsp/src/operator/dynamic/trace.rs
- crates/dbsp/src/operator/z1.rs
- crates/dbsp/src/profile/mod.rs
- crates/dbsp/src/trace/spine_async/mod.rs
With this, the root node in circuit profiles includes additional information that summarizes all the operators in the circuit, like this:
```
total size: 14385360
allocated bytes: 4.75 GiB
used bytes: 4.75 GiB
allocations: 34030654
shared bytes: 4.75 GiB
batches: 210
storage size: 3.53 GiB
merging batches: 20
merging size: 2.18 GiB
merge reduction: 23.93%
output redundancy: 0.00%
```
> dbsp: Summarize operator metadata into root in circuit profiles.

- crates/feldera-types/src/config.rs
We use jaeger for tracing. The default pipeline configuration had tracing enabled, the assumption being that it has negligible runtime cost. However, we've discovered that it can consume gigabytes of RAM (and I'm not even sure there's an upper bound) presumably buffering events in memory. We therefore switch the default to false.
> Disable tracing by default.

- web-console/src/routes/(authenticated)/+page.svelte
This simple change forces the preload of the bulk of code for Pipeline Edit page.
This greatly improves onboarding experience on a slower internet connection.
The following timeline of WebConsole bundle files loading in browser on a **slow connection** when the welcome page is first opened demonstrates the new app preload behavior:
> [WebConsole] Preload Pipeline Edit page code while on welcome screen

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/server/prometheus.rs
- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/circuit/metrics.rs
- crates/dbsp/src/circuit/operator_traits.rs
- crates/dbsp/src/operator/dynamic/distinct.rs
- crates/dbsp/src/operator/dynamic/join.rs
- crates/dbsp/src/operator/dynamic/trace.rs
- crates/dbsp/src/operator/z1.rs
- crates/dbsp/src/trace/mod.rs
dbsp_adapters: remove dependency on `prometheus` crate
dbsp: introduces `metrics` method in Node and Operator
1. This removes the dependency on the `prometheus` crate on `dbsp_adapters`. We just use `metrics` instead. I think it can be simplified further by messing with `Controller` and `ControllerInner`, but we can do that later if necessary. Fixes: #2361
2. Adds the method `metrics` in `Node` and `Operator` traits. `metrics` has an empty body by default, and is overridden by operators that already have an implementation for `metadata`.
> dbsp_adapters: remove dependency on `prometheus` crate

- CONTRIBUTING.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
Fixes #2584 
We now decompose a filter condition into a sequence of conjunctions.
Each conjunct has one of the forms
- noNow (does not involve now)
- temporal (involves now and it can be implemented as a temporal comparison - complicated rules)
- nonTemporal (involves now and it cannot be implemented as a temporal comparison)
We implement 
- noNow conditions using standard (chained) filters, 
- temporal conjuncts using temporal windows
- nonTemporal conjuncts using joins and filters
As a bonus, we can sometimes combine multiple temporal conjuncts into a single window operator call.
So the example in the test case is written as a regular filter followed by a temporal filter.
Subtly, we take advantage of the fact that in SQL the AND operator is *not* short circuit as in C/Java.
> [SQL] Extract temporal filters from more kinds of comparison expressions 

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Monotonicity.java
Fixes #2531 
Only timestamp fields copied to the output are monotone.
Then the waterline is the min of both timestamps.
> [SQL] More conservative ASOF join monotonicity inference

- crates/feldera-types/src/config.rs
We don't use RuntimeConfig::default anywhere except in `fda create`, so I don't see harm in adjusting this default directly.
If #workers is 1, users not familiar with feldera
will likely have sub-optimal settings creating a new pipeline with fda and not get great performance as we'd like them to see.
> Set default_workers() to 8.

- deploy/Dockerfile
This should fix the nightly container build failure.
> docker: make sqllib crate available to sql-compiler, which got recently moved to crates/

- docs/sandbox.md
The Feldera Cloud Sandbox page did not have a link to the sandbox.
> [docs] Add link to the sandbox.

- docs/connectors/sources/s3.md
Fixup broken link to delta lake docs from the S3 connector page.
> [docs] Fixup a link to delta docs.

- web-console/src/lib/components/layout/Drawer.svelte
- web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte
- web-console/src/lib/components/pipelines/List.svelte
- web-console/src/lib/components/pipelines/editor/CodeEditor.svelte
- web-console/src/lib/components/pipelines/editor/InteractionsPanel.svelte
- web-console/src/lib/components/pipelines/list/DeploymentStatus.svelte
- web-console/src/lib/compositions/layout/useDrawer.svelte.ts
- web-console/src/lib/compositions/layout/useIsMobile.svelte.ts
- web-console/src/routes/(authenticated)/(pipelines)/+layout.svelte
- web-console/src/routes/(authenticated)/+layout.svelte
Turns 
into
Also now when switching pipeline via drawer button while on mobile - drawer auto-closes
> [WebConsole] improve layout on mobile

- python/feldera/enums.py
- python/feldera/pipeline.py
- python/feldera/rest/_httprequests.py
- python/feldera/rest/feldera_client.py
- python/tests/test_pipeline.py
- python/tests/test_variant.py
- python/uv.lock
Fixes: #2493 
Adds methods to run adhoc queries against running or paused pipelines.
In FelderaClient:
- adds ~query()~ query_as_text(), query_as_json() & query_as_parquet() methods
In Pipeline:
- adds query() for JSON (returns generator that yields dict), query_parquet() (saves to the given file) and query_tabular() (returns generator that yields string) methods
~A new enum is also added to represent the different formats of responses for ad-hoc queries: `QueryResponseFormat`.~
***
While discussing this implementation we talked about potentially introducing a `Cursor` type that users can use to iterate upon the result, however, that might not be necessary as we can just yield responses and use the generator. 
The function names could change to improve clarity.
> [py] add Pipeline.query() and Pipeline.query_tabular() for adhoc queries

- python/feldera/__init__.py
- python/feldera/rest/errors.py
- python/feldera/rest/feldera_client.py
- python/pyproject.toml
- python/tests/test_pipeline_builder.py
- python/uv.lock
Display SQL compliation errors in a pretty format.
Also use `pretty-errors` library that improves how errors are presented in general.
Fixes: #1842
Fixes: #1802
> [py] pretty SQL compilation errors

- crates/pipeline-manager/src/compiler.rs
- crates/pipeline-manager/src/integration_test.rs
- web-console/src/lib/compositions/health/systemErrors.ts
Every database interaction to transition the program status of a pipeline can yield the UnknownPipeline error as pipelines can be deleted at any point in time. This is now handled by either skipping its re-queueing or canceling the corresponding job.
Also fixes: https://github.com/feldera/feldera/issues/2643
> pipeline-manager: handle pipeline deletion in compiler server

- sql-to-dbsp-compiler/build.sh
This will enable people who aren't rebased on the latest main use the compiler correctly
> CI: Fix Calcite commit in build script

- crates/dbsp/src/operator/dynamic/input.rs
- crates/dbsp/src/operator/input.rs
As explained in https://github.com/feldera/feldera/issues/2669, the use of GC with `add_input_map` is unsound. This caused random errors in three tests, two of them previously disabled. We now fix the tests by disabling the unsound functionality.
> [dbsp] Fix broken `add_input_map` tests.

- Earthfile
- crates/pipeline-manager/src/api/config_api.rs
- crates/pipeline-manager/src/api/mod.rs
- crates/pipeline-manager/src/auth.rs
- crates/pipeline-manager/src/config.rs
- crates/pipeline-manager/src/demo.rs
- crates/pipeline-manager/src/integration_test.rs
- demo/packaged/README.md
- demo/packaged/sql/00-fraud-detection.sql
- demo/packaged/sql/01-sec-ops.sql
- demo/packaged/sql/02-product-availability.sql
- demo/packaged/sql/03-statistics.sql
- demo/packaged/sql/04-supply-chain.sql
- demo/packaged/validate-preamble.py
- deploy/Dockerfile
- openapi.json
- web-console/src/lib/compositions/health/systemErrors.ts
- web-console/src/lib/compositions/pipelines/useTryPipeline.ts
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/services.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
- web-console/src/routes/(authenticated)/+page.svelte
- Support multiple demos directories
- Ignore directories and files not ending with '.sql' within a demo directory
- Python SQL preamble validation script which is called in Earthfile
- pipeline-manager does SQL preamble validation
- Copy demos in Earthfile/Dockerfile and add argument to entry points
- First five packaged demos
- Web Console uses new demos endpoint format
> demo: packaged SQL-only demos

- python/tests/aggregate_tests/aggtst_base.py
- python/tests/aggregate_tests/main.py
- python/tests/aggregate_tests/test_array.py
- python/tests/aggregate_tests/test_avg.py
- python/tests/aggregate_tests/test_bit_and.py
- python/tests/aggregate_tests/test_bit_or.py
- python/tests/aggregate_tests/test_bit_table.py
- python/tests/aggregate_tests/test_bit_xor.py
- python/tests/aggregate_tests/test_count.py
- python/tests/aggregate_tests/test_count_col.py
- python/tests/aggregate_tests/test_decimal_avg.py
- python/tests/aggregate_tests/test_decimal_sum.py
- python/tests/aggregate_tests/test_decimal_table.py
- python/tests/aggregate_tests/test_every.py
- python/tests/aggregate_tests/test_int_table.py
- python/tests/aggregate_tests/test_max.py
- python/tests/aggregate_tests/test_min.py
- python/tests/aggregate_tests/test_some.py
- python/tests/aggregate_tests/test_stddev_pop.py
- python/tests/aggregate_tests/test_stddev_samp.py
- python/tests/aggregate_tests/test_sum.py
Fixes: #2650
Note that the adhoc query backend doesn't support DECIMAL yet, so DECIMAL tests have been currently disabled.
See issue: #2667
Re-enable them by uncommenting the DECIMAL related imports in aggtest_base.py.
**Note that it is important for the VIEWs created for the tests are materialized views.**
> [py] test: use adhoc queries for python SQL tests

- web-console/src/lib/components/MonacoEditor.svelte
- web-console/src/lib/components/MonacoEditor_svelte5.svelte
Some of the web console's styling is spilling over to the monaco editor. I'm assuming this is unintentional
This is what VSCode normally looks like
Here is the styling fix
This thing was bothering me. I don't have any experience in Svelte so I just did whatever worked.
> [WebConsole] Fix monaco find widget styling

- python/pyproject.toml
Updates the docs link to point to the python SDK docs at https://docs.feldera.com/python/
Fixes: #2686
> [py] fix docs link in pyproject.toml; PyPi page

- python/feldera/pipeline.py
- python/tests/test_pipeline_builder.py
`execute(query)` takes a query, executes it and prints the tabular response.
The printing can be disabled with `execute(query, False)`.
Fixes: #2688
> [py] add `Pipeline.execute()` method to execute queries

- crates/pipeline-manager/src/config.rs
- crates/pipeline-manager/src/demo.rs
- demo/packaged/sql/05-udf-tutorial.sql
- demo/packaged/sql/05-udf-tutorial.udf.rs
- demo/packaged/sql/05-udf-tutorial.udf.toml
- openapi.json
- scripts/start_manager.sh
- web-console/src/lib/compositions/pipelines/useTryPipeline.ts
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
If a `<filename>.sql` is found in a demos directory, also check for `<filename>.udf.rs` and `<filename>.udf.toml`. If present, these will be included in the demo as well.
Add a UDF tutorial demo in which to encode incoming binary data as base64.
> pipeline-manager: demos with user defined functions

- crates/pipeline-manager/src/compiler.rs
A pipeline compiled with a pre-UDF version of Feldera may not have a stubs.rs file in the source directory.  Handle this situation gracefully by returning an empty string instead of failing the compiler task.
> [manager] Gracefully handling missing stubs.rs.

- sql-to-dbsp-compiler/README.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/CompilerMain.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/NegativeParserTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
- sql-to-dbsp-compiler/using.md
Fixes #2694 
I am not sure that the JSON version of the Calcite plans is actually useful. Perhaps a simple string would be better.
Please note that each view generates a separate plan, so the output is a map from view name to plan.
There is an example of the generated JSON in a test.
> [SQL] Added compiler flag --plan to generate Calcite plan as JSON

- docs/sql/streaming.md
I have verified manually that this is true using the web ui.
> [SQL] Explain that WATERMARK is evaluated in the next circuit step

- python/tests/aggregate_tests/test_varchar_max.py
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/AggregateTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
A tumble window on a nullable timestamp needs to filter out null timestamps first.
For some unexplained reason we never tested this case.
> [SQL] tumble windows on nullable timestamps

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/test/mod.rs
- crates/adapters/src/transport/kafka/ft/test.rs
- crates/adapters/src/transport/kafka/mod.rs
- crates/adapters/src/transport/kafka/nonft/input.rs
- crates/adapters/src/transport/kafka/nonft/output.rs
- crates/adapters/src/transport/mod.rs
- docs/connectors/sinks/kafka.md
- docs/connectors/sources/kafka.md
Workaround around: https://github.com/confluentinc/librdkafka/issues/3225
Modifies kafka options `ssl.*.pem` to `ssl.*.location`, saves the PEM keys to a file named after their SHA256 hash and the file path to this file is set as the value for this option.
> [adapters] kafka: workaround ssl.certificate.pem librdkafka issue

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/format/avro/output.rs
- crates/adapters/src/format/avro/schema.rs
- crates/adapters/src/format/avro/serializer.rs
This is needed to resolve the conflict between the newer version of Avro picked up by the schema_registry_converter crate.
> [adapters] Upgrade avro dependency to 0.17.

- crates/dbsp/src/operator/chain_aggregate.rs
- crates/dbsp/src/operator/dynamic/aggregate/chain_aggregate.rs
- crates/dbsp/src/operator/dynamic/aggregate/mod.rs
- crates/dbsp/src/operator/dynamic/group/mod.rs
- crates/dbsp/src/operator/mod.rs
Introduce a specialized operator that computes an aggregate whose value depends on the previous value of the aggregate and changes to the input collection.  Unlike general aggregates, such aggregates don't require storing the integral of the input collection and hence require only O(1) memory per key, similar to linear aggregates.
Examples include min and max over append-only collections.
> [dbsp] Chain aggregate operator.

- crates/pipeline-manager/src/db/test.rs
The transition to ShuttingDown sets `deployment_config`, `deployment_location` and `deployment_error` to NULL as from that moment the deployment is being terminated and deleted. This was not yet reflected in the database test model.
> pipeline-manager: database test model fix for Shutdown and ShuttingDown

- docs/docker.md
- docs/enterprise/index.md
- docs/enterprise/quickstart.md
- docs/interact/index.mdx
- docs/reference/cli.md
- docs/reference/rest.md
- docs/reference/web-console.md
- docs/sandbox.md
- docs/sidebars.js
- docs/tutorials/monitoring/index.md
- docs/tutorials/rest_api/index.md
- docs/writing/index.mdx
- scripts/bump-versions.sh
Current sidebar:
I also removed some stale content.
As for next steps:
> docs: make the user-relevant sections of the documentation more prominent

- crates/sqllib/src/string.rs
- docs/sql/string.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresStringTests.java
Since calcite already support ilike, we can support ilike for postgres string in feldera.
> [sql] support ilike for postgres string

- crates/feldera-types/src/transport/kafka.rs
- openapi.json
This brings back the `fault_tolerance` field for the Kafka input connector for backwards compatibility. This prevents `fault_tolerance` from being deserialized as part of the flattened `kafka_options` for existing stored connectors that have its value as `null`.
> feldera-types: bring back `fault_tolerance` field

- sql-to-dbsp-compiler/run-tests.sh
- sql-to-dbsp-compiler/slt/pom.xml
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/Main.java
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/InputFunctionGenerator.java
- sql-to-dbsp-compiler/slt/src/test/java/org/dbsp/sqllogictest/RotateTests.java
- sql-to-dbsp-compiler/slt/src/test/java/org/dbsp/sqllogictest/package-info.java
This spreads the SLT tests over a number of days, using the current date to decide which tests to run.
Currently the tests are spread over 1 year, requiring running about 15K tests/day.
This is a trade-off between CI time and test coverage which we can tweak.
> [SQL] Run sqllogictests by rotation, some every day

- crates/sqllib/src/aggregates.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPControlledFilterOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainKeysOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainValuesOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
Fixes #2775 
This uses a integrate_retain_keys operator for the WINDOW operator that is introduced for an emit_final annotation.
> [SQL] GC for emit_final WINDOW operator

- crates/dbsp/src/circuit/dbsp_handle.rs
Disabled `commit_restore_bounds` test, which was failing in CI. The test assumes that `integrate_trace_with_bounds` applies bounds eagerly, which is not the case.
Fixes #2801
> [dbsp] Disable incorrect test.

- crates/adapters/src/transport/url.rs
Although they work OK locally, they keep failing in CI.  It's hard to get timing-based tests to run reliably.
Reported by @mihaibudiu.
> dbsp_adapters: Set url transport pause tests as ignored for now.

- crates/dbsp/src/operator/dynamic/time_series/window.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/LowerCircuitVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/Monotonicity.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
Fixes #2846
Outer joins are decomposed into regular joins and some subtractions. This PR implements monotonicity analysis for subtract and negate, and thus enables propagation of such information through outer joins.
The fact that the test program even compiles is a proof that the analysis works, otherwise the program would be rejected, since it has an emit_final annotation.
> [SQL] Monotonicity analysis for subtract and negate operators

- crates/pipeline-manager/src/api/mod.rs
If no bg theme can be detected in the terminal, we chose the wrong banner instead of the one that is background agnostic.
Fixes https://github.com/feldera/feldera/issues/2837
> Fix banner display in docker form factor.

- crates/adapterlib/src/transport.rs
`push_with_aux` swapped arguments to consumer.buffered(), which messed up the buffered records accounting, and caused #2845.
Fixes #2845
> [adapters] Typo in `push_with_aux`.

- demo/packaged/sql/06-time-series-tutorial.sql
- docs/sidebars.js
- docs/sql/streaming.md
- docs/tutorials/time-series.md
A guide that systematically introduces concepts around GC and time series processing, the various SQL extensions we support for time seris analytics, as well as standard SQL that works well for time series (and that's GC'able).
Removed most text from the "Streaming extensions" section in the SQL reference, just keeping the list of features with pointers to corresponding sections of the guide.
I am still working on SQL examples.  I will combine them all in one program and will add it as a pre-packaged demo accompanying the guide.
> [docs] Guide: Time Series Analysis with Feldera

- docs/sql/array.md
Fixed typos, but `UNNEST` needs to be documented better, will file an issue for that.
> [docs] Fix typos in `UNNEST` documentation

- docs/connectors/sources/http.md
- docs/interact/index.mdx
- docs/sql/ad-hoc.md
- docs/sql/udf.md
- docs/tutorials/basics/part1.md
- docs/use_cases/fraud_detection/fraud_detection.md
Docusaurus cannot resolve links to /python/... because they are generated separately, so need to be resolved as an absolute path. Rather than hardcoding docs.feldera.com, Docusaurus has special syntax for this : `pathname://`, e.g. `pathname:///python/...`
> [Docs] Fix links to python docs with Docusaurus'es 'pathname://'

- crates/dbsp/src/storage/backend/io_uring_impl/mod.rs
- crates/dbsp/src/storage/backend/memory_impl.rs
- crates/dbsp/src/storage/backend/mod.rs
- crates/dbsp/src/storage/backend/posixio_impl.rs
- crates/dbsp/src/storage/backend/tests.rs
- crates/dbsp/src/storage/buffer_cache/cache.rs
- crates/dbsp/src/storage/file/reader.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/ord/fallback/indexed_wset.rs
- crates/dbsp/src/trace/ord/fallback/key_batch.rs
- crates/dbsp/src/trace/ord/fallback/val_batch.rs
- crates/dbsp/src/trace/ord/fallback/wset.rs
- crates/dbsp/src/trace/ord/file/indexed_wset_batch.rs
- crates/dbsp/src/trace/ord/file/key_batch.rs
- crates/dbsp/src/trace/ord/file/val_batch.rs
- crates/dbsp/src/trace/ord/file/wset_batch.rs
- crates/dbsp/src/trace/ord/vec/key_batch.rs
- crates/dbsp/src/trace/ord/vec/val_batch.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/dbsp/src/trace/spine_fueled.rs
When we run with storage, we didn't delete files that got replaced with new ones by merging.
This PR removes the explicit delete in the storage backend as it's hard to know when it's safe to delete files. Instead we delete files automatically in the drop handle for ImmutableFile. This is good as long as the file isn't part of a checkpoint, when we can no longer do that. For this case we add a new method, mark_for_checkpoint that, when called stops deleting on drop.
After mark_for_checkpoint is called, the Checkpointer becomes responsible to remove files that are no longer reachable from any checkpoint.
> Delete files that are no longer part of a spine.

- crates/adapters/src/transport/kafka/nonft/input.rs
Thanks to Simon Kassing for reporting these.
> dbsp_adapters: Remove stray debug prints.

- sql-to-dbsp-compiler/SQL-compiler/pom.xml
- sql-to-dbsp-compiler/SQL-compiler/src/main/codegen/config.fmpp
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/ProfilingTests.java
- sql-to-dbsp-compiler/build.sh
The new Calcite is a bit more finicky with respect to casts, so some ASOF joins that used to compile will now report some rather obscure errors. An error may look like this:
```
(no input file):261:4: error: Error in SQL statement: ASOF JOIN condition must be a conjunction of equality comparisons
261|ON B.mod = S.key;
^^^^^^^^^^^^^
```
This comparison looks right. But the problem is that in the compiler this looks like `CAST(B.mod as BIGINT) = S.key`, which is not a simple comparison.
I have filed https://issues.apache.org/jira/browse/CALCITE-6641 to track this issue, and I will try to implement a solution. 
For now the solution is to edit the SQL and to to insert the casts manually before invoking the join.
> [SQL] Migrate to Calcite 1.38

- crates/adapters/src/adhoc/mod.rs
- crates/pipeline-manager/src/integration_test.rs
- python/tests/aggregate_tests/aggtst_base.py
- python/tests/aggregate_tests/test_varcharn_argmin.py
Otherwise it's hard for clients to figure out which fields a query returns.
Fixes #2839
> Send attributes that are null as part of JSON response.

- docs/docker.md
Noticed a very minor typo as I was reading through the documentation — just patching that.
> docs/docker: fix typo

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainKeysOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/monotone/MonotoneTransferFunctions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/Monotonicity.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
Fixes #2847 
This analysis treats the LAG operator very much like an aggregate operator, but assumes that some of the data's monotonicity can be propagated to the output. It would be nice to review the design.
> [SQL] Monotonicity analysis for LAG operator

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/RepeatedExpressions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/ExpressionTree.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ir/ExpressionTreeTests.java
There were two typos in the visitor implementation for expressions.
It is a bit unfortunate that there is no easy way to catch such bugs except through visual inspection.
To help debug this problem I created a new class ExpressionTree.
> [SQL] Fix typo in visitor implementation; ExpressionTree class for debugging help

- .github/workflows/python-publish.yml
> [ci] python-publish: fix path to uv.lock

- crates/feldera-types/src/serde_with_context/serialize.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
Auto-generated Rust structs only need to implement `(De)SerializeWithContext`, and not the standard serde `Serialize/Deserialize` traits.
Turns out, `SerializeWithContext` derived `serde::Serialize`, but it was completely unnecessary, so I removed the derivation and changed Java code not to auto-derive serde traits.
I don't think this improves compilation speed.  The serde traits weren't actually used and ended up getting compiled away.
> [sql] Don't generate serde traits for structs.

- crates/sqllib/src/aggregates.rs
- crates/sqllib/src/binary.rs
- crates/sqllib/src/casts.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeBinary.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeWeight.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggScottTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/WinAggPostTests.java
The weight of the item was ignored when computing XOR.
The new implementation uses the item when the weight is odd, and zero when the weight is even.
> [SQL] Fix bug in implementation of XOR aggregate

- Earthfile
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Projection.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/NarrowJoins.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeMaps.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeProjectionVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeWithGraph.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/Monotonicity.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/ComplexQueriesTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/ProfilingTests.java
This optimization replaces the unsound Calcite optimization PROJECT_JOIN_TRANSPOSE.
The optimization essentially moves projections backwards through the plan, pushing projections at the output of a join to the inputs of the join.
This optimization was disabled in our compiler a while ago, but the lack of this optimization caused some SLT tests to fail, since the plans they were generating we very inefficient.
> [SQL] Trim unused fields backwards from joins

- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/Main.java
There are 610 test files, and we run all tests ever 305 days, so we run exactly 2 test files every day.
They are now chosen to be at offsets today % 305 + i * 305 for i in 0, 1.
> [SQL/SLT] Improve algorithm to select tests to run every day

- web-console/src/lib/components/adhoc/Query.svelte
- web-console/src/lib/components/common/virtualList/HeadlessVirtualList.svelte
- web-console/src/lib/components/dialogs/JSONDialog.svelte
- web-console/src/lib/components/pipelines/editor/ChangeStream.svelte
- web-console/src/lib/components/pipelines/editor/CodeEditor.svelte
- web-console/src/lib/components/pipelines/editor/InteractionsPanel.svelte
- web-console/src/lib/components/pipelines/editor/ReverseScrollFixedList.svelte
- web-console/src/lib/components/pipelines/editor/TabAdHocQuery.svelte
- web-console/src/lib/components/pipelines/editor/TabPerformance.svelte
- web-console/src/lib/components/pipelines/editor/TabPipelineErrors.svelte
- web-console/src/lib/components/pipelines/editor/TabQueryData.svelte
- web-console/src/lib/components/relationData/SQLValue.svelte
- web-console/src/lib/compositions/common/usePopoverTooltip.svelte.ts
- web-console/src/lib/compositions/health/systemErrors.ts
- web-console/src/lib/compositions/layout/useDrawer.svelte.ts
- web-console/src/routes/(authenticated)/+layout.svelte
- web-console/src/routes/(authenticated)/+page.svelte
Hide drawer when WebConsole is first opened on mobile
Make SQL value popup appear on click instead of on hover in data tables
Make numbers right-aligned in data tables, add truncation of insignificant decimal digits
Display 'create new pipeline' button on home page above demos on mobile
Reduce right padding of file tabs so that they fit on mobile in one line
Use virtual list for better performance of Ad-hoc query results table
Improve scrollbar on examples page
Spell 'Insert' and 'Delete' instead of '+' and '-' in Change Stream
Other minor fixes
> Multiple WebConsole fixes and improvements

- crates/feldera-types/src/program_schema.rs
- openapi.json
A custom deserialization was implemented for `SqlType`, but its custom serialization counterpart was not implemented. This resulted in an error when deserializing the output of its own serialization for some of its variants (notably, interval types). This commit implements the custom serialization and adds a corresponding test. This also removes the `From` trait implementation, which is not used anywhere.
Fixes: https://github.com/feldera/feldera/issues/2947
> feldera-types: fix serialization of `SqlType`

- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
Should fix the last CI failure in SLT nightly tests.
> [SQL] Handle correctly the last SLT test in a file when the test output is empty

- crates/pipeline-manager/src/db/types/program.rs
Resolves https://github.com/feldera/feldera/issues/2972
When encoding table name in connector configuration, pipeline manager did not quote case-sensitive names.  On the pipeline side, the config decodes the name as SqlIdentifier, treating it as case-insensitive, so it no longer matches table name.
> [manager] Quote case-sensitive table names.

- crates/dbsp/src/hash.rs
`Xxh3::with_seed()` computes 192 bytes of a custom "secret" on every invocation, and stores that secret in the `Xxh3`, which makes the hasher bigger and slower.  We don't really need a custom secret, so switch to `Xxh3Default`, which is over 192 bytes smaller and does not compute a secret at initialization time, making it faster.
I did not measure performance.
Fixes https://github.com/feldera/feldera/issues/2975.
> dbsp: Use xxh3 default hasher instead of custom.

- crates/dbsp/src/operator/controlled_filter.rs
- crates/dbsp/src/operator/dynamic/controlled_filter.rs
- crates/dbsp/src/typed_batch.rs
Added versions of controlled filters that take strongly typed `threshold` stream instead of one that contains `TypedBox`.  This should make them easier to use in the SQL compiler.
Also added doc comments to these methods, which I somehow forgot in the original PR.
> [dbsp] Strongly typed controlled filters.

- crates/sqllib/src/string.rs
- docs/sql/string.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/ProgramMetadata.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/dot/ToDotEdgesVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TypeCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/IHasSchema.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/FreshName.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/NameGen.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/BigQueryTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/RedshiftTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/recursive/RecursiveTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/CalciteSqlOperatorTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/SqlIoTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TableParser.java
This implementation uses the Rust function replace_all.
Thus the syntax for regular expressions matches Rust, including capture groups, which are denoted with `$0`, `$1`, etc.
This differs from other SQL dialects.
The PR also fixes a bug which prevented SLT tests from running when a view has two columns with the same name.
> [SQL] Support for the regexp_replace function

- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TestCase.java
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
The code was assuming that the generated circuit always has a single output.
This fix should restore the nightly CI tests.
> [SQL/SLT] SLT tests were broken when the error view was introduced

- docs/connectors/sources/kafka.md
> [docs] Fix typo in Kafka input connector docs

- crates/sqllib/src/operators.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CustomFunctions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/PredefinedFunctions.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/MapTests.java
Adds the function `blackbox(T) -> T`, so that we can force Calcite to skip making optimizations.
> [SQL] implement blackbox function

- crates/dbsp/src/storage/file/writer.rs
- crates/dbsp/src/time/mod.rs
- crates/dbsp/src/trace/layers/layer.rs
- crates/dbsp/src/trace/layers/leaf.rs
- crates/dbsp/src/trace/layers/mod.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/ord/fallback/utils.rs
- crates/dbsp/src/trace/ord/file/key_batch.rs
- crates/dbsp/src/trace/ord/file/val_batch.rs
A recent commit introduced lazy compaction of traces by bumping
timestamps up to the frontier. In that commit compaction was only
applied when merging identical values from the two input batches, but
not when simply copying values from one of the inputs to the output
batch. The thinking was that individual batches are always compacted,
so there is nothing else to compact. However, this is not true, since
individual batches are only compacted when the are first generated, but
as the frontier moves forward over time, compacted batches can become no
longer compacted. This may not sound too bad, but can lead to unbounded
inflation of memory/storage in some scenarios.  In particular, this
happens when the batch contains a value that was inserted and deleted and
that never occurs again in any …
> dbsp: Improved trace compaction

- Cargo.lock
- crates/adapterlib/Cargo.toml
- crates/adapters/Cargo.toml
- crates/adapters/src/adhoc/table.rs
- crates/adapters/src/format/parquet/mod.rs
- crates/adapters/src/integrated/delta_table/input.rs
- crates/adapters/src/integrated/delta_table/output.rs
- crates/adapters/src/static_compile/seroutput.rs
Use the latest datafusion, arrow, and deltalake crates.  This will finally resolve #2667. This will also unblock work on the Iceberg connector, which requires the latest datafusion.
> adapters: Upgrade to datafusion 0.43.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/derived/DBSPTypeFunction.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/derived/DBSPTypeStruct.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeAny.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeStream.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeUser.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeVec.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
The code was using the wrong exception in several places, which led to a Compiler bug error instead of an error report.
This also adds a default value for arrays, which allows min and max computations for array values.
> [SQL] Use UnimplementedException instead of NotImplementedException

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/dot/ToDot.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeProjectionVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/MonotoneAnalyzer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeString.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresStringTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresWindowTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggScottTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/AggTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/HRWinAggTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/WinAggPostTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpcDsTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TableParser.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/resources/tpcds.sql
We used to reject this query:
```sql
create view v as
select max(t.x) OVER (PARTITION BY t.id)
from t;
```
This PR implements such queries in terms of standard aggregates followed by joins.
There are still a few patterns not supported for OVER, but this eliminates some of them.
Part of #457
> [SQL] Support for OVER without ROWS, RANK, or ORDER BY

- python/tests/aggregate_tests/main.py
- python/uv.lock
Re-enables the python based SQL aggregate tests for DECIMAL as #2667 has been fixed.
> [tests] re-enable SQL aggregate tests for decimals

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteObject/CalciteRelNode.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/IHasSchema.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
The metadata will be emitted as a legal SQL expression.
See the test case for an example.
> [SQL] Emit extra metadata information in JSON: default value, lateness, watermark

- README.md
- benchmark/feldera-sql/run.py
- demo/project_demo01-TimeSeriesEnrich/run.py
- demo/project_demo03-GreenTrip/run.py
- demo/project_demo04-SimpleSelect/run.py
- demo/project_demo06-SupplyChainTutorial/run.py
- demo/project_demo07-SnowflakeSink/run.py
- demo/steady/demo.py
- scripts/compilation_speed_benchmark.py
There are demo and benchmark Python scripts which use direct API calls for program compilation. Some of them do not yet account for the new status `SqlCompiled` that was introduced in the compiler rework, and fail as a result. This failure is nondeterministic, as when there is only one program, it would relatively quickly transition to `CompilingRust` and as such there is only a chance of the script observing the new status. This fixes it by adding an extra condition for `SqlCompiled` in the check of whether compilation is still ongoing.
> python: account for status `SqlCompiled` in program compilation check

- crates/sqllib/src/lib.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/MinMaxOptimize.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
There are separate commits.
Fixes #3093 
Fixes #3094 
The SLT bug is interesting: it is caused by a multiplication that produces an overflow. The multiplication is in a NOT BETWEEN statement. Postgres and sqlite convert the NOT BETWEEN to an OR, which evaluates lazily the right input. The SQL standard does *not* mandate lazy evaluation for OR or BETWEEN, but it does not prohibit it either. So this choice essentially will make fewer programs fail at runtime.
> Fixes 2 bugs found by Sqlancer and 1 bug found by SLT

- Cargo.lock
- crates/dbsp/Cargo.toml
- crates/fda/Cargo.toml
- crates/feldera-types/Cargo.toml
- crates/pipeline-manager/Cargo.toml
- crates/sqllib/Cargo.toml
- openapi.json
- python/pyproject.toml
0.31.1 containers didn't get built because of the missing Calcite commit ID issue. Creating another release.
> release: bump project version to 0.31.2

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/integrated/delta_table/input.rs
- crates/adapters/src/integrated/delta_table/test.rs
- crates/adapters/src/test/data.rs
- crates/adapters/src/test/datagen.rs
- crates/datagen/src/lib.rs
- crates/feldera-types/src/program_schema.rs
- crates/feldera-types/src/transport/delta_table.rs
- demo/project_demo10-FraudDetectionDeltaLake/notebook.ipynb
- demo/project_demo10-FraudDetectionDeltaLake/run.py
- docs/connectors/sources/delta.md
- openapi.json
When loading a snapshot of a Delta table with lateness the connector must
satisfy the lateness constraint. Until now, we achieved
this by sorting the table by timestamp by issuing a snapshot query of
the form `select * from snapshot order by ts`, which is very
inefficient for large tables, as it involves storing and sorting the
entire dataset inside the pipeline. This is also unnecessary in most
cases, since lateness allows out-of-order ingest as long as it doesn't
exceed the specified lateness bound.
This commit implements a more efficient strategy, which, instead of
issuing a single expensive snapshot query, generates a sequence of
queries for lateness-width timestamp ranges. Assuming the input table is
optimized for timestamp queries, e.g., partitioned, Z-ordered, or liquid
clustered …
> [adapters] Optimize loading delta tables with lateness

- sql-to-dbsp-compiler/temp/Cargo.toml
The issue was solver in lexical-write-integer 1.0.5.
This reverts commit 43b8d0ef8faeab173316a46e3ff9e3b5c074f86f.
> Revert "[adapters] Workaround for datafusion regression."

- Cargo.lock
- crates/dbsp/Cargo.toml
- crates/dbsp/src/storage/backend/io_uring_impl/mod.rs
- crates/dbsp/src/storage/backend/io_uring_impl/tests.rs
- crates/dbsp/src/storage/backend/memory_impl.rs
- crates/dbsp/src/storage/backend/mod.rs
- crates/dbsp/src/storage/backend/posixio_impl.rs
- crates/dbsp/src/storage/backend/tests.rs
- crates/dbsp/src/storage/buffer_cache/cache.rs
- crates/dbsp/src/storage/file/cache.rs
- crates/dbsp/src/storage/file/reader.rs
- crates/dbsp/src/storage/file/writer.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/dbsp/src/trace/spine_async/thread.rs
- deploy/docker-compose.yml
Until now, the storage system has used a single `Storage` trait, which
had methods for creating and open files and reading and writing them.
`Storage` identified files with handles that were newtypes for integers.
This worked but it was not ideal because the handles could be passed
around in arbitrary ways, they had no useful behavior on drop, they
were not tied to their own `Storage` instance (that is, a handle for one
storage instance could be used with another, even though this was wrong),
they had possibly overlapping ranges for different `Storage` instances (so
sometimes using one with the wrong `Storage` would silently misbehave
rather than panicking), and lifetimes were confusing.
This commit fixes these problems by refactoring how things work.  Now,
`Storage` only has methods for …
> Use types that directly represent files, instead of file handles.

- crates/sqllib/src/casts.rs
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
I initially thought these functions are not necessary, since VARIANTs can never be null when produced by casts, but the type inference of Calcite requires them anyway, since it doesn't know this fact.
> [SQL] Add missing cast functions to variant (#3140)

- Cargo.lock
- crates/adapters/src/server/mod.rs
- crates/fda/src/cli.rs
- crates/fda/src/main.rs
- crates/feldera-types/src/program_schema.rs
- crates/pipeline-manager/Cargo.toml
- crates/pipeline-manager/src/api/api_key.rs
- crates/pipeline-manager/src/api/error.rs
- crates/pipeline-manager/src/api/http_io.rs
- crates/pipeline-manager/src/api/mod.rs
- crates/pipeline-manager/src/api/pipeline.rs
- crates/pipeline-manager/src/api/util.rs
- crates/pipeline-manager/src/db/types/program.rs
- crates/pipeline-manager/src/integration_test.rs
- crates/pipeline-manager/src/runner/main.rs
- demo/project_demo06-SupplyChainTutorial/run.py
- openapi.json
Restructures the API endpoint for starting (resuming) and pausing connectors.
Instead of requiring endpoint name (previous):
```
POST /v0/pipelines/{pipeline_name}/input_endpoints/{endpoint_name}/{action}
```
It now requires table and (input) connector name (new):
```
POST /v0/pipelines/{pipeline_name}/tables/{table_name}/connectors/{connector_name}/{action}
```
This is more user-friendly, as endpoints are not a user-facing concept. Case-(in)sensitivity and special characters are now handled by using URL encoding. Integration tests for orchestration are added.
The CLI tool `fda` has its `endpoint` subcommand replaced with the `table-connector` subcommand.
**Remaining:**
**Future PRs:**
- Add support for connector orchestration to the Python SDK …
> pipeline-manager: connector orchestration

- docs/sql/datetime.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/TimestampdiffTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/DateArithmeticTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
I will mark this as a draft for now.
A big problem is that merging this will invalidate many Python date arithmetic tests, and there is no easy way to rewrite them. These tests rely on the difference function to create INTERVAL values.
I have sent a question to the Calcite dev mailing list about the intended semantics of these operations.
I believe that most SQL dialects actually do not support this operation.
> [SQL] Restrict the kinds of results that can be produced by date subtraction (#3132)

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/transport/http/input.rs
- crates/pipeline-manager/src/runner/interaction.rs
This was reported in #3139.
The problem boils down to re-entrant read() locking that leads to the 2nd read() call blocking when you have an outstanding writer. Consider this code that locks up as an example of what was happening:
```
use std::sync::RwLock;
use std::thread;
use std::time::Duration;
static LOCK: RwLock<i32> = RwLock::new(42);
fn main() {
let r1 = LOCK.read().unwrap();
thread::spawn(|| {
let w1 = LOCK.write().unwrap();
});
thread::sleep(Duration::from_millis(100));
let r2 = LOCK.read().unwrap();
}
```
The performance of http input is still terrible OTOH we made it a little bit better by reducing the timeout but it doesn't go beyond a 200req/s, probably thanks to all the overheads of creating separate endpoints/locking for each POST request.
> Fixes deadlocks with input stats RwLock.

- deploy/Dockerfile
We needed this when the REST API was more complex and users needed
the swagger-ui / docs website to learn how the API works. These two
mechanisms have become somehwat stale.
The swagger-ui isn't easily discoverable by users anymore (we've stopped
showing it on the UI). The docs website does not allow users to
configure servers either.
This defaults to allowing all origins, which is appropriate for this
developer build.
> docker: remove stale default origins

- crates/fda/src/main.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/api/mod.rs
- crates/pipeline-manager/src/api/pipeline.rs
- crates/pipeline-manager/src/compiler/util.rs
- crates/pipeline-manager/src/db/types/pipeline.rs
- crates/pipeline-manager/src/integration_test.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/services.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
- web-console/src/lib/services/pipelineManager.ts
The `code` query parameter for the retrieval of a list of pipelines is replaced because it is not descriptive enough and its boolean value is not expressive enough. It is replaced by the `selector` query parameter, which can be set to `status` for only status-related information or `all` (default) for all fields. The internal fields of the pipeline descriptor are no longer included in the API response.
When POST or PUT a pipeline, currently the API requires supplying a value for all fields. This commit instead allows the `description`, `runtime_config`, `udf_rust`, `udf_toml`, and `program_config` to not be specified (or `null`). Fields `name` and `program_code` remain required.
This commit includes edits to the CLI client `fda` and the Web Console to handle the aforementioned API …
> pipeline-manager: pipeline GET selector and allow missing in POST/PUT

- benchmark/feldera-sql/benchmarks/tpc-h/generate.bash
- benchmark/feldera-sql/benchmarks/tpc-h/table.sql
- crates/adapterlib/src/catalog.rs
- crates/adapters/src/format/csv.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/adapters/src/test/mock_dezset.rs
- crates/adapters/src/transport/file.rs
- crates/feldera-types/src/format/csv.rs
- docs/formats/csv.md
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/using.md
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
TPC-H uses `|` instead of `,` and I'm sure that other datasets use other characters too.
> Support custom CSV delimiters

- crates/pipeline-manager/src/runner/interaction.rs
There seems to be a bug in reqwest that either caches or mixes up prior GET requests from the same client. This is a temporary fix, as the client should ideally be reused to improve performance.
> pipeline-manager: revert reuse of reqwest client

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPStreamAntiJoinOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPStreamJoinIndexOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ExpandJoins.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeMaps.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/Monotonicity.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPLiteral.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/derived/DBSPTypeStruct.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMonthsInterval.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/CastTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
Fixes #3154 
The previous implementation was only correct for joins on sets. The previous implementation used DISTINCT and EXCEPT (DBSP subtract) to compute the left and right sets that are added to an INNER JOIN when implementing an OUTER JOIN.
This implementation uses Anti Joins, a primitive DBSP operator, to correctly compute the correct "difference" between multisets.
The optimization that trims unused fields does not currently work with the code generated for an outer join, but this will be fixed in a future PR.
> [SQL] Correctly implement outer joins

- crates/pipeline-manager/src/runner/error.rs
The service is not available (503) rather than that an internal error (500) occurred.
> pipeline-manager: pipeline unreachable status code 503 instead of 500

- crates/adapters/src/transport/http/input.rs
When we replay steps during ft recovery, we don't initialize the http input adapter within the context of a tokio runtime, so we explicitly choose the runtime where we spawn the tokio task for the adapter.
> Make sure there is always a tokio runtime for http input.

- crates/fda/src/main.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/db/error.rs
- crates/pipeline-manager/src/db/types/program.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
- openapi.json
We add the compiler message to the corresponding error type in the manager to do that.
Fixes #3214
> Show compilation errors for pipeline in fda.

- crates/adapters/src/server/mod.rs
It took me some time to track down what `/metadata` is supposed to do, so here's a comment to save time later.
> dbsp_adapters: Add comments.

- web-console/src/lib/components/adhoc/Query.svelte
- web-console/src/lib/components/common/virtualList/HeadlessVirtualList.svelte
- web-console/src/lib/components/pipelines/editor/ChangeStream.svelte
- web-console/src/lib/components/pipelines/editor/ReverseScrollFixedList.svelte
Fix https://github.com/feldera/feldera/issues/2999: scrolling in changestream not working
> [WebConsole] Fix Change Stream and Ad-Hoc Query tables flicker in Safari

- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/api/metrics.rs
- crates/pipeline-manager/src/api/pipeline.rs
- crates/pipeline-manager/src/compiler/main.rs
- crates/pipeline-manager/src/compiler/rust_compiler.rs
- crates/pipeline-manager/src/compiler/sql_compiler.rs
- crates/pipeline-manager/src/db/operations/pipeline.rs
- crates/pipeline-manager/src/db/storage.rs
- crates/pipeline-manager/src/db/storage_postgres.rs
- crates/pipeline-manager/src/db/test.rs
- crates/pipeline-manager/src/db/types/pipeline.rs
- crates/pipeline-manager/src/integration_test.rs
- crates/pipeline-manager/src/metrics.rs
- crates/pipeline-manager/src/runner/interaction.rs
- crates/pipeline-manager/src/runner/local_runner.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
The manager currently retrieves all columns when retrieving a pipeline irrespective of which ones are needed, and only applies a filter at API endpoints. This becomes an issue when pipelines fields become very large, which in particular can occur for `program_code` and `program_info`. This results in unnecessarily high CPU usage.
This commit adds new and modifies some existing database operations to retrieve pipeline descriptors with only the fields relevant to monitoring. These operations are then used both internally when monitoring pipelines (e.g., by the SQL compiler, Rust compiler, and runners), as well as by the API endpoints when possible (e.g., when the field selector is `status`).
> pipeline-manager: reduce monitoring overhead

- docs/sidebars.js
- docs/sql/ad-hoc.md
- docs/sql/aggregates.md
- docs/sql/binary.md
- docs/sql/casts.md
- docs/sql/datetime.md
- docs/sql/decimal.md
- docs/sql/float.md
- docs/sql/function-index.md
- docs/sql/index.mdx
- docs/sql/json.md
- docs/sql/recursion.mdx
- docs/sql/string.md
- docs/sql/system.md
- docs/sql/table.md
- docs/sql/types.md
- docs/sql/udf.md
- Create a top-level page that we can link to directly instead of linking to one of the subsections.
- Reorder sections in a more logical way
- Consistent page names.
> [docs] Improve SQL doc structure.

- crates/pipeline-manager/src/compiler/rust_compiler.rs
This turned out to result in very large binaries (up to 1 GiB), so we decided to revert the change again.
This reverts commit 50b1491e8e3bc509ee6f4ad53f283b42226433f8.
> Revert "Add debug = true to Cargo workspace for pipelines."

- crates/adapters/src/server/error.rs
Until https://github.com/apache/datafusion/issues/14080 is fixed, we'll remove the `DataFusionError::External` strings from the error message displayed to clients.
temporary workaround for https://github.com/feldera/feldera/issues/3215
> Fix display of datafusion errors.

- crates/dbsp/src/storage/file/mod.rs
These warnings have been cropping up for me lately.  I don't know why.
> dbsp: Disable missing documentation warnings for test-only items.

- crates/pipeline-manager/src/runner/interaction.rs
This is another instance of read after write lock that I added by accident which can cause the pipeline-manager to become unresponsive
FWIW I think we should just replace all our std RwLock instances with parking lot RwLock which panics when you attempt to do this
Fixes #3307 (I hope)
> Fixes a RwLock deadlock in manager.

- README.md
Most doc references in README were broken. The tutorials link is still broken, I will fix it in a separate PR.
> Broken doc references inREADME.md

- crates/pipeline-manager/src/db/error.rs
- crates/pipeline-manager/src/db/operations/pipeline.rs
- crates/pipeline-manager/src/db/storage.rs
- crates/pipeline-manager/src/db/storage_postgres.rs
- crates/pipeline-manager/src/db/test.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
In the transition from `Shutdown` to `Provisioning`, there is a particular concurrency scenario:
1. User calls `/start` on pipeline (v1)
2. Runner picks up that desired state is `Running` and creates the deployment configuration (v1), but it has not yet stored it in the database
3. User calls `/shutdown`, making the pipeline editable again
4. User edits pipeline (e.g., runtime configuration) to become (v2)
5. User calls `/start`
6. The runner stores the transition to `Provisioning` in the database with deployment configuration (v1)
The above is unlikely to happen given the exact timing required. Nevertheless, this fixes it by adding a version guard such that at step (6) the runner does not transition but instead tries again next cycle.
> pipeline-manager: runner version guard

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/adhoc/format.rs
- crates/adapters/src/adhoc/mod.rs
- crates/fda/Cargo.toml
- crates/fda/src/cli.rs
- crates/fda/src/main.rs
- crates/fda/src/shell.rs
- crates/fda/test.bash
This fixes some problems from #2541.
Turns out that the issue (making pipeline unresponsive) was already fixed but the ad-hoc queries were still very slow if individual records have a lot of data in them.
> Fix issues with `text` format ad-hoc queries and huge records

- crates/fda/src/cli.rs
- crates/fda/src/main.rs
- crates/pipeline-manager/src/db/error.rs
- crates/pipeline-manager/src/db/operations/pipeline.rs
- crates/pipeline-manager/src/db/test.rs
- crates/pipeline-manager/src/db/types/program.rs
- crates/pipeline-manager/src/integration_test.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
Currently, the `runtime_config` and `program_config` fields are stored as the direct JSON that was supplied for them. As a consequence, they do not have any defaults set when supplied during POST, PUT or PATCH. As such, currently it is needed to look at the OpenAPI specification or the documentation generated from it to discover which parameters can be set and what their default values are. This is too inconvenient for the user at this moment, especially in the Web Console. In the future this might be sufficiently mitigated by linking to documentation and providing autocomplete.
This commit adds back the reserialization of `runtime_config` and `program_config`.
To illustrate, when a user supplies the following JSON for the `program_config`:
```
{
"profile": "unoptimized"
}
```
The …
> pipeline-manager: reserialize `runtime_config` and `program_config`

- Cargo.lock
- crates/pipeline-manager/Cargo.toml
- crates/pipeline-manager/src/db/storage.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
This commit changes the (de)serialization of JSON to preserve the order of the keys in a JSON object. The order as such will be the one in the Rust struct that it (de)serialized. This is particularly useful for the `runtime_config`, such that the most important properties `workers` and `storage` are at the top of the Web Console edit dialog. Note that JSON already stored in the database is not changed, and only new JSON stored will have the preserved order.
> pipeline-manager: preserve order when (de)serializing JSON

- crates/dbsp/src/operator/aggregate.rs
- crates/dbsp/src/operator/dynamic/aggregate/mod.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/DBSPCircuit.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPAggregateLinearPostprocessRetainKeysOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPControlledKeyFilterOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitGraph.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/LinearPostprocessRetainKeys.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/RemoveTable.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/expansion/ExpandOperators.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/graph/DFSOrder.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/nexmark/NexmarkTest.java
Fixes #3344.
Linear aggregation operators create an internal integral of the weighted stream, which is not exposed outside the operator and therefore cannot get GC'd using `integrate_trace_retain_keys`. This integral is usually small, but if the number of groups grows over time, it can keep growing unbounded. To fix this, we add a version of linear aggregation operators that take waterline as an extra argument and apply it to the internal aggregate.
> [dbsp] API to GC linear aggregates.

- crates/adapters/src/transport/s3/mod.rs
- crates/feldera-types/src/transport/s3.rs
- docs/connectors/sources/s3.md
- openapi.json
> s3: pass an endpoint_url argument to interact with non-AWS services

- docs/connectors/sources/s3.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Utilities.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/TestListener.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TestCase.java
This may save 50% of the running time for Java tests.
> [SQL] Use 'cargo check' instead of 'cargo test' for tests that have no data

- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/integration_test.rs
The pipeline action endpoint is now matched after the checkpoint endpoint, such that `/checkpoint` is not matched to the action endpoint. A test is added to check this behavior.
> pipeline-manager: reorder action and checkpoint API endpoints

- crates/dbsp/src/operator/dynamic/communication/shard.rs
- crates/dbsp/src/operator/dynamic/distinct.rs
- crates/dbsp/src/operator/dynamic/join.rs
- crates/dbsp/src/operator/join.rs
The implementation of `antijoin` did not account for the fact that the
right collection could have multiple values per key.  It called
`distinct` on the original collection, which only made values distinct.
With more than one value per key, the subsequent join could end up
returning entries with weights greater than the weight of the left
input, so that `minus` ended up creating outputs with negative weights.
The fix is to convert the right input into a z-set by projecting away
the value before joining.
Fixes https://github.com/feldera/feldera/issues/3365
> [dbsp] Fix antijoin for indexed z-sets.

- crates/pipeline-manager/src/api/endpoints/config.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_management.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/api/main.rs
- openapi.json
- Use the same declaration order for `utoipa::path` across all endpoints
- Update the tags to match the endpoint categories
- Update description of pipeline action endpoint to emphasize it sets desired state
- Update main API text to more closely describe current API
Part of the initiative to gradually improve the API.
> pipeline-manager: organize endpoints of API

- crates/adapterlib/src/errors/controller.rs
Can't really tell if it's an overall net benefit.
We don't have a good way to test/see error messages side-by-side before and after this change. But it does improve the errors reported by the S3 connector.
> Print root-cause for input/output errors.

- crates/pipeline-manager/src/api/endpoints/pipeline_management.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/db/types/program.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/services.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
The SQL compilation of large programs results in large Rust programs being generated, which are currently not used elsewhere by the API clients. As such, this commit removes the `main_rust` subfield of the `program_info` field at API level in order to speed up retrieval. Internally, the subfield is still present.
In addition, removes unnecessary cloning of fields when generating pipeline responses.
> pipeline-manager: remove `main_rust` from API GET endpoints

- crates/dbsp/src/operator/dynamic/join.rs
- crates/dbsp/src/storage/backend/mod.rs
The antijoin operator projects away values from the right input and then
applies `distinct` to it. If the input collection is sharded, then the
input to `distinct` will be sharded as well and doesn't require another
shuffle. We pass this information to DBSP via `mark_sharded_if`.
> [dbsp] Avoid sharding in antijoin.

- .github/workflows/ci.yml
I think this will prevent ci.yml from running twice
(in merge queue and for PRs). We have a branch
rule that it needs to pass all steps called `build` before being merged which according to
https://github.com/orgs/community/discussions/103114
is sufficient for checking that ci.yml passed.
> Remove ci.yml build from merge_queue trigger.

- crates/pipeline-manager/migrations/V21__refresh_version.sql
- crates/pipeline-manager/src/api/endpoints/pipeline_management.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/db/operations/pipeline.rs
- crates/pipeline-manager/src/db/storage.rs
- crates/pipeline-manager/src/db/test.rs
- crates/pipeline-manager/src/db/types/pipeline.rs
- crates/pipeline-manager/src/integration_test.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
Adds the `refresh_version` field to the pipeline. The `refresh_version` is incremented for the same fields as `version` but also including `program_info` as it contains information of interest to the user regarding the pipeline. It is a notification mechanism for users. If a user detects it changed while monitoring only the status fields, it should refresh fully (retrieve all fields). This will reduce the frequency at which the full pipeline with all fields needs to be retrieved.
> pipeline-manager: `refresh_version` field

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
Without this PR, adding lateness annotations on a view can cause a parse error, if the view's column is a reserved keyword which is quoted, e.g.:
```sql
CREATE VIEW V AS SELECT x as "timestamp" FROM t;
LATENESS V."timestamp" 0;
```
> [SQL] Quote column names when generating SQL code internally

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/transport/kafka/nonft/input.rs
- crates/nexmark/Cargo.toml
This PR fixes the issue where we failed to ingest zstd-compressed topic because the corresponding feature wasn't enabled in rdkafka. It also upgraded tot he latest rdkafka crate and improves error reporting in the non-FT Kafka connector.
> [adapters] Ingest zstd-compressed Kafka streams

- crates/pipeline-manager/src/compiler/rust_compiler.rs
- crates/pipeline-manager/src/compiler/sql_compiler.rs
- crates/pipeline-manager/src/compiler/util.rs
Until this commit, the cleanup interval was set to every minute. If it occurred that a pipeline SQL was insignificantly edited (i.e., not affecting the source checksum), and the Rust cleanup occurred during this time or while it was queued for Rust compilation, the files/directories for that source checksum would be cleaned up. When then the pipeline arrived at Rust compilation, it would recompile again.
This commit adds a time-based retention mechanism. When a source checksum is detected which is no longer in use, it will be marked for deletion in the future after the retention period is over. The retention state is stored in the file `cleanup_state.json` under the `rust-compilation` directory. It is still possible that a Rust compilation is so delayed due to SQL compilation or queuing, …
> pipeline-manager: fix cleanup retention of compiler server

- crates/dbsp/src/operator/asof_join.rs
- crates/dbsp/src/operator/chain_aggregate.rs
- crates/dbsp/src/operator/consolidate.rs
- crates/dbsp/src/operator/controlled_filter.rs
- crates/dbsp/src/operator/count.rs
- crates/dbsp/src/operator/delta0.rs
- crates/dbsp/src/operator/differentiate.rs
- crates/dbsp/src/operator/distinct.rs
- crates/dbsp/src/operator/inspect.rs
- crates/dbsp/src/operator/integrate.rs
- crates/dbsp/src/operator/join.rs
- crates/dbsp/src/operator/join_range.rs
- crates/dbsp/src/operator/neg.rs
- crates/dbsp/src/operator/neighborhood.rs
- crates/dbsp/src/operator/output.rs
- crates/dbsp/src/operator/plus.rs
- crates/dbsp/src/operator/recursive.rs
- crates/dbsp/src/operator/sample.rs
- crates/dbsp/src/operator/semijoin.rs
- crates/dbsp/src/operator/stream_fold.rs
- crates/dbsp/src/operator/sum.rs
- crates/dbsp/src/operator/trace.rs
- crates/dbsp/src/operator/z1.rs
- crates/dbsp/src/storage/backend/mod.rs
We use `track_caller` annotations to output the location in `main.rs` that instantiates each operator in the generated profile.  This commit adds a bunch of missing annotations. Unfortunately, we are still not able to track every operator's location because this is still unstable:
https://doc.rust-lang.org/beta/unstable-book/language-features/closure-track-caller.html
But this still improves profile readability.
> [dbsp] Missing track_caller annotations.

- Cargo.lock
- crates/dbsp/Cargo.toml
- crates/dbsp/src/circuit/metadata.rs
- crates/dbsp/src/operator/communication/exchange.rs
- crates/dbsp/src/operator/dynamic/distinct.rs
- crates/dbsp/src/operator/dynamic/filter_map.rs
- crates/dbsp/src/operator/dynamic/input.rs
- crates/dbsp/src/operator/dynamic/trace.rs
- crates/dbsp/src/operator/input.rs
- crates/dbsp/src/storage/buffer_cache/cache.rs
- crates/dbsp/src/storage/buffer_cache/mod.rs
- crates/dbsp/src/storage/file/cache.rs
- crates/dbsp/src/storage/file/reader.rs
- crates/dbsp/src/storage/file/writer.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/ord/fallback/indexed_wset.rs
- crates/dbsp/src/trace/ord/fallback/key_batch.rs
- crates/dbsp/src/trace/ord/fallback/val_batch.rs
- crates/dbsp/src/trace/ord/fallback/wset.rs
- crates/dbsp/src/trace/ord/file/indexed_wset_batch.rs
- crates/dbsp/src/trace/ord/file/key_batch.rs
- crates/dbsp/src/trace/ord/file/val_batch.rs
- crates/dbsp/src/trace/ord/file/wset_batch.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- Include input/output tuple counts in the profile for distinct, map, exchange, and trace-append operators.
- Some more missing #[track_caller] annotations (for input operators)
> [dbsp] Profiling improvements.

- crates/adapterlib/src/catalog.rs
- crates/adapters/src/format/mod.rs
- crates/adapters/src/format/raw.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/adapters/src/test/mock_dezset.rs
- crates/feldera-types/src/format/mod.rs
- crates/feldera-types/src/format/raw.rs
- crates/feldera-types/src/program_schema.rs
- crates/feldera-types/src/serde_with_context/serde_config.rs
- crates/sqllib/src/binary.rs
- docs/formats/raw.md
- docs/sidebars.js
The raw data format can be used to configure an input connector to pass raw, unparsed, data buffers from the transport connector to the SQL program.  Normally the byte stream received from the transport connector is parsed using the specified data format, e.g., JSON or Avro.  The parser converts the raw byte stream into a stream of SQL table records. In some cases it is preferable to pass the raw bytes to the SQL program unmodified and perform all parsing in SQL.  In particular this is useful for:
* **Custom data formats:** If the required data format is not supported by built-in parsers, raw data can be ingested into a SQL table and processed using a UDF.
* **Parallelized parsing**: Parsing large volumes of incoming data can become a performance bottleneck.  Offloading parsing to the SQL …
> [adapters] Raw input format.

- Cargo.lock
- crates/sqllib/Cargo.toml
- crates/sqllib/src/string.rs
- docs/sql/udf.md
- sql-to-dbsp-compiler/temp/Cargo.toml
The previous SqlString implementation was backed by `Arc<String>`,
which creates two heap allocations per string. This made creating and
deserializing strings, including from rkyv relatively expensive.  This
commit instead uses the `ArcStr` type from the `arcstr` crate, which
is a reference-counted string backed by a single memory allocation.
> [sqllib] Implement SqlString using arcstr

- crates/adapters/src/test/kafka.rs
Thanks to Simon Kassing for drawing my attention to this.
> [adapters] Improve panic message when the Kafka broker is down.

- crates/pipeline-manager/src/compiler/rust_compiler.rs
- crates/pipeline-manager/src/demo.rs
It should be a warning when unable to read a demos directory, as it will still start. This is necessary as by default a path is provided for the argument to have demos show up even when running from source.
Initially at the start of the first Rust compilation cleanup cycle, it will be unable to read the cleanup state file as there is none. It is however still useful information to have, as it shouldn't be deleted afterwards. Therefore it should be at debug level.
**Notes:**
- Thanks @mihaibudiu for mentioning the issue
- Fixes: https://github.com/feldera/feldera/issues/3409
> pipeline-manager: fix two error log prints

- crates/adapterlib/src/catalog.rs
- crates/adapters/src/integrated/delta_table/input.rs
- crates/adapters/src/integrated/delta_table/test.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/feldera-types/src/transport/delta_table.rs
- crates/sqllib/src/aggregates.rs
- openapi.json
- python/tests/aggregate_tests/test_decimal_stddev_pop.py
- python/tests/aggregate_tests/test_decimal_stddev_samp.py
In CDC mode the table behaves as an append-only log where every row represents an insert
or delete action.  The order of actions is determined by the `cdc_order_by`
property, and the type of each action is determined by the `cdc_delete_filter`
property.
In this mode, the connector does not read the initial snapshot of the table
and follows the transaction log starting from the version of the table
specified by the `version` or `datetime` property.
> [adapters] Experimental CDC mode for DeltaLake.

- crates/adapterlib/src/transport.rs
- crates/adapters/src/integrated/delta_table/input.rs
- crates/adapters/src/integrated/postgres/input.rs
- crates/iceberg/src/input.rs
Fixes https://github.com/feldera/feldera/issues/3487
Previously the DeltaLake connector read all columns from the Delta
table, including columns that were not part of the Feldera table
declaration. These columns get discarded during deserialization. Reading
only relevant columns instead reduces network traffic and speeds up
ingestion and parsing, especially for wide tables.
For now, we only optimize the backfill logic. Table following requires
extra care as the schema
>  [adapters] Only ingest Delta columns declared in SQL. 

- crates/adapterlib/src/catalog.rs
- crates/adapters/src/format/avro/test.rs
- crates/adapters/src/format/json/input.rs
- crates/adapters/src/format/parquet/mod.rs
- crates/adapters/src/format/raw.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/test/datagen.rs
- crates/adapters/src/test/mock_dezset.rs
- crates/adapters/src/test/mod.rs
Previously we parsed Parquet data by first converting it to JSON, which was highly inefficient. Since this code was written we added support for Arrow-based deserialization to `adapters`. This commit takes advantage of the ArrowStream API to parse Parquet data directly into a stream of RecordBatch's, which is several times more efficient.
> [adapters] Parse Parquet data using arrow.

- crates/adapterlib/src/format.rs
- crates/adapterlib/src/transport.rs
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/format/avro/output.rs
- crates/adapters/src/format/avro/test.rs
- crates/adapters/src/format/json/output.rs
- crates/adapters/src/format/parquet/test.rs
- crates/adapters/src/integrated/delta_table/output.rs
- crates/adapters/src/test/mock_output_consumer.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/http/output.rs
- crates/adapters/src/transport/kafka/ft/output.rs
- crates/adapters/src/transport/kafka/nonft/output.rs
- docs/formats/avro.md
Previously, the Avro encoder simply dropped deletions in raw mode. This commit changes the behavior to output both insertions and deletions, and use a Kafka header to encode operation type. I can imagine making this behavior more configurable, but I think this is strictly an improvement compared to silently dropping deletes.
> [adapters] Add operation type to raw Avro messages.

- Earthfile
- python/tests/aggregate_tests/aggtst_base.py
- python/tests/requirements.txt
- python/tests/test_udf.py
- python/uv.lock
- scripts/start_manager.sh
- sql-to-dbsp-compiler/SQL-compiler/sql-to-dbsp
- sql-to-dbsp-compiler/build.sh
Fixes: #3306
* 5 min for individual tests
* 1 hour for compiling aggregate tests
Also changes the shebang on the bash scripts to `/usr/bin/env bash` instead of `/bin/bash` as it doesn't exist in non Filesystem Hierarchy Standard compliant systems (like NixOS).
> ci: python: set test execution timeout

- crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs
This will allow larger (Parquet) file upload using the ingress endpoint.
> pipeline-manager: increase HTTP ingress timeout to 300s

- python/feldera/rest/_httprequests.py
- python/feldera/rest/config.py
- python/feldera/rest/feldera_client.py
- python/uv.lock
Adds parameter `requests_verify` to `FelderaClient`, this parameter is passed to the requests package while making HTTP requests.
If `requests_verify` is set to `False` then, SSL warnings are suppressed. `requests_verify` is set to `True` by default.
> py: support disabling SSL verification

- crates/dbsp/src/trace/spine_async/mod.rs
- crates/dbsp/src/trace/spine_async/thread.rs
This reverts commits b6d4603c7ab1a18f98e436a52e02f26362fcb0c6 and 3ffabef9bf5410f371615832c20ea99fae24524b.  They do not have egregious bugs but it seems like overall they cause slower and more irregular performance.
> [dbsp] Revert priority scheduler for spine merging

- crates/adapterlib/src/errors/controller.rs
- crates/adapterlib/src/utils/datafusion.rs
- crates/adapters/src/adhoc/table.rs
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/controller/validate.rs
- crates/adapters/src/server/mod.rs
- crates/feldera-types/src/config.rs
- docs/connectors/index.mdx
- docs/connectors/orchestration.md
- docs/sidebars.js
- openapi.json
Fixes https://github.com/feldera/feldera/issues/3535
Introduce two new connector attributes that support automatic connector orchestration:
* `labels` - attach arbitrary text labels to connectors
* `start_after` - start the connector once all connectors with specified labels have finished.
See https://github.com/feldera/feldera/issues/3535 for a detailed design discussion.
I added docs for the new feature and moved the connector orchestration section to a separate doc page, since it was getting too big.
TODO: The connector orchestration doc needs an explanation of the end-of-input flag (including the fact that only some of the connectors can reach the end of input and only with certain configuration options), and the API to check it. I plan to work on this in a separate PR, which will …
> [adapters] Automatic connector orchestration.

- crates/adapterlib/src/catalog.rs
- crates/adapters/Cargo.toml
- crates/adapters/src/format/avro/deserializer.rs
- crates/adapters/src/format/avro/input.rs
- crates/adapters/src/format/avro/schema.rs
- crates/adapters/src/format/avro/serializer.rs
- crates/adapters/src/format/avro/test.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/test/data.rs
- crates/adapters/src/test/mock_dezset.rs
The Avro parser did not previously support parsing decimal values.  The issue was that serde_avro::Decimal stores only the mantissa; scale must be extracted from the schema, so I had to modify the deserializer to thread the schema throughout the deserialization process.
I also simplified the deserializer by removing support for enums, which we don't currently use.  Finally I removed tests that we inherited from `serde_avro`, since they were a pain to maintain, and it's easier to keep extending our own tests in `avro/test.rs`.
> [adapters] Parsing for avro decimals.

- Cargo.lock
- crates/adapters/src/controller/mod.rs
- crates/dbsp/Cargo.toml
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/circuit/runtime.rs
- crates/feldera-types/src/config.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/db/test.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
In my testing, setting CPU affinity both speeds up the fastest that pipelines run, and reduces the variability between the fastest and slowest runs from over 2x to about 1.3x.
> [dbsp] Add CPU affinity support for pipelines.

- crates/dbsp/src/trace/ord/vec/wset_batch.rs
> [dbsp] Avoid dead code warning when compiling without debug assertions.

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- Cargo.lock
- Earthfile
- crates/adapterlib/Cargo.toml
- crates/adapters/Cargo.toml
- deploy/Dockerfile
Some time ago we started seeing serde_arrow errors due to unsupported
Utf8View type. This was caused by the new version of deltalake,
datafusion, and arrow crates generating schemas with view types. Back
then configuring
`datafusion.execution.parquet.schema_force_view_types=false` solved the
issue.  Recently a user shared an example creating a delta table using
polars with a recent version of the Python Arrow package that triggered
the same error in the `follow` mode. I am not sure how this is possible
given that `Utf8View` is an internal arrow type, which should be stored
as a regular string in Parquet.
Fortunately, the creator of serde_arrow recently added support for
Utf8View (https://github.com/chmp/serde_arrow/issues/252) in 0.13-rc.1,
so I was able to fix the issue by simply …
>  [adapters] Upgrade serde_arrow to handle Utf8View

- crates/pipeline-manager/src/api/endpoints/pipeline_management.rs
- crates/pipeline-manager/src/db/operations/pipeline.rs
- crates/pipeline-manager/src/db/storage.rs
- crates/pipeline-manager/src/db/storage_postgres.rs
- crates/pipeline-manager/src/db/test.rs
The start/pause/shutdown pipeline action info logging now displays the pipeline identifier instead of the name, which is in line with the other pipeline management endpoints. The consistency is important such that the log messages across the endpoints relate to each other. In addition, they must also relate to other internal logs (i.e., the compiler server and runner). The usage of pipeline identifiers might later be replaced with a 2-tuple (tenant id, name) or a different naming solution that is both not verbose and unique across tenants, however this change would be quite involved as it needs to be applied everywhere to have consistent logs. Currently with the pipeline identifier, an operator can `grep` the pipeline identifier to get all relevant lines in a log.
> pipeline-manager: pipeline identifier in pipeline action logging

- crates/feldera-types/src/error.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_management.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/db/error.rs
- crates/pipeline-manager/src/db/types/pipeline.rs
- crates/pipeline-manager/src/runner/interaction.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/services.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
This commit refactors duplicate status declarations (which caused only one of them to show), improves descriptions, removes statuses that cannot occur, and adds ones that are missing. In particular, this commit adds the `SERVICE_UNAVAILABLE` status for the pipeline interaction endpoints, which is information important for their correct usage.
> pipeline-manager: improve OpenAPI documentation

- web-console/src/lib/components/pipelines/editor/TabAdHocQuery.svelte
- web-console/src/lib/components/pipelines/editor/TabChangeStream.svelte
- web-console/src/lib/components/pipelines/editor/TabLogs.svelte
- web-console/src/lib/functions/pipelines/changeStream.ts
- web-console/src/lib/services/pipelineManager.ts
Fix streaming HTTP requests (e.g. logs) not cancelling when leaving context (page, tab etc.)
Steps to reproduce:
- Open WebConsole in Firefox
- Start a pipeline in local form factor and navigate between "Changes Stream" and "Logs" tabs 9 times
- Observe that the UI becomes unresponsive to certain actions (e.g. stop the pipeline)
> Fix streaming HTTP requests (e.g. logs) not cancelling

- .github/workflows/ci-integration.yml
Add a `workflow_dispatch` clause to the integration test script, so we can run it on-demand.
> Add workflow_dispatch to ci-integration.yml

- crates/adapters/src/integrated/delta_table/input.rs
- crates/adapters/src/util.rs
This patch improves error reporting when reading from Delta Lake. The DataFusionError type can wrap multiple errors from different crates. In case when the error is returned from object_store via the arrow crate, printing it using the Display trait outputs partial information about the error, e.g.,:
"Generic S3 error: error decoding response body"
This fix additionally prints the root cause of the error, e.g.:
"Generic S3 error: error decoding response body (root cause: operation timed out)"
> [adapters] Better arrow error reporting.

- Earthfile
- crates/pipeline-manager/src/bin/pipeline-manager.rs
- crates/pipeline-manager/src/config.rs
- deploy/Dockerfile
The `--preinstall-pg-embed` flag causes the pipeline-manager main to download the Postgres binaries, run the embedded instance, connect to it, and then immediately return. The benefit of this is that it doesn't need to download the Postgres binaries afterward.
- Fixes: https://github.com/feldera/feldera/issues/3642
> pipeline-manager: flag to preinstall pg-embed

- crates/dbsp/src/operator/dynamic/aggregate/chain_aggregate.rs
- crates/dbsp/src/operator/dynamic/aggregate/mod.rs
- crates/dbsp/src/operator/dynamic/asof_join.rs
- crates/dbsp/src/operator/dynamic/distinct.rs
- crates/dbsp/src/operator/dynamic/group/mod.rs
- crates/dbsp/src/operator/dynamic/input_upsert.rs
- crates/dbsp/src/operator/dynamic/time_series/radix_tree/partitioned_tree_aggregate.rs
- crates/dbsp/src/operator/dynamic/time_series/rolling_aggregate.rs
- crates/dbsp/src/operator/dynamic/upsert.rs
Fixes #3486
`seek_key_exact` is more efficient than `seek_key` as it takes advantage of the Bloom filter and possibly other future optimizations. Most of DBSP operators that use `seek_key` can use `seek_key_exact` instead, so we apply it wherever possible. In particular, using it in `input_upsert` makes ingesting data in tables with primary keys much more efficient.
> [dbsp] Use seek_key_exact more widely.

- crates/pipeline-manager/src/api/endpoints/config.rs
- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/config.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
Aligns the type of the `/config` endpoint denoted by the OpenAPI to what is returned.
Adjusts the `platform_version` depending on if it is the enterprise edition and whether a suffix (e.g., git commit hash) is provided:
- `x.y.z`
- `x.y.z+[suffix]`
- `x.y.z+enterprise`
- `x.y.z+enterprise.[suffix]`
... with `x.y.z` either the package version (open source) or the enterprise version.
> pipeline-manager: `/config` endpoint type and adjust `platform_version`

- web-console/src/lib/components/adhoc/Query.svelte
- web-console/src/lib/components/common/virtualList/HeadlessVirtualList.svelte
- web-console/src/lib/components/pipelines/editor/LogsStreamList.svelte
- web-console/src/lib/components/pipelines/editor/TabPipelineErrors.svelte
Now, when the results contain a single error it is displayed as a simple element, not in a virtual table
If the multiline error will appear after some ad-hoc results it will be displayed in a single line
The issue is this particular virtual table implementation does not support multiline rows
The proper fix is to display ad-hoc query results in a virtual list component that supports both multiline rows and native HTML tables, which requires an upstream contribution to a library we use
Fix https://github.com/feldera/feldera/issues/3630: Fix multiline ad-hoc error breaks the results table
Also: added ability to Ctrl+A only the content of a single ad-hoc query error
> [WebConsole] Fix long error content breaks adhoc results table

- crates/dbsp/src/dynamic/lean_vec.rs
The code that this fixes produced warnings like this:
```
warning: unexpected `cfg` condition value: `archive_le`
--> crates/dbsp/src/dynamic/lean_vec.rs:937:9
|
937 |         from_archived!(self.len) as usize
|         ^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: expected values for `feature` are: `backend-mode` and `default`
```
I think this is a bug in rkyv: it tests for the `archive_le` and `archive_be` features inside the macro implementation, which ends up testing dbsp's features instead of rkyv's.  The correct way to do it would be to test the feature outside the macro implementation, and use a different macro implementation depending on the feature set.  The bug wasn't visible before updating to Rust 1.85 (which starts warning about unknown features) but it was still there.
This commit …
> [dbsp] Avoid warnings for `from_archived`.

- crates/dbsp/src/circuit/runtime.rs
- crates/feldera-types/src/config.rs
- openapi.json
Before this commit, each foreground and background worker had cache size:
- If `cache_mib` was unset, 256 MiB.
- If `cache_mib` was set, `cache_mib / nworkers` MiB.
After this commit, each foreground and background worker has cache size:
- If `cache_mib` is unset, 128 MiB.
- If `cache_mib` is set, `cache_mib / nworkers / 2` MiB.
This change is meant to better implement what the documentation says, which is that `cache_mib` is the total cache size (not half the total) and that in its absence each worker gets 256 MiB (not 256 MiB times 2).
Fixes https://github.com/feldera/feldera/issues/3664.
> [dbsp] Fix cache sizing.

- crates/dbsp/src/lib.rs
This feature disables the tutorial, which we want in the docs.
> [dbsp] Don't include "backend-mode" in features for docs.rs.

- Cargo.lock
- crates/dbsp/Cargo.toml
- crates/dbsp/src/storage/file/format.rs
- crates/dbsp/src/storage/file/mod.rs
- crates/dbsp/src/storage/file/reader.rs
- crates/dbsp/src/storage/file/writer.rs
- crates/storage/src/block.rs
This fixes the problem that filters disappeared when restarting from a checkpoint with FT enabled.
> [dbsp] Write Bloom filters to layer files.

- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/operator/dynamic/filter_map.rs
- crates/dbsp/src/tutorial.rs
It isn't needed and it is not available if `backend-mode` is enabled.
This fixes a broken build on main.
> [dbsp] Don't use `FilterMap` in the tutorial or reference it in docs.

- web-console/src/lib/components/pipelines/editor/TabPerformance.svelte
The current unit formatting uses SI prefixes for orders of magnitude. This PR changes: G (Giga) -> B (Billion), P (Peta) -> Q (Quintillion)
Fix https://github.com/feldera/feldera/issues/3624: Use appropriate units for large numbers in the UI
> Change prefixes of number formatting to colloquial

- crates/feldera-types/src/config.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/db/test.rs
- crates/pipeline-manager/src/runner/error.rs
- crates/pipeline-manager/src/runner/local_runner.rs
- crates/pipeline-manager/src/runner/main.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
- crates/pipeline-manager/src/runner/pipeline_executor.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
The provisioning timeout can be set per pipeline using the `provisioning_timeout_secs` parameter in the runtime configuration. This is useful for pipelines with resources that take longer to provision than usual.
The poll periods in each deployment status are set by the automaton, and an explanation of each value is provided.
The setting of `initializing_timeout_secs` will be in a follow-up PR.
- Partial fix for: https://github.com/feldera/feldera/issues/3662
**Notes**
- Default initializing timeout 300s -> 600s
- Default provisioning timeout remains at 20s for local runner
> pipeline-manager: configurable provisioning timeout

- crates/adapters/src/integrated/delta_table/output.rs
We used to create a Delta Lake transaction on every step even if the output was empty. This patch only creates a transaction when there is some new data to add to the Delta table.
> [adapters] Don't write empty transaction to Delta.

- python/tests/test_pipeline.py
All tests that used `test_create_pipeline` and therefore transitively `test_delete_all_pipelines` were sometimes failing during deletion because they weren't shutdown. 
This explicitly calls shutdown before deleting these pipelines.
> [python] test_delete_all_pipelines: shutdown before deletion

- web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte
- web-console/src/lib/components/pipelines/PipelineNameInput.svelte
Fix https://github.com/feldera/feldera/issues/3694: Pipeline name edit (pencil) tooltip when you can't edit
> Add a tooltip to warn when can't edit the pipeline's name

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/annotation/MerkleHash.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainKeysOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainValuesOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/MerkleInner.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/MerkleOuter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToJsonInnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToJsonOuterVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/CanonicalForm.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/TestSerialize.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/DBSPParameter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/ICastable.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/IIndentStream.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/IndentStream.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/JsonStream.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/NullIndentStream.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/VariantTests.java
- sql-to-dbsp-compiler/slt/skip.txt
This is a step towards having circuits reuse storage after being restarted.
What this PR does is to add a method of fingerprinting operators based on Merkle trees (really DAGs in our case).
There is a visitor called `MerkleOuter` which computes a cryptographic hash value for each operator in a circuit.
This hash value will be used in the future to derive the name of the storage files that are keeping the data for this operator.
The hash has the property that if two nodes have the same hash, then very (very!) likely they are computing the same function.
The hash of an operator is computed by applying a hash function to the following strings:
- the hash of its inputs (recursively computed)
- the hash of the functions it is invoking
- other metadata the operator may have (e.g., column names …
> [SQL] Merkle-tree based operator naming

- crates/adapterlib/src/catalog.rs
- crates/adapters/src/integrated/delta_table/output.rs
- crates/adapters/src/integrated/delta_table/test.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/adapters/src/transport/file.rs
- crates/feldera-types/src/serde_with_context/serialize.rs
- docs/connectors/sinks/delta.md
- docs/connectors/sources/delta.md
Fixes #3286.
The Delta Lake format does not support efficient real-time deletes and updates.
To delete a record from a Delta table, one must first locate the record, which
often requires an expensive table scan. This limitation makes it inefficient to
directly write the output of a Feldera pipeline, which consists of both inserts
and deletes, to a Delta table.
To address this issue, we transform both inserts and deletes
into table records with additional metadata columns that describe the type and order
of operations. Specifically, this commit adds the following columns to the output
Delta table:
* `__feldera_op` -  Operation that this record represents: `i` for "insert" or `d`
for "delete".
* `__feldera_ts` -  Timestamp of the update, used to establish the order of
updates. Updates with …
> Support deletes in the Delta sink connector.

- crates/dbsp/src/operator/dynamic/join.rs
The join operator sorts outputs by timestamp, which is a noop for unit timestamps in the top-level circuit. It's likely not an expensive operation which should amount to a linear scan, but it's better to avoid it altogether.
> [dbsp] Small optimization in join.

- .github/workflows/build-rust.yml
- deploy/build.Dockerfile
This speeds up CI job by a few minutes. Rust build on x86 is down to 3 min and on arm down to 8 min with this.
I also figured out how to configure sccache to our docker build precompile step and the integration test but currently the cache hit rate is 0% because the build paths we form in the manager are not deterministic so I'm hoping the many-crates-pr will fix that and we should see some significant speedup once this in.
> Enable sccache for build-rust jobs.

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
This can be monitored with a command something like this:
```
watch -n.1 "curl -s -X 'GET' 'http://localhost:8080/v0/pipelines/<name>/stats' -H 'accept: application/json' | jq .global_metrics.runtime_elapsed_msecs"
```
> [adapters] Add `runtime_elapsed_msecs` to pipeline statistics.

- web-console/src/lib/components/pipelines/editor/TabPerformance.svelte
Do not truncate quantities in stats
This fixes a column "Processed records" that had the same value across all views, and avoids a situation where small changes to already large quantities are not visible
Display per-table and per-view metrics side-by-side when possible
> [WebConsole] Do not display total records processed in per-view metrics

- .github/workflows/build-docker-dev.yml
- .github/workflows/ci-post-release.yml
- .github/workflows/ci-release.yml
- .github/workflows/publish-crates.yml
- .github/workflows/publish-python.yml
- .github/workflows/test-adapters.yml
- CONTRIBUTING.md
- Cargo.lock
- README.md
- crates/dbsp/Cargo.toml
- crates/fda/Cargo.toml
- crates/feldera-types/Cargo.toml
- crates/pipeline-manager/Cargo.toml
- crates/sqllib/Cargo.toml
- crates/storage/Cargo.toml
- deploy/build.Dockerfile
- deploy/docker-compose-extra.yml
- deploy/docker-compose.yml
- docs/docker.md
- openapi.json
- python/pyproject.toml
- python/uv.lock
This provides a release action that does all the steps to release our software (currently still needs to be triggered manually, but if it works we can run this in nightly).
As opposed to updating the version with a commit before the release in the repo, we now set the versions to the next release after the release is done. This makes sure we can release a commit that passed the merge queue and has pre-built artifacts.
> Automate release in CI

- crates/adapters/src/controller/stats.rs
- crates/adapters/src/server/mod.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
Introduces the `/status` endpoint to the pipeline which solely returns the status (i.e., `Paused`, `Running`, or `Terminated`). This is useful for the pipeline automaton to only retrieve the minimal information it needs, as the endpoint is called frequently for monitoring. The endpoint is not (yet) directly exposed to the user, as it is folded into the `deployment_status` by the automaton. This might change in the future.
This commit is part of series of changes to replace the `/stats` endpoint which is used for too many purposes currently.
> pipeline: `/status` endpoint

- benchmark/feldera-sql/run.py
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/server/mod.rs
- crates/feldera-types/src/lib.rs
- crates/feldera-types/src/query_params.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs
- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/tests/integration_test.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/services.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
No longer serializes `metrics` as part of `/stats`.
Exposes the retrieval of circuit metrics to the user via `GET /v0/pipelines/{pipeline_name}/metrics`. The output format can be specified via the `format` query parameter, with two formats currently being supported: `prometheus` (default) and `json`.
This separate retrieval functionality is needed because metrics are no longer included in the `/stats` endpoint response.
This commit does not change the underlying snapshot mechanism which supplies the metrics, and as such does not improve or affect the existing performance overhead it incurs.
- Fixes: https://github.com/feldera/feldera/issues/3725
> pipeline-manager: pipeline interaction metrics endpoint

- crates/dbsp/src/operator/dynamic/trace.rs
- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/dbsp/src/trace/test/test_batch.rs
We used to assign each spine a unique ID and use this ID to generate metrics for the spine. This caused two issues. First, spine metrics weren't attributed to an operator. Second, there is at least one situation where a new spine is generated dynamically on every step (in a recursive fragment), which causes un unbounded number of gauges to be created over time.
The fix decouples metrics from a spine instance that generates them: metrics are stored in the operator, which invokes the spine to update them on-demand.
> [dbsp] Associate spine metrics with operators.

- crates/sqllib/src/lib.rs
- crates/sqllib/src/uuid.rs
- Expose `Map` type which previously couldn't be found in the docs
- Re-export some other types in the crate root consistent with other types
- Hides the modules removing unnecessary stuff that gets exposed
> Fixes for sqllib-docs

- docs/connectors/sinks/http.md
- docs/connectors/sinks/redis.md
- docs/connectors/sources/debezium.md
- docs/connectors/sources/http-get.md
- docs/connectors/sources/http.md
- docs/connectors/sources/iceberg.md
- docs/connectors/sources/postgresql.md
- docs/contributors/dev-flow.md
- docs/contributors/ui-testing.md
- docs/formats/avro.md
- docs/formats/json.md
- docs/formats/raw.md
- docs/get-started/docker.md
- docs/get-started/enterprise/helm-guide.md
- docs/get-started/enterprise/kubernetes-guides/eks/ingress.md
- docs/get-started/enterprise/quickstart.md
- docs/interface/index.mdx
- docs/interface/web-console.md
- docs/sql/grammar.md
- docs/sql/udf.md
- docs/tour/tour.md
- docs/tutorials/basics/part1.md
- docs/tutorials/basics/part2.md
- docs/tutorials/monitoring/index.md
- docs/tutorials/rest_api/index.md
- docs/use_cases/fine_grained_authorization/dynamic.md
- docs/use_cases/fraud_detection/fraud_detection.md
- python/docs/examples.rst
- python/feldera/rest/feldera_client.py
A user reported that DNS lookup significantly slowed down the entire Python SDK on Windows with Feldera running in WSL. So we skip the lookup by using 127.0.0.1 instead.
> [py] Use 127.0.0.1 instead of localhost.

- .gitignore
- crates/adapters/src/test/kafka.rs
- crates/adapters/src/transport/kafka/ft/input.rs
- crates/adapters/src/transport/kafka/nonft/input.rs
- crates/adapters/src/transport/kafka/nonft/test.rs
- crates/feldera-types/src/transport/kafka.rs
- docs/connectors/sources/kafka.md
- openapi.json
Implementation to support reading from a specific offset.
**Important Considerations:**
- The topic specified in `start_from` must also be included in `topics` field.
- If a topic has multiple partitions but only one partition is defined in
`start_from`, only that partition will be read.
**Example:**
```sql
CREATE TABLE INPUT (
... -- columns omitted
) WITH (
'connectors' = '[
{
"transport": {
"name": "kafka_input",
"config": {
"bootstrap.servers": "example.com:9092",
"topics": ["book-fair-sales"],
"start_from": [{
"topic": "book-fair-sales",
"partition": 0,
"offset": 42
}]
}
},
"format": {
"name": "json",
"config": {
"update_format": "insert_delete",
"array": false
}
}
}]'
)
```
The `start_from` field takes a list of JSON objects that must include the
following fields:
- `topic`: The …
> [adapters] kafka_input: start reading from offset

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/server/mod.rs
- crates/dbsp/src/circuit/circuit_builder.rs
We used to init operators with circuit id instead of operator's own id. So far this has only affected metrics, but going forward it will be used in more ways.
> [dbsp] Init operators with correct ids.

- crates/dbsp/src/mono/mod.rs
- crates/dbsp/src/operator/distinct.rs
- crates/dbsp/src/operator/dynamic/communication/shard.rs
- crates/dbsp/src/operator/dynamic/distinct.rs
We have noticed that the `distinct` operator can be very expensive for
collections with large keys. This commit introduces a new operator that
may solve this problem. It is a version of `distinct` that has the exact
same semantics, but internally it indexes the input collection by the
hash of the key before computing `distinct`.  This has the potential to
avoid the overheads related to reading, deserializing, and comparing
large keys.
I so far don't have any experimental validation that the new operator is
beneficial.
To take advantage of this, we will need to add logic to the compiler to
call `hash_distinct` instead of `distinct` when it expects the input
collection to have wide keys.
In addition, there are a couple of places where we use `distinct`
internally, most notably in …
> [dbsp] hash_distinct operator

- crates/adapters/src/integrated/delta_table/input.rs
We used to start reading the initial snapshot of a Delta table without waiting for the rest of the pipeline to initialize. No data was actually parsed or pushed to the pipeline, but the connector could issue a read request to the storage layer prematurely, and after that start waiting for pipeline state=RUNNING. This could cause S3 timeouts for pipelines that take a long time to initialize.
> [adapters] Delta source: wait for state=RUNNING.

- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/util.rs
- crates/feldera-types/src/config.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/db/test.rs
- openapi.json
Fixes #3663.
Use a thread pool to initialize multiple input/output connectors in parallel in order to reduce the startup time for circuits with many connectors that requires slow initialization (e.g., Delta).
> [adapters] Initialize connectors concurrently.

- crates/adapters/src/format/avro/deserializer.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/feldera-types/src/serde_with_context/serialize.rs
This is mostly intended to speed-up multi-crate compilation, but should also help with the single-crate setup by doing more work during precompilation.
> [adapters] Monomorphize erased serializers and deserializers early

- Cargo.lock
- crates/pipeline-manager/Cargo.toml
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/CrateGenerator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/MultiCratesWriter.java
- Organize existing dependencies in the `[dependencies]` section
- Add the pipeline crate dependencies `compare` and `tikv-jemallocator` such they are part of `Cargo.lock`
- Have the SQL compiler multi-crate compilation use `tikv-jemallocator` defined in the workspace
> pipeline-manager: refactor dependencies

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNestedOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/MerkleOuter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/recursive/RecursiveTests.java
Fixes #3740 
This ensures that the back-edges are used at least once in the hash computation
> [SQL] Global Merkle hashes in recursive components are computed twice

- Cargo.lock
- crates/adapters/src/adhoc/mod.rs
- crates/fda/Cargo.toml
- crates/fda/src/cli.rs
- crates/fda/src/main.rs
- crates/fda/src/shell.rs
- crates/feldera-types/src/query.rs
- openapi.json
JSON is unable to represent some datatypes we support like MAP with non-string keys so the serialization to JSON fails (https://github.com/feldera/feldera/issues/3546).
This adds a new query format for arrow ipc to the backend and fda. Using this formats the queries also work for map types with non-string keys.
Also adds support for parquet format to fda which was previously missing.
> Add Arrow IPC format for ad-hoc queries.

- Cargo.lock
- crates/adapterlib/Cargo.toml
- crates/adapters/Cargo.toml
- crates/adapters/src/adhoc/mod.rs
- crates/adapters/src/format/json/input.rs
- crates/adapters/src/format/json/output.rs
- crates/adapters/src/integrated/delta_table/test.rs
- crates/adapters/src/test/data.rs
- crates/adapters/src/transport/kafka/ft/input.rs
- crates/dbsp/benches/gdelt/main.rs
- crates/dbsp/src/dynamic/lean_vec.rs
- crates/dbsp/src/operator/output.rs
- crates/dbsp/src/utils/consolidation/quicksort.rs
- crates/feldera-types/Cargo.toml
- crates/feldera-types/src/serde_with_context/deserialize.rs
- crates/feldera-types/src/serde_with_context/mod.rs
- crates/feldera-types/src/serde_with_context/serde_config.rs
- crates/sqllib/src/array.rs
- sql-to-dbsp-compiler/temp/Cargo.toml
The `deserialize_table_record` macro generated Rust code that compiled very slowly. This commit improves compilation times significantly by breaking the code up into smaller functions and shoving dynamic dispatch down compiler's throat.
* Invoke `deserialize` for individual fields via dynamic dispatch, thus preventing these functions from getting inlined.
* Convert generared `visit_map` and `visit_seq` into loops.
* Use a static HashMap for field name lookups. This can potentially speed up the parsing of records with many fields, but I haven't run any benchmarks.
I've been testing this on a program that consists of ~10 tables with ~90 columns each. It reduces the number of generated LLVM code by ~30% and compilation time by approximately 2.5x (which shows that the compiler doesn't like …
> [adapters] Improve deserialize_table_record.

- crates/adapters/src/format/avro/output.rs
- crates/adapters/src/format/avro/test.rs
- crates/feldera-types/src/format/avro.rs
- docs/formats/avro.md
This PR refers to the `CREATE INDEX` mechanism, which hasn't been documented yet. I am writing those docs and will create another PR shortly. Wanted to get this in in the meantime.
---
Previously the Avro raw output format generated messages without the key component. This is problematic when sending to a Kafka topic with multiple partitions, since there is no way to ensure that messages with the same key are assigned to the same partition, while different keys are load balanced across all partitions. Depending on the Kafka config, we either end up with messages without a key assigned to random partitions, or to the same partition.
This commit adds the `key_mode` configuration option to the Avro output connector, which allows generating Kafka keys for output connectors with unique keys …
> [adapters] Avro raw format with keys.

- .github/workflows/build-java.yml
- .github/workflows/build-rust.yml
- .github/workflows/ci-post-release.yml
- .github/workflows/ci-pre-mergequeue.yml
- .github/workflows/publish-crates.yml
- .github/workflows/test-integration.yml
- .github/workflows/test-java.yml
- .github/workflows/test-unit.yml
- CONTRIBUTING.md
- Cargo.lock
- README.md
- crates/adapters/Cargo.toml
- crates/nexmark/Cargo.toml
- deploy/Dockerfile
- deploy/build.Dockerfile
Building Kafka with cmake started causing issues recently (most likely due to pip installing cmake 4.0 and this issue: https://github.com/confluentinc/librdkafka/issues/4594#issuecomment-2765371512)
This feature should only be needed on Windows, which we don't support anyway, so this commit removes it.  Hopefully this will make rdkafka builds less fragile in the future.
> [adapters] Remove cmake dependency for rdkafka.

- Cargo.lock
- crates/feldera-types/Cargo.toml
- crates/feldera-types/src/transport/kafka.rs
Every non-FT Kafka input connector needs a unique `group.id`.  Until now, uniqueness was ensured by using a timestamp in milliseconds.  Until commit d6d512e86ebf ("[adapters] Initialize connectors concurrently."), the connectors were initialized one-by-one.  Initialization took multiple milliseconds, at least, because it required a round trip to the broker. After that commit, though, the early phase of initialization that assigned `group.id` happened concurrently, so it was possible to get duplicate timestamps and therefore duplicate `group.id`s.
This commit fixes the problem by using a UUID instead.
With this commit, it might be possible to revert commit d047940fc161 ("[adapters] Serialize Kafka adapter initialization.").
Thanks to Simon Kassing for reporting the bug.
> [adapters] Make sure Kafka input connectors have unique group IDs.

- web-console/src/lib/components/pipelines/table/AvailableActions.svelte
Fix https://github.com/feldera/feldera/issues/3160: Shutdown button presence
> Allow shutting down Unavailable pipelines on home page

- crates/adapters/src/transport/kafka/ft/input.rs
- crates/adapters/src/transport/kafka/mod.rs
- crates/adapters/src/transport/kafka/nonft/input.rs
This reverts commit d047940fc161675b71a6e3d28a99dcda509b9e9f. Serialization of Kafka adapter initialization should no longer be necessary now that we fixed out the likely root cause for the problem with commit daade5140962 ("[adapters] Make sure Kafka input connectors have unique group IDs.")
> Revert "[adapters] Serialize Kafka adapter initialization."

- crates/adapters/src/transport/kafka/ft/input.rs
- crates/adapters/src/transport/kafka/ft/test.rs
For replay in Kafka, we need to make sure that we only read exactly the
messages in the range to be replayed.  In general, we're pretty good about
this, with one exception: initially, the maximum offset is set to 0
(inclusive).  If the first range of records to be replayed is empty (0..0),
then an initial maximum of 0 will allow in a record anyway.
This commit sets the initial maximum to i64::MIN instead, to fix the
problem.  (-1, or any other negative value, would also work.)
This bug manifested in a failure of the `empty_initial_input` test, e.g.:
```
2025-04-11T16:21:27.9716520Z thread 'transport::kafka::ft::test::empty_initial_input' panicked at crates/adapters/src/transport/kafka/ft/test.rs:240:26:
2025-04-11T16:21:27.9716629Z assertion `left == right` failed …
```
> [adapters] Don't read kafka message 0 if we're not queuing or replaying.

- crates/adapters/src/controller/stats.rs
> [adapters] Rename `run_uuid` to `incarnation_uuid`.

- crates/adapters/src/transport/kafka/ft/mod.rs
- crates/feldera-types/src/transport/kafka.rs
Fix a regression introduced in #3811.
We now link with openssl statically, which means that the default OPENSSLDIR location baked into openssl is not correct (see https://github.com/fede1024/rust-rdkafka/issues/594). We set `ssl.ca.location` to "probe" so that librdkafka can find the CA certificates in a standard location by default (e.g., /etc/ssl/).
> [adapters] ssl.ca.location defaults to probe.

- crates/adapters/src/server/mod.rs
Return type is now JSON for both success and failure.
This fixes the checkpoint test in the `pipeline-manager`.
> adapters: `/checkpoint` return type is JSON

- .github/workflows/build-docker-dev.yml
- .github/workflows/build-docker.yml
- .github/workflows/ci-release.yml
- .github/workflows/test-integration.yml
- demo/all-packaged/run.py
This seems to have gotten removed during the CI rework.
Additionally, fix `setup-buildx-action`.
> ci: validate and run packaged demos

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/NegativeParserTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
We produced a warning for UNION when the field names are permuted.
Turns out that we can produce the warning when the permutation is the identity permutation, and the types are not identical (because they differ in nullability). This case no longer produces a warning.
This used to appear in the sec-ops demo.
> [SQL] Remove incorrect warning

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
> [SQL] Do not report an internal compiler error for exceptions that derive from BaseCompilerException

- crates/sqllib/src/operators.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIndexedTopKOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/ToJsonInnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/dot/ToDotNodesVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/MultiCrates.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/ExpressionTranslator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/monotone/NonMonotoneType.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitRewriter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPComparatorExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPCustomOrdExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPDirectComparatorExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPFieldComparatorExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPNoComparatorExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPComparatorType.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeWithCustomOrd.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/CalciteJdbcTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/HRWinAggTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/RedshiftTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/SubQueryTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/WinAggPostTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
We support `FIRST_VALUE` and `LAST_VALUE` only if they are used with an `UNLIMITED RANGE`.
This is still useful, because `FIRST_VALUE` is generated by the Calcite decorrelator when decorrelating queries that contain `(ORDER BY ... LIMIT 1)`. This enables us to support such queries.
This partially fixes #3918.
Testing this has uncovered some bugs related to the sorting of `NULL` values and the handling of `NULLS LAST` and `NULLS FIRST`. Some tests were passing although they were incorrect, because they were tested on a system where `NULL`s compare largest. In our SQL dialect `NULL`s compare smallest (conveniently matches Rust, and cannot be easily changed).
We will write more tests for sorting as part of #3922
> [SQL] Implement (partially) `FIRST_VALUE` and `LAST_VALUE` window aggregation functions

- crates/adapterlib/src/catalog.rs
- crates/adapterlib/src/errors/controller.rs
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/integrated/delta_table/test.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/static_compile/catalog.rs
- crates/adapters/src/test/iceberg.rs
- crates/adapters/src/test/kafka.rs
- crates/adapters/src/test/mod.rs
- crates/adapters/src/transport/kafka/ft/test.rs
- crates/adapters/src/transport/kafka/nonft/output.rs
- crates/adapters/src/transport/redis/test.rs
- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/circuit/dbsp_handle.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/ViewMetadata.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/MerkleOuter.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/resources/metadataTests-generateDF.json
- sql-to-dbsp-compiler/SQL-compiler/src/test/resources/metadataTests-generateDFRecursive.json
- Add bootstrap_in_progress pipeline state, which is a substate of RUNNING.
Some API endpoints are disabled in this state: checkpoint, suspend, add input endpoint.
- Disable FT journal while bootstrapping; reenable it on the first checkpoint after bootstrapping.
- Disable input connectors during bootstrapping.
- Add `_persistent` versions of `register_XXX` catalog operators, which attach a persistent label to the output stream.
@blp , can you look at the changes in `controller/mod.rs` wrt how the new changes interact with FT. 
@mihaibudiu , this needs changes to the SQL compiler. All `register_input_` and `register_output_` methods now have `_persistent` variants, which is the unique label attached to the output operator. We should only use these variants in the generated SQL code.
> [adapters] Support for internal backfill. 

- crates/adapters/src/lib.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustVisitor.java
The compiler issued dbsp calls in this order:
1. circuit.add_input_map_persistent
2. catalog.register_materialized_input_map
3. operator_355307ae9ebfd547.set_persistent_id
2 and 3 being in the wrong order.  This resulted in the two output
streams created by register_materialized_input_map not getting
persistent ids.
> [sql] Fix persistent id assignment.

- .github/workflows/test-integration.yml
- crates/adapterlib/src/errors/controller.rs
- crates/adapters/src/server/mod.rs
- crates/pipeline-manager/tests/integration_test.rs
- python/tests/test_pipeline.py
Remove the pipeline and connector configuration from the `/stats` response. Only for the connector configuration the `stream` field remains as it is used by the Web Console Performance tab for aggregating statistics across tables and views.
> adapters: remove configuration from `/stats`

- Cargo.lock
- Cargo.toml
- crates/adapters/Cargo.toml
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/test.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/static_compile/catalog.rs
- crates/adapters/src/test/mod.rs
- crates/dbsp/Cargo.toml
- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/ir.rs
- crates/dbsp/src/lib.rs
- crates/dbsp/src/operator/output.rs
- crates/dbsp/src/profile/mod.rs
- crates/dbsp/src/utils/dot.rs
- crates/ir/Cargo.toml
- crates/ir/src/hir.rs
- crates/ir/src/lib.rs
- crates/ir/src/lir.rs
- crates/ir/src/mir.rs
- scripts/bump-versions.sh
- sql-to-dbsp-compiler/temp/Cargo.lock
Define Low-Level DBSP IR and implement LIR extraction from a DBSP circuit.
This is the simplest possible implementation. We can change and improve
it as we start using it to build the profiler.
Notes:
* I did not attempt to unify LIR and MIR formats, although I think it is feasible to do so if we think it will simplify tool development.
* The LIR is currently flat: it doesn't specify the boundaries of recursive circuits and logical operator groupings. The former should probably come from MIR (but currently it doesn't). The latter we can add easily in the future.
* DBSP doesn't number output streams of an operator, so that correspondence is lost between MIR and LIR. It is possible to fix this if necessary.
* The mapping between MIR and LIR is done by assigning MIR operator ID's as labels …
> Low-level DBSP IR

- crates/adapters/src/controller/stats.rs
- crates/pipeline-manager/tests/integration_test.rs
The suspend_errors field can contain endpoint names, which we don't want to expose as part of pipeline metrics. We therefore move it out of the GlobalControllerMetrics struct into ControllerStatus.
> [adapters] Move suspend_errors from global metrics

- crates/adapters/src/integrated/delta_table/input.rs
Output root cause of the error when opening a delta table fails. This is likely to generate error messages that report the same error twice, but can also produce some useful additional information in some cases.
> [adapters] Delta: add root cause to error message.

- crates/adapters/src/controller/test.rs
Depending on the order of connector initialization, the test randomly failed because of the missing input file. Remove bogus input connectors from the test pipeline config.
> [adapters] Fix lir test.

- crates/dbsp/src/storage/file/reader.rs
We used FBuf length to measure the amount of cache capacity occupied by an FBuf; however FBuf's actual heap usage is determined by its capacity, which can be larger than size.
> [dbsp] Account for full FBuf capacity in the buffer cache.

- crates/adapters/src/controller/test.rs
Fixes #3950.
- controller::test::ft_without_checkpoints_with_pauses was failing because of a race condition. The test needs to wait for the pause connector command to get written out to the journal. It did this by waiting for the step_requested flag, which doesn't actually guarantee that the step is started. I added an extra sleep, which isn't ideal, but seems to do the trick.
- Three other tests were failing on my MacOS laptop because their checkpointing timeouts were too short.
> [adapters] Fix FT tests.

- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/pipeline-manager/src/api/main.rs
- openapi.json
- web-console/src/lib/components/pipelines/editor/TabAdHocQuery.svelte
- web-console/src/lib/compositions/health/systemErrors.ts
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/services.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
- web-console/src/lib/types/pipelineManager.ts
Fix mocked /pipeline/{x}/stats endpoint response types not up to date
This is a regression after the /stats endpoint was changed. It is untyped, so manually mocked types went out-of-sync, so the type error due to a breaking change did not occur.
To reproduce, try running the fololwing program:
```
CREATE TABLE binary_data ( 
entry VARBINARY
) WITH (
'materialized' = 'true',
'connectors' = '[{
"transport": {
"name": "datagen",
"config": {
"plan": [{
"limit": 1,
"fields": {
"entry": { "values": ["a"] }
}
}]
}
}
}]'
);
```
> [WebConsole] Fix page crashing when any connector error happens

- crates/pipeline-manager/src/api/endpoints/pipeline_management.rs
- crates/pipeline-manager/src/compiler/test.rs
- crates/pipeline-manager/src/db/operations/pipeline.rs
- crates/pipeline-manager/src/db/storage.rs
- crates/pipeline-manager/src/db/test.rs
- crates/pipeline-manager/src/db/types/pipeline.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
- crates/pipeline-manager/tests/integration_test.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
- web-console/src/lib/services/pipelineManager.ts
The `program_error` field contains further compilation details including logs, which are better not to include in the status as the details can be on the larger side and are not directly relevant to display of status. This commit moves the `program_error` to only the complete retrieval. In addition, whenever `program_error` is changed, there also is an increment of `refresh_version`.
- Fixes: https://github.com/feldera/feldera/issues/3965
> pipeline-manager: move `program_error` away from status

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ModifyTableTranslation.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/DBSPMinMax.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/NonLinearAggregate.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPArrayExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPIndexedZSetExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPZSetExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/IDBSPContainer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Utilities.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresTimestampTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/MultiViewTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/NaiveIncrementalTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/Change.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/SqlIoTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TableParser.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/TestCase.java
- sql-to-dbsp-compiler/slt/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
Didn't mean to do this, but I got fed up.
This may speed up the Java tests by roughly 2x
> [SQL] Speed-up Java tests by avoiding generating repeated Rust code for inputs common to many tests

- web-console/src/routes/(system)/(authenticated)/(pipelines)/pipelines/+page.ts
This PR fixes the bad UX resulting from the confusion when navigating the WebConsole.
The issue was some users occasionally experiencing a 404 not found error.
The reason was when the users had some issue with the pipeline on a page e.g. https://cluster.staging.com/pipelines/broken-pipeline/, where the page would become unresponsive.
They then would edit the url in the browser by hand, removing the last path element - to end up with http://cluster.staging.com/pipelines/ and hit Enter.
This is not a home page of the WebConsole - that would be located on http://cluster.staging.com/
So they would end up requesting a non-existing page and getting a 404 page.
Then the browser would store the URL http://cluster.staging.com/pipelines/ and suggest it as an auto-complete when people would start …
> [WebConsole] Redirect users ending up on '/pipelines/' URL to '/'

- docs/get-started/docker.md
- docs/tutorials/basics/part3.md
- docs/tutorials/rest_api/index.md
This is no longer included in the release artifacts, so pull it straight off the `main` branch.
> docs: fix broken docker-compose.yml download links.

- crates/dbsp/src/trace/mod.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/sqllib/src/string.rs
This adds information on per-slot occupancy and merging batches to circuit profiles for spines, to aid in debugging.
> [dbsp] Add slot occupancy information in circuit profiles.

- crates/dbsp/src/trace/ord/fallback/mod.rs
- crates/dbsp/src/trace/ord/fallback/utils.rs
- crates/dbsp/src/trace/spine_async/mod.rs
A user has a workload that produces very large batches in intermediate operators that can in some cases exceed the memory size.  This commit adds a stopgap measure to spill those batches to disk before they would first be merged in the ordinary course of operations for merger, which should make it less likely that they will run the system out of memory.
> [dbsp] Spill to storage very large batches at insertion into the spine.

- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/profile/mod.rs
The immediate use case for this is being able to match operators in the profile back to SQL by including operator's persistent id's in the profile.
> [dbsp] Add node labels to profiles.

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/server/error.rs
- crates/adapters/src/server/mod.rs
When the pipeline manager triggers a suspend, it would prefer to shut down the process itself, rather than to have the process exit on its own.
> [adapters] Make suspend stop the circuit but not shut down the process.

- crates/adapterlib/src/catalog.rs
- crates/adapters/src/format/avro/output.rs
- crates/adapters/src/format/avro/test.rs
- crates/adapters/src/integrated/postgres/output.rs
- crates/adapters/src/static_compile/seroutput.rs
- crates/adapters/src/util.rs
Output detailed information about unique key violations in output connectors, including:
* key that had non-unique outputs
* error type: duplicate records, or multiple unique records for the same key.
* list all updates associated with the key.
> [adapters] Print details of unique key violations.

- web-console/src/lib/components/pipelines/editor/TabPerformance.svelte
Disambiguate the message when pipeline is not running and has not reported usage
Fix [The performance tab says "Pipeline is not running" when it is](https://github.com/feldera/feldera/issues/3935)
> [WebConsole] Fix tables and views performance tables forced to the same height

- crates/storage/src/tokio.rs
This may help with stack-overflow happening in ad-hoc queries.
> Increase stack size of tokio tasks.

- .github/workflows/test-adapters.yml
This wasn't previously possible because blacksmith didn't have ubuntu 24.04 runners for arm, but now they added them.
> [ci] enable adapter tests on aarch64.

- docs/operations/guide.md
- docs/sidebars.js
This page is more cross-cutting than I'd like, but I wanted to start somewhere. Ideally, each connector type would have its own troubleshooting section too.
> docs: add a troubleshooting page

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustInnerVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/ImmutableSetopOptimizerRule.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SetopOptimizerRule.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/InnerRewriteVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/IsolatedTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpchTest.java
- sql-to-dbsp-compiler/build.sh
Fixes #3863 
Fixes #3936 
Fixes #3913
This also enables compiling some classes of correlated subqueries which couldn't be compiled previously.
> [SQL] Migrate to new Calcite version

- crates/adapterlib/src/transport.rs
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/controller/test.rs
- crates/adapters/src/format/parquet/test.rs
- crates/adapters/src/integrated/delta_table/input.rs
- crates/adapters/src/integrated/delta_table/test.rs
- crates/adapters/src/test/datagen.rs
- crates/adapters/src/test/mock_input_consumer.rs
- crates/adapters/src/transport/adhoc.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/http/input.rs
- crates/adapters/src/transport/kafka/ft/input.rs
- crates/adapters/src/transport/kafka/ft/test.rs
- crates/adapters/src/transport/nexmark.rs
- crates/adapters/src/transport/pubsub/test.rs
- crates/adapters/src/transport/s3/mod.rs
- crates/adapters/src/transport/url.rs
- crates/datagen/src/lib.rs
Support suspend/resume and at-least-once FT in the delta connector.  The state of the connector is checkpointable after the initial snapshot at the boundary between transaction log entries.
Fixes #3884 
Fixes #4026 
@blp , I tried my best to use the new barrier API correctly, but this needs your review.
> [adapters] Delta connector suspend/resume support.

- crates/dbsp/src/operator/dynamic/recursive.rs
- crates/dbsp/src/trace/spine_async/list_merger.rs
The ListMerger algorithm assumed that an individual batch cannot contain zero-weight entries. This is correct, except when applying a map function to times in the batch, which can map records with different timestamps to the same timestamp, in which case such entries can cancel each other out.  This happens as part of lazy trace compaction where we consolidate entries with old timestamps that are no longer distinguishable to the algorithm.
Fixes #4028
> [dbsp] Fix invalid assumption in list merger.

- crates/sqllib/src/operators.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/RustSqlRuntimeLibrary.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPOpcode.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
- sql-to-dbsp-compiler/slt/skip.txt
Fixes #4032 
This is a bug introduced in #4017 when we switched to our own implementation of `NULLIF`.
It turns out that we didn't get the semantics quite right.
> [SQL] Correct implementation of NULLIF

- .gitignore
- Cargo.lock
- crates/adapters/Cargo.toml
- crates/adapters/src/transport/kafka/ft/input.rs
- crates/adapters/src/transport/kafka/ft/mod.rs
- crates/adapters/src/transport/kafka/ft/output.rs
- crates/adapters/src/transport/kafka/ft/test.rs
- crates/adapters/src/transport/kafka/mod.rs
- crates/adapters/src/transport/kafka/nonft/output.rs
- crates/feldera-types/src/transport/kafka.rs
- docs/connectors/sinks/kafka.md
- docs/connectors/sources/kafka.md
- openapi.json
Uses the `OAUTHBEARER` `sasl.mechanism` to support IAM based authentication and SASL / SSL.
There are some todos like inserting timeouts while trying to get the bearer token, unsure what a good timeout period would be.
Before fetching the metadata, it is important to call `poll` to set the bearer token, this is currently done in a hacky way outside the `count_partitions_in_topic` method. This should be improved.
Also, the code to fetch the bearer token across different contexts is repeated and identical. We should extract this out in one place.
More importantly, it might cause a regression in end to end performance with Kafka.
```
"sasl.mechanism": "OAUTHBEARER",
"security.protocol": "SASL_SSL",
```
> adapters: kafka: support AWS MSK IAM SASL

- crates/pipeline-manager/src/runner/interaction.rs
- web-console/src/lib/compositions/useAggregatePipelineStats.svelte.ts
- web-console/src/lib/functions/pipelines/status.ts
> Improvements to suspend/resume functionality.

- crates/pipeline-manager/tests/integration_test.rs
This is currently required by our k8s test setup.
> [manager] Add 10-second delay in suspend test.

- web-console/src/lib/components/adhoc/Query.svelte
- web-console/src/lib/components/layout/pipelines/PipelineMemoryGraph.svelte
- web-console/src/lib/components/layout/pipelines/PipelineStorageGraph.svelte
- web-console/src/lib/components/layout/pipelines/PipelineThroughputGraph.svelte
- web-console/src/lib/components/pipelines/editor/TabAdHocQuery.svelte
Make performance graphs scroll smoothly
Fix https://github.com/feldera/feldera/issues/4012: adhoc query table in dark mode is white cell bg with white text
> [WebConsole] Fix white lines in AdHoc query results in dark mode

- crates/pipeline-manager/src/config.rs
- crates/pipeline-manager/src/db/storage_postgres.rs
- crates/pipeline-manager/src/db_notifier.rs
- Make providing a PEM file optional (system certs will be used to verify if nothing is provided)
- Make code a bit easier by always making a TlsConnector. I read the postgres-tokio code and this is ok as it will respect the cases where sslmode=never is set.
- Add a flag to disable TLS verification. This helps with debugging things.
> PostgreSQL TLS connection improvements.

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/transport/clock.rs
- crates/adapters/src/transport/mod.rs
- crates/feldera-types/src/config.rs
- crates/feldera-types/src/format/json.rs
- crates/feldera-types/src/serde_with_context/serde_config.rs
- crates/feldera-types/src/transport/clock.rs
- crates/feldera-types/src/transport/mod.rs
- crates/pipeline-manager/src/compiler/sql_compiler.rs
- openapi.json
Fixes #3987
Fixes #2803
This PR re-implements the clock that drives the value of NOW() as an input connector, and also enforces clock resolution more strictly.
Previous design
---------------
The value of NOW() used to be provided by a generator running inside the circuit. In addition, the circuit controller had the logic to trigger a step every `clock_resolution_usecs`. There were two problems with this design:
* It didn't work with fault tolerance as there was no way to deterministically replay clock ticks (issue #2803)
* The clock resolution setting only controlled the frequency of the steps, but not the actual resolution at which the clock changed. Even if clock resolution was set to 1 hour, the value of NOW() was still updated on every invocation. This could trigger very expensive …
> [adapters] Re-implement the NOW() clock as a connector.

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/transport/clock.rs
- crates/adapters/src/transport/mod.rs
- crates/feldera-types/src/config.rs
- crates/feldera-types/src/format/json.rs
- crates/feldera-types/src/serde_with_context/serde_config.rs
- crates/feldera-types/src/transport/clock.rs
- crates/feldera-types/src/transport/mod.rs
- crates/pipeline-manager/src/compiler/sql_compiler.rs
- openapi.json
Second attempt to merge the new implementation of the NOW() clock with several postfixes.
The first commit is the exact same PR that was merged a few days ago and later revered. Postfixes are added as separate commits.
> [adapters] Re-implement NOW() using adapter - take 2.

- crates/adapters/src/integrated/delta_table/test.rs
Fixes #4097.
The tests suspended the pipeline without waiting for the first input batch to be fully processed.
> [adapters] Fix delta suspend test.

- crates/pipeline-manager/src/db/error.rs
- crates/pipeline-manager/src/db/operations/pipeline.rs
- crates/pipeline-manager/src/runner/error.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
- Only the `runtime_config` field can be edited while suspended, with the exception of its `workers`, `storage` and `fault_tolerance` fields
- Dedicated error types for suspend-and-resume
> pipeline-manager: suspend fixes

- crates/adapters/src/format/avro/input.rs
- crates/adapters/src/format/avro/schema.rs
- crates/adapters/src/format/avro/serializer.rs
- crates/adapters/src/format/avro/test.rs
Serialize/deserialize SQL `BINARY` and `VARBINARY` types to/from Avro `bytes` and `fixed` types.
> [adapters] Avro: improve handling of binary types.

- crates/adapters/src/controller/mod.rs
- crates/feldera-types/src/config.rs
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/db/storage_postgres.rs
- crates/pipeline-manager/src/db/test.rs
- crates/pipeline-manager/src/db/types/pipeline.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
- openapi.json
- web-console/src/lib/services/manager/schemas.gen.ts
- web-console/src/lib/services/manager/services.gen.ts
- web-console/src/lib/services/manager/types.gen.ts
Add the `checkpoint_during_suspend` field (default: `true`) to the runtime configuration. This boolean field determines during suspend whether the circuit is first checkpointed and terminated, before the compute resources are deprovisioned (i.e., the `SuspendingCircuit` phase). If it is `false`, that phase is skipped while transitioning towards `Suspended`, going immediately to `SuspendingCompute`.
> pipeline-manager: suspend without checkpoint

- crates/datagen/src/lib.rs
The adapter relied on the `running` flag to decide when to stop polling. However setting `running` to false after EOI doesn't guarantee it will stay there, since the controller can still send an Extend request to the adapter, setting `running` to true. The fix is to additionally check for the `eoi` flag and to park the thread if it's true.
> [adapters] Fix EOI handling in datagen.

- Cargo.lock
- crates/dbsp/src/circuit/checkpointer.rs
- crates/dbsp/src/trace/spine_async/mod.rs
- crates/storage/Cargo.toml
- crates/storage/src/error.rs
- crates/storage/src/lib.rs
JSON is easier for outside tools and humans and, unlike `rkyv`, it is stable and doesn't change from one release to another.
> [dbsp] Use JSON for `pspine-batches-*` and `checkpoint.feldera`.

- Cargo.lock
- Cargo.toml
Use v0.13.4, which includes this fix:
https://github.com/chmp/serde_arrow/pull/277.
> [adapters] Bump serde-arrow crate.

- .github/workflows/test-java.yml
This job is very inefficient and hence expensive to run on the blacksmith arm runners. I migrate this to our own runners Need to migrate the rest too but it some need code changes, but I'm pretty sure this one will "just work".
> Run java tests on self-hosted arm.

- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/circuit/runtime.rs
- crates/dbsp/src/circuit/schedule/mod.rs
- crates/dbsp/src/operator/condition.rs
- crates/dbsp/src/operator/dynamic/aggregate/mod.rs
- crates/dbsp/src/operator/dynamic/distinct.rs
- crates/dbsp/src/operator/dynamic/recursive.rs
Fixes #4168.
A DBSP circuit with multiple independent recursive fragments (which schedulable at the same time) could deadlock.
What happened:
- Worker thread 1 starts executing recursive fragment 1.
- At the end of each iteration it checks termination condition, which requires waiting for a notification from all other workers.
- Worker thread 2 picks a different recursive fragment and blocks waiting for a notification from thread 1.
The fix uses async notifications instead of sync blocking, which allows the circuit to continue evaluating other operators while waiting for other threads. This way in the above scenario worker 1 can evaluate the second recursive fragment and unblock worker 2.
> [dbsp] Fix deadlock w multiple recursive fragments

- python/tests/orderby_tests/automate_orderby_views.py
- python/tests/orderby_tests/main.py
- python/tests/orderby_tests/orderby_binary_ts.py
- python/tests/orderby_tests/orderby_int.py
- python/tests/orderby_tests/orderby_tbl_manual.py
- python/tests/orderby_tests/orderby_tbl_sqlite.py
- python/tests/orderby_tests/orderby_varchar.py
- python/tests/orderby_tests/sqlite_runner.py
**Changes:**
1. Added mechanism to skip table creation in SQLite for unsupported data types
2. Modified the table name in view definition for views that reference the table `orderby_tbl_sqlite_int_varchar`(was previously `orderby_tbl_int_varchar`)
3. Added manual tests for data types unsupported in SQLite but supported in Feldera
4. Added automated tests for data types supported in both SQLite and Feldera
> py: add new orderby tests

- Cargo.lock
- crates/fda/Cargo.toml
- crates/fda/bench_openapi.json
- crates/fda/build.rs
- crates/fda/src/bench/api.rs
- crates/fda/src/bench/mod.rs
- crates/fda/src/cli.rs
- crates/fda/src/main.rs
This adds a benchmark command for fda which makes it easier to track basic metrics (memory, storage and throughput) in CI.
Also fixes a bug with the cache-disabler that tried to change the pipeline settings in the Drop handler which no longer works since we changed the part
where we can modify the pipeline settings at any time.
> Add `fda bench` command.

- Cargo.lock
- Cargo.toml
This commit switches to our form of the delta-rs project, which attempts to open delta tables despite unsupported reader features.  Instead of failing, it simply prints the following warning:
```
WARNING: Unsupported reader features required: [DeletionVectors]
```
> [adapters] Ignore unsupported delta lake features.

- crates/datagen/src/lib.rs
- crates/pipeline-manager/tests/integration_test.rs
Makes it easier to measure storage amplification in benchmarks. Thanks @blp for pointing out the mistake.
> Record ingested bytes in datagen.

- crates/adapters/src/transport/s3/mod.rs
The input connector only checked for pause requests between objects. Objects can be multiple gigabytes, so this is not granular enough.  This commit fixes the problem.
Fixes https://github.com/feldera/feldera/issues/4217.
> [adapters] Honor pause requests in s3 input connector.

- .github/workflows/ci-release.yml
While the release took the right SHA for container and artifacts, it didn't actually use the right SHA for the release page on github and instead created it on the latest HEAD.
> Fix the release sha for release page.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/AggregateCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java
Fixes a regression introduced with the UNSIGNED numbers PR in the computation of non-linear aggregates.
Bug found by nightly SLT tests.
> [SQL] Fix incorrect non-linear aggregate result for empty sets

- crates/adapters/src/controller/stats.rs
- crates/adapters/src/server/mod.rs
The code for `/stats` in the server generated the controller status then edited it to remove configuration details.  I assumed this was because there are other code paths that do want to serialize those configuration details, but I couldn't find any (even by removing the `Serialize` implementation and then checking the compiler errors).  Therefore, this commit simply changes the Serialize implementation to avoid serializing the data we don't want.
> [adapters] Serialize desired `ControllerStatus` instead of post-editing.

- crates/adapters/Cargo.toml
By default, `memory-stats` tries to read `/proc/$pid/smaps`, which for our pipeline process could be over a megabyte and for which the kernel does a lot of computation.  Use the `always_use_statm` feature to avoid that, so that it only read `/proc/$pid/statm`, which is only a few bytes long and easy for the kernel to compute.
I found that I was seeing a lot of calls to the `/stats` endpoint blocking in memory_stats, and this fixed that.
> [adapters] Make collecting memory stats cheaper.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/CompilerMain.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Logger.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/using.md
A while ago I have disabled the -T SQL compiler flag, which is used to control logging (you specify an instrumented class in the compiler and a logging level). I find myself missing it while debugging compiler problems, so this PR brings it back.
> Re-enable -T sql compiler flag to control logging

- crates/adapters/src/adhoc/table.rs
- crates/adapters/src/format/parquet/mod.rs
- crates/sqllib/src/casts.rs
- crates/sqllib/src/dec.rs
I am not 100% this is foolproof either, but we plan to replace the entire implementation of decimals anyway.
I don't understand why https://docs.rs/dec/latest/dec/struct.Decimal.html#method.to_packed_bcd requires a mut self - this is also very expensive.
> [SQLLIB] Different implementation of Hash for decimals

- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/circuit/runtime.rs
This causes the circuit as a whole to abort if a background thread panics (e.g. if the merger runs out of storage).
> Fail the circuit on background thread panics

- crates/adapters/src/server/mod.rs
- crates/pipeline-manager/src/logging.rs
Simplify the logging by just setting the filter to `info`, rather than `warn` with several exceptions that print at `info` level.
This eases maintenance, as now it is not necessary to add an exception each time a new Feldera crate is added. In addition, `info` level should provide useful information in general. This does make logging a bit more verbose, especially at the start due to actix and postgres operations.
> pipeline-manager: info log level

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/RemoveUnusedFields.java
In the INTERNED PR #4245 we have fixed a bug in a method related to unused field detection: https://github.com/feldera/feldera/pull/4245/files#diff-40713b22f9615bf15b15c6bce9e96efc46326e1634a9d4ab23579edc22b3a397
The bug was genuine, but it was masking another bug: we were not looking for enough unused fields. This has caused a regression for some programs with unused fields.
This PR fixes the regression by looking for the right unused fields; I have checked with some test programs that the same output is produced as with the previous version of the code.
> [SQL] Improve detection of unused fields

- crates/adapters/src/server/mod.rs
- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/auth.rs
- crates/pipeline-manager/src/bin/pipeline-manager.rs
- crates/pipeline-manager/src/compiler/main.rs
- crates/pipeline-manager/src/compiler/rust_compiler.rs
- crates/pipeline-manager/src/compiler/test.rs
- crates/pipeline-manager/src/config.rs
- crates/pipeline-manager/src/runner/interaction.rs
- crates/pipeline-manager/src/runner/local_runner.rs
- crates/pipeline-manager/src/runner/main.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
- crates/pipeline-manager/src/runner/pipeline_executor.rs
API server, compiler, runner and pipelines now all bind to the same address, which is `127.0.0.1` when running from source and `0.0.0.0` when as a Docker image.
Hosts and ports are now commonly known to all via the CLI configuration.
> pipeline-manager: networking fixes

- .github/workflows/test-integration.yml
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/server/mod.rs
- crates/fda/src/cli.rs
- crates/fda/src/main.rs
- crates/feldera-types/src/config.rs
- crates/pipeline-manager/Cargo.toml
- crates/pipeline-manager/src/api/examples.rs
- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/auth.rs
- crates/pipeline-manager/src/compiler/main.rs
- crates/pipeline-manager/src/compiler/test.rs
- crates/pipeline-manager/src/config.rs
- crates/pipeline-manager/src/db/test.rs
- crates/pipeline-manager/src/runner/local_runner.rs
- crates/pipeline-manager/src/runner/main.rs
- crates/storage/src/tokio.rs
- docs.feldera.com/docs/changelog.md
- openapi.json
In the past we let the runtimes figure this out, and they did so using std::thread::available_parallelism().
However, this doesn't work in kubernetes because it will use the number of cores on the node rather the number of cores assigned to the pod.
See also:
- https://github.com/rust-lang/rust/issues/74479#issuecomment-717097590
- One alternative suggested is to use the num_cpus crate, but with cgroupv2 this does not seem to work either:
https://github.com/seanmonstar/num_cpus/issues/130
Changes:
- We add a http-worker flag to the CLI of various control plane binaries
- We add 2 new config settings `io_workers` and `http_workers` to the pipeline config.
- We change the default from available_parallelism() to the `worker` argument in the config.
> Make runtime and worker threads configurable for actix and tokio.

- .github/workflows/test-integration.yml
- python/tests/test_shared_pipeline0.py
* listeners setup after starting a pipeline can be flaky and may not receive all of the data
* however, listeners setup before starting a pipeline are shutdown more gracefully, and should receive all of the data
> pytest: setup listeners before starting pipelines

- Cargo.lock
- crates/adapters/src/controller/mod.rs
- crates/adapters/src/server/mod.rs
- crates/dbsp/src/circuit/checkpointer.rs
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/feldera-types/src/checkpoint.rs
- crates/feldera-types/src/config.rs
- crates/feldera-types/src/constants.rs
- crates/pipeline-manager/src/api/main.rs
- crates/storage/Cargo.toml
- crates/storage/src/checkpoint_synchronizer.rs
- crates/storage/src/lib.rs
- docs.feldera.com/docs/pipelines/checkpoint-sync.md
- openapi.json
- python/feldera/pipeline.py
- python/tests/test_shared_pipeline1.py
* `sync.start_from_checkpoint` takes either a UUID to a checkpoint or `latest` which just pulls the latest checkpoint
* checkpoints now include state.json inside the checkpoint directory as well
* syncs individual pipelines to object store, as now they are self contained
> s3_sync: start from any checkpoint in object store

- crates/pipeline-manager/src/runner/local_runner.rs
- crates/pipeline-manager/src/runner/main.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
- crates/pipeline-manager/src/runner/pipeline_executor.rs
- crates/pipeline-manager/src/runner/pipeline_logs.rs
- Wrap sending logs messages in function that writes in the regular logs when the receiver buffer is full and retries a set number of times, rather than simply blocking without writing anything to regular logs
- Fix logs buffer size
- Increase request timeout of `/suspend` from 5s to 600s
- Documentation fixes
> pipeline-manager: automaton and runner fixes

- crates/adapters/src/controller/mod.rs
- crates/adapters/src/integrated/delta_table/input.rs
- crates/adapters/src/integrated/delta_table/output.rs
- crates/adapters/src/integrated/postgres/input.rs
- crates/adapters/src/server/mod.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/kafka/ft/input.rs
- crates/adapters/src/transport/pubsub/input.rs
- crates/adapters/src/transport/s3/mod.rs
- crates/adapters/src/transport/url.rs
- crates/datagen/src/lib.rs
- crates/iceberg/src/input.rs
Make sure that all threads we spawn are assigned names to help debug panics and crashes. The next step would be adding endpoint name to thread name (we currently only do this for the delta connector).
> [adapters] Name all spawned threads.

- crates/fda/src/adhoc.rs
- crates/fda/src/bench/mod.rs
- crates/fda/src/cli.rs
- crates/fda/src/main.rs
- crates/fda/src/shell.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs
- openapi.json
This required updating the definition of the pipeline metrics API at the pipeline manager, since it defined /metrics to return JSON but that's not always the case.
> [fda] Add `metrics` command for retrieving metrics.

- crates/pipeline-manager/src/api/main.rs
> pipeline-manager: disable limit for awc client connections

- .github/workflows/build-docker-dev.yml
- crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs
- deploy/build.Dockerfile
- python/feldera/_callback_runner.py
- python/feldera/pipeline.py
- python/feldera/rest/_httprequests.py
- python/feldera/rest/feldera_client.py
- python/tests/__init__.py
- python/tests/test_shared_pipeline0.py
- python/tests/test_shared_pipeline1.py
See details in commit. I suspect these things just fail more with k8s CI runners because the pipeline, and control plane and the CI job that test them can all end up being on different nodes.
> Fixes for running cloud tests in k8s

- crates/feldera-types/src/config.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_management.rs
- crates/pipeline-manager/src/db/test.rs
- crates/pipeline-manager/tests/integration_test.rs
- openapi.json
Basically nothing in the tree uses this, so it didn't require much change.
I had to remove some `Eq` and `Ord` derivations, but that broke nothing, so it seemed better than the alternatives.
I don't think this breaks anything.
> [types] Support fractional CPUs.

- crates/adapters/src/controller/stats.rs
The trailing `=` can be hard to select in terminals.  They are not required for correctness, so omit them.  See also
https://docs.rs/base64/latest/base64/#padding-characters.
Fixes: https://github.com/feldera/feldera/issues/4131
> [adapters] Don't pad out base64 with `=`.

- Cargo.lock
- crates/datagen/Cargo.toml
- crates/datagen/src/lib.rs
Datagen used std::thread::park/unpark, which brittle and I believe I saw an instance where it caused datagen to get stuck. The problem is that if thread 1 calls `unpark` before thread 2 calls `park`, and there is another instance of `park` in thread 2 before it hits the `park` in question, including anywhere in a library, then the `unpark` will have no effect. The crossbeam parker doesn't have this issue.
> [datagen] Use crossbeam::Parker

- crates/fda/src/adhoc.rs
- crates/pipeline-manager/src/compiler/sql_compiler.rs
- crates/pipeline-manager/src/error.rs
- crates/pipeline-manager/src/runner/local_runner.rs
- crates/pipeline-manager/src/runner/pipeline_automata.rs
fixes #4469 
^ not required.
shoudn't be anything that's an breaking change, only error messages are changed.
> pipeline-manager: include error source of reqwest error for additional context

- docs.feldera.com/docs/pipelines/checkpoint-sync.md
Adds the S3 sync transfer speeds to the docs website.
> docs: add sync performance numbers

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Projection.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
We used to generated nested tuples `Tup2<Tup2<>, ...>`, for the keys of some index operators when compiling window aggregates, which could not be analyzed by the monotonicity analyzer, which never expected complex keys in joins. We now flatten the inner keys, generating `Tup3<...>` instead. The results should be indistinguishable, but the program should be easier to analyze.
> [SQL] Generate simpler keys when indexing the output of PartitionedWindowAggregates

- Cargo.lock
- crates/fda/src/cli.rs
- crates/fda/src/main.rs
- crates/pipeline-manager/Cargo.toml
- crates/pipeline-manager/src/api/endpoints/config.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_interaction/mod.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_interaction/support_bundle.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_management.rs
- crates/pipeline-manager/src/api/error.rs
- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/db/types/pipeline.rs
- crates/pipeline-manager/src/license.rs
- crates/pipeline-manager/src/runner/interaction.rs
- docs.feldera.com/docs/interface/cli.md
- docs.feldera.com/docs/operations/guide.md
- openapi.json
- python/docs/examples.rst
- python/feldera/pipeline.py
- python/feldera/rest/feldera_client.py
- python/tests/test_shared_pipeline.py
Adds a support-bundle endpoint to gather various metrics/logs/and profiles of a pipeline.
This should be complete in terms of the data it gathers, but future PRs will improve this to 
None, purely additive feature (it does remove the program-info endpoint which I think was added by accident a few weeks ago and shouldn't be in use anyways)
> Support bundle v0

- crates/pipeline-manager/src/db/types/program.rs
- crates/pipeline-manager/tests/integration_test.rs
- docs.feldera.com/docs/connectors/index.mdx
Before this commit, an unnamed connector would get assigned a randomly generated unique name. However, this name would be regenerated every time SQL compilation occurred. This is particularly inconvenient for attributing state to the corresponding connector across stop and resume.
This commit instead assigns unnamed connectors within a table or view the names `unnamed-{index}`. For example, if a table has four connectors: `abc`, (unnamed), `def` and (unnamed), the SQL compilation will produce the names `abc`, `unnamed-1`, `def` and `unnamed-3` in the `program_info` it outputs. Note that the indexes are per table/view, as connector names are only unique in the scope of a table/view not across all.
**PR information**
- Checklist: documentation updated, changelog is not updated
- Breaking …
> pipeline-manager: name unnamed connector using index

- deploy/grafana_dashboard.json
The metrics in our sample Grafana dashboard (which I hadn't known about) mostly referred to metrics by names that have changed.  This commit updates those, removes metrics that no longer exist, and adds visualizations for some new metrics (like storage latencies, and process resident set size and CPU use).
> Update Grafana dashboard template to reflect current metrics.

- Cargo.lock
- Cargo.toml
- crates/adapterlib/Cargo.toml
- crates/adapterlib/src/transport.rs
- crates/adapters/Cargo.toml
- crates/adapters/src/adhoc/mod.rs
- crates/adapters/src/controller/checkpoint.rs
- crates/adapters/src/controller/journal.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/static_compile/catalog.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/url.rs
serde_json produces poor error messages for deserialization.  This commit uses the serde_json_path_to_error crate to add paths to most kinds of errors.  This is a fairly simple crate that generally works as a drop-in replacement for serde_json (it is a wrapper for it, not a reimplementation).
This commit introduces use of serde_json_path_to_error for deserialzing metadata such as checkpoint information, but it does not introduce it for data parsing for two reasons.  First, it has a performance hit because it clones names within the paths as it traverses them.  Second, we don't yet know whether it introduces any incompatibilities.
> [adapters] Use serde_json_path_to_error to get better error messages.

- crates/fda/test.bash
- crates/pipeline-manager/src/runner/interaction.rs
The https support we added recently didn't change the websocket protocol to wss.
None, bugfix.
> Use wss protocol instead of ws when https is enabled.

- crates/pipeline-manager/src/api/main.rs
- crates/pipeline-manager/src/compiler/main.rs
- crates/pipeline-manager/src/db/probe.rs
- crates/pipeline-manager/src/runner/main.rs
- crates/pipeline-manager/tests/integration_test.rs
- Log error if the regular probe fails, and also log when it recovers
- The API already logs when errors are returned by it, as such it is not necessary to every time also have the HTTP response conversion function log it
- Refer to the logs for details regarding the health status
**PR information**
- Documentation is not updated, changelog is not updated
- No breaking changes: health checks still returns OK upon success and INTERNAL_SERVER_ERROR upon failure
- Backward incompatible changes: health check endpoint is different, but its guarantees remain the same
> pipeline-manager: refactor regular database probe

- python/feldera/rest/feldera_client.py
- python/tests/negative_test.py
Fixes: #4512
Bugfix
Add a few sentences describing the incompatible changes if any.
> py: bugfix: give full errors for RustError and SystemError

- crates/adapters/src/transport/clock.rs
- crates/dbsp/src/operator/dynamic/aggregate/min.rs
- crates/dbsp/src/operator/dynamic/aggregate/mod.rs
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/BaseRustCodeGenerator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/MinMaxOptimize.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/DBSPMinMax.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPCastExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/OtherTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/AggregateTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/EndToEndTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
This introduces a new DBSP Aggregator, which is very tailored towards the needs of `ARG_MIN`.
What doesn't one do for performance?
> [SQL] Optimized implementation of ARG_MIN

- docs.feldera.com/docs/changelog.md
- docs.feldera.com/docs/sql/string.md
- docs.feldera.com/docs/sql/types.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/functions/FunctionsTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
I didn't realize that Calcite by default uses ISO-8859-1. Switched to using UTF-8.
Fixes #4559 
If programs were relying on the character set being ISO-8859-1 they may now break.
Previously we documented that each string column could have a different charset; I have removed this from the documentation (but not the implementation). If anyone asks for it, we can consider adding it back, but for now it is unsupported. To support it we have to test it thoroughly and figure out what happens when you try to mix char types with different charsets.
> [SQL] Make UTF-8 the default character set

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/Simplify.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/ValueNumbering.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/AdjustSqlIndex.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CSE.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/LowerAsof.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/Passes.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/FieldUseMap.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/RemoveUnusedFields.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPTupleExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMillisInterval.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeMonthsInterval.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Logger.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/tools/BaseSQLTests.java
Fixes #4577 
- Avoids some clones
- Considers casts to/from strings expensive, so it can CSE identical casts
> [SQL] Code generation improvements

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPClosureExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ir/InliningTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
We will always inline the call `f(g(x))` when f is a projection.
This has big benefits for some programs, especially improving the detection of unused fields if g projects away many fields of f.
> [SQL] Improve policy for inlining functions

- docs.feldera.com/docs/changelog.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPChainAggregateOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPControlledKeyFilterOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPIntegrateTraceRetainKeysOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/DBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementNow.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/InsertLimiters.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/monotonicity/Monotonicity.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPForExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPSortExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/derived/DBSPTypeRawTuple.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/derived/DBSPTypeTuple.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
Now is implemented as a stream that feeds user-controlled clock values.
There is an adapter which provides these values, but users do not have to use it.
Not every NOW stream is valid, though (NOW is supposed to have LATENESS 0).
This implementation is more robust to incorrect external NOW streams; instead of using the previous LATENESS-based mechanism with WATERLINE operators it uses a DBSP `chain_aggregate` operator. 
Apparently this will play better with transactions.
> [SQL] Alternative implementation of NOW using chain_aggregates

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPStreamAggregateOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitCloneVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/MinMaxOptimize.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/DBSPFold.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/NonLinearAggregate.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/user/DBSPTypeSemigroup.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
Generally it's more efficient to implement MIN(a), MIN(b) as two operators followed by a join rather than a single scan.
This PR makes this choice when there are no other non-linear aggregates that scan the same collection.
Note: this plan used to be generated in a previous version of the compiler, but the optimizations related to chain aggregates no longer produce such plans.
> [SQL] Implement a set of MIN/MAX/ARG_MIN/ARG_MAX operators as a sequence of individual operators

- python/feldera/rest/errors.py
If there is a FelderaAPIError, show the response code. This is useful in cases where the server doesn't respond with a response body.
#4634
> py: show resp status in error messages

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/annotation/NoChain.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPChainOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPMapOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ChainVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/ImplementChains.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeMaps.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/RemoveUnusedFields.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/MinMaxAggregate.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/resources/metadataTests-generateDF.json
Fixes #4660 
Contains 3 commits fixing independent problems:
- Some aggregates, such as Max, always return Nullable results, because they have no choice over an empty collection.
However, a window aggregate never runs over an empty collection, so the result can be non-nullable when the field aggregated is not nullable. This requires "correcting" the result using a cast (unwrap) which can never fail.
- The stream produced by a `partitioned_rolling_aggregate` does not support operations such as flat_map, so the `map_index` operator following the rolling aggregate should not be combined with other operators.
- If a chain operator does not contain any filters, produce a Map/MapIndex instead of a FlatMap/FlatMapIndex
> [SQL] Produce correct result nullability for window aggregates

- crates/adapters/src/format/avro/schema.rs
- crates/adapters/src/format/avro/test.rs
Fixes issue #4664.
More permissive Avro parsing: accept Avro `int` type for `bigint` and `bigint unsigned` columns.
> [adapters] Deserialize 64-bit ints from Avro `int`.

- crates/adapters/src/controller/mod.rs
- docs.feldera.com/docs/changelog.md
- python/feldera/pipeline.py
- python/feldera/rest/feldera_client.py
Only clears the `sync_checkpoint_request` once the sync has actually completed. Checkpoints will only get GCed once the sync process has completed.
`Pipeline.sync_checkpoint(wait=True)` will now panic if syncing the checkpoint fails.
> sync: prevent syncing checkpoints from being GCed

- crates/adapters/src/integrated/postgres/output.rs
Fixes: #4680
This is what new errors will look like:
```txt
FATAL error on output endpoint 'v1.unnamed-0':
while executing insert statement: [{"id":1}]
Caused by:
postgres error: permanent: SqlState: Some(SqlState(E23505)): db error:
ERROR: duplicate key value violates unique constraint "feldera_out_pkey"
DETAIL: Key (id)=(1) already exists.
```
> pg: print the entire error context

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/AggregateCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/FirstLastAggregate.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/GroupAndAggregates.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/LeadLagAggregates.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/RangeAggregates.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/SimpleAggregates.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/package-info.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/CalciteJdbcTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/quidem/WinAggPostTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
For a `FIRST_VALUE` window aggregate a range of `ROWS` or `RANGE` which is `UNBOUNDED` on both sides produces the same result.
Moreover, a `ROWS` or `RANGE` unbounded that ends at the current row is the same as `UNBOUNDED` on both sides.
A symmetric case occurs for `LAST_VALUE`.
So now we accept such programs, whereas previously we used to reject them.
We also reject `LEAD` and `LAG` programs with `IGNORE NULLS`, which previously we were incorrectly accepting and producing wrong results.
> [SQL] For FIRST_VALUE and LAST_VALUE some ranges are equivalent

- crates/adapters/src/format/avro/schema.rs
- crates/adapters/src/format/avro/serializer.rs
- crates/adapters/src/format/avro/test.rs
Fixes #4722.
The UUID type can be represented either as Avro `string` type or as { "type": "string", "logicalType": "uuid"}. We did not support the latter option in our schema validator and serializer. This commit adds such support.
> [adapters] Avro: handle `uuid` logical type.

- crates/adapterlib/src/catalog.rs
- crates/adapters/src/format/avro/deserializer.rs
- crates/adapters/src/format/avro/input.rs
- crates/adapters/src/format/avro/mod.rs
- crates/adapters/src/format/avro/schema.rs
- crates/adapters/src/format/avro/test.rs
- crates/adapters/src/static_compile/deinput.rs
- crates/adapters/src/test/mock_dezset.rs
- crates/adapters/src/util.rs
Fixes #4721.
We did not handle type references in the Avro parser. These are uncommon with streaming Avro. One exception is Debezium, which uses the same schema for `before` and `after` fields. Our implementation worked assuming that the Debezium message Avro schema specified `before` as an alias to `after`.  This commit adds support for deserializing Avro records with type aliases that can occur anywhere within the schema.
> [adapters] Resolve Avro schema references.

- docs.feldera.com/docs/changelog.md
- docs.feldera.com/docs/sql/udf.md
- python/tests/runtime/test_uda.py
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TypeCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/AggregateCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/FirstLastAggregate.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/RangeAggregates.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/WindowAggregates.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/ExternalFunction.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/aggregate/LinearAggregate.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MultiCrateTests.java
There are two commits.
First one improves a little error reporting in some cases.
Second one makes it easier to implement linear aggregates, by moving the task of handling `NULL` values in the compiler, and letting users only worry about the non-null case. This way users are also less likely to get it wrong.
> [SQL] Simplify linear aggregates for users

- crates/adapters/src/server.rs
- crates/pipeline-manager/src/api/endpoints/pipeline_interaction.rs
- crates/pipeline-manager/src/api/util.rs
- python/feldera/rest/feldera_client.py
- python/tests/platform/test_shared_pipeline.py
- web-console/src/lib/services/pipelineManager.ts
Steps to reproduce:
1. Create a program:
```
CREATE TABLE  "direct__document#parent__document" (
object_id TEXT NOT NULL
);
```
2. Subscribe to the table's Change Stream in web-console
3. Insert a value via ad-hoc query:
```
INSERT INTO "direct__document#parent__document" (object_id) VALUES ('foo');
```
4. Observe change does not appear
> Fix egress endpoint does not urlencode relation name

- python/feldera/testutils.py
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/FilterCorrelateRule.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/SqlToRelCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/inner/ReferenceMap.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/suites/TpchTest.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/resources/metadataTests-generateDFRecursive.json
- sql-to-dbsp-compiler/SQL-compiler/src/test/resources/tpch.sql
This should improve the plans for many TPC-H queries.
We always had an attribute for tables `expected_size` which can be used to pass a cost for the table to the Calcite optimizer. With some small fixes in this PR, now the optimizer has access to the cost. I have not verified that the costs themselves do improve the plans, but there is no harm having them. I have also annotated the TPC-H tables in our test with their expected sizes.
> [SQL] Perform Calcite join optimizations both before and after decorrelation

- crates/adapterlib/src/format.rs
- crates/adapters/src/format/parquet/test.rs
- crates/adapters/src/transport/s3.rs
An additional parquet parser test + better error reporting in the s3 connector.
See individual commits for details.
> Parquet test + S3 error handling

- crates/sqllib/src/array.rs
- docs.feldera.com/docs/sql/aggregates.md
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/aggregates/AggregateCompiler.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPNoComparatorExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/AggregateTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
Fixes #4777
To support ORDER BY in `ARRAY_AGG` we build the accumulator with all fields that one needs in the output OR in the sort order, and in the postprocessing function we sort the accumulator. This is very expensive, but the asymptotic cost is the same as the standard `ARRAY_AGG`. It's conceivable that this could be improved on by relying on Z-sets to keep the input collection sorted on the correct fields.
> [SQL] Support `ORDER BY` in `ARRAY_AGG`

- crates/adapters/src/transport/clock.rs
The test assumed that the connector cannot produce new inputs after `pause`, however pause is an async operation, which can return before the connector performs an extra clock tick.
> [adapters] Fixup clock test.

- crates/pipeline-manager/src/api/endpoints/pipeline_management.rs
- python/feldera/_callback_runner.py
- python/feldera/enums.py
- python/feldera/pipeline.py
- python/feldera/pipeline_builder.py
- python/feldera/rest/feldera_client.py
- python/tests/platform/helper.py
- python/tests/platform/test_pipeline_lifecycle.py
- python/tests/platform/test_shared_pipeline.py
Python SDK called the GET /pipeline/<name> endpoint without using the
selector argument. This meant that even when polling the manager waiting
for pipeline compilation to complete or for a specific pipeline status,
it retrieved the entire source code, schema, and the list of compiler
errors and warnings every time. This could cause a lot of unnecessary
load on the manager.
This commit changes the SDK to instead use the "status" selector where
possible to only retrieve fields needed for runtime monitoring of the
pipeline. This approach may still be a bit crude, and we may want an
even more fine grained API, but it should improve things significantly.
> [py] Take advantage of pipeline field selector.

- Cargo.lock
- crates/adapterlib/Cargo.toml
- crates/adapterlib/src/transport.rs
- crates/adapters/src/controller.rs
- crates/adapters/src/controller/checkpoint.rs
- crates/adapters/src/controller/stats.rs
- crates/adapters/src/integrated/delta_table/input.rs
- crates/adapters/src/integrated/delta_table/test.rs
- crates/adapters/src/integrated/postgres/input.rs
- crates/adapters/src/test/mock_input_consumer.rs
- crates/adapters/src/transport/adhoc.rs
- crates/adapters/src/transport/clock.rs
- crates/adapters/src/transport/file.rs
- crates/adapters/src/transport/http/input.rs
- crates/adapters/src/transport/kafka/ft/input.rs
- crates/adapters/src/transport/kafka/ft/test.rs
- crates/adapters/src/transport/nexmark.rs
- crates/adapters/src/transport/pubsub/input.rs
- crates/adapters/src/transport/s3.rs
- crates/adapters/src/transport/url.rs
- crates/datagen/src/lib.rs
- crates/iceberg/src/input.rs
- docs.feldera.com/docs/operations/metrics.md
Fixes: #4637.
A minimal implementation of RFC #4637.
**Defitions: Processing latency and completion latency**
*Processing latency* is the time it takes the pipeline to process a batch of records from when they are ingested from the wire to when the circuit completes processing these records. This includes: parsing, queuing, and processing by the circuit.
*Completion latency* includes processing latency plus the time it takes the pipeline to push outputs to all output endpoints (this includes output buffering delay if output buffers are enabled for some endpoints).
**API**
This commit introduces two extensions to the Feldera API:
1. We add two new histograms per input connector in the set of metrics produced by the `/metrics` endpoint: processing latency and completion latency, both for a …
> [adapters] Latency measurement framework.

- .github/workflows/test-integration-platform.yml
- .github/workflows/test-integration-runtime.yml
- .github/workflows/test-unit.yml
- crates/adapters/src/controller.rs
- crates/adapters/src/controller/sync.rs
- crates/adapters/src/server.rs
- crates/feldera-types/src/runtime_status.rs
- python/feldera/rest/feldera_client.py
- python/tests/platform/test_checkpoint_sync.py
- python/tests/platform/test_pipeline_crud.py
Even if the pipeline isn't configured to start in standby mode, allow
for resuming from an S3 checkpoint.
Also properly expose the standby state. As the pipeline is still
technically stuck in initializing, and no controller exists, the methods
we use to handle replaying and bootstrapping do not apply for standby
mode. Instead, this commit introduces `InitializationState`, a more fine
state within the Initalizing PipelinePhase. By default, the
InitializationState will be `Starting`. If the pipeline is configured to
start from an S3 checkpoint this state will transition to
`DownloadingCheckpoint`, which for the outside world is still
`Initializing`, but with more detailed information via
`runtime_status_details`. For Standby, the `InitializationState` will be
`Standby`, which means the …
> sync: expose standby state as pipeline status

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPChainOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/operator/DBSPNowOperator.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/dot/ToDotNodesVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CSE.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPClosureExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPZSetExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/util/Maybe.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/resources/metadataTests-generateDF.json
The CSE pass would not detect identical constant operators, preventing it from CSE-ing all their successors.
This had an impact on programs that used global aggregates, where there is always a constant input holding the result for an empty collection.
This compiler was sound, though.
> [SQL] Improve CSE pass for operators

- docs.feldera.com/docs/changelog.md
- python/docs/examples.rst
- python/docs/pandas.rst
- python/feldera/_callback_runner.py
- python/feldera/output_handler.py
- python/feldera/pipeline.py
- python/tests/platform/test_shared_pipeline.py
- python/tests/runtime/lateness/test_issue4457.py
- python/tests/runtime/test_udf.py
The `Pipeline.listen` method can now only be called when the pipeline is running or paused. Previously it was possible to call `Pipeline.listen` before starting the pipeline in order to guarantee that all outputs produced by the pipeline are captured by the listener.  With the new API, you can achieve the same by starting the pipeline in a paused state using `Pipeline.start_paused` and calling `Pipeline.listen` before unpausing the pipeline using `Pipeline.resume`.
This change eliminates some complex code that deal with setting up listeners before starting the pipeline.
The main reason for implementing this simplification now is the upcoming backfill avoidance feature, which would make maintaining the previous API even harder.
Mark if you think …
> [py] Don't allow listen() on a stopped pipeline.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/OptimizeProjectionVisitor.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/PropagateEmptySources.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPIndexedZSetExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPMapExpression.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/IDBSPContainer.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/Regression1Tests.java
This was motivated by the SLT test failure overnight.
But by looking the program generated I realized that we were missing some optimizations:
- empty constant followed by map-index
- empty constant followed by antijoin
> [SQL] A few more optimizations for empty inputs

- crates/dbsp/src/circuit/circuit_builder.rs
- crates/dbsp/src/circuit/dbsp_handle.rs
- crates/dbsp/src/monitor.rs
- crates/dbsp/src/monitor/circuit_graph.rs
- crates/dbsp/src/monitor/visual_graph.rs
- crates/dbsp/src/profile.rs
Recently we have added the capability of retrieving a profile in JSON format.
However, the profile is just a map from node to metadata.
This PR adds to the JSON document an array of graphs, one per worker.
I believe that today all graphs are identical, so maybe this can be simplified.
The node name serialization has been changed to match in the profile and in the graph.
> [DBSP] Include circuit graph(s) with JSON profile

- web-console/src/lib/components/layout/pipelines/PipelineConfigurationsPopup.svelte
- web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte
- web-console/src/lib/components/layout/pipelines/PipelineToolbarMenuPopup.svelte
- web-console/src/lib/components/pipelines/list/Actions.svelte
- web-console/src/lib/compositions/usePipelineAction.svelte.ts
- web-console/src/lib/compositions/useWritablePipeline.svelte.ts
- web-console/src/lib/services/pipelineManager.ts
- web-console/src/routes/(system)/(authenticated)/(pipelines)/pipelines/[pipelineName]/+page.svelte
This is more likely to occur on a slower connection to a Feldera instance
Fix https://github.com/feldera/feldera/issues/4835: The cursor jumps to the beginning of the code
The issue was caused by local code cache not getting updated before patch pipeline request resolves, before which a pipeline polling request could resolve and overwrite the code editor with now-stale cache data. The solution is to optimistically update code state cache
> [WebConsole] Fix cursor jumps to beginning when pipeline polling is in flight

- crates/iceberg/src/test/requirements.ci.txt
- crates/iceberg/src/test/requirements.txt
We have a transitive dependency on pydantic in iceberg tests. It looks like a recent release (3 hours ago at the time of writing) broke pyiceberg. I pinned the pydantic version as a workaround.
> [adapters] Pin pydantic version.

- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CircuitOptimizer.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/outer/CloneOperatorsWithFanout.java
- sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/unusedFields/ReplaceCommonProjections.java
- sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java
The first optimization regards joinIndex operators followed by multiple projections: we enable the "widest" projection that comprises both to be propagated up through the joinIndex. (We used to do it for other kinds of joins, not handling this one was an omission).
The second optimization regards Map/MapIndex/Filter operators with a fanout > 1. We now expand these into multiple copies if they are followed by an operator that can be merged into a single one with its source. A side-effect of this optimization is that plans will contain fewer shared operators between unrelated views, enabling more state reuse when modifying the program.
There is a test where adding a view used to change the hash for 4 views, but after this optimization only 1 hash is changed.
> [SQL] Two more optimizations related to unused fields
